/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.cop.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRCOPProductType service. Represents a row in the &quot;vr_copproducttype&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.cop.model.impl.VRCOPProductTypeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.cop.model.impl.VRCOPProductTypeImpl}.
 * </p>
 *
 * @author HoangLeTrongNhan
 * @see VRCOPProductType
 * @see com.fds.vr.cop.model.impl.VRCOPProductTypeImpl
 * @see com.fds.vr.cop.model.impl.VRCOPProductTypeModelImpl
 * @generated
 */
@ProviderType
public interface VRCOPProductTypeModel extends BaseModel<VRCOPProductType> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vrcop product type model instance should use the {@link VRCOPProductType} interface instead.
	 */

	/**
	 * Returns the primary key of this vrcop product type.
	 *
	 * @return the primary key of this vrcop product type
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vrcop product type.
	 *
	 * @param primaryKey the primary key of this vrcop product type
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vrcop product type.
	 *
	 * @return the ID of this vrcop product type
	 */
	public long getId();

	/**
	 * Sets the ID of this vrcop product type.
	 *
	 * @param id the ID of this vrcop product type
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vrcop product type.
	 *
	 * @return the mt core of this vrcop product type
	 */
	public int getMtCore();

	/**
	 * Sets the mt core of this vrcop product type.
	 *
	 * @param mtCore the mt core of this vrcop product type
	 */
	public void setMtCore(int mtCore);

	/**
	 * Returns the cop report repository ID of this vrcop product type.
	 *
	 * @return the cop report repository ID of this vrcop product type
	 */
	public long getCOPReportRepositoryID();

	/**
	 * Sets the cop report repository ID of this vrcop product type.
	 *
	 * @param COPReportRepositoryID the cop report repository ID of this vrcop product type
	 */
	public void setCOPReportRepositoryID(long COPReportRepositoryID);

	/**
	 * Returns the cop report no of this vrcop product type.
	 *
	 * @return the cop report no of this vrcop product type
	 */
	@AutoEscape
	public String getCOPReportNo();

	/**
	 * Sets the cop report no of this vrcop product type.
	 *
	 * @param COPReportNo the cop report no of this vrcop product type
	 */
	public void setCOPReportNo(String COPReportNo);

	/**
	 * Returns the sequence no of this vrcop product type.
	 *
	 * @return the sequence no of this vrcop product type
	 */
	public long getSequenceNo();

	/**
	 * Sets the sequence no of this vrcop product type.
	 *
	 * @param sequenceNo the sequence no of this vrcop product type
	 */
	public void setSequenceNo(long sequenceNo);

	/**
	 * Returns the vehicle class of this vrcop product type.
	 *
	 * @return the vehicle class of this vrcop product type
	 */
	@AutoEscape
	public String getVehicleClass();

	/**
	 * Sets the vehicle class of this vrcop product type.
	 *
	 * @param vehicleClass the vehicle class of this vrcop product type
	 */
	public void setVehicleClass(String vehicleClass);

	/**
	 * Returns the vehicle type code of this vrcop product type.
	 *
	 * @return the vehicle type code of this vrcop product type
	 */
	@AutoEscape
	public String getVehicleTypeCode();

	/**
	 * Sets the vehicle type code of this vrcop product type.
	 *
	 * @param vehicleTypeCode the vehicle type code of this vrcop product type
	 */
	public void setVehicleTypeCode(String vehicleTypeCode);

	/**
	 * Returns the vehicle type description of this vrcop product type.
	 *
	 * @return the vehicle type description of this vrcop product type
	 */
	@AutoEscape
	public String getVehicleTypeDescription();

	/**
	 * Sets the vehicle type description of this vrcop product type.
	 *
	 * @param vehicleTypeDescription the vehicle type description of this vrcop product type
	 */
	public void setVehicleTypeDescription(String vehicleTypeDescription);

	/**
	 * Returns the product classification code of this vrcop product type.
	 *
	 * @return the product classification code of this vrcop product type
	 */
	@AutoEscape
	public String getProductClassificationCode();

	/**
	 * Sets the product classification code of this vrcop product type.
	 *
	 * @param productClassificationCode the product classification code of this vrcop product type
	 */
	public void setProductClassificationCode(String productClassificationCode);

	/**
	 * Returns the product classification description of this vrcop product type.
	 *
	 * @return the product classification description of this vrcop product type
	 */
	@AutoEscape
	public String getProductClassificationDescription();

	/**
	 * Sets the product classification description of this vrcop product type.
	 *
	 * @param productClassificationDescription the product classification description of this vrcop product type
	 */
	public void setProductClassificationDescription(
		String productClassificationDescription);

	/**
	 * Returns the trade mark of this vrcop product type.
	 *
	 * @return the trade mark of this vrcop product type
	 */
	@AutoEscape
	public String getTradeMark();

	/**
	 * Sets the trade mark of this vrcop product type.
	 *
	 * @param tradeMark the trade mark of this vrcop product type
	 */
	public void setTradeMark(String tradeMark);

	/**
	 * Returns the trade mark name of this vrcop product type.
	 *
	 * @return the trade mark name of this vrcop product type
	 */
	@AutoEscape
	public String getTradeMarkName();

	/**
	 * Sets the trade mark name of this vrcop product type.
	 *
	 * @param tradeMarkName the trade mark name of this vrcop product type
	 */
	public void setTradeMarkName(String tradeMarkName);

	/**
	 * Returns the commercial name of this vrcop product type.
	 *
	 * @return the commercial name of this vrcop product type
	 */
	@AutoEscape
	public String getCommercialName();

	/**
	 * Sets the commercial name of this vrcop product type.
	 *
	 * @param commercialName the commercial name of this vrcop product type
	 */
	public void setCommercialName(String commercialName);

	/**
	 * Returns the model code of this vrcop product type.
	 *
	 * @return the model code of this vrcop product type
	 */
	@AutoEscape
	public String getModelCode();

	/**
	 * Sets the model code of this vrcop product type.
	 *
	 * @param modelCode the model code of this vrcop product type
	 */
	public void setModelCode(String modelCode);

	/**
	 * Returns the design symbol no of this vrcop product type.
	 *
	 * @return the design symbol no of this vrcop product type
	 */
	@AutoEscape
	public String getDesignSymbolNo();

	/**
	 * Sets the design symbol no of this vrcop product type.
	 *
	 * @param designSymbolNo the design symbol no of this vrcop product type
	 */
	public void setDesignSymbolNo(String designSymbolNo);

	/**
	 * Returns the sync date of this vrcop product type.
	 *
	 * @return the sync date of this vrcop product type
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vrcop product type.
	 *
	 * @param syncDate the sync date of this vrcop product type
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRCOPProductType vrcopProductType);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRCOPProductType> toCacheModel();

	@Override
	public VRCOPProductType toEscapedModel();

	@Override
	public VRCOPProductType toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}