/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ILVehicle service. Represents a row in the &quot;il_vehicle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.ILVehicleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.ILVehicleImpl}.
 * </p>
 *
 * @author LamTV
 * @see ILVehicle
 * @see com.fds.vr.business.model.impl.ILVehicleImpl
 * @see com.fds.vr.business.model.impl.ILVehicleModelImpl
 * @generated
 */
@ProviderType
public interface ILVehicleModel extends BaseModel<ILVehicle> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a il vehicle model instance should use the {@link ILVehicle} interface instead.
	 */

	/**
	 * Returns the primary key of this il vehicle.
	 *
	 * @return the primary key of this il vehicle
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this il vehicle.
	 *
	 * @param primaryKey the primary key of this il vehicle
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this il vehicle.
	 *
	 * @return the ID of this il vehicle
	 */
	public long getId();

	/**
	 * Sets the ID of this il vehicle.
	 *
	 * @param id the ID of this il vehicle
	 */
	public void setId(long id);

	/**
	 * Returns the issuing dispatch no of this il vehicle.
	 *
	 * @return the issuing dispatch no of this il vehicle
	 */
	@AutoEscape
	public String getIssuingDispatchNo();

	/**
	 * Sets the issuing dispatch no of this il vehicle.
	 *
	 * @param issuingDispatchNo the issuing dispatch no of this il vehicle
	 */
	public void setIssuingDispatchNo(String issuingDispatchNo);

	/**
	 * Returns the sequence no of this il vehicle.
	 *
	 * @return the sequence no of this il vehicle
	 */
	public int getSequenceNo();

	/**
	 * Sets the sequence no of this il vehicle.
	 *
	 * @param sequenceNo the sequence no of this il vehicle
	 */
	public void setSequenceNo(int sequenceNo);

	/**
	 * Returns the registration number of this il vehicle.
	 *
	 * @return the registration number of this il vehicle
	 */
	@AutoEscape
	public String getRegistrationNumber();

	/**
	 * Sets the registration number of this il vehicle.
	 *
	 * @param registrationNumber the registration number of this il vehicle
	 */
	public void setRegistrationNumber(String registrationNumber);

	/**
	 * Returns the registration driver of this il vehicle.
	 *
	 * @return the registration driver of this il vehicle
	 */
	@AutoEscape
	public String getRegistrationDriver();

	/**
	 * Sets the registration driver of this il vehicle.
	 *
	 * @param registrationDriver the registration driver of this il vehicle
	 */
	public void setRegistrationDriver(String registrationDriver);

	/**
	 * Returns the vehicle model code of this il vehicle.
	 *
	 * @return the vehicle model code of this il vehicle
	 */
	@AutoEscape
	public String getVehicleModelCode();

	/**
	 * Sets the vehicle model code of this il vehicle.
	 *
	 * @param vehicleModelCode the vehicle model code of this il vehicle
	 */
	public void setVehicleModelCode(String vehicleModelCode);

	/**
	 * Returns the vehicle model name of this il vehicle.
	 *
	 * @return the vehicle model name of this il vehicle
	 */
	@AutoEscape
	public String getVehicleModelName();

	/**
	 * Sets the vehicle model name of this il vehicle.
	 *
	 * @param vehicleModelName the vehicle model name of this il vehicle
	 */
	public void setVehicleModelName(String vehicleModelName);

	/**
	 * Returns the capacity of this il vehicle.
	 *
	 * @return the capacity of this il vehicle
	 */
	@AutoEscape
	public String getCapacity();

	/**
	 * Sets the capacity of this il vehicle.
	 *
	 * @param capacity the capacity of this il vehicle
	 */
	public void setCapacity(String capacity);

	/**
	 * Returns the manufactured year of this il vehicle.
	 *
	 * @return the manufactured year of this il vehicle
	 */
	@AutoEscape
	public String getManufacturedYear();

	/**
	 * Sets the manufactured year of this il vehicle.
	 *
	 * @param manufacturedYear the manufactured year of this il vehicle
	 */
	public void setManufacturedYear(String manufacturedYear);

	/**
	 * Returns the vehicle exp imp gate code of this il vehicle.
	 *
	 * @return the vehicle exp imp gate code of this il vehicle
	 */
	@AutoEscape
	public String getVehicleExpImpGateCode();

	/**
	 * Sets the vehicle exp imp gate code of this il vehicle.
	 *
	 * @param vehicleExpImpGateCode the vehicle exp imp gate code of this il vehicle
	 */
	public void setVehicleExpImpGateCode(String vehicleExpImpGateCode);

	/**
	 * Returns the vehicle exp imp gate of this il vehicle.
	 *
	 * @return the vehicle exp imp gate of this il vehicle
	 */
	@AutoEscape
	public String getVehicleExpImpGate();

	/**
	 * Sets the vehicle exp imp gate of this il vehicle.
	 *
	 * @param vehicleExpImpGate the vehicle exp imp gate of this il vehicle
	 */
	public void setVehicleExpImpGate(String vehicleExpImpGate);

	/**
	 * Returns the operation type of this il vehicle.
	 *
	 * @return the operation type of this il vehicle
	 */
	@AutoEscape
	public String getOperationType();

	/**
	 * Sets the operation type of this il vehicle.
	 *
	 * @param operationType the operation type of this il vehicle
	 */
	public void setOperationType(String operationType);

	/**
	 * Returns the passenger or cargo of this il vehicle.
	 *
	 * @return the passenger or cargo of this il vehicle
	 */
	@AutoEscape
	public String getPassengerOrCargo();

	/**
	 * Sets the passenger or cargo of this il vehicle.
	 *
	 * @param passengerOrCargo the passenger or cargo of this il vehicle
	 */
	public void setPassengerOrCargo(String passengerOrCargo);

	/**
	 * Returns the lien van no of this il vehicle.
	 *
	 * @return the lien van no of this il vehicle
	 */
	@AutoEscape
	public String getLienVanNo();

	/**
	 * Sets the lien van no of this il vehicle.
	 *
	 * @param lienVanNo the lien van no of this il vehicle
	 */
	public void setLienVanNo(String lienVanNo);

	/**
	 * Returns the sync date of this il vehicle.
	 *
	 * @return the sync date of this il vehicle
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this il vehicle.
	 *
	 * @param syncDate the sync date of this il vehicle
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ILVehicle ilVehicle);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ILVehicle> toCacheModel();

	@Override
	public ILVehicle toEscapedModel();

	@Override
	public ILVehicle toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}