/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRApplicantProfileHistory service. Represents a row in the &quot;vr_applicantprofilehistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRApplicantProfileHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRApplicantProfileHistoryImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRApplicantProfileHistory
 * @see com.fds.vr.business.model.impl.VRApplicantProfileHistoryImpl
 * @see com.fds.vr.business.model.impl.VRApplicantProfileHistoryModelImpl
 * @generated
 */
@ProviderType
public interface VRApplicantProfileHistoryModel extends BaseModel<VRApplicantProfileHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr applicant profile history model instance should use the {@link VRApplicantProfileHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this vr applicant profile history.
	 *
	 * @return the primary key of this vr applicant profile history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr applicant profile history.
	 *
	 * @param primaryKey the primary key of this vr applicant profile history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr applicant profile history.
	 *
	 * @return the ID of this vr applicant profile history
	 */
	public long getId();

	/**
	 * Sets the ID of this vr applicant profile history.
	 *
	 * @param id the ID of this vr applicant profile history
	 */
	public void setId(long id);

	/**
	 * Returns the applicant code of this vr applicant profile history.
	 *
	 * @return the applicant code of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantCode();

	/**
	 * Sets the applicant code of this vr applicant profile history.
	 *
	 * @param applicantCode the applicant code of this vr applicant profile history
	 */
	public void setApplicantCode(String applicantCode);

	/**
	 * Returns the applicant name of this vr applicant profile history.
	 *
	 * @return the applicant name of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantName();

	/**
	 * Sets the applicant name of this vr applicant profile history.
	 *
	 * @param applicantName the applicant name of this vr applicant profile history
	 */
	public void setApplicantName(String applicantName);

	/**
	 * Returns the applicant address of this vr applicant profile history.
	 *
	 * @return the applicant address of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantAddress();

	/**
	 * Sets the applicant address of this vr applicant profile history.
	 *
	 * @param applicantAddress the applicant address of this vr applicant profile history
	 */
	public void setApplicantAddress(String applicantAddress);

	/**
	 * Returns the applicant representative of this vr applicant profile history.
	 *
	 * @return the applicant representative of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantRepresentative();

	/**
	 * Sets the applicant representative of this vr applicant profile history.
	 *
	 * @param applicantRepresentative the applicant representative of this vr applicant profile history
	 */
	public void setApplicantRepresentative(String applicantRepresentative);

	/**
	 * Returns the applicant representative title of this vr applicant profile history.
	 *
	 * @return the applicant representative title of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantRepresentativeTitle();

	/**
	 * Sets the applicant representative title of this vr applicant profile history.
	 *
	 * @param applicantRepresentativeTitle the applicant representative title of this vr applicant profile history
	 */
	public void setApplicantRepresentativeTitle(
		String applicantRepresentativeTitle);

	/**
	 * Returns the applicant phone of this vr applicant profile history.
	 *
	 * @return the applicant phone of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantPhone();

	/**
	 * Sets the applicant phone of this vr applicant profile history.
	 *
	 * @param applicantPhone the applicant phone of this vr applicant profile history
	 */
	public void setApplicantPhone(String applicantPhone);

	/**
	 * Returns the applicant email of this vr applicant profile history.
	 *
	 * @return the applicant email of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantEmail();

	/**
	 * Sets the applicant email of this vr applicant profile history.
	 *
	 * @param applicantEmail the applicant email of this vr applicant profile history
	 */
	public void setApplicantEmail(String applicantEmail);

	/**
	 * Returns the applicant fax of this vr applicant profile history.
	 *
	 * @return the applicant fax of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantFax();

	/**
	 * Sets the applicant fax of this vr applicant profile history.
	 *
	 * @param applicantFax the applicant fax of this vr applicant profile history
	 */
	public void setApplicantFax(String applicantFax);

	/**
	 * Returns the applicant contact name of this vr applicant profile history.
	 *
	 * @return the applicant contact name of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantContactName();

	/**
	 * Sets the applicant contact name of this vr applicant profile history.
	 *
	 * @param applicantContactName the applicant contact name of this vr applicant profile history
	 */
	public void setApplicantContactName(String applicantContactName);

	/**
	 * Returns the applicant contact email of this vr applicant profile history.
	 *
	 * @return the applicant contact email of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantContactEmail();

	/**
	 * Sets the applicant contact email of this vr applicant profile history.
	 *
	 * @param applicantContactEmail the applicant contact email of this vr applicant profile history
	 */
	public void setApplicantContactEmail(String applicantContactEmail);

	/**
	 * Returns the applicant contact phone of this vr applicant profile history.
	 *
	 * @return the applicant contact phone of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantContactPhone();

	/**
	 * Sets the applicant contact phone of this vr applicant profile history.
	 *
	 * @param applicantContactPhone the applicant contact phone of this vr applicant profile history
	 */
	public void setApplicantContactPhone(String applicantContactPhone);

	/**
	 * Returns the applicant nationality of this vr applicant profile history.
	 *
	 * @return the applicant nationality of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantNationality();

	/**
	 * Sets the applicant nationality of this vr applicant profile history.
	 *
	 * @param applicantNationality the applicant nationality of this vr applicant profile history
	 */
	public void setApplicantNationality(String applicantNationality);

	/**
	 * Returns the applicant region of this vr applicant profile history.
	 *
	 * @return the applicant region of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantRegion();

	/**
	 * Sets the applicant region of this vr applicant profile history.
	 *
	 * @param applicantRegion the applicant region of this vr applicant profile history
	 */
	public void setApplicantRegion(String applicantRegion);

	/**
	 * Returns the applicant ceremony date of this vr applicant profile history.
	 *
	 * @return the applicant ceremony date of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantCeremonyDate();

	/**
	 * Sets the applicant ceremony date of this vr applicant profile history.
	 *
	 * @param applicantCeremonyDate the applicant ceremony date of this vr applicant profile history
	 */
	public void setApplicantCeremonyDate(String applicantCeremonyDate);

	/**
	 * Returns the applicant operation period of this vr applicant profile history.
	 *
	 * @return the applicant operation period of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantOperationPeriod();

	/**
	 * Sets the applicant operation period of this vr applicant profile history.
	 *
	 * @param applicantOperationPeriod the applicant operation period of this vr applicant profile history
	 */
	public void setApplicantOperationPeriod(String applicantOperationPeriod);

	/**
	 * Returns the applicant business type of this vr applicant profile history.
	 *
	 * @return the applicant business type of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantBusinessType();

	/**
	 * Sets the applicant business type of this vr applicant profile history.
	 *
	 * @param applicantBusinessType the applicant business type of this vr applicant profile history
	 */
	public void setApplicantBusinessType(String applicantBusinessType);

	/**
	 * Returns the applicant metadata of this vr applicant profile history.
	 *
	 * @return the applicant metadata of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantMetadata();

	/**
	 * Sets the applicant metadata of this vr applicant profile history.
	 *
	 * @param applicantMetadata the applicant metadata of this vr applicant profile history
	 */
	public void setApplicantMetadata(String applicantMetadata);

	/**
	 * Returns the applicant status of this vr applicant profile history.
	 *
	 * @return the applicant status of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantStatus();

	/**
	 * Sets the applicant status of this vr applicant profile history.
	 *
	 * @param applicantStatus the applicant status of this vr applicant profile history
	 */
	public void setApplicantStatus(String applicantStatus);

	/**
	 * Returns the applicant issue type of this vr applicant profile history.
	 *
	 * @return the applicant issue type of this vr applicant profile history
	 */
	@AutoEscape
	public String getApplicantIssueType();

	/**
	 * Sets the applicant issue type of this vr applicant profile history.
	 *
	 * @param applicantIssueType the applicant issue type of this vr applicant profile history
	 */
	public void setApplicantIssueType(String applicantIssueType);

	/**
	 * Returns the modify date of this vr applicant profile history.
	 *
	 * @return the modify date of this vr applicant profile history
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr applicant profile history.
	 *
	 * @param modifyDate the modify date of this vr applicant profile history
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr applicant profile history.
	 *
	 * @return the sync date of this vr applicant profile history
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr applicant profile history.
	 *
	 * @param syncDate the sync date of this vr applicant profile history
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRApplicantProfileHistory vrApplicantProfileHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRApplicantProfileHistory> toCacheModel();

	@Override
	public VRApplicantProfileHistory toEscapedModel();

	@Override
	public VRApplicantProfileHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}