/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the VRCertificateProgressFile service. Represents a row in the &quot;vr_certificate_progress_file&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRCertificateProgressFileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRCertificateProgressFileImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRCertificateProgressFile
 * @see com.fds.vr.business.model.impl.VRCertificateProgressFileImpl
 * @see com.fds.vr.business.model.impl.VRCertificateProgressFileModelImpl
 * @generated
 */
@ProviderType
public interface VRCertificateProgressFileModel extends BaseModel<VRCertificateProgressFile> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr certificate progress file model instance should use the {@link VRCertificateProgressFile} interface instead.
	 */

	/**
	 * Returns the primary key of this vr certificate progress file.
	 *
	 * @return the primary key of this vr certificate progress file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr certificate progress file.
	 *
	 * @param primaryKey the primary key of this vr certificate progress file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr certificate progress file.
	 *
	 * @return the ID of this vr certificate progress file
	 */
	public long getId();

	/**
	 * Sets the ID of this vr certificate progress file.
	 *
	 * @param id the ID of this vr certificate progress file
	 */
	public void setId(long id);

	/**
	 * Returns the certificate progress ID of this vr certificate progress file.
	 *
	 * @return the certificate progress ID of this vr certificate progress file
	 */
	public long getCertificateProgressID();

	/**
	 * Sets the certificate progress ID of this vr certificate progress file.
	 *
	 * @param certificateProgressID the certificate progress ID of this vr certificate progress file
	 */
	public void setCertificateProgressID(long certificateProgressID);

	/**
	 * Returns the attached file ID of this vr certificate progress file.
	 *
	 * @return the attached file ID of this vr certificate progress file
	 */
	public long getAttachedFileID();

	/**
	 * Sets the attached file ID of this vr certificate progress file.
	 *
	 * @param attachedFileID the attached file ID of this vr certificate progress file
	 */
	public void setAttachedFileID(long attachedFileID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRCertificateProgressFile vrCertificateProgressFile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRCertificateProgressFile> toCacheModel();

	@Override
	public VRCertificateProgressFile toEscapedModel();

	@Override
	public VRCertificateProgressFile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}