/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRCOPProductionPlantEquipment service. Represents a row in the &quot;vr_copproductionplantequipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRCOPProductionPlantEquipmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRCOPProductionPlantEquipmentImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRCOPProductionPlantEquipment
 * @see com.fds.vr.business.model.impl.VRCOPProductionPlantEquipmentImpl
 * @see com.fds.vr.business.model.impl.VRCOPProductionPlantEquipmentModelImpl
 * @generated
 */
@ProviderType
public interface VRCOPProductionPlantEquipmentModel extends BaseModel<VRCOPProductionPlantEquipment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vrcop production plant equipment model instance should use the {@link VRCOPProductionPlantEquipment} interface instead.
	 */

	/**
	 * Returns the primary key of this vrcop production plant equipment.
	 *
	 * @return the primary key of this vrcop production plant equipment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vrcop production plant equipment.
	 *
	 * @param primaryKey the primary key of this vrcop production plant equipment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vrcop production plant equipment.
	 *
	 * @return the ID of this vrcop production plant equipment
	 */
	public long getId();

	/**
	 * Sets the ID of this vrcop production plant equipment.
	 *
	 * @param id the ID of this vrcop production plant equipment
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vrcop production plant equipment.
	 *
	 * @return the mt core of this vrcop production plant equipment
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vrcop production plant equipment.
	 *
	 * @param mtCore the mt core of this vrcop production plant equipment
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the cop report repository ID of this vrcop production plant equipment.
	 *
	 * @return the cop report repository ID of this vrcop production plant equipment
	 */
	public long getCopReportRepositoryID();

	/**
	 * Sets the cop report repository ID of this vrcop production plant equipment.
	 *
	 * @param copReportRepositoryID the cop report repository ID of this vrcop production plant equipment
	 */
	public void setCopReportRepositoryID(long copReportRepositoryID);

	/**
	 * Returns the cop report no of this vrcop production plant equipment.
	 *
	 * @return the cop report no of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getCopReportNo();

	/**
	 * Sets the cop report no of this vrcop production plant equipment.
	 *
	 * @param copReportNo the cop report no of this vrcop production plant equipment
	 */
	public void setCopReportNo(String copReportNo);

	/**
	 * Returns the sequence no of this vrcop production plant equipment.
	 *
	 * @return the sequence no of this vrcop production plant equipment
	 */
	public long getSequenceNo();

	/**
	 * Sets the sequence no of this vrcop production plant equipment.
	 *
	 * @param sequenceNo the sequence no of this vrcop production plant equipment
	 */
	public void setSequenceNo(long sequenceNo);

	/**
	 * Returns the equipment code of this vrcop production plant equipment.
	 *
	 * @return the equipment code of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getEquipmentCode();

	/**
	 * Sets the equipment code of this vrcop production plant equipment.
	 *
	 * @param equipmentCode the equipment code of this vrcop production plant equipment
	 */
	public void setEquipmentCode(String equipmentCode);

	/**
	 * Returns the equipment name of this vrcop production plant equipment.
	 *
	 * @return the equipment name of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getEquipmentName();

	/**
	 * Sets the equipment name of this vrcop production plant equipment.
	 *
	 * @param equipmentName the equipment name of this vrcop production plant equipment
	 */
	public void setEquipmentName(String equipmentName);

	/**
	 * Returns the equipment type of this vrcop production plant equipment.
	 *
	 * @return the equipment type of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getEquipmentType();

	/**
	 * Sets the equipment type of this vrcop production plant equipment.
	 *
	 * @param equipmentType the equipment type of this vrcop production plant equipment
	 */
	public void setEquipmentType(String equipmentType);

	/**
	 * Returns the trademark of this vrcop production plant equipment.
	 *
	 * @return the trademark of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getTrademark();

	/**
	 * Sets the trademark of this vrcop production plant equipment.
	 *
	 * @param trademark the trademark of this vrcop production plant equipment
	 */
	public void setTrademark(String trademark);

	/**
	 * Returns the trademark name of this vrcop production plant equipment.
	 *
	 * @return the trademark name of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getTrademarkName();

	/**
	 * Sets the trademark name of this vrcop production plant equipment.
	 *
	 * @param trademarkName the trademark name of this vrcop production plant equipment
	 */
	public void setTrademarkName(String trademarkName);

	/**
	 * Returns the commercial name of this vrcop production plant equipment.
	 *
	 * @return the commercial name of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getCommercialName();

	/**
	 * Sets the commercial name of this vrcop production plant equipment.
	 *
	 * @param commercialName the commercial name of this vrcop production plant equipment
	 */
	public void setCommercialName(String commercialName);

	/**
	 * Returns the model code of this vrcop production plant equipment.
	 *
	 * @return the model code of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getModelCode();

	/**
	 * Sets the model code of this vrcop production plant equipment.
	 *
	 * @param modelCode the model code of this vrcop production plant equipment
	 */
	public void setModelCode(String modelCode);

	/**
	 * Returns the production country code of this vrcop production plant equipment.
	 *
	 * @return the production country code of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getProductionCountryCode();

	/**
	 * Sets the production country code of this vrcop production plant equipment.
	 *
	 * @param productionCountryCode the production country code of this vrcop production plant equipment
	 */
	public void setProductionCountryCode(String productionCountryCode);

	/**
	 * Returns the equipment status of this vrcop production plant equipment.
	 *
	 * @return the equipment status of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getEquipmentStatus();

	/**
	 * Sets the equipment status of this vrcop production plant equipment.
	 *
	 * @param equipmentStatus the equipment status of this vrcop production plant equipment
	 */
	public void setEquipmentStatus(String equipmentStatus);

	/**
	 * Returns the expire date of this vrcop production plant equipment.
	 *
	 * @return the expire date of this vrcop production plant equipment
	 */
	public Date getExpireDate();

	/**
	 * Sets the expire date of this vrcop production plant equipment.
	 *
	 * @param expireDate the expire date of this vrcop production plant equipment
	 */
	public void setExpireDate(Date expireDate);

	/**
	 * Returns the notes of this vrcop production plant equipment.
	 *
	 * @return the notes of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this vrcop production plant equipment.
	 *
	 * @param notes the notes of this vrcop production plant equipment
	 */
	public void setNotes(String notes);

	/**
	 * Returns the modify date of this vrcop production plant equipment.
	 *
	 * @return the modify date of this vrcop production plant equipment
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vrcop production plant equipment.
	 *
	 * @param modifyDate the modify date of this vrcop production plant equipment
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vrcop production plant equipment.
	 *
	 * @return the sync date of this vrcop production plant equipment
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vrcop production plant equipment.
	 *
	 * @param syncDate the sync date of this vrcop production plant equipment
	 */
	public void setSyncDate(Date syncDate);

	/**
	 * Returns the equipment serial no of this vrcop production plant equipment.
	 *
	 * @return the equipment serial no of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getEquipmentSerialNo();

	/**
	 * Sets the equipment serial no of this vrcop production plant equipment.
	 *
	 * @param equipmentSerialNo the equipment serial no of this vrcop production plant equipment
	 */
	public void setEquipmentSerialNo(String equipmentSerialNo);

	/**
	 * Returns the production year of this vrcop production plant equipment.
	 *
	 * @return the production year of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getProductionYear();

	/**
	 * Sets the production year of this vrcop production plant equipment.
	 *
	 * @param productionYear the production year of this vrcop production plant equipment
	 */
	public void setProductionYear(String productionYear);

	/**
	 * Returns the registration year of this vrcop production plant equipment.
	 *
	 * @return the registration year of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getRegistrationYear();

	/**
	 * Sets the registration year of this vrcop production plant equipment.
	 *
	 * @param registrationYear the registration year of this vrcop production plant equipment
	 */
	public void setRegistrationYear(String registrationYear);

	/**
	 * Returns the markup xcg of this vrcop production plant equipment.
	 *
	 * @return the markup xcg of this vrcop production plant equipment
	 */
	public long getMarkupXCG();

	/**
	 * Sets the markup xcg of this vrcop production plant equipment.
	 *
	 * @param markupXCG the markup xcg of this vrcop production plant equipment
	 */
	public void setMarkupXCG(long markupXCG);

	/**
	 * Returns the markup xcgnk of this vrcop production plant equipment.
	 *
	 * @return the markup xcgnk of this vrcop production plant equipment
	 */
	public long getMarkupXCGNK();

	/**
	 * Sets the markup xcgnk of this vrcop production plant equipment.
	 *
	 * @param markupXCGNK the markup xcgnk of this vrcop production plant equipment
	 */
	public void setMarkupXCGNK(long markupXCGNK);

	/**
	 * Returns the markup smrm of this vrcop production plant equipment.
	 *
	 * @return the markup smrm of this vrcop production plant equipment
	 */
	public long getMarkupSMRM();

	/**
	 * Sets the markup smrm of this vrcop production plant equipment.
	 *
	 * @param markupSMRM the markup smrm of this vrcop production plant equipment
	 */
	public void setMarkupSMRM(long markupSMRM);

	/**
	 * Returns the markup xch of this vrcop production plant equipment.
	 *
	 * @return the markup xch of this vrcop production plant equipment
	 */
	public long getMarkupXCH();

	/**
	 * Sets the markup xch of this vrcop production plant equipment.
	 *
	 * @param markupXCH the markup xch of this vrcop production plant equipment
	 */
	public void setMarkupXCH(long markupXCH);

	/**
	 * Returns the markup xcn of this vrcop production plant equipment.
	 *
	 * @return the markup xcn of this vrcop production plant equipment
	 */
	public long getMarkupXCN();

	/**
	 * Sets the markup xcn of this vrcop production plant equipment.
	 *
	 * @param markupXCN the markup xcn of this vrcop production plant equipment
	 */
	public void setMarkupXCN(long markupXCN);

	/**
	 * Returns the markup xmy of this vrcop production plant equipment.
	 *
	 * @return the markup xmy of this vrcop production plant equipment
	 */
	public long getMarkupXMY();

	/**
	 * Sets the markup xmy of this vrcop production plant equipment.
	 *
	 * @param markupXMY the markup xmy of this vrcop production plant equipment
	 */
	public void setMarkupXMY(long markupXMY);

	/**
	 * Returns the markup xdd of this vrcop production plant equipment.
	 *
	 * @return the markup xdd of this vrcop production plant equipment
	 */
	public long getMarkupXDD();

	/**
	 * Sets the markup xdd of this vrcop production plant equipment.
	 *
	 * @param markupXDD the markup xdd of this vrcop production plant equipment
	 */
	public void setMarkupXDD(long markupXDD);

	/**
	 * Returns the testing result of this vrcop production plant equipment.
	 *
	 * @return the testing result of this vrcop production plant equipment
	 */
	public int getTestingResult();

	/**
	 * Sets the testing result of this vrcop production plant equipment.
	 *
	 * @param testingResult the testing result of this vrcop production plant equipment
	 */
	public void setTestingResult(int testingResult);

	/**
	 * Returns the description of this vrcop production plant equipment.
	 *
	 * @return the description of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vrcop production plant equipment.
	 *
	 * @param description the description of this vrcop production plant equipment
	 */
	public void setDescription(String description);

	/**
	 * Returns the inspection record number of this vrcop production plant equipment.
	 *
	 * @return the inspection record number of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getInspectionRecordNumber();

	/**
	 * Sets the inspection record number of this vrcop production plant equipment.
	 *
	 * @param inspectionRecordNumber the inspection record number of this vrcop production plant equipment
	 */
	public void setInspectionRecordNumber(String inspectionRecordNumber);

	/**
	 * Returns the inspection record date of this vrcop production plant equipment.
	 *
	 * @return the inspection record date of this vrcop production plant equipment
	 */
	public Date getInspectionRecordDate();

	/**
	 * Sets the inspection record date of this vrcop production plant equipment.
	 *
	 * @param inspectionRecordDate the inspection record date of this vrcop production plant equipment
	 */
	public void setInspectionRecordDate(Date inspectionRecordDate);

	/**
	 * Returns the expired date of this vrcop production plant equipment.
	 *
	 * @return the expired date of this vrcop production plant equipment
	 */
	public Date getExpiredDate();

	/**
	 * Sets the expired date of this vrcop production plant equipment.
	 *
	 * @param expiredDate the expired date of this vrcop production plant equipment
	 */
	public void setExpiredDate(Date expiredDate);

	/**
	 * Returns the expired status of this vrcop production plant equipment.
	 *
	 * @return the expired status of this vrcop production plant equipment
	 */
	public int getExpiredStatus();

	/**
	 * Sets the expired status of this vrcop production plant equipment.
	 *
	 * @param expiredStatus the expired status of this vrcop production plant equipment
	 */
	public void setExpiredStatus(int expiredStatus);

	/**
	 * Returns the stamp testing no of this vrcop production plant equipment.
	 *
	 * @return the stamp testing no of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getStampTestingNo();

	/**
	 * Sets the stamp testing no of this vrcop production plant equipment.
	 *
	 * @param stampTestingNo the stamp testing no of this vrcop production plant equipment
	 */
	public void setStampTestingNo(String stampTestingNo);

	/**
	 * Returns the dossier ID of this vrcop production plant equipment.
	 *
	 * @return the dossier ID of this vrcop production plant equipment
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vrcop production plant equipment.
	 *
	 * @param dossierId the dossier ID of this vrcop production plant equipment
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier ID ctn of this vrcop production plant equipment.
	 *
	 * @return the dossier ID ctn of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vrcop production plant equipment.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vrcop production plant equipment
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the dossier no of this vrcop production plant equipment.
	 *
	 * @return the dossier no of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vrcop production plant equipment.
	 *
	 * @param dossierNo the dossier no of this vrcop production plant equipment
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the production plant ID of this vrcop production plant equipment.
	 *
	 * @return the production plant ID of this vrcop production plant equipment
	 */
	public long getProductionPlantId();

	/**
	 * Sets the production plant ID of this vrcop production plant equipment.
	 *
	 * @param productionPlantId the production plant ID of this vrcop production plant equipment
	 */
	public void setProductionPlantId(long productionPlantId);

	/**
	 * Returns the production plant code of this vrcop production plant equipment.
	 *
	 * @return the production plant code of this vrcop production plant equipment
	 */
	@AutoEscape
	public String getProductionPlantCode();

	/**
	 * Sets the production plant code of this vrcop production plant equipment.
	 *
	 * @param productionPlantCode the production plant code of this vrcop production plant equipment
	 */
	public void setProductionPlantCode(String productionPlantCode);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		VRCOPProductionPlantEquipment vrcopProductionPlantEquipment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRCOPProductionPlantEquipment> toCacheModel();

	@Override
	public VRCOPProductionPlantEquipment toEscapedModel();

	@Override
	public VRCOPProductionPlantEquipment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}