/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRCOPProductClassification service. Represents a row in the &quot;vr_copproductclassification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRCOPProductClassificationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRCOPProductClassificationImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRCOPProductClassification
 * @see com.fds.vr.business.model.impl.VRCOPProductClassificationImpl
 * @see com.fds.vr.business.model.impl.VRCOPProductClassificationModelImpl
 * @generated
 */
@ProviderType
public interface VRCOPProductClassificationModel extends BaseModel<VRCOPProductClassification> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vrcop product classification model instance should use the {@link VRCOPProductClassification} interface instead.
	 */

	/**
	 * Returns the primary key of this vrcop product classification.
	 *
	 * @return the primary key of this vrcop product classification
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vrcop product classification.
	 *
	 * @param primaryKey the primary key of this vrcop product classification
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vrcop product classification.
	 *
	 * @return the ID of this vrcop product classification
	 */
	public long getId();

	/**
	 * Sets the ID of this vrcop product classification.
	 *
	 * @param id the ID of this vrcop product classification
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vrcop product classification.
	 *
	 * @return the mt core of this vrcop product classification
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vrcop product classification.
	 *
	 * @param mtCore the mt core of this vrcop product classification
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the cop report repository ID of this vrcop product classification.
	 *
	 * @return the cop report repository ID of this vrcop product classification
	 */
	public long getCopReportRepositoryID();

	/**
	 * Sets the cop report repository ID of this vrcop product classification.
	 *
	 * @param copReportRepositoryID the cop report repository ID of this vrcop product classification
	 */
	public void setCopReportRepositoryID(long copReportRepositoryID);

	/**
	 * Returns the cop report no of this vrcop product classification.
	 *
	 * @return the cop report no of this vrcop product classification
	 */
	@AutoEscape
	public String getCopReportNo();

	/**
	 * Sets the cop report no of this vrcop product classification.
	 *
	 * @param copReportNo the cop report no of this vrcop product classification
	 */
	public void setCopReportNo(String copReportNo);

	/**
	 * Returns the sequence no of this vrcop product classification.
	 *
	 * @return the sequence no of this vrcop product classification
	 */
	public long getSequenceNo();

	/**
	 * Sets the sequence no of this vrcop product classification.
	 *
	 * @param sequenceNo the sequence no of this vrcop product classification
	 */
	public void setSequenceNo(long sequenceNo);

	/**
	 * Returns the product classification code of this vrcop product classification.
	 *
	 * @return the product classification code of this vrcop product classification
	 */
	@AutoEscape
	public String getProductClassificationCode();

	/**
	 * Sets the product classification code of this vrcop product classification.
	 *
	 * @param productClassificationCode the product classification code of this vrcop product classification
	 */
	public void setProductClassificationCode(String productClassificationCode);

	/**
	 * Returns the product classification description of this vrcop product classification.
	 *
	 * @return the product classification description of this vrcop product classification
	 */
	@AutoEscape
	public String getProductClassificationDescription();

	/**
	 * Sets the product classification description of this vrcop product classification.
	 *
	 * @param productClassificationDescription the product classification description of this vrcop product classification
	 */
	public void setProductClassificationDescription(
		String productClassificationDescription);

	/**
	 * Returns the modify date of this vrcop product classification.
	 *
	 * @return the modify date of this vrcop product classification
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vrcop product classification.
	 *
	 * @param modifyDate the modify date of this vrcop product classification
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vrcop product classification.
	 *
	 * @return the sync date of this vrcop product classification
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vrcop product classification.
	 *
	 * @param syncDate the sync date of this vrcop product classification
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRCOPProductClassification vrcopProductClassification);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRCOPProductClassification> toCacheModel();

	@Override
	public VRCOPProductClassification toEscapedModel();

	@Override
	public VRCOPProductClassification toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}