/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRCorporationInspector service. Represents a row in the &quot;vr_corporation_inspector&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRCorporationInspectorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRCorporationInspectorImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRCorporationInspector
 * @see com.fds.vr.business.model.impl.VRCorporationInspectorImpl
 * @see com.fds.vr.business.model.impl.VRCorporationInspectorModelImpl
 * @generated
 */
@ProviderType
public interface VRCorporationInspectorModel extends BaseModel<VRCorporationInspector> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr corporation inspector model instance should use the {@link VRCorporationInspector} interface instead.
	 */

	/**
	 * Returns the primary key of this vr corporation inspector.
	 *
	 * @return the primary key of this vr corporation inspector
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr corporation inspector.
	 *
	 * @param primaryKey the primary key of this vr corporation inspector
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr corporation inspector.
	 *
	 * @return the ID of this vr corporation inspector
	 */
	public long getId();

	/**
	 * Sets the ID of this vr corporation inspector.
	 *
	 * @param id the ID of this vr corporation inspector
	 */
	public void setId(long id);

	/**
	 * Returns the corporation ID of this vr corporation inspector.
	 *
	 * @return the corporation ID of this vr corporation inspector
	 */
	@AutoEscape
	public String getCorporationId();

	/**
	 * Sets the corporation ID of this vr corporation inspector.
	 *
	 * @param corporationId the corporation ID of this vr corporation inspector
	 */
	public void setCorporationId(String corporationId);

	/**
	 * Returns the inspector ID of this vr corporation inspector.
	 *
	 * @return the inspector ID of this vr corporation inspector
	 */
	public long getInspectorId();

	/**
	 * Sets the inspector ID of this vr corporation inspector.
	 *
	 * @param inspectorId the inspector ID of this vr corporation inspector
	 */
	public void setInspectorId(long inspectorId);

	/**
	 * Returns the inspector name of this vr corporation inspector.
	 *
	 * @return the inspector name of this vr corporation inspector
	 */
	@AutoEscape
	public String getInspectorName();

	/**
	 * Sets the inspector name of this vr corporation inspector.
	 *
	 * @param inspectorName the inspector name of this vr corporation inspector
	 */
	public void setInspectorName(String inspectorName);

	/**
	 * Returns the inspector phone of this vr corporation inspector.
	 *
	 * @return the inspector phone of this vr corporation inspector
	 */
	@AutoEscape
	public String getInspectorPhone();

	/**
	 * Sets the inspector phone of this vr corporation inspector.
	 *
	 * @param inspectorPhone the inspector phone of this vr corporation inspector
	 */
	public void setInspectorPhone(String inspectorPhone);

	/**
	 * Returns the inspector email of this vr corporation inspector.
	 *
	 * @return the inspector email of this vr corporation inspector
	 */
	@AutoEscape
	public String getInspectorEmail();

	/**
	 * Sets the inspector email of this vr corporation inspector.
	 *
	 * @param inspectorEmail the inspector email of this vr corporation inspector
	 */
	public void setInspectorEmail(String inspectorEmail);

	/**
	 * Returns the contact code of this vr corporation inspector.
	 *
	 * @return the contact code of this vr corporation inspector
	 */
	public Date getContactCode();

	/**
	 * Sets the contact code of this vr corporation inspector.
	 *
	 * @param contactCode the contact code of this vr corporation inspector
	 */
	public void setContactCode(Date contactCode);

	/**
	 * Returns the team ID of this vr corporation inspector.
	 *
	 * @return the team ID of this vr corporation inspector
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this vr corporation inspector.
	 *
	 * @param teamId the team ID of this vr corporation inspector
	 */
	public void setTeamId(long teamId);

	/**
	 * Returns the markup team leader of this vr corporation inspector.
	 *
	 * @return the markup team leader of this vr corporation inspector
	 */
	public long getMarkupTeamLeader();

	/**
	 * Sets the markup team leader of this vr corporation inspector.
	 *
	 * @param markupTeamLeader the markup team leader of this vr corporation inspector
	 */
	public void setMarkupTeamLeader(long markupTeamLeader);

	/**
	 * Returns the markup boss of this vr corporation inspector.
	 *
	 * @return the markup boss of this vr corporation inspector
	 */
	public long getMarkupBoss();

	/**
	 * Sets the markup boss of this vr corporation inspector.
	 *
	 * @param markupBoss the markup boss of this vr corporation inspector
	 */
	public void setMarkupBoss(long markupBoss);

	/**
	 * Returns the place of this vr corporation inspector.
	 *
	 * @return the place of this vr corporation inspector
	 */
	@AutoEscape
	public String getPlace();

	/**
	 * Sets the place of this vr corporation inspector.
	 *
	 * @param place the place of this vr corporation inspector
	 */
	public void setPlace(String place);

	/**
	 * Returns the title of this vr corporation inspector.
	 *
	 * @return the title of this vr corporation inspector
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this vr corporation inspector.
	 *
	 * @param title the title of this vr corporation inspector
	 */
	public void setTitle(String title);

	/**
	 * Returns the file chu ky ID of this vr corporation inspector.
	 *
	 * @return the file chu ky ID of this vr corporation inspector
	 */
	public long getFileChuKyId();

	/**
	 * Sets the file chu ky ID of this vr corporation inspector.
	 *
	 * @param fileChuKyId the file chu ky ID of this vr corporation inspector
	 */
	public void setFileChuKyId(long fileChuKyId);

	/**
	 * Returns the modify date of this vr corporation inspector.
	 *
	 * @return the modify date of this vr corporation inspector
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr corporation inspector.
	 *
	 * @param modifyDate the modify date of this vr corporation inspector
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr corporation inspector.
	 *
	 * @return the sync date of this vr corporation inspector
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr corporation inspector.
	 *
	 * @param syncDate the sync date of this vr corporation inspector
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRCorporationInspector vrCorporationInspector);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRCorporationInspector> toCacheModel();

	@Override
	public VRCorporationInspector toEscapedModel();

	@Override
	public VRCorporationInspector toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}