/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRCOPReportRepository service. Represents a row in the &quot;vr_copreportrepository&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRCOPReportRepositoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRCOPReportRepositoryImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRCOPReportRepository
 * @see com.fds.vr.business.model.impl.VRCOPReportRepositoryImpl
 * @see com.fds.vr.business.model.impl.VRCOPReportRepositoryModelImpl
 * @generated
 */
@ProviderType
public interface VRCOPReportRepositoryModel extends BaseModel<VRCOPReportRepository> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vrcop report repository model instance should use the {@link VRCOPReportRepository} interface instead.
	 */

	/**
	 * Returns the primary key of this vrcop report repository.
	 *
	 * @return the primary key of this vrcop report repository
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vrcop report repository.
	 *
	 * @param primaryKey the primary key of this vrcop report repository
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vrcop report repository.
	 *
	 * @return the ID of this vrcop report repository
	 */
	public long getId();

	/**
	 * Sets the ID of this vrcop report repository.
	 *
	 * @param id the ID of this vrcop report repository
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vrcop report repository.
	 *
	 * @return the mt core of this vrcop report repository
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vrcop report repository.
	 *
	 * @param mtCore the mt core of this vrcop report repository
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the applicant profile ID of this vrcop report repository.
	 *
	 * @return the applicant profile ID of this vrcop report repository
	 */
	public long getApplicantProfileId();

	/**
	 * Sets the applicant profile ID of this vrcop report repository.
	 *
	 * @param applicantProfileId the applicant profile ID of this vrcop report repository
	 */
	public void setApplicantProfileId(long applicantProfileId);

	/**
	 * Returns the applicant code of this vrcop report repository.
	 *
	 * @return the applicant code of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantCode();

	/**
	 * Sets the applicant code of this vrcop report repository.
	 *
	 * @param applicantCode the applicant code of this vrcop report repository
	 */
	public void setApplicantCode(String applicantCode);

	/**
	 * Returns the applicant name of this vrcop report repository.
	 *
	 * @return the applicant name of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantName();

	/**
	 * Sets the applicant name of this vrcop report repository.
	 *
	 * @param applicantName the applicant name of this vrcop report repository
	 */
	public void setApplicantName(String applicantName);

	/**
	 * Returns the applicant address of this vrcop report repository.
	 *
	 * @return the applicant address of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantAddress();

	/**
	 * Sets the applicant address of this vrcop report repository.
	 *
	 * @param applicantAddress the applicant address of this vrcop report repository
	 */
	public void setApplicantAddress(String applicantAddress);

	/**
	 * Returns the overseas manufacturer code of this vrcop report repository.
	 *
	 * @return the overseas manufacturer code of this vrcop report repository
	 */
	@AutoEscape
	public String getOverseasManufacturerCode();

	/**
	 * Sets the overseas manufacturer code of this vrcop report repository.
	 *
	 * @param overseasManufacturerCode the overseas manufacturer code of this vrcop report repository
	 */
	public void setOverseasManufacturerCode(String overseasManufacturerCode);

	/**
	 * Returns the overseas manufacturer name of this vrcop report repository.
	 *
	 * @return the overseas manufacturer name of this vrcop report repository
	 */
	@AutoEscape
	public String getOverseasManufacturerName();

	/**
	 * Sets the overseas manufacturer name of this vrcop report repository.
	 *
	 * @param overseasManufacturerName the overseas manufacturer name of this vrcop report repository
	 */
	public void setOverseasManufacturerName(String overseasManufacturerName);

	/**
	 * Returns the overseas manufacturer address of this vrcop report repository.
	 *
	 * @return the overseas manufacturer address of this vrcop report repository
	 */
	@AutoEscape
	public String getOverseasManufacturerAddress();

	/**
	 * Sets the overseas manufacturer address of this vrcop report repository.
	 *
	 * @param overseasManufacturerAddress the overseas manufacturer address of this vrcop report repository
	 */
	public void setOverseasManufacturerAddress(
		String overseasManufacturerAddress);

	/**
	 * Returns the production plant ID of this vrcop report repository.
	 *
	 * @return the production plant ID of this vrcop report repository
	 */
	public long getProductionPlantId();

	/**
	 * Sets the production plant ID of this vrcop report repository.
	 *
	 * @param productionPlantId the production plant ID of this vrcop report repository
	 */
	public void setProductionPlantId(long productionPlantId);

	/**
	 * Returns the production plant code of this vrcop report repository.
	 *
	 * @return the production plant code of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionPlantCode();

	/**
	 * Sets the production plant code of this vrcop report repository.
	 *
	 * @param productionPlantCode the production plant code of this vrcop report repository
	 */
	public void setProductionPlantCode(String productionPlantCode);

	/**
	 * Returns the production plant name of this vrcop report repository.
	 *
	 * @return the production plant name of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionPlantName();

	/**
	 * Sets the production plant name of this vrcop report repository.
	 *
	 * @param productionPlantName the production plant name of this vrcop report repository
	 */
	public void setProductionPlantName(String productionPlantName);

	/**
	 * Returns the production plant address of this vrcop report repository.
	 *
	 * @return the production plant address of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionPlantAddress();

	/**
	 * Sets the production plant address of this vrcop report repository.
	 *
	 * @param productionPlantAddress the production plant address of this vrcop report repository
	 */
	public void setProductionPlantAddress(String productionPlantAddress);

	/**
	 * Returns the cop report no of this vrcop report repository.
	 *
	 * @return the cop report no of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportNo();

	/**
	 * Sets the cop report no of this vrcop report repository.
	 *
	 * @param copReportNo the cop report no of this vrcop report repository
	 */
	public void setCopReportNo(String copReportNo);

	/**
	 * Returns the cop report status of this vrcop report repository.
	 *
	 * @return the cop report status of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportStatus();

	/**
	 * Sets the cop report status of this vrcop report repository.
	 *
	 * @param copReportStatus the cop report status of this vrcop report repository
	 */
	public void setCopReportStatus(String copReportStatus);

	/**
	 * Returns the cop report type of this vrcop report repository.
	 *
	 * @return the cop report type of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportType();

	/**
	 * Sets the cop report type of this vrcop report repository.
	 *
	 * @param copReportType the cop report type of this vrcop report repository
	 */
	public void setCopReportType(String copReportType);

	/**
	 * Returns the cop report metadata of this vrcop report repository.
	 *
	 * @return the cop report metadata of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportMetadata();

	/**
	 * Sets the cop report metadata of this vrcop report repository.
	 *
	 * @param copReportMetadata the cop report metadata of this vrcop report repository
	 */
	public void setCopReportMetadata(String copReportMetadata);

	/**
	 * Returns the cop report sign name of this vrcop report repository.
	 *
	 * @return the cop report sign name of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportSignName();

	/**
	 * Sets the cop report sign name of this vrcop report repository.
	 *
	 * @param copReportSignName the cop report sign name of this vrcop report repository
	 */
	public void setCopReportSignName(String copReportSignName);

	/**
	 * Returns the cop report sign title of this vrcop report repository.
	 *
	 * @return the cop report sign title of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportSignTitle();

	/**
	 * Sets the cop report sign title of this vrcop report repository.
	 *
	 * @param copReportSignTitle the cop report sign title of this vrcop report repository
	 */
	public void setCopReportSignTitle(String copReportSignTitle);

	/**
	 * Returns the cop report sign place of this vrcop report repository.
	 *
	 * @return the cop report sign place of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportSignPlace();

	/**
	 * Sets the cop report sign place of this vrcop report repository.
	 *
	 * @param copReportSignPlace the cop report sign place of this vrcop report repository
	 */
	public void setCopReportSignPlace(String copReportSignPlace);

	/**
	 * Returns the cop report date of this vrcop report repository.
	 *
	 * @return the cop report date of this vrcop report repository
	 */
	public Date getCopReportDate();

	/**
	 * Sets the cop report date of this vrcop report repository.
	 *
	 * @param copReportDate the cop report date of this vrcop report repository
	 */
	public void setCopReportDate(Date copReportDate);

	/**
	 * Returns the cop report approved date of this vrcop report repository.
	 *
	 * @return the cop report approved date of this vrcop report repository
	 */
	public Date getCopReportApprovedDate();

	/**
	 * Sets the cop report approved date of this vrcop report repository.
	 *
	 * @param copReportApprovedDate the cop report approved date of this vrcop report repository
	 */
	public void setCopReportApprovedDate(Date copReportApprovedDate);

	/**
	 * Returns the cop report expired date of this vrcop report repository.
	 *
	 * @return the cop report expired date of this vrcop report repository
	 */
	public Date getCopReportExpiredDate();

	/**
	 * Sets the cop report expired date of this vrcop report repository.
	 *
	 * @param copReportExpiredDate the cop report expired date of this vrcop report repository
	 */
	public void setCopReportExpiredDate(Date copReportExpiredDate);

	/**
	 * Returns the cop file entry ID of this vrcop report repository.
	 *
	 * @return the cop file entry ID of this vrcop report repository
	 */
	public long getCOPFileEntryId();

	/**
	 * Sets the cop file entry ID of this vrcop report repository.
	 *
	 * @param COPFileEntryId the cop file entry ID of this vrcop report repository
	 */
	public void setCOPFileEntryId(long COPFileEntryId);

	/**
	 * Returns the modify date of this vrcop report repository.
	 *
	 * @return the modify date of this vrcop report repository
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vrcop report repository.
	 *
	 * @param modifyDate the modify date of this vrcop report repository
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vrcop report repository.
	 *
	 * @return the sync date of this vrcop report repository
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vrcop report repository.
	 *
	 * @param syncDate the sync date of this vrcop report repository
	 */
	public void setSyncDate(Date syncDate);

	/**
	 * Returns the importer manufacturer code of this vrcop report repository.
	 *
	 * @return the importer manufacturer code of this vrcop report repository
	 */
	@AutoEscape
	public String getImporterManufacturerCode();

	/**
	 * Sets the importer manufacturer code of this vrcop report repository.
	 *
	 * @param importerManufacturerCode the importer manufacturer code of this vrcop report repository
	 */
	public void setImporterManufacturerCode(String importerManufacturerCode);

	/**
	 * Returns the importer manufacturer name of this vrcop report repository.
	 *
	 * @return the importer manufacturer name of this vrcop report repository
	 */
	@AutoEscape
	public String getImporterManufacturerName();

	/**
	 * Sets the importer manufacturer name of this vrcop report repository.
	 *
	 * @param importerManufacturerName the importer manufacturer name of this vrcop report repository
	 */
	public void setImporterManufacturerName(String importerManufacturerName);

	/**
	 * Returns the importer manufacturer address of this vrcop report repository.
	 *
	 * @return the importer manufacturer address of this vrcop report repository
	 */
	@AutoEscape
	public String getImporterManufacturerAddress();

	/**
	 * Sets the importer manufacturer address of this vrcop report repository.
	 *
	 * @param importerManufacturerAddress the importer manufacturer address of this vrcop report repository
	 */
	public void setImporterManufacturerAddress(
		String importerManufacturerAddress);

	/**
	 * Returns the markup domestics manufacturer of this vrcop report repository.
	 *
	 * @return the markup domestics manufacturer of this vrcop report repository
	 */
	@AutoEscape
	public String getMarkupDomesticsManufacturer();

	/**
	 * Sets the markup domestics manufacturer of this vrcop report repository.
	 *
	 * @param markupDomesticsManufacturer the markup domestics manufacturer of this vrcop report repository
	 */
	public void setMarkupDomesticsManufacturer(
		String markupDomesticsManufacturer);

	/**
	 * Returns the markup importer of this vrcop report repository.
	 *
	 * @return the markup importer of this vrcop report repository
	 */
	@AutoEscape
	public String getMarkupImporter();

	/**
	 * Sets the markup importer of this vrcop report repository.
	 *
	 * @param markupImporter the markup importer of this vrcop report repository
	 */
	public void setMarkupImporter(String markupImporter);

	/**
	 * Returns the cop classification of this vrcop report repository.
	 *
	 * @return the cop classification of this vrcop report repository
	 */
	@AutoEscape
	public String getCopClassification();

	/**
	 * Sets the cop classification of this vrcop report repository.
	 *
	 * @param copClassification the cop classification of this vrcop report repository
	 */
	public void setCopClassification(String copClassification);

	/**
	 * Returns the product classification description of this vrcop report repository.
	 *
	 * @return the product classification description of this vrcop report repository
	 */
	@AutoEscape
	public String getProductClassificationDescription();

	/**
	 * Sets the product classification description of this vrcop report repository.
	 *
	 * @param productClassificationDescription the product classification description of this vrcop report repository
	 */
	public void setProductClassificationDescription(
		String productClassificationDescription);

	/**
	 * Returns the total point a of this vrcop report repository.
	 *
	 * @return the total point a of this vrcop report repository
	 */
	public int getTotalPointA();

	/**
	 * Sets the total point a of this vrcop report repository.
	 *
	 * @param totalPointA the total point a of this vrcop report repository
	 */
	public void setTotalPointA(int totalPointA);

	/**
	 * Returns the total point b of this vrcop report repository.
	 *
	 * @return the total point b of this vrcop report repository
	 */
	public int getTotalPointB();

	/**
	 * Sets the total point b of this vrcop report repository.
	 *
	 * @param totalPointB the total point b of this vrcop report repository
	 */
	public void setTotalPointB(int totalPointB);

	/**
	 * Returns the total point c of this vrcop report repository.
	 *
	 * @return the total point c of this vrcop report repository
	 */
	public int getTotalPointC();

	/**
	 * Sets the total point c of this vrcop report repository.
	 *
	 * @param totalPointC the total point c of this vrcop report repository
	 */
	public void setTotalPointC(int totalPointC);

	/**
	 * Returns the cop non conformity of this vrcop report repository.
	 *
	 * @return the cop non conformity of this vrcop report repository
	 */
	@AutoEscape
	public String getCopNonConformity();

	/**
	 * Sets the cop non conformity of this vrcop report repository.
	 *
	 * @param copNonConformity the cop non conformity of this vrcop report repository
	 */
	public void setCopNonConformity(String copNonConformity);

	/**
	 * Returns the inspection record no of this vrcop report repository.
	 *
	 * @return the inspection record no of this vrcop report repository
	 */
	@AutoEscape
	public String getInspectionRecordNo();

	/**
	 * Sets the inspection record no of this vrcop report repository.
	 *
	 * @param inspectionRecordNo the inspection record no of this vrcop report repository
	 */
	public void setInspectionRecordNo(String inspectionRecordNo);

	/**
	 * Returns the inspection record date of this vrcop report repository.
	 *
	 * @return the inspection record date of this vrcop report repository
	 */
	public Date getInspectionRecordDate();

	/**
	 * Sets the inspection record date of this vrcop report repository.
	 *
	 * @param inspectionRecordDate the inspection record date of this vrcop report repository
	 */
	public void setInspectionRecordDate(Date inspectionRecordDate);

	/**
	 * Returns the corporation ID of this vrcop report repository.
	 *
	 * @return the corporation ID of this vrcop report repository
	 */
	public long getCorporationId();

	/**
	 * Sets the corporation ID of this vrcop report repository.
	 *
	 * @param corporationId the corporation ID of this vrcop report repository
	 */
	public void setCorporationId(long corporationId);

	/**
	 * Returns the inspector ID of this vrcop report repository.
	 *
	 * @return the inspector ID of this vrcop report repository
	 */
	public long getInspectorId();

	/**
	 * Sets the inspector ID of this vrcop report repository.
	 *
	 * @param inspectorId the inspector ID of this vrcop report repository
	 */
	public void setInspectorId(long inspectorId);

	/**
	 * Returns the inspection site of this vrcop report repository.
	 *
	 * @return the inspection site of this vrcop report repository
	 */
	@AutoEscape
	public String getInspectionSite();

	/**
	 * Sets the inspection site of this vrcop report repository.
	 *
	 * @param inspectionSite the inspection site of this vrcop report repository
	 */
	public void setInspectionSite(String inspectionSite);

	/**
	 * Returns the inspection date from of this vrcop report repository.
	 *
	 * @return the inspection date from of this vrcop report repository
	 */
	public Date getInspectionDateFrom();

	/**
	 * Sets the inspection date from of this vrcop report repository.
	 *
	 * @param inspectionDateFrom the inspection date from of this vrcop report repository
	 */
	public void setInspectionDateFrom(Date inspectionDateFrom);

	/**
	 * Returns the inspection date to of this vrcop report repository.
	 *
	 * @return the inspection date to of this vrcop report repository
	 */
	public Date getInspectionDateTo();

	/**
	 * Sets the inspection date to of this vrcop report repository.
	 *
	 * @param inspectionDateTo the inspection date to of this vrcop report repository
	 */
	public void setInspectionDateTo(Date inspectionDateTo);

	/**
	 * Returns the sub inspector of this vrcop report repository.
	 *
	 * @return the sub inspector of this vrcop report repository
	 */
	@AutoEscape
	public String getSubInspector();

	/**
	 * Sets the sub inspector of this vrcop report repository.
	 *
	 * @param subInspector the sub inspector of this vrcop report repository
	 */
	public void setSubInspector(String subInspector);

	/**
	 * Returns the description of this vrcop report repository.
	 *
	 * @return the description of this vrcop report repository
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vrcop report repository.
	 *
	 * @param description the description of this vrcop report repository
	 */
	public void setDescription(String description);

	/**
	 * Returns the applicant representative of this vrcop report repository.
	 *
	 * @return the applicant representative of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantRepresentative();

	/**
	 * Sets the applicant representative of this vrcop report repository.
	 *
	 * @param applicantRepresentative the applicant representative of this vrcop report repository
	 */
	public void setApplicantRepresentative(String applicantRepresentative);

	/**
	 * Returns the applicant representative title of this vrcop report repository.
	 *
	 * @return the applicant representative title of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantRepresentativeTitle();

	/**
	 * Sets the applicant representative title of this vrcop report repository.
	 *
	 * @param applicantRepresentativeTitle the applicant representative title of this vrcop report repository
	 */
	public void setApplicantRepresentativeTitle(
		String applicantRepresentativeTitle);

	/**
	 * Returns the inspection record file entry ID of this vrcop report repository.
	 *
	 * @return the inspection record file entry ID of this vrcop report repository
	 */
	public long getInspectionRecordFileEntryId();

	/**
	 * Sets the inspection record file entry ID of this vrcop report repository.
	 *
	 * @param inspectionRecordFileEntryId the inspection record file entry ID of this vrcop report repository
	 */
	public void setInspectionRecordFileEntryId(long inspectionRecordFileEntryId);

	/**
	 * Returns the cop report ref no of this vrcop report repository.
	 *
	 * @return the cop report ref no of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportRefNo();

	/**
	 * Sets the cop report ref no of this vrcop report repository.
	 *
	 * @param copReportRefNo the cop report ref no of this vrcop report repository
	 */
	public void setCopReportRefNo(String copReportRefNo);

	/**
	 * Returns the cop report ref date of this vrcop report repository.
	 *
	 * @return the cop report ref date of this vrcop report repository
	 */
	public Date getCopReportRefDate();

	/**
	 * Sets the cop report ref date of this vrcop report repository.
	 *
	 * @param copReportRefDate the cop report ref date of this vrcop report repository
	 */
	public void setCopReportRefDate(Date copReportRefDate);

	/**
	 * Returns the cop report previous no of this vrcop report repository.
	 *
	 * @return the cop report previous no of this vrcop report repository
	 */
	@AutoEscape
	public String getCopReportPreviousNo();

	/**
	 * Sets the cop report previous no of this vrcop report repository.
	 *
	 * @param copReportPreviousNo the cop report previous no of this vrcop report repository
	 */
	public void setCopReportPreviousNo(String copReportPreviousNo);

	/**
	 * Returns the cop report previous date of this vrcop report repository.
	 *
	 * @return the cop report previous date of this vrcop report repository
	 */
	public Date getCopReportPreviousDate();

	/**
	 * Sets the cop report previous date of this vrcop report repository.
	 *
	 * @param copReportPreviousDate the cop report previous date of this vrcop report repository
	 */
	public void setCopReportPreviousDate(Date copReportPreviousDate);

	/**
	 * Returns the expired status of this vrcop report repository.
	 *
	 * @return the expired status of this vrcop report repository
	 */
	@AutoEscape
	public String getExpiredStatus();

	/**
	 * Sets the expired status of this vrcop report repository.
	 *
	 * @param expiredStatus the expired status of this vrcop report repository
	 */
	public void setExpiredStatus(String expiredStatus);

	/**
	 * Returns the dossier ID of this vrcop report repository.
	 *
	 * @return the dossier ID of this vrcop report repository
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vrcop report repository.
	 *
	 * @param dossierId the dossier ID of this vrcop report repository
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier ID ctn of this vrcop report repository.
	 *
	 * @return the dossier ID ctn of this vrcop report repository
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vrcop report repository.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vrcop report repository
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the dossier no of this vrcop report repository.
	 *
	 * @return the dossier no of this vrcop report repository
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vrcop report repository.
	 *
	 * @param dossierNo the dossier no of this vrcop report repository
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the applicant email of this vrcop report repository.
	 *
	 * @return the applicant email of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantEmail();

	/**
	 * Sets the applicant email of this vrcop report repository.
	 *
	 * @param applicantEmail the applicant email of this vrcop report repository
	 */
	public void setApplicantEmail(String applicantEmail);

	/**
	 * Returns the applicant phone of this vrcop report repository.
	 *
	 * @return the applicant phone of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantPhone();

	/**
	 * Sets the applicant phone of this vrcop report repository.
	 *
	 * @param applicantPhone the applicant phone of this vrcop report repository
	 */
	public void setApplicantPhone(String applicantPhone);

	/**
	 * Returns the applicant tel no of this vrcop report repository.
	 *
	 * @return the applicant tel no of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantTelNo();

	/**
	 * Sets the applicant tel no of this vrcop report repository.
	 *
	 * @param applicantTelNo the applicant tel no of this vrcop report repository
	 */
	public void setApplicantTelNo(String applicantTelNo);

	/**
	 * Returns the applicant fax of this vrcop report repository.
	 *
	 * @return the applicant fax of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantFax();

	/**
	 * Sets the applicant fax of this vrcop report repository.
	 *
	 * @param applicantFax the applicant fax of this vrcop report repository
	 */
	public void setApplicantFax(String applicantFax);

	/**
	 * Returns the applicant contact name of this vrcop report repository.
	 *
	 * @return the applicant contact name of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantContactName();

	/**
	 * Sets the applicant contact name of this vrcop report repository.
	 *
	 * @param applicantContactName the applicant contact name of this vrcop report repository
	 */
	public void setApplicantContactName(String applicantContactName);

	/**
	 * Returns the applicant contact email of this vrcop report repository.
	 *
	 * @return the applicant contact email of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantContactEmail();

	/**
	 * Sets the applicant contact email of this vrcop report repository.
	 *
	 * @param applicantContactEmail the applicant contact email of this vrcop report repository
	 */
	public void setApplicantContactEmail(String applicantContactEmail);

	/**
	 * Returns the applicant contact phone of this vrcop report repository.
	 *
	 * @return the applicant contact phone of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantContactPhone();

	/**
	 * Sets the applicant contact phone of this vrcop report repository.
	 *
	 * @param applicantContactPhone the applicant contact phone of this vrcop report repository
	 */
	public void setApplicantContactPhone(String applicantContactPhone);

	/**
	 * Returns the applicant contact tel no of this vrcop report repository.
	 *
	 * @return the applicant contact tel no of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantContactTelNo();

	/**
	 * Sets the applicant contact tel no of this vrcop report repository.
	 *
	 * @param applicantContactTelNo the applicant contact tel no of this vrcop report repository
	 */
	public void setApplicantContactTelNo(String applicantContactTelNo);

	/**
	 * Returns the applicant business type of this vrcop report repository.
	 *
	 * @return the applicant business type of this vrcop report repository
	 */
	@AutoEscape
	public String getApplicantBusinessType();

	/**
	 * Sets the applicant business type of this vrcop report repository.
	 *
	 * @param applicantBusinessType the applicant business type of this vrcop report repository
	 */
	public void setApplicantBusinessType(String applicantBusinessType);

	/**
	 * Returns the markup designer of this vrcop report repository.
	 *
	 * @return the markup designer of this vrcop report repository
	 */
	@AutoEscape
	public String getMarkupDesigner();

	/**
	 * Sets the markup designer of this vrcop report repository.
	 *
	 * @param markupDesigner the markup designer of this vrcop report repository
	 */
	public void setMarkupDesigner(String markupDesigner);

	/**
	 * Returns the markup overseas manufacturer of this vrcop report repository.
	 *
	 * @return the markup overseas manufacturer of this vrcop report repository
	 */
	@AutoEscape
	public String getMarkupOverseasManufacturer();

	/**
	 * Sets the markup overseas manufacturer of this vrcop report repository.
	 *
	 * @param markupOverseasManufacturer the markup overseas manufacturer of this vrcop report repository
	 */
	public void setMarkupOverseasManufacturer(String markupOverseasManufacturer);

	/**
	 * Returns the markup maintainer of this vrcop report repository.
	 *
	 * @return the markup maintainer of this vrcop report repository
	 */
	@AutoEscape
	public String getMarkupMaintainer();

	/**
	 * Sets the markup maintainer of this vrcop report repository.
	 *
	 * @param markupMaintainer the markup maintainer of this vrcop report repository
	 */
	public void setMarkupMaintainer(String markupMaintainer);

	/**
	 * Returns the importer domestic site of this vrcop report repository.
	 *
	 * @return the importer domestic site of this vrcop report repository
	 */
	@AutoEscape
	public String getImporterDomesticSite();

	/**
	 * Sets the importer domestic site of this vrcop report repository.
	 *
	 * @param importerDomesticSite the importer domestic site of this vrcop report repository
	 */
	public void setImporterDomesticSite(String importerDomesticSite);

	/**
	 * Returns the site of nationality of this vrcop report repository.
	 *
	 * @return the site of nationality of this vrcop report repository
	 */
	@AutoEscape
	public String getSiteOfNationality();

	/**
	 * Sets the site of nationality of this vrcop report repository.
	 *
	 * @param siteOfNationality the site of nationality of this vrcop report repository
	 */
	public void setSiteOfNationality(String siteOfNationality);

	/**
	 * Returns the site of nationality code of this vrcop report repository.
	 *
	 * @return the site of nationality code of this vrcop report repository
	 */
	@AutoEscape
	public String getSiteOfNationalityCode();

	/**
	 * Sets the site of nationality code of this vrcop report repository.
	 *
	 * @param siteOfNationalityCode the site of nationality code of this vrcop report repository
	 */
	public void setSiteOfNationalityCode(String siteOfNationalityCode);

	/**
	 * Returns the site of region of this vrcop report repository.
	 *
	 * @return the site of region of this vrcop report repository
	 */
	@AutoEscape
	public String getSiteOfRegion();

	/**
	 * Sets the site of region of this vrcop report repository.
	 *
	 * @param siteOfRegion the site of region of this vrcop report repository
	 */
	public void setSiteOfRegion(String siteOfRegion);

	/**
	 * Returns the site of region code of this vrcop report repository.
	 *
	 * @return the site of region code of this vrcop report repository
	 */
	@AutoEscape
	public String getSiteOfRegionCode();

	/**
	 * Sets the site of region code of this vrcop report repository.
	 *
	 * @param siteOfRegionCode the site of region code of this vrcop report repository
	 */
	public void setSiteOfRegionCode(String siteOfRegionCode);

	/**
	 * Returns the site of city of this vrcop report repository.
	 *
	 * @return the site of city of this vrcop report repository
	 */
	@AutoEscape
	public String getSiteOfCity();

	/**
	 * Sets the site of city of this vrcop report repository.
	 *
	 * @param siteOfCity the site of city of this vrcop report repository
	 */
	public void setSiteOfCity(String siteOfCity);

	/**
	 * Returns the site of city code of this vrcop report repository.
	 *
	 * @return the site of city code of this vrcop report repository
	 */
	@AutoEscape
	public String getSiteOfCityCode();

	/**
	 * Sets the site of city code of this vrcop report repository.
	 *
	 * @param siteOfCityCode the site of city code of this vrcop report repository
	 */
	public void setSiteOfCityCode(String siteOfCityCode);

	/**
	 * Returns the manufacturer representative of this vrcop report repository.
	 *
	 * @return the manufacturer representative of this vrcop report repository
	 */
	@AutoEscape
	public String getManufacturerRepresentative();

	/**
	 * Sets the manufacturer representative of this vrcop report repository.
	 *
	 * @param manufacturerRepresentative the manufacturer representative of this vrcop report repository
	 */
	public void setManufacturerRepresentative(String manufacturerRepresentative);

	/**
	 * Returns the manufacturer representative title of this vrcop report repository.
	 *
	 * @return the manufacturer representative title of this vrcop report repository
	 */
	@AutoEscape
	public String getManufacturerRepresentativeTitle();

	/**
	 * Sets the manufacturer representative title of this vrcop report repository.
	 *
	 * @param manufacturerRepresentativeTitle the manufacturer representative title of this vrcop report repository
	 */
	public void setManufacturerRepresentativeTitle(
		String manufacturerRepresentativeTitle);

	/**
	 * Returns the manufacturer email of this vrcop report repository.
	 *
	 * @return the manufacturer email of this vrcop report repository
	 */
	@AutoEscape
	public String getManufacturerEmail();

	/**
	 * Sets the manufacturer email of this vrcop report repository.
	 *
	 * @param manufacturerEmail the manufacturer email of this vrcop report repository
	 */
	public void setManufacturerEmail(String manufacturerEmail);

	/**
	 * Returns the manufacturer phone of this vrcop report repository.
	 *
	 * @return the manufacturer phone of this vrcop report repository
	 */
	@AutoEscape
	public String getManufacturerPhone();

	/**
	 * Sets the manufacturer phone of this vrcop report repository.
	 *
	 * @param manufacturerPhone the manufacturer phone of this vrcop report repository
	 */
	public void setManufacturerPhone(String manufacturerPhone);

	/**
	 * Returns the manufacturer fax of this vrcop report repository.
	 *
	 * @return the manufacturer fax of this vrcop report repository
	 */
	@AutoEscape
	public String getManufacturerFax();

	/**
	 * Sets the manufacturer fax of this vrcop report repository.
	 *
	 * @param manufacturerFax the manufacturer fax of this vrcop report repository
	 */
	public void setManufacturerFax(String manufacturerFax);

	/**
	 * Returns the production plant email of this vrcop report repository.
	 *
	 * @return the production plant email of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionPlantEmail();

	/**
	 * Sets the production plant email of this vrcop report repository.
	 *
	 * @param productionPlantEmail the production plant email of this vrcop report repository
	 */
	public void setProductionPlantEmail(String productionPlantEmail);

	/**
	 * Returns the production plant website of this vrcop report repository.
	 *
	 * @return the production plant website of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionPlantWebsite();

	/**
	 * Sets the production plant website of this vrcop report repository.
	 *
	 * @param productionPlantWebsite the production plant website of this vrcop report repository
	 */
	public void setProductionPlantWebsite(String productionPlantWebsite);

	/**
	 * Returns the production plant representative of this vrcop report repository.
	 *
	 * @return the production plant representative of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionPlantRepresentative();

	/**
	 * Sets the production plant representative of this vrcop report repository.
	 *
	 * @param productionPlantRepresentative the production plant representative of this vrcop report repository
	 */
	public void setProductionPlantRepresentative(
		String productionPlantRepresentative);

	/**
	 * Returns the production plant representative title of this vrcop report repository.
	 *
	 * @return the production plant representative title of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionPlantRepresentativeTitle();

	/**
	 * Sets the production plant representative title of this vrcop report repository.
	 *
	 * @param productionPlantRepresentativeTitle the production plant representative title of this vrcop report repository
	 */
	public void setProductionPlantRepresentativeTitle(
		String productionPlantRepresentativeTitle);

	/**
	 * Returns the corporation name of this vrcop report repository.
	 *
	 * @return the corporation name of this vrcop report repository
	 */
	@AutoEscape
	public String getCorporationName();

	/**
	 * Sets the corporation name of this vrcop report repository.
	 *
	 * @param corporationName the corporation name of this vrcop report repository
	 */
	public void setCorporationName(String corporationName);

	/**
	 * Returns the inspector contact code of this vrcop report repository.
	 *
	 * @return the inspector contact code of this vrcop report repository
	 */
	@AutoEscape
	public String getInspectorContactCode();

	/**
	 * Sets the inspector contact code of this vrcop report repository.
	 *
	 * @param inspectorContactCode the inspector contact code of this vrcop report repository
	 */
	public void setInspectorContactCode(String inspectorContactCode);

	/**
	 * Returns the inspector name of this vrcop report repository.
	 *
	 * @return the inspector name of this vrcop report repository
	 */
	@AutoEscape
	public String getInspectorName();

	/**
	 * Sets the inspector name of this vrcop report repository.
	 *
	 * @param inspectorName the inspector name of this vrcop report repository
	 */
	public void setInspectorName(String inspectorName);

	/**
	 * Returns the inspecto rendor sement date of this vrcop report repository.
	 *
	 * @return the inspecto rendor sement date of this vrcop report repository
	 */
	public Date getInspectoRendorSementDate();

	/**
	 * Sets the inspecto rendor sement date of this vrcop report repository.
	 *
	 * @param inspectoRendorSementDate the inspecto rendor sement date of this vrcop report repository
	 */
	public void setInspectoRendorSementDate(Date inspectoRendorSementDate);

	/**
	 * Returns the inspector deadline of this vrcop report repository.
	 *
	 * @return the inspector deadline of this vrcop report repository
	 */
	public Date getInspectorDeadline();

	/**
	 * Sets the inspector deadline of this vrcop report repository.
	 *
	 * @param inspectorDeadline the inspector deadline of this vrcop report repository
	 */
	public void setInspectorDeadline(Date inspectorDeadline);

	/**
	 * Returns the resolved status of this vrcop report repository.
	 *
	 * @return the resolved status of this vrcop report repository
	 */
	@AutoEscape
	public String getResolvedStatus();

	/**
	 * Sets the resolved status of this vrcop report repository.
	 *
	 * @param resolvedStatus the resolved status of this vrcop report repository
	 */
	public void setResolvedStatus(String resolvedStatus);

	/**
	 * Returns the number of non conformity of this vrcop report repository.
	 *
	 * @return the number of non conformity of this vrcop report repository
	 */
	public int getNumberOfNonConformity();

	/**
	 * Sets the number of non conformity of this vrcop report repository.
	 *
	 * @param numberOfNonConformity the number of non conformity of this vrcop report repository
	 */
	public void setNumberOfNonConformity(int numberOfNonConformity);

	/**
	 * Returns the number of resolved of this vrcop report repository.
	 *
	 * @return the number of resolved of this vrcop report repository
	 */
	public int getNumberOfResolved();

	/**
	 * Sets the number of resolved of this vrcop report repository.
	 *
	 * @param numberOfResolved the number of resolved of this vrcop report repository
	 */
	public void setNumberOfResolved(int numberOfResolved);

	/**
	 * Returns the observation description of this vrcop report repository.
	 *
	 * @return the observation description of this vrcop report repository
	 */
	@AutoEscape
	public String getObservationDescription();

	/**
	 * Sets the observation description of this vrcop report repository.
	 *
	 * @param observationDescription the observation description of this vrcop report repository
	 */
	public void setObservationDescription(String observationDescription);

	/**
	 * Returns the inspection audit cycle of this vrcop report repository.
	 *
	 * @return the inspection audit cycle of this vrcop report repository
	 */
	@AutoEscape
	public String getInspectionAuditCycle();

	/**
	 * Sets the inspection audit cycle of this vrcop report repository.
	 *
	 * @param inspectionAuditCycle the inspection audit cycle of this vrcop report repository
	 */
	public void setInspectionAuditCycle(String inspectionAuditCycle);

	/**
	 * Returns the inspection note of this vrcop report repository.
	 *
	 * @return the inspection note of this vrcop report repository
	 */
	@AutoEscape
	public String getInspectionNote();

	/**
	 * Sets the inspection note of this vrcop report repository.
	 *
	 * @param inspectionNote the inspection note of this vrcop report repository
	 */
	public void setInspectionNote(String inspectionNote);

	/**
	 * Returns the production conformity checking of this vrcop report repository.
	 *
	 * @return the production conformity checking of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionConformityChecking();

	/**
	 * Sets the production conformity checking of this vrcop report repository.
	 *
	 * @param productionConformityChecking the production conformity checking of this vrcop report repository
	 */
	public void setProductionConformityChecking(
		String productionConformityChecking);

	/**
	 * Returns the production stamp checking of this vrcop report repository.
	 *
	 * @return the production stamp checking of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionStampChecking();

	/**
	 * Sets the production stamp checking of this vrcop report repository.
	 *
	 * @param productionStampChecking the production stamp checking of this vrcop report repository
	 */
	public void setProductionStampChecking(String productionStampChecking);

	/**
	 * Returns the testing equipment checking of this vrcop report repository.
	 *
	 * @return the testing equipment checking of this vrcop report repository
	 */
	@AutoEscape
	public String getTestingEquipmentChecking();

	/**
	 * Sets the testing equipment checking of this vrcop report repository.
	 *
	 * @param testingEquipmentChecking the testing equipment checking of this vrcop report repository
	 */
	public void setTestingEquipmentChecking(String testingEquipmentChecking);

	/**
	 * Returns the production plant classification of this vrcop report repository.
	 *
	 * @return the production plant classification of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionPlantClassification();

	/**
	 * Sets the production plant classification of this vrcop report repository.
	 *
	 * @param productionPlantClassification the production plant classification of this vrcop report repository
	 */
	public void setProductionPlantClassification(
		String productionPlantClassification);

	/**
	 * Returns the actual capacity of this vrcop report repository.
	 *
	 * @return the actual capacity of this vrcop report repository
	 */
	@AutoEscape
	public String getActualCapacity();

	/**
	 * Sets the actual capacity of this vrcop report repository.
	 *
	 * @param actualCapacity the actual capacity of this vrcop report repository
	 */
	public void setActualCapacity(String actualCapacity);

	/**
	 * Returns the max capacity of this vrcop report repository.
	 *
	 * @return the max capacity of this vrcop report repository
	 */
	@AutoEscape
	public String getMaxCapacity();

	/**
	 * Sets the max capacity of this vrcop report repository.
	 *
	 * @param maxCapacity the max capacity of this vrcop report repository
	 */
	public void setMaxCapacity(String maxCapacity);

	/**
	 * Returns the average capacity of this vrcop report repository.
	 *
	 * @return the average capacity of this vrcop report repository
	 */
	@AutoEscape
	public String getAverageCapacity();

	/**
	 * Sets the average capacity of this vrcop report repository.
	 *
	 * @param averageCapacity the average capacity of this vrcop report repository
	 */
	public void setAverageCapacity(String averageCapacity);

	/**
	 * Returns the total employee of this vrcop report repository.
	 *
	 * @return the total employee of this vrcop report repository
	 */
	@AutoEscape
	public String getTotalEmployee();

	/**
	 * Sets the total employee of this vrcop report repository.
	 *
	 * @param totalEmployee the total employee of this vrcop report repository
	 */
	public void setTotalEmployee(String totalEmployee);

	/**
	 * Returns the total worker of this vrcop report repository.
	 *
	 * @return the total worker of this vrcop report repository
	 */
	@AutoEscape
	public String getTotalWorker();

	/**
	 * Sets the total worker of this vrcop report repository.
	 *
	 * @param totalWorker the total worker of this vrcop report repository
	 */
	public void setTotalWorker(String totalWorker);

	/**
	 * Returns the total manager of this vrcop report repository.
	 *
	 * @return the total manager of this vrcop report repository
	 */
	@AutoEscape
	public String getTotalManager();

	/**
	 * Sets the total manager of this vrcop report repository.
	 *
	 * @param totalManager the total manager of this vrcop report repository
	 */
	public void setTotalManager(String totalManager);

	/**
	 * Returns the total technical of this vrcop report repository.
	 *
	 * @return the total technical of this vrcop report repository
	 */
	@AutoEscape
	public String getTotalTechnical();

	/**
	 * Sets the total technical of this vrcop report repository.
	 *
	 * @param totalTechnical the total technical of this vrcop report repository
	 */
	public void setTotalTechnical(String totalTechnical);

	/**
	 * Returns the total qa employee of this vrcop report repository.
	 *
	 * @return the total qa employee of this vrcop report repository
	 */
	@AutoEscape
	public String getTotalQaEmployee();

	/**
	 * Sets the total qa employee of this vrcop report repository.
	 *
	 * @param totalQaEmployee the total qa employee of this vrcop report repository
	 */
	public void setTotalQaEmployee(String totalQaEmployee);

	/**
	 * Returns the total square meter of this vrcop report repository.
	 *
	 * @return the total square meter of this vrcop report repository
	 */
	@AutoEscape
	public String getTotalSquareMeter();

	/**
	 * Sets the total square meter of this vrcop report repository.
	 *
	 * @param totalSquareMeter the total square meter of this vrcop report repository
	 */
	public void setTotalSquareMeter(String totalSquareMeter);

	/**
	 * Returns the ware house square of this vrcop report repository.
	 *
	 * @return the ware house square of this vrcop report repository
	 */
	@AutoEscape
	public String getWareHouseSquare();

	/**
	 * Sets the ware house square of this vrcop report repository.
	 *
	 * @param wareHouseSquare the ware house square of this vrcop report repository
	 */
	public void setWareHouseSquare(String wareHouseSquare);

	/**
	 * Returns the office square of this vrcop report repository.
	 *
	 * @return the office square of this vrcop report repository
	 */
	@AutoEscape
	public String getOfficeSquare();

	/**
	 * Sets the office square of this vrcop report repository.
	 *
	 * @param officeSquare the office square of this vrcop report repository
	 */
	public void setOfficeSquare(String officeSquare);

	/**
	 * Returns the production square of this vrcop report repository.
	 *
	 * @return the production square of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionSquare();

	/**
	 * Sets the production square of this vrcop report repository.
	 *
	 * @param productionSquare the production square of this vrcop report repository
	 */
	public void setProductionSquare(String productionSquare);

	/**
	 * Returns the machining area of this vrcop report repository.
	 *
	 * @return the machining area of this vrcop report repository
	 */
	@AutoEscape
	public String getMachiningArea();

	/**
	 * Sets the machining area of this vrcop report repository.
	 *
	 * @param machiningArea the machining area of this vrcop report repository
	 */
	public void setMachiningArea(String machiningArea);

	/**
	 * Returns the welding area of this vrcop report repository.
	 *
	 * @return the welding area of this vrcop report repository
	 */
	@AutoEscape
	public String getWeldingArea();

	/**
	 * Sets the welding area of this vrcop report repository.
	 *
	 * @param weldingArea the welding area of this vrcop report repository
	 */
	public void setWeldingArea(String weldingArea);

	/**
	 * Returns the painting area of this vrcop report repository.
	 *
	 * @return the painting area of this vrcop report repository
	 */
	@AutoEscape
	public String getPaintingArea();

	/**
	 * Sets the painting area of this vrcop report repository.
	 *
	 * @param paintingArea the painting area of this vrcop report repository
	 */
	public void setPaintingArea(String paintingArea);

	/**
	 * Returns the production assemble area of this vrcop report repository.
	 *
	 * @return the production assemble area of this vrcop report repository
	 */
	@AutoEscape
	public String getProductionAssembleArea();

	/**
	 * Sets the production assemble area of this vrcop report repository.
	 *
	 * @param productionAssembleArea the production assemble area of this vrcop report repository
	 */
	public void setProductionAssembleArea(String productionAssembleArea);

	/**
	 * Returns the finish product area of this vrcop report repository.
	 *
	 * @return the finish product area of this vrcop report repository
	 */
	@AutoEscape
	public String getFinishProductArea();

	/**
	 * Sets the finish product area of this vrcop report repository.
	 *
	 * @param finishProductArea the finish product area of this vrcop report repository
	 */
	public void setFinishProductArea(String finishProductArea);

	/**
	 * Returns the testing area of this vrcop report repository.
	 *
	 * @return the testing area of this vrcop report repository
	 */
	@AutoEscape
	public String getTestingArea();

	/**
	 * Sets the testing area of this vrcop report repository.
	 *
	 * @param testingArea the testing area of this vrcop report repository
	 */
	public void setTestingArea(String testingArea);

	/**
	 * Returns the self equipment of this vrcop report repository.
	 *
	 * @return the self equipment of this vrcop report repository
	 */
	@AutoEscape
	public String getSelfEquipment();

	/**
	 * Sets the self equipment of this vrcop report repository.
	 *
	 * @param selfEquipment the self equipment of this vrcop report repository
	 */
	public void setSelfEquipment(String selfEquipment);

	/**
	 * Returns the contract equipment of this vrcop report repository.
	 *
	 * @return the contract equipment of this vrcop report repository
	 */
	@AutoEscape
	public String getContractEquipment();

	/**
	 * Sets the contract equipment of this vrcop report repository.
	 *
	 * @param contractEquipment the contract equipment of this vrcop report repository
	 */
	public void setContractEquipment(String contractEquipment);

	/**
	 * Returns the circular no of this vrcop report repository.
	 *
	 * @return the circular no of this vrcop report repository
	 */
	@AutoEscape
	public String getCircularNo();

	/**
	 * Sets the circular no of this vrcop report repository.
	 *
	 * @param circularNo the circular no of this vrcop report repository
	 */
	public void setCircularNo(String circularNo);

	/**
	 * Returns the circular date of this vrcop report repository.
	 *
	 * @return the circular date of this vrcop report repository
	 */
	public Date getCircularDate();

	/**
	 * Sets the circular date of this vrcop report repository.
	 *
	 * @param circularDate the circular date of this vrcop report repository
	 */
	public void setCircularDate(Date circularDate);

	/**
	 * Returns the circular no2 of this vrcop report repository.
	 *
	 * @return the circular no2 of this vrcop report repository
	 */
	@AutoEscape
	public String getCircularNo2();

	/**
	 * Sets the circular no2 of this vrcop report repository.
	 *
	 * @param circularNo2 the circular no2 of this vrcop report repository
	 */
	public void setCircularNo2(String circularNo2);

	/**
	 * Returns the circular date2 of this vrcop report repository.
	 *
	 * @return the circular date2 of this vrcop report repository
	 */
	public Date getCircularDate2();

	/**
	 * Sets the circular date2 of this vrcop report repository.
	 *
	 * @param circularDate2 the circular date2 of this vrcop report repository
	 */
	public void setCircularDate2(Date circularDate2);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRCOPReportRepository vrcopReportRepository);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRCOPReportRepository> toCacheModel();

	@Override
	public VRCOPReportRepository toEscapedModel();

	@Override
	public VRCOPReportRepository toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}