/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRCorporationAttendee service. Represents a row in the &quot;vr_corporation_attendee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRCorporationAttendeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRCorporationAttendeeImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRCorporationAttendee
 * @see com.fds.vr.business.model.impl.VRCorporationAttendeeImpl
 * @see com.fds.vr.business.model.impl.VRCorporationAttendeeModelImpl
 * @generated
 */
@ProviderType
public interface VRCorporationAttendeeModel extends BaseModel<VRCorporationAttendee> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr corporation attendee model instance should use the {@link VRCorporationAttendee} interface instead.
	 */

	/**
	 * Returns the primary key of this vr corporation attendee.
	 *
	 * @return the primary key of this vr corporation attendee
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr corporation attendee.
	 *
	 * @param primaryKey the primary key of this vr corporation attendee
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr corporation attendee.
	 *
	 * @return the ID of this vr corporation attendee
	 */
	public long getId();

	/**
	 * Sets the ID of this vr corporation attendee.
	 *
	 * @param id the ID of this vr corporation attendee
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr corporation attendee.
	 *
	 * @return the mt core of this vr corporation attendee
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr corporation attendee.
	 *
	 * @param mtCore the mt core of this vr corporation attendee
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the create date of this vr corporation attendee.
	 *
	 * @return the create date of this vr corporation attendee
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this vr corporation attendee.
	 *
	 * @param createDate the create date of this vr corporation attendee
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modify date of this vr corporation attendee.
	 *
	 * @return the modify date of this vr corporation attendee
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr corporation attendee.
	 *
	 * @param modifyDate the modify date of this vr corporation attendee
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr corporation attendee.
	 *
	 * @return the sync date of this vr corporation attendee
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr corporation attendee.
	 *
	 * @param syncDate the sync date of this vr corporation attendee
	 */
	public void setSyncDate(Date syncDate);

	/**
	 * Returns the corporation code of this vr corporation attendee.
	 *
	 * @return the corporation code of this vr corporation attendee
	 */
	@AutoEscape
	public String getCorporationCode();

	/**
	 * Sets the corporation code of this vr corporation attendee.
	 *
	 * @param corporationCode the corporation code of this vr corporation attendee
	 */
	public void setCorporationCode(String corporationCode);

	/**
	 * Returns the corporation name of this vr corporation attendee.
	 *
	 * @return the corporation name of this vr corporation attendee
	 */
	@AutoEscape
	public String getCorporationName();

	/**
	 * Sets the corporation name of this vr corporation attendee.
	 *
	 * @param corporationName the corporation name of this vr corporation attendee
	 */
	public void setCorporationName(String corporationName);

	/**
	 * Returns the inspection date of this vr corporation attendee.
	 *
	 * @return the inspection date of this vr corporation attendee
	 */
	public Date getInspectionDate();

	/**
	 * Sets the inspection date of this vr corporation attendee.
	 *
	 * @param inspectionDate the inspection date of this vr corporation attendee
	 */
	public void setInspectionDate(Date inspectionDate);

	/**
	 * Returns the registerednumber of this vr corporation attendee.
	 *
	 * @return the registerednumber of this vr corporation attendee
	 */
	@AutoEscape
	public String getRegisterednumber();

	/**
	 * Sets the registerednumber of this vr corporation attendee.
	 *
	 * @param registerednumber the registerednumber of this vr corporation attendee
	 */
	public void setRegisterednumber(String registerednumber);

	/**
	 * Returns the testing registered place of this vr corporation attendee.
	 *
	 * @return the testing registered place of this vr corporation attendee
	 */
	@AutoEscape
	public String getTestingRegisteredPlace();

	/**
	 * Sets the testing registered place of this vr corporation attendee.
	 *
	 * @param testingRegisteredPlace the testing registered place of this vr corporation attendee
	 */
	public void setTestingRegisteredPlace(String testingRegisteredPlace);

	/**
	 * Returns the testing place district of this vr corporation attendee.
	 *
	 * @return the testing place district of this vr corporation attendee
	 */
	@AutoEscape
	public String getTestingPlaceDistrict();

	/**
	 * Sets the testing place district of this vr corporation attendee.
	 *
	 * @param testingPlaceDistrict the testing place district of this vr corporation attendee
	 */
	public void setTestingPlaceDistrict(String testingPlaceDistrict);

	/**
	 * Returns the testing place city of this vr corporation attendee.
	 *
	 * @return the testing place city of this vr corporation attendee
	 */
	@AutoEscape
	public String getTestingPlaceCity();

	/**
	 * Sets the testing place city of this vr corporation attendee.
	 *
	 * @param testingPlaceCity the testing place city of this vr corporation attendee
	 */
	public void setTestingPlaceCity(String testingPlaceCity);

	/**
	 * Returns the testing place region of this vr corporation attendee.
	 *
	 * @return the testing place region of this vr corporation attendee
	 */
	@AutoEscape
	public String getTestingPlaceRegion();

	/**
	 * Sets the testing place region of this vr corporation attendee.
	 *
	 * @param testingPlaceRegion the testing place region of this vr corporation attendee
	 */
	public void setTestingPlaceRegion(String testingPlaceRegion);

	/**
	 * Returns the testing place country of this vr corporation attendee.
	 *
	 * @return the testing place country of this vr corporation attendee
	 */
	@AutoEscape
	public String getTestingPlaceCountry();

	/**
	 * Sets the testing place country of this vr corporation attendee.
	 *
	 * @param testingPlaceCountry the testing place country of this vr corporation attendee
	 */
	public void setTestingPlaceCountry(String testingPlaceCountry);

	/**
	 * Returns the testing remarks of this vr corporation attendee.
	 *
	 * @return the testing remarks of this vr corporation attendee
	 */
	@AutoEscape
	public String getTestingRemarks();

	/**
	 * Sets the testing remarks of this vr corporation attendee.
	 *
	 * @param testingRemarks the testing remarks of this vr corporation attendee
	 */
	public void setTestingRemarks(String testingRemarks);

	/**
	 * Returns the activity ID of this vr corporation attendee.
	 *
	 * @return the activity ID of this vr corporation attendee
	 */
	public long getActivityId();

	/**
	 * Sets the activity ID of this vr corporation attendee.
	 *
	 * @param activityId the activity ID of this vr corporation attendee
	 */
	public void setActivityId(long activityId);

	/**
	 * Returns the user ID of this vr corporation attendee.
	 *
	 * @return the user ID of this vr corporation attendee
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this vr corporation attendee.
	 *
	 * @param userId the user ID of this vr corporation attendee
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vr corporation attendee.
	 *
	 * @return the user uuid of this vr corporation attendee
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this vr corporation attendee.
	 *
	 * @param userUuid the user uuid of this vr corporation attendee
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vr corporation attendee.
	 *
	 * @return the user name of this vr corporation attendee
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this vr corporation attendee.
	 *
	 * @param userName the user name of this vr corporation attendee
	 */
	public void setUserName(String userName);

	/**
	 * Returns the activity type of this vr corporation attendee.
	 *
	 * @return the activity type of this vr corporation attendee
	 */
	@AutoEscape
	public String getActivityType();

	/**
	 * Sets the activity type of this vr corporation attendee.
	 *
	 * @param activityType the activity type of this vr corporation attendee
	 */
	public void setActivityType(String activityType);

	/**
	 * Returns the activity catetory of this vr corporation attendee.
	 *
	 * @return the activity catetory of this vr corporation attendee
	 */
	@AutoEscape
	public String getActivityCatetory();

	/**
	 * Sets the activity catetory of this vr corporation attendee.
	 *
	 * @param activityCatetory the activity catetory of this vr corporation attendee
	 */
	public void setActivityCatetory(String activityCatetory);

	/**
	 * Returns the category name of this vr corporation attendee.
	 *
	 * @return the category name of this vr corporation attendee
	 */
	@AutoEscape
	public String getCategoryName();

	/**
	 * Sets the category name of this vr corporation attendee.
	 *
	 * @param categoryName the category name of this vr corporation attendee
	 */
	public void setCategoryName(String categoryName);

	/**
	 * Returns the dossier ID of this vr corporation attendee.
	 *
	 * @return the dossier ID of this vr corporation attendee
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr corporation attendee.
	 *
	 * @param dossierId the dossier ID of this vr corporation attendee
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the service name of this vr corporation attendee.
	 *
	 * @return the service name of this vr corporation attendee
	 */
	@AutoEscape
	public String getServiceName();

	/**
	 * Sets the service name of this vr corporation attendee.
	 *
	 * @param serviceName the service name of this vr corporation attendee
	 */
	public void setServiceName(String serviceName);

	/**
	 * Returns the subject of this vr corporation attendee.
	 *
	 * @return the subject of this vr corporation attendee
	 */
	@AutoEscape
	public String getSubject();

	/**
	 * Sets the subject of this vr corporation attendee.
	 *
	 * @param subject the subject of this vr corporation attendee
	 */
	public void setSubject(String subject);

	/**
	 * Returns the hosting ID of this vr corporation attendee.
	 *
	 * @return the hosting ID of this vr corporation attendee
	 */
	public int getHostingId();

	/**
	 * Sets the hosting ID of this vr corporation attendee.
	 *
	 * @param hostingId the hosting ID of this vr corporation attendee
	 */
	public void setHostingId(int hostingId);

	/**
	 * Returns the hosting of this vr corporation attendee.
	 *
	 * @return the hosting of this vr corporation attendee
	 */
	@AutoEscape
	public String getHosting();

	/**
	 * Sets the hosting of this vr corporation attendee.
	 *
	 * @param hosting the hosting of this vr corporation attendee
	 */
	public void setHosting(String hosting);

	/**
	 * Returns the location ID of this vr corporation attendee.
	 *
	 * @return the location ID of this vr corporation attendee
	 */
	public int getLocationId();

	/**
	 * Sets the location ID of this vr corporation attendee.
	 *
	 * @param locationId the location ID of this vr corporation attendee
	 */
	public void setLocationId(int locationId);

	/**
	 * Returns the location of this vr corporation attendee.
	 *
	 * @return the location of this vr corporation attendee
	 */
	@AutoEscape
	public String getLocation();

	/**
	 * Sets the location of this vr corporation attendee.
	 *
	 * @param location the location of this vr corporation attendee
	 */
	public void setLocation(String location);

	/**
	 * Returns the geolocation of this vr corporation attendee.
	 *
	 * @return the geolocation of this vr corporation attendee
	 */
	@AutoEscape
	public String getGeolocation();

	/**
	 * Sets the geolocation of this vr corporation attendee.
	 *
	 * @param geolocation the geolocation of this vr corporation attendee
	 */
	public void setGeolocation(String geolocation);

	/**
	 * Returns the start date of this vr corporation attendee.
	 *
	 * @return the start date of this vr corporation attendee
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this vr corporation attendee.
	 *
	 * @param startDate the start date of this vr corporation attendee
	 */
	public void setStartDate(Date startDate);

	/**
	 * Returns the end date of this vr corporation attendee.
	 *
	 * @return the end date of this vr corporation attendee
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this vr corporation attendee.
	 *
	 * @param endDate the end date of this vr corporation attendee
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the finish date of this vr corporation attendee.
	 *
	 * @return the finish date of this vr corporation attendee
	 */
	public Date getFinishDate();

	/**
	 * Sets the finish date of this vr corporation attendee.
	 *
	 * @param finishDate the finish date of this vr corporation attendee
	 */
	public void setFinishDate(Date finishDate);

	/**
	 * Returns the state of this vr corporation attendee.
	 *
	 * @return the state of this vr corporation attendee
	 */
	@AutoEscape
	public String getState();

	/**
	 * Sets the state of this vr corporation attendee.
	 *
	 * @param state the state of this vr corporation attendee
	 */
	public void setState(String state);

	/**
	 * Returns the state name of this vr corporation attendee.
	 *
	 * @return the state name of this vr corporation attendee
	 */
	@AutoEscape
	public String getStateName();

	/**
	 * Sets the state name of this vr corporation attendee.
	 *
	 * @param stateName the state name of this vr corporation attendee
	 */
	public void setStateName(String stateName);

	/**
	 * Returns the state color of this vr corporation attendee.
	 *
	 * @return the state color of this vr corporation attendee
	 */
	@AutoEscape
	public String getStateColor();

	/**
	 * Sets the state color of this vr corporation attendee.
	 *
	 * @param stateColor the state color of this vr corporation attendee
	 */
	public void setStateColor(String stateColor);

	/**
	 * Returns the priority of this vr corporation attendee.
	 *
	 * @return the priority of this vr corporation attendee
	 */
	@AutoEscape
	public String getPriority();

	/**
	 * Sets the priority of this vr corporation attendee.
	 *
	 * @param priority the priority of this vr corporation attendee
	 */
	public void setPriority(String priority);

	/**
	 * Returns the overdue of this vr corporation attendee.
	 *
	 * @return the overdue of this vr corporation attendee
	 */
	@AutoEscape
	public String getOverdue();

	/**
	 * Sets the overdue of this vr corporation attendee.
	 *
	 * @param overdue the overdue of this vr corporation attendee
	 */
	public void setOverdue(String overdue);

	/**
	 * Returns the manager ID of this vr corporation attendee.
	 *
	 * @return the manager ID of this vr corporation attendee
	 */
	public long getManagerId();

	/**
	 * Sets the manager ID of this vr corporation attendee.
	 *
	 * @param managerId the manager ID of this vr corporation attendee
	 */
	public void setManagerId(long managerId);

	/**
	 * Returns the manager name of this vr corporation attendee.
	 *
	 * @return the manager name of this vr corporation attendee
	 */
	@AutoEscape
	public String getManagerName();

	/**
	 * Sets the manager name of this vr corporation attendee.
	 *
	 * @param managerName the manager name of this vr corporation attendee
	 */
	public void setManagerName(String managerName);

	/**
	 * Returns the leader ID of this vr corporation attendee.
	 *
	 * @return the leader ID of this vr corporation attendee
	 */
	public long getLeaderId();

	/**
	 * Sets the leader ID of this vr corporation attendee.
	 *
	 * @param leaderId the leader ID of this vr corporation attendee
	 */
	public void setLeaderId(long leaderId);

	/**
	 * Returns the leader name of this vr corporation attendee.
	 *
	 * @return the leader name of this vr corporation attendee
	 */
	@AutoEscape
	public String getLeaderName();

	/**
	 * Sets the leader name of this vr corporation attendee.
	 *
	 * @param leaderName the leader name of this vr corporation attendee
	 */
	public void setLeaderName(String leaderName);

	/**
	 * Returns the leader job title of this vr corporation attendee.
	 *
	 * @return the leader job title of this vr corporation attendee
	 */
	@AutoEscape
	public String getLeaderJobTitle();

	/**
	 * Sets the leader job title of this vr corporation attendee.
	 *
	 * @param leaderJobTitle the leader job title of this vr corporation attendee
	 */
	public void setLeaderJobTitle(String leaderJobTitle);

	/**
	 * Returns the description of this vr corporation attendee.
	 *
	 * @return the description of this vr corporation attendee
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this vr corporation attendee.
	 *
	 * @param description the description of this vr corporation attendee
	 */
	public void setDescription(String description);

	/**
	 * Returns the permission of this vr corporation attendee.
	 *
	 * @return the permission of this vr corporation attendee
	 */
	@AutoEscape
	public String getPermission();

	/**
	 * Sets the permission of this vr corporation attendee.
	 *
	 * @param permission the permission of this vr corporation attendee
	 */
	public void setPermission(String permission);

	/**
	 * Returns the result note of this vr corporation attendee.
	 *
	 * @return the result note of this vr corporation attendee
	 */
	@AutoEscape
	public String getResultNote();

	/**
	 * Sets the result note of this vr corporation attendee.
	 *
	 * @param resultNote the result note of this vr corporation attendee
	 */
	public void setResultNote(String resultNote);

	/**
	 * Returns the progress of this vr corporation attendee.
	 *
	 * @return the progress of this vr corporation attendee
	 */
	@AutoEscape
	public String getProgress();

	/**
	 * Sets the progress of this vr corporation attendee.
	 *
	 * @param progress the progress of this vr corporation attendee
	 */
	public void setProgress(String progress);

	/**
	 * Returns the assign type of this vr corporation attendee.
	 *
	 * @return the assign type of this vr corporation attendee
	 */
	@AutoEscape
	public String getAssignType();

	/**
	 * Sets the assign type of this vr corporation attendee.
	 *
	 * @param assignType the assign type of this vr corporation attendee
	 */
	public void setAssignType(String assignType);

	/**
	 * Returns the job pos ID of this vr corporation attendee.
	 *
	 * @return the job pos ID of this vr corporation attendee
	 */
	public long getJobPosId();

	/**
	 * Sets the job pos ID of this vr corporation attendee.
	 *
	 * @param jobPosId the job pos ID of this vr corporation attendee
	 */
	public void setJobPosId(long jobPosId);

	/**
	 * Returns the job pos title of this vr corporation attendee.
	 *
	 * @return the job pos title of this vr corporation attendee
	 */
	@AutoEscape
	public String getJobPosTitle();

	/**
	 * Sets the job pos title of this vr corporation attendee.
	 *
	 * @param jobPosTitle the job pos title of this vr corporation attendee
	 */
	public void setJobPosTitle(String jobPosTitle);

	/**
	 * Returns the invitation of this vr corporation attendee.
	 *
	 * @return the invitation of this vr corporation attendee
	 */
	@AutoEscape
	public String getInvitation();

	/**
	 * Sets the invitation of this vr corporation attendee.
	 *
	 * @param invitation the invitation of this vr corporation attendee
	 */
	public void setInvitation(String invitation);

	/**
	 * Returns the editable of this vr corporation attendee.
	 *
	 * @return the editable of this vr corporation attendee
	 */
	@AutoEscape
	public String getEditable();

	/**
	 * Sets the editable of this vr corporation attendee.
	 *
	 * @param editable the editable of this vr corporation attendee
	 */
	public void setEditable(String editable);

	/**
	 * Returns the vaqcontactname of this vr corporation attendee.
	 *
	 * @return the vaqcontactname of this vr corporation attendee
	 */
	@AutoEscape
	public String getVaqcontactname();

	/**
	 * Sets the vaqcontactname of this vr corporation attendee.
	 *
	 * @param vaqcontactname the vaqcontactname of this vr corporation attendee
	 */
	public void setVaqcontactname(String vaqcontactname);

	/**
	 * Returns the vaqcontactphone of this vr corporation attendee.
	 *
	 * @return the vaqcontactphone of this vr corporation attendee
	 */
	@AutoEscape
	public String getVaqcontactphone();

	/**
	 * Sets the vaqcontactphone of this vr corporation attendee.
	 *
	 * @param vaqcontactphone the vaqcontactphone of this vr corporation attendee
	 */
	public void setVaqcontactphone(String vaqcontactphone);

	/**
	 * Returns the applicant ID no of this vr corporation attendee.
	 *
	 * @return the applicant ID no of this vr corporation attendee
	 */
	@AutoEscape
	public String getApplicantIdNo();

	/**
	 * Sets the applicant ID no of this vr corporation attendee.
	 *
	 * @param applicantIdNo the applicant ID no of this vr corporation attendee
	 */
	public void setApplicantIdNo(String applicantIdNo);

	/**
	 * Returns the importercontactname of this vr corporation attendee.
	 *
	 * @return the importercontactname of this vr corporation attendee
	 */
	@AutoEscape
	public String getImportercontactname();

	/**
	 * Sets the importercontactname of this vr corporation attendee.
	 *
	 * @param importercontactname the importercontactname of this vr corporation attendee
	 */
	public void setImportercontactname(String importercontactname);

	/**
	 * Returns the importercontactphone of this vr corporation attendee.
	 *
	 * @return the importercontactphone of this vr corporation attendee
	 */
	@AutoEscape
	public String getImportercontactphone();

	/**
	 * Sets the importercontactphone of this vr corporation attendee.
	 *
	 * @param importercontactphone the importercontactphone of this vr corporation attendee
	 */
	public void setImportercontactphone(String importercontactphone);

	/**
	 * Returns the importercontactemail of this vr corporation attendee.
	 *
	 * @return the importercontactemail of this vr corporation attendee
	 */
	@AutoEscape
	public String getImportercontactemail();

	/**
	 * Sets the importercontactemail of this vr corporation attendee.
	 *
	 * @param importercontactemail the importercontactemail of this vr corporation attendee
	 */
	public void setImportercontactemail(String importercontactemail);

	/**
	 * Returns the importerfax of this vr corporation attendee.
	 *
	 * @return the importerfax of this vr corporation attendee
	 */
	@AutoEscape
	public String getImporterfax();

	/**
	 * Sets the importerfax of this vr corporation attendee.
	 *
	 * @param importerfax the importerfax of this vr corporation attendee
	 */
	public void setImporterfax(String importerfax);

	/**
	 * Returns the so tkhq of this vr corporation attendee.
	 *
	 * @return the so tkhq of this vr corporation attendee
	 */
	@AutoEscape
	public String getSoTKHQ();

	/**
	 * Sets the so tkhq of this vr corporation attendee.
	 *
	 * @param soTKHQ the so tkhq of this vr corporation attendee
	 */
	public void setSoTKHQ(String soTKHQ);

	/**
	 * Returns the ngay tkhq of this vr corporation attendee.
	 *
	 * @return the ngay tkhq of this vr corporation attendee
	 */
	@AutoEscape
	public String getNgayTKHQ();

	/**
	 * Sets the ngay tkhq of this vr corporation attendee.
	 *
	 * @param ngayTKHQ the ngay tkhq of this vr corporation attendee
	 */
	public void setNgayTKHQ(String ngayTKHQ);

	/**
	 * Returns the ma chi cuc hq of this vr corporation attendee.
	 *
	 * @return the ma chi cuc hq of this vr corporation attendee
	 */
	@AutoEscape
	public String getMaChiCucHQ();

	/**
	 * Sets the ma chi cuc hq of this vr corporation attendee.
	 *
	 * @param maChiCucHQ the ma chi cuc hq of this vr corporation attendee
	 */
	public void setMaChiCucHQ(String maChiCucHQ);

	/**
	 * Returns the nhan hieu of this vr corporation attendee.
	 *
	 * @return the nhan hieu of this vr corporation attendee
	 */
	@AutoEscape
	public String getNhanHieu();

	/**
	 * Sets the nhan hieu of this vr corporation attendee.
	 *
	 * @param nhanHieu the nhan hieu of this vr corporation attendee
	 */
	public void setNhanHieu(String nhanHieu);

	/**
	 * Returns the ten thuong mai of this vr corporation attendee.
	 *
	 * @return the ten thuong mai of this vr corporation attendee
	 */
	@AutoEscape
	public String getTenThuongMai();

	/**
	 * Sets the ten thuong mai of this vr corporation attendee.
	 *
	 * @param tenThuongMai the ten thuong mai of this vr corporation attendee
	 */
	public void setTenThuongMai(String tenThuongMai);

	/**
	 * Returns the ma kieu loai of this vr corporation attendee.
	 *
	 * @return the ma kieu loai of this vr corporation attendee
	 */
	@AutoEscape
	public String getMaKieuLoai();

	/**
	 * Sets the ma kieu loai of this vr corporation attendee.
	 *
	 * @param maKieuLoai the ma kieu loai of this vr corporation attendee
	 */
	public void setMaKieuLoai(String maKieuLoai);

	/**
	 * Returns the loai phuong tien of this vr corporation attendee.
	 *
	 * @return the loai phuong tien of this vr corporation attendee
	 */
	@AutoEscape
	public String getLoaiPhuongTien();

	/**
	 * Sets the loai phuong tien of this vr corporation attendee.
	 *
	 * @param loaiPhuongTien the loai phuong tien of this vr corporation attendee
	 */
	public void setLoaiPhuongTien(String loaiPhuongTien);

	/**
	 * Returns the so khung of this vr corporation attendee.
	 *
	 * @return the so khung of this vr corporation attendee
	 */
	@AutoEscape
	public String getSoKhung();

	/**
	 * Sets the so khung of this vr corporation attendee.
	 *
	 * @param soKhung the so khung of this vr corporation attendee
	 */
	public void setSoKhung(String soKhung);

	/**
	 * Returns the so dong co of this vr corporation attendee.
	 *
	 * @return the so dong co of this vr corporation attendee
	 */
	@AutoEscape
	public String getSoDongCo();

	/**
	 * Sets the so dong co of this vr corporation attendee.
	 *
	 * @param soDongCo the so dong co of this vr corporation attendee
	 */
	public void setSoDongCo(String soDongCo);

	/**
	 * Returns the tinh trang phuong tien of this vr corporation attendee.
	 *
	 * @return the tinh trang phuong tien of this vr corporation attendee
	 */
	@AutoEscape
	public String getTinhTrangPhuongTien();

	/**
	 * Sets the tinh trang phuong tien of this vr corporation attendee.
	 *
	 * @param tinhTrangPhuongTien the tinh trang phuong tien of this vr corporation attendee
	 */
	public void setTinhTrangPhuongTien(String tinhTrangPhuongTien);

	/**
	 * Returns the ky hieu thiet ke of this vr corporation attendee.
	 *
	 * @return the ky hieu thiet ke of this vr corporation attendee
	 */
	@AutoEscape
	public String getKyHieuThietKe();

	/**
	 * Sets the ky hieu thiet ke of this vr corporation attendee.
	 *
	 * @param kyHieuThietKe the ky hieu thiet ke of this vr corporation attendee
	 */
	public void setKyHieuThietKe(String kyHieuThietKe);

	/**
	 * Returns the so gcn tham dinh thiet ke of this vr corporation attendee.
	 *
	 * @return the so gcn tham dinh thiet ke of this vr corporation attendee
	 */
	@AutoEscape
	public String getSoGCNThamDinhThietKe();

	/**
	 * Sets the so gcn tham dinh thiet ke of this vr corporation attendee.
	 *
	 * @param soGCNThamDinhThietKe the so gcn tham dinh thiet ke of this vr corporation attendee
	 */
	public void setSoGCNThamDinhThietKe(String soGCNThamDinhThietKe);

	/**
	 * Returns the so gcn phe duyet kieu loai nuoc ngoai of this vr corporation attendee.
	 *
	 * @return the so gcn phe duyet kieu loai nuoc ngoai of this vr corporation attendee
	 */
	@AutoEscape
	public String getSoGCNPheDuyetKieuLoaiNuocNgoai();

	/**
	 * Sets the so gcn phe duyet kieu loai nuoc ngoai of this vr corporation attendee.
	 *
	 * @param soGCNPheDuyetKieuLoaiNuocNgoai the so gcn phe duyet kieu loai nuoc ngoai of this vr corporation attendee
	 */
	public void setSoGCNPheDuyetKieuLoaiNuocNgoai(
		String soGCNPheDuyetKieuLoaiNuocNgoai);

	/**
	 * Returns the ten co so san xuat of this vr corporation attendee.
	 *
	 * @return the ten co so san xuat of this vr corporation attendee
	 */
	@AutoEscape
	public String getTenCoSoSanXuat();

	/**
	 * Sets the ten co so san xuat of this vr corporation attendee.
	 *
	 * @param tenCoSoSanXuat the ten co so san xuat of this vr corporation attendee
	 */
	public void setTenCoSoSanXuat(String tenCoSoSanXuat);

	/**
	 * Returns the dia chi co so san xuat of this vr corporation attendee.
	 *
	 * @return the dia chi co so san xuat of this vr corporation attendee
	 */
	@AutoEscape
	public String getDiaChiCoSoSanXuat();

	/**
	 * Sets the dia chi co so san xuat of this vr corporation attendee.
	 *
	 * @param diaChiCoSoSanXuat the dia chi co so san xuat of this vr corporation attendee
	 */
	public void setDiaChiCoSoSanXuat(String diaChiCoSoSanXuat);

	/**
	 * Returns the ten xuong san xuat of this vr corporation attendee.
	 *
	 * @return the ten xuong san xuat of this vr corporation attendee
	 */
	@AutoEscape
	public String getTenXuongSanXuat();

	/**
	 * Sets the ten xuong san xuat of this vr corporation attendee.
	 *
	 * @param tenXuongSanXuat the ten xuong san xuat of this vr corporation attendee
	 */
	public void setTenXuongSanXuat(String tenXuongSanXuat);

	/**
	 * Returns the dia chi xuong san xuat of this vr corporation attendee.
	 *
	 * @return the dia chi xuong san xuat of this vr corporation attendee
	 */
	@AutoEscape
	public String getDiaChiXuongSanXuat();

	/**
	 * Sets the dia chi xuong san xuat of this vr corporation attendee.
	 *
	 * @param diaChiXuongSanXuat the dia chi xuong san xuat of this vr corporation attendee
	 */
	public void setDiaChiXuongSanXuat(String diaChiXuongSanXuat);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRCorporationAttendee vrCorporationAttendee);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRCorporationAttendee> toCacheModel();

	@Override
	public VRCorporationAttendee toEscapedModel();

	@Override
	public VRCorporationAttendee toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}