/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRDossier service. Represents a row in the &quot;opencps_dossier&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRDossierModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRDossierImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRDossier
 * @see com.fds.vr.business.model.impl.VRDossierImpl
 * @see com.fds.vr.business.model.impl.VRDossierModelImpl
 * @generated
 */
@ProviderType
public interface VRDossierModel extends BaseModel<VRDossier>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr dossier model instance should use the {@link VRDossier} interface instead.
	 */

	/**
	 * Returns the primary key of this vr dossier.
	 *
	 * @return the primary key of this vr dossier
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr dossier.
	 *
	 * @param primaryKey the primary key of this vr dossier
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this vr dossier.
	 *
	 * @return the uuid of this vr dossier
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this vr dossier.
	 *
	 * @param uuid the uuid of this vr dossier
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the dossier ID of this vr dossier.
	 *
	 * @return the dossier ID of this vr dossier
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr dossier.
	 *
	 * @param dossierId the dossier ID of this vr dossier
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the group ID of this vr dossier.
	 *
	 * @return the group ID of this vr dossier
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this vr dossier.
	 *
	 * @param groupId the group ID of this vr dossier
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this vr dossier.
	 *
	 * @return the company ID of this vr dossier
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this vr dossier.
	 *
	 * @param companyId the company ID of this vr dossier
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this vr dossier.
	 *
	 * @return the user ID of this vr dossier
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this vr dossier.
	 *
	 * @param userId the user ID of this vr dossier
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this vr dossier.
	 *
	 * @return the user uuid of this vr dossier
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this vr dossier.
	 *
	 * @param userUuid the user uuid of this vr dossier
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this vr dossier.
	 *
	 * @return the user name of this vr dossier
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this vr dossier.
	 *
	 * @param userName the user name of this vr dossier
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this vr dossier.
	 *
	 * @return the create date of this vr dossier
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this vr dossier.
	 *
	 * @param createDate the create date of this vr dossier
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this vr dossier.
	 *
	 * @return the modified date of this vr dossier
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this vr dossier.
	 *
	 * @param modifiedDate the modified date of this vr dossier
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the reference uid of this vr dossier.
	 *
	 * @return the reference uid of this vr dossier
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr dossier.
	 *
	 * @param referenceUid the reference uid of this vr dossier
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the counter of this vr dossier.
	 *
	 * @return the counter of this vr dossier
	 */
	public int getCounter();

	/**
	 * Sets the counter of this vr dossier.
	 *
	 * @param counter the counter of this vr dossier
	 */
	public void setCounter(int counter);

	/**
	 * Returns the service code of this vr dossier.
	 *
	 * @return the service code of this vr dossier
	 */
	@AutoEscape
	public String getServiceCode();

	/**
	 * Sets the service code of this vr dossier.
	 *
	 * @param serviceCode the service code of this vr dossier
	 */
	public void setServiceCode(String serviceCode);

	/**
	 * Returns the service name of this vr dossier.
	 *
	 * @return the service name of this vr dossier
	 */
	@AutoEscape
	public String getServiceName();

	/**
	 * Sets the service name of this vr dossier.
	 *
	 * @param serviceName the service name of this vr dossier
	 */
	public void setServiceName(String serviceName);

	/**
	 * Returns the gov agency code of this vr dossier.
	 *
	 * @return the gov agency code of this vr dossier
	 */
	@AutoEscape
	public String getGovAgencyCode();

	/**
	 * Sets the gov agency code of this vr dossier.
	 *
	 * @param govAgencyCode the gov agency code of this vr dossier
	 */
	public void setGovAgencyCode(String govAgencyCode);

	/**
	 * Returns the gov agency name of this vr dossier.
	 *
	 * @return the gov agency name of this vr dossier
	 */
	@AutoEscape
	public String getGovAgencyName();

	/**
	 * Sets the gov agency name of this vr dossier.
	 *
	 * @param govAgencyName the gov agency name of this vr dossier
	 */
	public void setGovAgencyName(String govAgencyName);

	/**
	 * Returns the applicant name of this vr dossier.
	 *
	 * @return the applicant name of this vr dossier
	 */
	@AutoEscape
	public String getApplicantName();

	/**
	 * Sets the applicant name of this vr dossier.
	 *
	 * @param applicantName the applicant name of this vr dossier
	 */
	public void setApplicantName(String applicantName);

	/**
	 * Returns the applicant ID type of this vr dossier.
	 *
	 * @return the applicant ID type of this vr dossier
	 */
	@AutoEscape
	public String getApplicantIdType();

	/**
	 * Sets the applicant ID type of this vr dossier.
	 *
	 * @param applicantIdType the applicant ID type of this vr dossier
	 */
	public void setApplicantIdType(String applicantIdType);

	/**
	 * Returns the applicant ID no of this vr dossier.
	 *
	 * @return the applicant ID no of this vr dossier
	 */
	@AutoEscape
	public String getApplicantIdNo();

	/**
	 * Sets the applicant ID no of this vr dossier.
	 *
	 * @param applicantIdNo the applicant ID no of this vr dossier
	 */
	public void setApplicantIdNo(String applicantIdNo);

	/**
	 * Returns the applicant ID date of this vr dossier.
	 *
	 * @return the applicant ID date of this vr dossier
	 */
	public Date getApplicantIdDate();

	/**
	 * Sets the applicant ID date of this vr dossier.
	 *
	 * @param applicantIdDate the applicant ID date of this vr dossier
	 */
	public void setApplicantIdDate(Date applicantIdDate);

	/**
	 * Returns the address of this vr dossier.
	 *
	 * @return the address of this vr dossier
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this vr dossier.
	 *
	 * @param address the address of this vr dossier
	 */
	public void setAddress(String address);

	/**
	 * Returns the city code of this vr dossier.
	 *
	 * @return the city code of this vr dossier
	 */
	@AutoEscape
	public String getCityCode();

	/**
	 * Sets the city code of this vr dossier.
	 *
	 * @param cityCode the city code of this vr dossier
	 */
	public void setCityCode(String cityCode);

	/**
	 * Returns the city name of this vr dossier.
	 *
	 * @return the city name of this vr dossier
	 */
	@AutoEscape
	public String getCityName();

	/**
	 * Sets the city name of this vr dossier.
	 *
	 * @param cityName the city name of this vr dossier
	 */
	public void setCityName(String cityName);

	/**
	 * Returns the district code of this vr dossier.
	 *
	 * @return the district code of this vr dossier
	 */
	@AutoEscape
	public String getDistrictCode();

	/**
	 * Sets the district code of this vr dossier.
	 *
	 * @param districtCode the district code of this vr dossier
	 */
	public void setDistrictCode(String districtCode);

	/**
	 * Returns the district name of this vr dossier.
	 *
	 * @return the district name of this vr dossier
	 */
	@AutoEscape
	public String getDistrictName();

	/**
	 * Sets the district name of this vr dossier.
	 *
	 * @param districtName the district name of this vr dossier
	 */
	public void setDistrictName(String districtName);

	/**
	 * Returns the ward code of this vr dossier.
	 *
	 * @return the ward code of this vr dossier
	 */
	@AutoEscape
	public String getWardCode();

	/**
	 * Sets the ward code of this vr dossier.
	 *
	 * @param wardCode the ward code of this vr dossier
	 */
	public void setWardCode(String wardCode);

	/**
	 * Returns the ward name of this vr dossier.
	 *
	 * @return the ward name of this vr dossier
	 */
	@AutoEscape
	public String getWardName();

	/**
	 * Sets the ward name of this vr dossier.
	 *
	 * @param wardName the ward name of this vr dossier
	 */
	public void setWardName(String wardName);

	/**
	 * Returns the contact name of this vr dossier.
	 *
	 * @return the contact name of this vr dossier
	 */
	@AutoEscape
	public String getContactName();

	/**
	 * Sets the contact name of this vr dossier.
	 *
	 * @param contactName the contact name of this vr dossier
	 */
	public void setContactName(String contactName);

	/**
	 * Returns the contact tel no of this vr dossier.
	 *
	 * @return the contact tel no of this vr dossier
	 */
	@AutoEscape
	public String getContactTelNo();

	/**
	 * Sets the contact tel no of this vr dossier.
	 *
	 * @param contactTelNo the contact tel no of this vr dossier
	 */
	public void setContactTelNo(String contactTelNo);

	/**
	 * Returns the contact email of this vr dossier.
	 *
	 * @return the contact email of this vr dossier
	 */
	@AutoEscape
	public String getContactEmail();

	/**
	 * Sets the contact email of this vr dossier.
	 *
	 * @param contactEmail the contact email of this vr dossier
	 */
	public void setContactEmail(String contactEmail);

	/**
	 * Returns the dossier template no of this vr dossier.
	 *
	 * @return the dossier template no of this vr dossier
	 */
	@AutoEscape
	public String getDossierTemplateNo();

	/**
	 * Sets the dossier template no of this vr dossier.
	 *
	 * @param dossierTemplateNo the dossier template no of this vr dossier
	 */
	public void setDossierTemplateNo(String dossierTemplateNo);

	/**
	 * Returns the dossier template name of this vr dossier.
	 *
	 * @return the dossier template name of this vr dossier
	 */
	@AutoEscape
	public String getDossierTemplateName();

	/**
	 * Sets the dossier template name of this vr dossier.
	 *
	 * @param dossierTemplateName the dossier template name of this vr dossier
	 */
	public void setDossierTemplateName(String dossierTemplateName);

	/**
	 * Returns the dossier note of this vr dossier.
	 *
	 * @return the dossier note of this vr dossier
	 */
	@AutoEscape
	public String getDossierNote();

	/**
	 * Sets the dossier note of this vr dossier.
	 *
	 * @param dossierNote the dossier note of this vr dossier
	 */
	public void setDossierNote(String dossierNote);

	/**
	 * Returns the submission note of this vr dossier.
	 *
	 * @return the submission note of this vr dossier
	 */
	@AutoEscape
	public String getSubmissionNote();

	/**
	 * Sets the submission note of this vr dossier.
	 *
	 * @param submissionNote the submission note of this vr dossier
	 */
	public void setSubmissionNote(String submissionNote);

	/**
	 * Returns the applicant note of this vr dossier.
	 *
	 * @return the applicant note of this vr dossier
	 */
	@AutoEscape
	public String getApplicantNote();

	/**
	 * Sets the applicant note of this vr dossier.
	 *
	 * @param applicantNote the applicant note of this vr dossier
	 */
	public void setApplicantNote(String applicantNote);

	/**
	 * Returns the brief note of this vr dossier.
	 *
	 * @return the brief note of this vr dossier
	 */
	@AutoEscape
	public String getBriefNote();

	/**
	 * Sets the brief note of this vr dossier.
	 *
	 * @param briefNote the brief note of this vr dossier
	 */
	public void setBriefNote(String briefNote);

	/**
	 * Returns the dossier no of this vr dossier.
	 *
	 * @return the dossier no of this vr dossier
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr dossier.
	 *
	 * @param dossierNo the dossier no of this vr dossier
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the submitting of this vr dossier.
	 *
	 * @return the submitting of this vr dossier
	 */
	public boolean getSubmitting();

	/**
	 * Returns <code>true</code> if this vr dossier is submitting.
	 *
	 * @return <code>true</code> if this vr dossier is submitting; <code>false</code> otherwise
	 */
	public boolean isSubmitting();

	/**
	 * Sets whether this vr dossier is submitting.
	 *
	 * @param submitting the submitting of this vr dossier
	 */
	public void setSubmitting(boolean submitting);

	/**
	 * Returns the submit date of this vr dossier.
	 *
	 * @return the submit date of this vr dossier
	 */
	public Date getSubmitDate();

	/**
	 * Sets the submit date of this vr dossier.
	 *
	 * @param submitDate the submit date of this vr dossier
	 */
	public void setSubmitDate(Date submitDate);

	/**
	 * Returns the receive date of this vr dossier.
	 *
	 * @return the receive date of this vr dossier
	 */
	public Date getReceiveDate();

	/**
	 * Sets the receive date of this vr dossier.
	 *
	 * @param receiveDate the receive date of this vr dossier
	 */
	public void setReceiveDate(Date receiveDate);

	/**
	 * Returns the due date of this vr dossier.
	 *
	 * @return the due date of this vr dossier
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this vr dossier.
	 *
	 * @param dueDate the due date of this vr dossier
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the release date of this vr dossier.
	 *
	 * @return the release date of this vr dossier
	 */
	public Date getReleaseDate();

	/**
	 * Sets the release date of this vr dossier.
	 *
	 * @param releaseDate the release date of this vr dossier
	 */
	public void setReleaseDate(Date releaseDate);

	/**
	 * Returns the finish date of this vr dossier.
	 *
	 * @return the finish date of this vr dossier
	 */
	public Date getFinishDate();

	/**
	 * Sets the finish date of this vr dossier.
	 *
	 * @param finishDate the finish date of this vr dossier
	 */
	public void setFinishDate(Date finishDate);

	/**
	 * Returns the cancelling date of this vr dossier.
	 *
	 * @return the cancelling date of this vr dossier
	 */
	public Date getCancellingDate();

	/**
	 * Sets the cancelling date of this vr dossier.
	 *
	 * @param cancellingDate the cancelling date of this vr dossier
	 */
	public void setCancellingDate(Date cancellingDate);

	/**
	 * Returns the correctting date of this vr dossier.
	 *
	 * @return the correctting date of this vr dossier
	 */
	public Date getCorrecttingDate();

	/**
	 * Sets the correctting date of this vr dossier.
	 *
	 * @param correcttingDate the correctting date of this vr dossier
	 */
	public void setCorrecttingDate(Date correcttingDate);

	/**
	 * Returns the dossier status of this vr dossier.
	 *
	 * @return the dossier status of this vr dossier
	 */
	@AutoEscape
	public String getDossierStatus();

	/**
	 * Sets the dossier status of this vr dossier.
	 *
	 * @param dossierStatus the dossier status of this vr dossier
	 */
	public void setDossierStatus(String dossierStatus);

	/**
	 * Returns the dossier status text of this vr dossier.
	 *
	 * @return the dossier status text of this vr dossier
	 */
	@AutoEscape
	public String getDossierStatusText();

	/**
	 * Sets the dossier status text of this vr dossier.
	 *
	 * @param dossierStatusText the dossier status text of this vr dossier
	 */
	public void setDossierStatusText(String dossierStatusText);

	/**
	 * Returns the dossier sub status of this vr dossier.
	 *
	 * @return the dossier sub status of this vr dossier
	 */
	@AutoEscape
	public String getDossierSubStatus();

	/**
	 * Sets the dossier sub status of this vr dossier.
	 *
	 * @param dossierSubStatus the dossier sub status of this vr dossier
	 */
	public void setDossierSubStatus(String dossierSubStatus);

	/**
	 * Returns the dossier sub status text of this vr dossier.
	 *
	 * @return the dossier sub status text of this vr dossier
	 */
	@AutoEscape
	public String getDossierSubStatusText();

	/**
	 * Sets the dossier sub status text of this vr dossier.
	 *
	 * @param dossierSubStatusText the dossier sub status text of this vr dossier
	 */
	public void setDossierSubStatusText(String dossierSubStatusText);

	/**
	 * Returns the folder ID of this vr dossier.
	 *
	 * @return the folder ID of this vr dossier
	 */
	public long getFolderId();

	/**
	 * Sets the folder ID of this vr dossier.
	 *
	 * @param folderId the folder ID of this vr dossier
	 */
	public void setFolderId(long folderId);

	/**
	 * Returns the dossier action ID of this vr dossier.
	 *
	 * @return the dossier action ID of this vr dossier
	 */
	public long getDossierActionId();

	/**
	 * Sets the dossier action ID of this vr dossier.
	 *
	 * @param dossierActionId the dossier action ID of this vr dossier
	 */
	public void setDossierActionId(long dossierActionId);

	/**
	 * Returns the via postal of this vr dossier.
	 *
	 * @return the via postal of this vr dossier
	 */
	public int getViaPostal();

	/**
	 * Sets the via postal of this vr dossier.
	 *
	 * @param viaPostal the via postal of this vr dossier
	 */
	public void setViaPostal(int viaPostal);

	/**
	 * Returns the postal address of this vr dossier.
	 *
	 * @return the postal address of this vr dossier
	 */
	@AutoEscape
	public String getPostalAddress();

	/**
	 * Sets the postal address of this vr dossier.
	 *
	 * @param postalAddress the postal address of this vr dossier
	 */
	public void setPostalAddress(String postalAddress);

	/**
	 * Returns the postal city code of this vr dossier.
	 *
	 * @return the postal city code of this vr dossier
	 */
	@AutoEscape
	public String getPostalCityCode();

	/**
	 * Sets the postal city code of this vr dossier.
	 *
	 * @param postalCityCode the postal city code of this vr dossier
	 */
	public void setPostalCityCode(String postalCityCode);

	/**
	 * Returns the postal city name of this vr dossier.
	 *
	 * @return the postal city name of this vr dossier
	 */
	@AutoEscape
	public String getPostalCityName();

	/**
	 * Sets the postal city name of this vr dossier.
	 *
	 * @param postalCityName the postal city name of this vr dossier
	 */
	public void setPostalCityName(String postalCityName);

	/**
	 * Returns the postal tel no of this vr dossier.
	 *
	 * @return the postal tel no of this vr dossier
	 */
	@AutoEscape
	public String getPostalTelNo();

	/**
	 * Sets the postal tel no of this vr dossier.
	 *
	 * @param postalTelNo the postal tel no of this vr dossier
	 */
	public void setPostalTelNo(String postalTelNo);

	/**
	 * Returns the password of this vr dossier.
	 *
	 * @return the password of this vr dossier
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this vr dossier.
	 *
	 * @param password the password of this vr dossier
	 */
	public void setPassword(String password);

	/**
	 * Returns the notification of this vr dossier.
	 *
	 * @return the notification of this vr dossier
	 */
	public boolean getNotification();

	/**
	 * Returns <code>true</code> if this vr dossier is notification.
	 *
	 * @return <code>true</code> if this vr dossier is notification; <code>false</code> otherwise
	 */
	public boolean isNotification();

	/**
	 * Sets whether this vr dossier is notification.
	 *
	 * @param notification the notification of this vr dossier
	 */
	public void setNotification(boolean notification);

	/**
	 * Returns the online of this vr dossier.
	 *
	 * @return the online of this vr dossier
	 */
	public boolean getOnline();

	/**
	 * Returns <code>true</code> if this vr dossier is online.
	 *
	 * @return <code>true</code> if this vr dossier is online; <code>false</code> otherwise
	 */
	public boolean isOnline();

	/**
	 * Sets whether this vr dossier is online.
	 *
	 * @param online the online of this vr dossier
	 */
	public void setOnline(boolean online);

	/**
	 * Returns the server no of this vr dossier.
	 *
	 * @return the server no of this vr dossier
	 */
	@AutoEscape
	public String getServerNo();

	/**
	 * Sets the server no of this vr dossier.
	 *
	 * @param serverNo the server no of this vr dossier
	 */
	public void setServerNo(String serverNo);

	/**
	 * Returns the endorsement date of this vr dossier.
	 *
	 * @return the endorsement date of this vr dossier
	 */
	public Date getEndorsementDate();

	/**
	 * Sets the endorsement date of this vr dossier.
	 *
	 * @param endorsementDate the endorsement date of this vr dossier
	 */
	public void setEndorsementDate(Date endorsementDate);

	/**
	 * Returns the lock state of this vr dossier.
	 *
	 * @return the lock state of this vr dossier
	 */
	@AutoEscape
	public String getLockState();

	/**
	 * Sets the lock state of this vr dossier.
	 *
	 * @param lockState the lock state of this vr dossier
	 */
	public void setLockState(String lockState);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRDossier vrDossier);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRDossier> toCacheModel();

	@Override
	public VRDossier toEscapedModel();

	@Override
	public VRDossier toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}