/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRInputSheet service. Represents a row in the &quot;vr_inputsheet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRInputSheetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRInputSheetImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRInputSheet
 * @see com.fds.vr.business.model.impl.VRInputSheetImpl
 * @see com.fds.vr.business.model.impl.VRInputSheetModelImpl
 * @generated
 */
@ProviderType
public interface VRInputSheetModel extends BaseModel<VRInputSheet> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr input sheet model instance should use the {@link VRInputSheet} interface instead.
	 */

	/**
	 * Returns the primary key of this vr input sheet.
	 *
	 * @return the primary key of this vr input sheet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr input sheet.
	 *
	 * @param primaryKey the primary key of this vr input sheet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr input sheet.
	 *
	 * @return the ID of this vr input sheet
	 */
	public long getId();

	/**
	 * Sets the ID of this vr input sheet.
	 *
	 * @param id the ID of this vr input sheet
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr input sheet.
	 *
	 * @return the mt core of this vr input sheet
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr input sheet.
	 *
	 * @param mtCore the mt core of this vr input sheet
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the input sheet no of this vr input sheet.
	 *
	 * @return the input sheet no of this vr input sheet
	 */
	@AutoEscape
	public String getInputSheetNo();

	/**
	 * Sets the input sheet no of this vr input sheet.
	 *
	 * @param inputSheetNo the input sheet no of this vr input sheet
	 */
	public void setInputSheetNo(String inputSheetNo);

	/**
	 * Returns the input sheet date of this vr input sheet.
	 *
	 * @return the input sheet date of this vr input sheet
	 */
	public Date getInputSheetDate();

	/**
	 * Sets the input sheet date of this vr input sheet.
	 *
	 * @param inputSheetDate the input sheet date of this vr input sheet
	 */
	public void setInputSheetDate(Date inputSheetDate);

	/**
	 * Returns the original document no of this vr input sheet.
	 *
	 * @return the original document no of this vr input sheet
	 */
	@AutoEscape
	public String getOriginalDocumentNo();

	/**
	 * Sets the original document no of this vr input sheet.
	 *
	 * @param originalDocumentNo the original document no of this vr input sheet
	 */
	public void setOriginalDocumentNo(String originalDocumentNo);

	/**
	 * Returns the corporation ID of this vr input sheet.
	 *
	 * @return the corporation ID of this vr input sheet
	 */
	public long getCorporationId();

	/**
	 * Sets the corporation ID of this vr input sheet.
	 *
	 * @param corporationId the corporation ID of this vr input sheet
	 */
	public void setCorporationId(long corporationId);

	/**
	 * Returns the input sheet type of this vr input sheet.
	 *
	 * @return the input sheet type of this vr input sheet
	 */
	public long getInputSheetType();

	/**
	 * Sets the input sheet type of this vr input sheet.
	 *
	 * @param inputSheetType the input sheet type of this vr input sheet
	 */
	public void setInputSheetType(long inputSheetType);

	/**
	 * Returns the maker of this vr input sheet.
	 *
	 * @return the maker of this vr input sheet
	 */
	@AutoEscape
	public String getMaker();

	/**
	 * Sets the maker of this vr input sheet.
	 *
	 * @param maker the maker of this vr input sheet
	 */
	public void setMaker(String maker);

	/**
	 * Returns the checker of this vr input sheet.
	 *
	 * @return the checker of this vr input sheet
	 */
	@AutoEscape
	public String getChecker();

	/**
	 * Sets the checker of this vr input sheet.
	 *
	 * @param checker the checker of this vr input sheet
	 */
	public void setChecker(String checker);

	/**
	 * Returns the approver of this vr input sheet.
	 *
	 * @return the approver of this vr input sheet
	 */
	@AutoEscape
	public String getApprover();

	/**
	 * Sets the approver of this vr input sheet.
	 *
	 * @param approver the approver of this vr input sheet
	 */
	public void setApprover(String approver);

	/**
	 * Returns the delivery name of this vr input sheet.
	 *
	 * @return the delivery name of this vr input sheet
	 */
	@AutoEscape
	public String getDeliveryName();

	/**
	 * Sets the delivery name of this vr input sheet.
	 *
	 * @param deliveryName the delivery name of this vr input sheet
	 */
	public void setDeliveryName(String deliveryName);

	/**
	 * Returns the inventory name of this vr input sheet.
	 *
	 * @return the inventory name of this vr input sheet
	 */
	@AutoEscape
	public String getInventoryName();

	/**
	 * Sets the inventory name of this vr input sheet.
	 *
	 * @param inventoryName the inventory name of this vr input sheet
	 */
	public void setInventoryName(String inventoryName);

	/**
	 * Returns the inventory place of this vr input sheet.
	 *
	 * @return the inventory place of this vr input sheet
	 */
	@AutoEscape
	public String getInventoryPlace();

	/**
	 * Sets the inventory place of this vr input sheet.
	 *
	 * @param inventoryPlace the inventory place of this vr input sheet
	 */
	public void setInventoryPlace(String inventoryPlace);

	/**
	 * Returns the inventory date of this vr input sheet.
	 *
	 * @return the inventory date of this vr input sheet
	 */
	public Date getInventoryDate();

	/**
	 * Sets the inventory date of this vr input sheet.
	 *
	 * @param inventoryDate the inventory date of this vr input sheet
	 */
	public void setInventoryDate(Date inventoryDate);

	/**
	 * Returns the book ID list of this vr input sheet.
	 *
	 * @return the book ID list of this vr input sheet
	 */
	@AutoEscape
	public String getBookIDList();

	/**
	 * Sets the book ID list of this vr input sheet.
	 *
	 * @param bookIDList the book ID list of this vr input sheet
	 */
	public void setBookIDList(String bookIDList);

	/**
	 * Returns the is approval of this vr input sheet.
	 *
	 * @return the is approval of this vr input sheet
	 */
	public long getIsApproval();

	/**
	 * Sets the is approval of this vr input sheet.
	 *
	 * @param isApproval the is approval of this vr input sheet
	 */
	public void setIsApproval(long isApproval);

	/**
	 * Returns the total quantities of this vr input sheet.
	 *
	 * @return the total quantities of this vr input sheet
	 */
	public long getTotalQuantities();

	/**
	 * Sets the total quantities of this vr input sheet.
	 *
	 * @param totalQuantities the total quantities of this vr input sheet
	 */
	public void setTotalQuantities(long totalQuantities);

	/**
	 * Returns the total amount of this vr input sheet.
	 *
	 * @return the total amount of this vr input sheet
	 */
	public long getTotalAmount();

	/**
	 * Sets the total amount of this vr input sheet.
	 *
	 * @param totalAmount the total amount of this vr input sheet
	 */
	public void setTotalAmount(long totalAmount);

	/**
	 * Returns the amount in words of this vr input sheet.
	 *
	 * @return the amount in words of this vr input sheet
	 */
	@AutoEscape
	public String getAmountInWords();

	/**
	 * Sets the amount in words of this vr input sheet.
	 *
	 * @param amountInWords the amount in words of this vr input sheet
	 */
	public void setAmountInWords(String amountInWords);

	/**
	 * Returns the remark of this vr input sheet.
	 *
	 * @return the remark of this vr input sheet
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this vr input sheet.
	 *
	 * @param remark the remark of this vr input sheet
	 */
	public void setRemark(String remark);

	/**
	 * Returns the modify date of this vr input sheet.
	 *
	 * @return the modify date of this vr input sheet
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr input sheet.
	 *
	 * @param modifyDate the modify date of this vr input sheet
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr input sheet.
	 *
	 * @return the sync date of this vr input sheet
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr input sheet.
	 *
	 * @param syncDate the sync date of this vr input sheet
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRInputSheet vrInputSheet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRInputSheet> toCacheModel();

	@Override
	public VRInputSheet toEscapedModel();

	@Override
	public VRInputSheet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}