/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRMethodOfIssue service. Represents a row in the &quot;vr_methodofissue&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRMethodOfIssueModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRMethodOfIssueImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRMethodOfIssue
 * @see com.fds.vr.business.model.impl.VRMethodOfIssueImpl
 * @see com.fds.vr.business.model.impl.VRMethodOfIssueModelImpl
 * @generated
 */
@ProviderType
public interface VRMethodOfIssueModel extends BaseModel<VRMethodOfIssue> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr method of issue model instance should use the {@link VRMethodOfIssue} interface instead.
	 */

	/**
	 * Returns the primary key of this vr method of issue.
	 *
	 * @return the primary key of this vr method of issue
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr method of issue.
	 *
	 * @param primaryKey the primary key of this vr method of issue
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr method of issue.
	 *
	 * @return the ID of this vr method of issue
	 */
	public long getId();

	/**
	 * Sets the ID of this vr method of issue.
	 *
	 * @param id the ID of this vr method of issue
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr method of issue.
	 *
	 * @return the mt core of this vr method of issue
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr method of issue.
	 *
	 * @param mtCore the mt core of this vr method of issue
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the vehicle class of this vr method of issue.
	 *
	 * @return the vehicle class of this vr method of issue
	 */
	@AutoEscape
	public String getVehicleClass();

	/**
	 * Sets the vehicle class of this vr method of issue.
	 *
	 * @param vehicleClass the vehicle class of this vr method of issue
	 */
	public void setVehicleClass(String vehicleClass);

	/**
	 * Returns the certified assembly type of this vr method of issue.
	 *
	 * @return the certified assembly type of this vr method of issue
	 */
	@AutoEscape
	public String getCertifiedAssemblyType();

	/**
	 * Sets the certified assembly type of this vr method of issue.
	 *
	 * @param certifiedAssemblyType the certified assembly type of this vr method of issue
	 */
	public void setCertifiedAssemblyType(String certifiedAssemblyType);

	/**
	 * Returns the certified assembly type description of this vr method of issue.
	 *
	 * @return the certified assembly type description of this vr method of issue
	 */
	@AutoEscape
	public String getCertifiedAssemblyTypeDescription();

	/**
	 * Sets the certified assembly type description of this vr method of issue.
	 *
	 * @param certifiedAssemblyTypeDescription the certified assembly type description of this vr method of issue
	 */
	public void setCertifiedAssemblyTypeDescription(
		String certifiedAssemblyTypeDescription);

	/**
	 * Returns the applicant profile ID of this vr method of issue.
	 *
	 * @return the applicant profile ID of this vr method of issue
	 */
	public long getApplicantProfileId();

	/**
	 * Sets the applicant profile ID of this vr method of issue.
	 *
	 * @param applicantProfileId the applicant profile ID of this vr method of issue
	 */
	public void setApplicantProfileId(long applicantProfileId);

	/**
	 * Returns the applicant name of this vr method of issue.
	 *
	 * @return the applicant name of this vr method of issue
	 */
	@AutoEscape
	public String getApplicantName();

	/**
	 * Sets the applicant name of this vr method of issue.
	 *
	 * @param applicantName the applicant name of this vr method of issue
	 */
	public void setApplicantName(String applicantName);

	/**
	 * Returns the applicant address of this vr method of issue.
	 *
	 * @return the applicant address of this vr method of issue
	 */
	@AutoEscape
	public String getApplicantAddress();

	/**
	 * Sets the applicant address of this vr method of issue.
	 *
	 * @param applicantAddress the applicant address of this vr method of issue
	 */
	public void setApplicantAddress(String applicantAddress);

	/**
	 * Returns the production plant ID of this vr method of issue.
	 *
	 * @return the production plant ID of this vr method of issue
	 */
	public long getProductionPlantId();

	/**
	 * Sets the production plant ID of this vr method of issue.
	 *
	 * @param productionPlantId the production plant ID of this vr method of issue
	 */
	public void setProductionPlantId(long productionPlantId);

	/**
	 * Returns the production plant code of this vr method of issue.
	 *
	 * @return the production plant code of this vr method of issue
	 */
	@AutoEscape
	public String getProductionPlantCode();

	/**
	 * Sets the production plant code of this vr method of issue.
	 *
	 * @param productionPlantCode the production plant code of this vr method of issue
	 */
	public void setProductionPlantCode(String productionPlantCode);

	/**
	 * Returns the production plant name of this vr method of issue.
	 *
	 * @return the production plant name of this vr method of issue
	 */
	@AutoEscape
	public String getProductionPlantName();

	/**
	 * Sets the production plant name of this vr method of issue.
	 *
	 * @param productionPlantName the production plant name of this vr method of issue
	 */
	public void setProductionPlantName(String productionPlantName);

	/**
	 * Returns the production plant address of this vr method of issue.
	 *
	 * @return the production plant address of this vr method of issue
	 */
	@AutoEscape
	public String getProductionPlantAddress();

	/**
	 * Sets the production plant address of this vr method of issue.
	 *
	 * @param productionPlantAddress the production plant address of this vr method of issue
	 */
	public void setProductionPlantAddress(String productionPlantAddress);

	/**
	 * Returns the method of issue of this vr method of issue.
	 *
	 * @return the method of issue of this vr method of issue
	 */
	@AutoEscape
	public String getMethodOfIssue();

	/**
	 * Sets the method of issue of this vr method of issue.
	 *
	 * @param methodOfIssue the method of issue of this vr method of issue
	 */
	public void setMethodOfIssue(String methodOfIssue);

	/**
	 * Returns the method approved of this vr method of issue.
	 *
	 * @return the method approved of this vr method of issue
	 */
	public int getMethodApproved();

	/**
	 * Sets the method approved of this vr method of issue.
	 *
	 * @param methodApproved the method approved of this vr method of issue
	 */
	public void setMethodApproved(int methodApproved);

	/**
	 * Returns the method in month of this vr method of issue.
	 *
	 * @return the method in month of this vr method of issue
	 */
	public int getMethodInMonth();

	/**
	 * Sets the method in month of this vr method of issue.
	 *
	 * @param methodInMonth the method in month of this vr method of issue
	 */
	public void setMethodInMonth(int methodInMonth);

	/**
	 * Returns the method in year of this vr method of issue.
	 *
	 * @return the method in year of this vr method of issue
	 */
	public int getMethodInYear();

	/**
	 * Sets the method in year of this vr method of issue.
	 *
	 * @param methodInYear the method in year of this vr method of issue
	 */
	public void setMethodInYear(int methodInYear);

	/**
	 * Returns the period duration of this vr method of issue.
	 *
	 * @return the period duration of this vr method of issue
	 */
	public int getPeriodDuration();

	/**
	 * Sets the period duration of this vr method of issue.
	 *
	 * @param periodDuration the period duration of this vr method of issue
	 */
	public void setPeriodDuration(int periodDuration);

	/**
	 * Returns the frequency index of this vr method of issue.
	 *
	 * @return the frequency index of this vr method of issue
	 */
	public int getFrequencyIndex();

	/**
	 * Sets the frequency index of this vr method of issue.
	 *
	 * @param frequencyIndex the frequency index of this vr method of issue
	 */
	public void setFrequencyIndex(int frequencyIndex);

	/**
	 * Returns the remarks of this vr method of issue.
	 *
	 * @return the remarks of this vr method of issue
	 */
	@AutoEscape
	public String getRemarks();

	/**
	 * Sets the remarks of this vr method of issue.
	 *
	 * @param remarks the remarks of this vr method of issue
	 */
	public void setRemarks(String remarks);

	/**
	 * Returns the average stb quantity index of this vr method of issue.
	 *
	 * @return the average stb quantity index of this vr method of issue
	 */
	public int getAverageStbQuantityIndex();

	/**
	 * Sets the average stb quantity index of this vr method of issue.
	 *
	 * @param averageStbQuantityIndex the average stb quantity index of this vr method of issue
	 */
	public void setAverageStbQuantityIndex(int averageStbQuantityIndex);

	/**
	 * Returns the max month quantity index of this vr method of issue.
	 *
	 * @return the max month quantity index of this vr method of issue
	 */
	public int getMaxMonthQuantityIndex();

	/**
	 * Sets the max month quantity index of this vr method of issue.
	 *
	 * @param maxMonthQuantityIndex the max month quantity index of this vr method of issue
	 */
	public void setMaxMonthQuantityIndex(int maxMonthQuantityIndex);

	/**
	 * Returns the average stm quantity index of this vr method of issue.
	 *
	 * @return the average stm quantity index of this vr method of issue
	 */
	public int getAverageStmQuantityIndex();

	/**
	 * Sets the average stm quantity index of this vr method of issue.
	 *
	 * @param averageStmQuantityIndex the average stm quantity index of this vr method of issue
	 */
	public void setAverageStmQuantityIndex(int averageStmQuantityIndex);

	/**
	 * Returns the accumulated month quantity index of this vr method of issue.
	 *
	 * @return the accumulated month quantity index of this vr method of issue
	 */
	public int getAccumulatedMonthQuantityIndex();

	/**
	 * Sets the accumulated month quantity index of this vr method of issue.
	 *
	 * @param accumulatedMonthQuantityIndex the accumulated month quantity index of this vr method of issue
	 */
	public void setAccumulatedMonthQuantityIndex(
		int accumulatedMonthQuantityIndex);

	/**
	 * Returns the latest other index1 of this vr method of issue.
	 *
	 * @return the latest other index1 of this vr method of issue
	 */
	public int getLatestOtherIndex1();

	/**
	 * Sets the latest other index1 of this vr method of issue.
	 *
	 * @param latestOtherIndex1 the latest other index1 of this vr method of issue
	 */
	public void setLatestOtherIndex1(int latestOtherIndex1);

	/**
	 * Returns the latest other index2 of this vr method of issue.
	 *
	 * @return the latest other index2 of this vr method of issue
	 */
	public int getLatestOtherIndex2();

	/**
	 * Sets the latest other index2 of this vr method of issue.
	 *
	 * @param latestOtherIndex2 the latest other index2 of this vr method of issue
	 */
	public void setLatestOtherIndex2(int latestOtherIndex2);

	/**
	 * Returns the latest other index3 of this vr method of issue.
	 *
	 * @return the latest other index3 of this vr method of issue
	 */
	public int getLatestOtherIndex3();

	/**
	 * Sets the latest other index3 of this vr method of issue.
	 *
	 * @param latestOtherIndex3 the latest other index3 of this vr method of issue
	 */
	public void setLatestOtherIndex3(int latestOtherIndex3);

	/**
	 * Returns the latest cop report date of this vr method of issue.
	 *
	 * @return the latest cop report date of this vr method of issue
	 */
	public Date getLatestCOPReportDate();

	/**
	 * Sets the latest cop report date of this vr method of issue.
	 *
	 * @param latestCOPReportDate the latest cop report date of this vr method of issue
	 */
	public void setLatestCOPReportDate(Date latestCOPReportDate);

	/**
	 * Returns the latest inspection record date of this vr method of issue.
	 *
	 * @return the latest inspection record date of this vr method of issue
	 */
	public Date getLatestInspectionRecordDate();

	/**
	 * Sets the latest inspection record date of this vr method of issue.
	 *
	 * @param latestInspectionRecordDate the latest inspection record date of this vr method of issue
	 */
	public void setLatestInspectionRecordDate(Date latestInspectionRecordDate);

	/**
	 * Returns the latest number of inspection in year of this vr method of issue.
	 *
	 * @return the latest number of inspection in year of this vr method of issue
	 */
	public int getLatestNumberOfInspectionInYear();

	/**
	 * Sets the latest number of inspection in year of this vr method of issue.
	 *
	 * @param latestNumberOfInspectionInYear the latest number of inspection in year of this vr method of issue
	 */
	public void setLatestNumberOfInspectionInYear(
		int latestNumberOfInspectionInYear);

	/**
	 * Returns the latest number of inspection in month of this vr method of issue.
	 *
	 * @return the latest number of inspection in month of this vr method of issue
	 */
	public int getLatestNumberOfInspectionInMonth();

	/**
	 * Sets the latest number of inspection in month of this vr method of issue.
	 *
	 * @param latestNumberOfInspectionInMonth the latest number of inspection in month of this vr method of issue
	 */
	public void setLatestNumberOfInspectionInMonth(
		int latestNumberOfInspectionInMonth);

	/**
	 * Returns the latest number of stamp in month of this vr method of issue.
	 *
	 * @return the latest number of stamp in month of this vr method of issue
	 */
	public int getLatestNumberOfStampInMonth();

	/**
	 * Sets the latest number of stamp in month of this vr method of issue.
	 *
	 * @param latestNumberOfStampInMonth the latest number of stamp in month of this vr method of issue
	 */
	public void setLatestNumberOfStampInMonth(int latestNumberOfStampInMonth);

	/**
	 * Returns the period start from of this vr method of issue.
	 *
	 * @return the period start from of this vr method of issue
	 */
	public Date getPeriodStartFrom();

	/**
	 * Sets the period start from of this vr method of issue.
	 *
	 * @param periodStartFrom the period start from of this vr method of issue
	 */
	public void setPeriodStartFrom(Date periodStartFrom);

	/**
	 * Returns the total inspection of this vr method of issue.
	 *
	 * @return the total inspection of this vr method of issue
	 */
	public int getTotalInspection();

	/**
	 * Sets the total inspection of this vr method of issue.
	 *
	 * @param totalInspection the total inspection of this vr method of issue
	 */
	public void setTotalInspection(int totalInspection);

	/**
	 * Returns the flow index of this vr method of issue.
	 *
	 * @return the flow index of this vr method of issue
	 */
	@AutoEscape
	public String getFlowIndex();

	/**
	 * Sets the flow index of this vr method of issue.
	 *
	 * @param flowIndex the flow index of this vr method of issue
	 */
	public void setFlowIndex(String flowIndex);

	/**
	 * Returns the modify date of this vr method of issue.
	 *
	 * @return the modify date of this vr method of issue
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr method of issue.
	 *
	 * @param modifyDate the modify date of this vr method of issue
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr method of issue.
	 *
	 * @return the sync date of this vr method of issue
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr method of issue.
	 *
	 * @param syncDate the sync date of this vr method of issue
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRMethodOfIssue vrMethodOfIssue);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRMethodOfIssue> toCacheModel();

	@Override
	public VRMethodOfIssue toEscapedModel();

	@Override
	public VRMethodOfIssue toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}