/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the VRMigrateReview service. Represents a row in the &quot;vr_migrate_review&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRMigrateReviewModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRMigrateReviewImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRMigrateReview
 * @see com.fds.vr.business.model.impl.VRMigrateReviewImpl
 * @see com.fds.vr.business.model.impl.VRMigrateReviewModelImpl
 * @generated
 */
@ProviderType
public interface VRMigrateReviewModel extends BaseModel<VRMigrateReview> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr migrate review model instance should use the {@link VRMigrateReview} interface instead.
	 */

	/**
	 * Returns the primary key of this vr migrate review.
	 *
	 * @return the primary key of this vr migrate review
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr migrate review.
	 *
	 * @param primaryKey the primary key of this vr migrate review
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr migrate review.
	 *
	 * @return the ID of this vr migrate review
	 */
	public long getId();

	/**
	 * Sets the ID of this vr migrate review.
	 *
	 * @param id the ID of this vr migrate review
	 */
	public void setId(long id);

	/**
	 * Returns the data group ID of this vr migrate review.
	 *
	 * @return the data group ID of this vr migrate review
	 */
	public int getDataGroupID();

	/**
	 * Sets the data group ID of this vr migrate review.
	 *
	 * @param dataGroupID the data group ID of this vr migrate review
	 */
	public void setDataGroupID(int dataGroupID);

	/**
	 * Returns the migrate table name of this vr migrate review.
	 *
	 * @return the migrate table name of this vr migrate review
	 */
	@AutoEscape
	public String getMigrateTableName();

	/**
	 * Sets the migrate table name of this vr migrate review.
	 *
	 * @param migrateTableName the migrate table name of this vr migrate review
	 */
	public void setMigrateTableName(String migrateTableName);

	/**
	 * Returns the migration configuration of this vr migrate review.
	 *
	 * @return the migration configuration of this vr migrate review
	 */
	@AutoEscape
	public String getMigrationConfiguration();

	/**
	 * Sets the migration configuration of this vr migrate review.
	 *
	 * @param migrationConfiguration the migration configuration of this vr migrate review
	 */
	public void setMigrationConfiguration(String migrationConfiguration);

	/**
	 * Returns the sequence no of this vr migrate review.
	 *
	 * @return the sequence no of this vr migrate review
	 */
	public int getSequenceNo();

	/**
	 * Sets the sequence no of this vr migrate review.
	 *
	 * @param sequenceNo the sequence no of this vr migrate review
	 */
	public void setSequenceNo(int sequenceNo);

	/**
	 * Returns the task migration ID of this vr migrate review.
	 *
	 * @return the task migration ID of this vr migrate review
	 */
	public int getTaskMigrationID();

	/**
	 * Sets the task migration ID of this vr migrate review.
	 *
	 * @param taskMigrationID the task migration ID of this vr migrate review
	 */
	public void setTaskMigrationID(int taskMigrationID);

	/**
	 * Returns the migrate rows of this vr migrate review.
	 *
	 * @return the migrate rows of this vr migrate review
	 */
	@AutoEscape
	public String getMigrateRows();

	/**
	 * Sets the migrate rows of this vr migrate review.
	 *
	 * @param migrateRows the migrate rows of this vr migrate review
	 */
	public void setMigrateRows(String migrateRows);

	/**
	 * Returns the migrate remarks of this vr migrate review.
	 *
	 * @return the migrate remarks of this vr migrate review
	 */
	@AutoEscape
	public String getMigrateRemarks();

	/**
	 * Sets the migrate remarks of this vr migrate review.
	 *
	 * @param migrateRemarks the migrate remarks of this vr migrate review
	 */
	public void setMigrateRemarks(String migrateRemarks);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRMigrateReview vrMigrateReview);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRMigrateReview> toCacheModel();

	@Override
	public VRMigrateReview toEscapedModel();

	@Override
	public VRMigrateReview toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}