/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the VRMigrateMappings service. Represents a row in the &quot;vr_migrate_mappings&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRMigrateMappingsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRMigrateMappingsImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRMigrateMappings
 * @see com.fds.vr.business.model.impl.VRMigrateMappingsImpl
 * @see com.fds.vr.business.model.impl.VRMigrateMappingsModelImpl
 * @generated
 */
@ProviderType
public interface VRMigrateMappingsModel extends BaseModel<VRMigrateMappings> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr migrate mappings model instance should use the {@link VRMigrateMappings} interface instead.
	 */

	/**
	 * Returns the primary key of this vr migrate mappings.
	 *
	 * @return the primary key of this vr migrate mappings
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr migrate mappings.
	 *
	 * @param primaryKey the primary key of this vr migrate mappings
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr migrate mappings.
	 *
	 * @return the ID of this vr migrate mappings
	 */
	public long getId();

	/**
	 * Sets the ID of this vr migrate mappings.
	 *
	 * @param id the ID of this vr migrate mappings
	 */
	public void setId(long id);

	/**
	 * Returns the data group ID of this vr migrate mappings.
	 *
	 * @return the data group ID of this vr migrate mappings
	 */
	public int getDataGroupId();

	/**
	 * Sets the data group ID of this vr migrate mappings.
	 *
	 * @param dataGroupId the data group ID of this vr migrate mappings
	 */
	public void setDataGroupId(int dataGroupId);

	/**
	 * Returns the sequence no of this vr migrate mappings.
	 *
	 * @return the sequence no of this vr migrate mappings
	 */
	public int getSequenceNo();

	/**
	 * Sets the sequence no of this vr migrate mappings.
	 *
	 * @param sequenceNo the sequence no of this vr migrate mappings
	 */
	public void setSequenceNo(int sequenceNo);

	/**
	 * Returns the migrate table name of this vr migrate mappings.
	 *
	 * @return the migrate table name of this vr migrate mappings
	 */
	@AutoEscape
	public String getMigrateTableName();

	/**
	 * Sets the migrate table name of this vr migrate mappings.
	 *
	 * @param migrateTableName the migrate table name of this vr migrate mappings
	 */
	public void setMigrateTableName(String migrateTableName);

	/**
	 * Returns the data item ID of this vr migrate mappings.
	 *
	 * @return the data item ID of this vr migrate mappings
	 */
	public int getDataItemID();

	/**
	 * Sets the data item ID of this vr migrate mappings.
	 *
	 * @param dataItemID the data item ID of this vr migrate mappings
	 */
	public void setDataItemID(int dataItemID);

	/**
	 * Returns the item code of this vr migrate mappings.
	 *
	 * @return the item code of this vr migrate mappings
	 */
	@AutoEscape
	public String getItemCode();

	/**
	 * Sets the item code of this vr migrate mappings.
	 *
	 * @param itemCode the item code of this vr migrate mappings
	 */
	public void setItemCode(String itemCode);

	/**
	 * Returns the item name of this vr migrate mappings.
	 *
	 * @return the item name of this vr migrate mappings
	 */
	@AutoEscape
	public String getItemName();

	/**
	 * Sets the item name of this vr migrate mappings.
	 *
	 * @param itemName the item name of this vr migrate mappings
	 */
	public void setItemName(String itemName);

	/**
	 * Returns the item short name of this vr migrate mappings.
	 *
	 * @return the item short name of this vr migrate mappings
	 */
	@AutoEscape
	public String getItemShortName();

	/**
	 * Sets the item short name of this vr migrate mappings.
	 *
	 * @param itemShortName the item short name of this vr migrate mappings
	 */
	public void setItemShortName(String itemShortName);

	/**
	 * Returns the item description of this vr migrate mappings.
	 *
	 * @return the item description of this vr migrate mappings
	 */
	@AutoEscape
	public String getItemDescription();

	/**
	 * Sets the item description of this vr migrate mappings.
	 *
	 * @param itemDescription the item description of this vr migrate mappings
	 */
	public void setItemDescription(String itemDescription);

	/**
	 * Returns the code_0 of this vr migrate mappings.
	 *
	 * @return the code_0 of this vr migrate mappings
	 */
	@AutoEscape
	public String getCode_0();

	/**
	 * Sets the code_0 of this vr migrate mappings.
	 *
	 * @param code_0 the code_0 of this vr migrate mappings
	 */
	public void setCode_0(String code_0);

	/**
	 * Returns the code_1 of this vr migrate mappings.
	 *
	 * @return the code_1 of this vr migrate mappings
	 */
	@AutoEscape
	public String getCode_1();

	/**
	 * Sets the code_1 of this vr migrate mappings.
	 *
	 * @param code_1 the code_1 of this vr migrate mappings
	 */
	public void setCode_1(String code_1);

	/**
	 * Returns the code_2 of this vr migrate mappings.
	 *
	 * @return the code_2 of this vr migrate mappings
	 */
	@AutoEscape
	public String getCode_2();

	/**
	 * Sets the code_2 of this vr migrate mappings.
	 *
	 * @param code_2 the code_2 of this vr migrate mappings
	 */
	public void setCode_2(String code_2);

	/**
	 * Returns the code_3 of this vr migrate mappings.
	 *
	 * @return the code_3 of this vr migrate mappings
	 */
	@AutoEscape
	public String getCode_3();

	/**
	 * Sets the code_3 of this vr migrate mappings.
	 *
	 * @param code_3 the code_3 of this vr migrate mappings
	 */
	public void setCode_3(String code_3);

	/**
	 * Returns the level of this vr migrate mappings.
	 *
	 * @return the level of this vr migrate mappings
	 */
	public int getLevel();

	/**
	 * Sets the level of this vr migrate mappings.
	 *
	 * @param level the level of this vr migrate mappings
	 */
	public void setLevel(int level);

	/**
	 * Returns the seq no of this vr migrate mappings.
	 *
	 * @return the seq no of this vr migrate mappings
	 */
	public int getSeqNo();

	/**
	 * Sets the seq no of this vr migrate mappings.
	 *
	 * @param seqNo the seq no of this vr migrate mappings
	 */
	public void setSeqNo(int seqNo);

	/**
	 * Returns the marked as restore of this vr migrate mappings.
	 *
	 * @return the marked as restore of this vr migrate mappings
	 */
	public int getMarkedAsRestore();

	/**
	 * Sets the marked as restore of this vr migrate mappings.
	 *
	 * @param markedAsRestore the marked as restore of this vr migrate mappings
	 */
	public void setMarkedAsRestore(int markedAsRestore);

	/**
	 * Returns the marked as delete of this vr migrate mappings.
	 *
	 * @return the marked as delete of this vr migrate mappings
	 */
	public int getMarkedAsDelete();

	/**
	 * Sets the marked as delete of this vr migrate mappings.
	 *
	 * @param markedAsDelete the marked as delete of this vr migrate mappings
	 */
	public void setMarkedAsDelete(int markedAsDelete);

	/**
	 * Returns the alter collection code of this vr migrate mappings.
	 *
	 * @return the alter collection code of this vr migrate mappings
	 */
	@AutoEscape
	public String getAlterCollectionCode();

	/**
	 * Sets the alter collection code of this vr migrate mappings.
	 *
	 * @param alterCollectionCode the alter collection code of this vr migrate mappings
	 */
	public void setAlterCollectionCode(String alterCollectionCode);

	/**
	 * Returns the alter item code of this vr migrate mappings.
	 *
	 * @return the alter item code of this vr migrate mappings
	 */
	@AutoEscape
	public String getAlterItemCode();

	/**
	 * Sets the alter item code of this vr migrate mappings.
	 *
	 * @param alterItemCode the alter item code of this vr migrate mappings
	 */
	public void setAlterItemCode(String alterItemCode);

	/**
	 * Returns the alter item name of this vr migrate mappings.
	 *
	 * @return the alter item name of this vr migrate mappings
	 */
	@AutoEscape
	public String getAlterItemName();

	/**
	 * Sets the alter item name of this vr migrate mappings.
	 *
	 * @param alterItemName the alter item name of this vr migrate mappings
	 */
	public void setAlterItemName(String alterItemName);

	/**
	 * Returns the alter group code of this vr migrate mappings.
	 *
	 * @return the alter group code of this vr migrate mappings
	 */
	@AutoEscape
	public String getAlterGroupCode();

	/**
	 * Sets the alter group code of this vr migrate mappings.
	 *
	 * @param alterGroupCode the alter group code of this vr migrate mappings
	 */
	public void setAlterGroupCode(String alterGroupCode);

	/**
	 * Returns the alter level of this vr migrate mappings.
	 *
	 * @return the alter level of this vr migrate mappings
	 */
	@AutoEscape
	public String getAlterLevel();

	/**
	 * Sets the alter level of this vr migrate mappings.
	 *
	 * @param alterLevel the alter level of this vr migrate mappings
	 */
	public void setAlterLevel(String alterLevel);

	/**
	 * Returns the task migration ID of this vr migrate mappings.
	 *
	 * @return the task migration ID of this vr migrate mappings
	 */
	public int getTaskMigrationID();

	/**
	 * Sets the task migration ID of this vr migrate mappings.
	 *
	 * @param taskMigrationID the task migration ID of this vr migrate mappings
	 */
	public void setTaskMigrationID(int taskMigrationID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRMigrateMappings vrMigrateMappings);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRMigrateMappings> toCacheModel();

	@Override
	public VRMigrateMappings toEscapedModel();

	@Override
	public VRMigrateMappings toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}