/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VROutputSheet service. Represents a row in the &quot;vr_outputsheet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VROutputSheetModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VROutputSheetImpl}.
 * </p>
 *
 * @author LamTV
 * @see VROutputSheet
 * @see com.fds.vr.business.model.impl.VROutputSheetImpl
 * @see com.fds.vr.business.model.impl.VROutputSheetModelImpl
 * @generated
 */
@ProviderType
public interface VROutputSheetModel extends BaseModel<VROutputSheet> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr output sheet model instance should use the {@link VROutputSheet} interface instead.
	 */

	/**
	 * Returns the primary key of this vr output sheet.
	 *
	 * @return the primary key of this vr output sheet
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr output sheet.
	 *
	 * @param primaryKey the primary key of this vr output sheet
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr output sheet.
	 *
	 * @return the ID of this vr output sheet
	 */
	public long getId();

	/**
	 * Sets the ID of this vr output sheet.
	 *
	 * @param id the ID of this vr output sheet
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr output sheet.
	 *
	 * @return the mt core of this vr output sheet
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr output sheet.
	 *
	 * @param mtCore the mt core of this vr output sheet
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the output sheet no of this vr output sheet.
	 *
	 * @return the output sheet no of this vr output sheet
	 */
	@AutoEscape
	public String getOutputSheetNo();

	/**
	 * Sets the output sheet no of this vr output sheet.
	 *
	 * @param outputSheetNo the output sheet no of this vr output sheet
	 */
	public void setOutputSheetNo(String outputSheetNo);

	/**
	 * Returns the output sheet date of this vr output sheet.
	 *
	 * @return the output sheet date of this vr output sheet
	 */
	public Date getOutputSheetDate();

	/**
	 * Sets the output sheet date of this vr output sheet.
	 *
	 * @param outputSheetDate the output sheet date of this vr output sheet
	 */
	public void setOutputSheetDate(Date outputSheetDate);

	/**
	 * Returns the original document no of this vr output sheet.
	 *
	 * @return the original document no of this vr output sheet
	 */
	@AutoEscape
	public String getOriginalDocumentNo();

	/**
	 * Sets the original document no of this vr output sheet.
	 *
	 * @param originalDocumentNo the original document no of this vr output sheet
	 */
	public void setOriginalDocumentNo(String originalDocumentNo);

	/**
	 * Returns the supplier corporation ID of this vr output sheet.
	 *
	 * @return the supplier corporation ID of this vr output sheet
	 */
	public long getSupplierCorporationId();

	/**
	 * Sets the supplier corporation ID of this vr output sheet.
	 *
	 * @param supplierCorporationId the supplier corporation ID of this vr output sheet
	 */
	public void setSupplierCorporationId(long supplierCorporationId);

	/**
	 * Returns the output sheet type of this vr output sheet.
	 *
	 * @return the output sheet type of this vr output sheet
	 */
	public long getOutputSheetType();

	/**
	 * Sets the output sheet type of this vr output sheet.
	 *
	 * @param outputSheetType the output sheet type of this vr output sheet
	 */
	public void setOutputSheetType(long outputSheetType);

	/**
	 * Returns the maker of this vr output sheet.
	 *
	 * @return the maker of this vr output sheet
	 */
	@AutoEscape
	public String getMaker();

	/**
	 * Sets the maker of this vr output sheet.
	 *
	 * @param maker the maker of this vr output sheet
	 */
	public void setMaker(String maker);

	/**
	 * Returns the checker of this vr output sheet.
	 *
	 * @return the checker of this vr output sheet
	 */
	@AutoEscape
	public String getChecker();

	/**
	 * Sets the checker of this vr output sheet.
	 *
	 * @param checker the checker of this vr output sheet
	 */
	public void setChecker(String checker);

	/**
	 * Returns the approver of this vr output sheet.
	 *
	 * @return the approver of this vr output sheet
	 */
	@AutoEscape
	public String getApprover();

	/**
	 * Sets the approver of this vr output sheet.
	 *
	 * @param approver the approver of this vr output sheet
	 */
	public void setApprover(String approver);

	/**
	 * Returns the receiver name of this vr output sheet.
	 *
	 * @return the receiver name of this vr output sheet
	 */
	@AutoEscape
	public String getReceiverName();

	/**
	 * Sets the receiver name of this vr output sheet.
	 *
	 * @param receiverName the receiver name of this vr output sheet
	 */
	public void setReceiverName(String receiverName);

	/**
	 * Returns the receiver place of this vr output sheet.
	 *
	 * @return the receiver place of this vr output sheet
	 */
	@AutoEscape
	public String getReceiverPlace();

	/**
	 * Sets the receiver place of this vr output sheet.
	 *
	 * @param receiverPlace the receiver place of this vr output sheet
	 */
	public void setReceiverPlace(String receiverPlace);

	/**
	 * Returns the receiver request of this vr output sheet.
	 *
	 * @return the receiver request of this vr output sheet
	 */
	@AutoEscape
	public String getReceiverRequest();

	/**
	 * Sets the receiver request of this vr output sheet.
	 *
	 * @param receiverRequest the receiver request of this vr output sheet
	 */
	public void setReceiverRequest(String receiverRequest);

	/**
	 * Returns the inventory name of this vr output sheet.
	 *
	 * @return the inventory name of this vr output sheet
	 */
	@AutoEscape
	public String getInventoryName();

	/**
	 * Sets the inventory name of this vr output sheet.
	 *
	 * @param inventoryName the inventory name of this vr output sheet
	 */
	public void setInventoryName(String inventoryName);

	/**
	 * Returns the inventory place of this vr output sheet.
	 *
	 * @return the inventory place of this vr output sheet
	 */
	@AutoEscape
	public String getInventoryPlace();

	/**
	 * Sets the inventory place of this vr output sheet.
	 *
	 * @param inventoryPlace the inventory place of this vr output sheet
	 */
	public void setInventoryPlace(String inventoryPlace);

	/**
	 * Returns the inventory date of this vr output sheet.
	 *
	 * @return the inventory date of this vr output sheet
	 */
	public Date getInventoryDate();

	/**
	 * Sets the inventory date of this vr output sheet.
	 *
	 * @param inventoryDate the inventory date of this vr output sheet
	 */
	public void setInventoryDate(Date inventoryDate);

	/**
	 * Returns the dossier ID of this vr output sheet.
	 *
	 * @return the dossier ID of this vr output sheet
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr output sheet.
	 *
	 * @param dossierId the dossier ID of this vr output sheet
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the issue ID of this vr output sheet.
	 *
	 * @return the issue ID of this vr output sheet
	 */
	public long getIssueId();

	/**
	 * Sets the issue ID of this vr output sheet.
	 *
	 * @param issueId the issue ID of this vr output sheet
	 */
	public void setIssueId(long issueId);

	/**
	 * Returns the purchaser ID of this vr output sheet.
	 *
	 * @return the purchaser ID of this vr output sheet
	 */
	public long getPurchaserId();

	/**
	 * Sets the purchaser ID of this vr output sheet.
	 *
	 * @param purchaserId the purchaser ID of this vr output sheet
	 */
	public void setPurchaserId(long purchaserId);

	/**
	 * Returns the purchaser corporation ID of this vr output sheet.
	 *
	 * @return the purchaser corporation ID of this vr output sheet
	 */
	public long getPurchaserCorporationId();

	/**
	 * Sets the purchaser corporation ID of this vr output sheet.
	 *
	 * @param purchaserCorporationId the purchaser corporation ID of this vr output sheet
	 */
	public void setPurchaserCorporationId(long purchaserCorporationId);

	/**
	 * Returns the book ID list of this vr output sheet.
	 *
	 * @return the book ID list of this vr output sheet
	 */
	@AutoEscape
	public String getBookIDList();

	/**
	 * Sets the book ID list of this vr output sheet.
	 *
	 * @param bookIDList the book ID list of this vr output sheet
	 */
	public void setBookIDList(String bookIDList);

	/**
	 * Returns the is approval of this vr output sheet.
	 *
	 * @return the is approval of this vr output sheet
	 */
	public long getIsApproval();

	/**
	 * Sets the is approval of this vr output sheet.
	 *
	 * @param isApproval the is approval of this vr output sheet
	 */
	public void setIsApproval(long isApproval);

	/**
	 * Returns the total quantities of this vr output sheet.
	 *
	 * @return the total quantities of this vr output sheet
	 */
	public long getTotalQuantities();

	/**
	 * Sets the total quantities of this vr output sheet.
	 *
	 * @param totalQuantities the total quantities of this vr output sheet
	 */
	public void setTotalQuantities(long totalQuantities);

	/**
	 * Returns the total amount of this vr output sheet.
	 *
	 * @return the total amount of this vr output sheet
	 */
	public long getTotalAmount();

	/**
	 * Sets the total amount of this vr output sheet.
	 *
	 * @param totalAmount the total amount of this vr output sheet
	 */
	public void setTotalAmount(long totalAmount);

	/**
	 * Returns the amount in words of this vr output sheet.
	 *
	 * @return the amount in words of this vr output sheet
	 */
	@AutoEscape
	public String getAmountInWords();

	/**
	 * Sets the amount in words of this vr output sheet.
	 *
	 * @param amountInWords the amount in words of this vr output sheet
	 */
	public void setAmountInWords(String amountInWords);

	/**
	 * Returns the remark of this vr output sheet.
	 *
	 * @return the remark of this vr output sheet
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this vr output sheet.
	 *
	 * @param remark the remark of this vr output sheet
	 */
	public void setRemark(String remark);

	/**
	 * Returns the modify date of this vr output sheet.
	 *
	 * @return the modify date of this vr output sheet
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr output sheet.
	 *
	 * @param modifyDate the modify date of this vr output sheet
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr output sheet.
	 *
	 * @return the sync date of this vr output sheet
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr output sheet.
	 *
	 * @param syncDate the sync date of this vr output sheet
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VROutputSheet vrOutputSheet);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VROutputSheet> toCacheModel();

	@Override
	public VROutputSheet toEscapedModel();

	@Override
	public VROutputSheet toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}