/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VROutputSheetDetails service. Represents a row in the &quot;vr_outputsheetdetails&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VROutputSheetDetailsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VROutputSheetDetailsImpl}.
 * </p>
 *
 * @author LamTV
 * @see VROutputSheetDetails
 * @see com.fds.vr.business.model.impl.VROutputSheetDetailsImpl
 * @see com.fds.vr.business.model.impl.VROutputSheetDetailsModelImpl
 * @generated
 */
@ProviderType
public interface VROutputSheetDetailsModel extends BaseModel<VROutputSheetDetails> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr output sheet details model instance should use the {@link VROutputSheetDetails} interface instead.
	 */

	/**
	 * Returns the primary key of this vr output sheet details.
	 *
	 * @return the primary key of this vr output sheet details
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr output sheet details.
	 *
	 * @param primaryKey the primary key of this vr output sheet details
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr output sheet details.
	 *
	 * @return the ID of this vr output sheet details
	 */
	public long getId();

	/**
	 * Sets the ID of this vr output sheet details.
	 *
	 * @param id the ID of this vr output sheet details
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr output sheet details.
	 *
	 * @return the mt core of this vr output sheet details
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr output sheet details.
	 *
	 * @param mtCore the mt core of this vr output sheet details
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the input sheet ID of this vr output sheet details.
	 *
	 * @return the input sheet ID of this vr output sheet details
	 */
	public long getInputSheetId();

	/**
	 * Sets the input sheet ID of this vr output sheet details.
	 *
	 * @param inputSheetId the input sheet ID of this vr output sheet details
	 */
	public void setInputSheetId(long inputSheetId);

	/**
	 * Returns the output sheet ID of this vr output sheet details.
	 *
	 * @return the output sheet ID of this vr output sheet details
	 */
	public long getOutputSheetId();

	/**
	 * Sets the output sheet ID of this vr output sheet details.
	 *
	 * @param outputSheetId the output sheet ID of this vr output sheet details
	 */
	public void setOutputSheetId(long outputSheetId);

	/**
	 * Returns the book ID of this vr output sheet details.
	 *
	 * @return the book ID of this vr output sheet details
	 */
	public long getBookId();

	/**
	 * Sets the book ID of this vr output sheet details.
	 *
	 * @param bookId the book ID of this vr output sheet details
	 */
	public void setBookId(long bookId);

	/**
	 * Returns the issue vehicle certificate ID of this vr output sheet details.
	 *
	 * @return the issue vehicle certificate ID of this vr output sheet details
	 */
	public long getIssueVehicleCertificateId();

	/**
	 * Sets the issue vehicle certificate ID of this vr output sheet details.
	 *
	 * @param issueVehicleCertificateId the issue vehicle certificate ID of this vr output sheet details
	 */
	public void setIssueVehicleCertificateId(long issueVehicleCertificateId);

	/**
	 * Returns the certificate ID of this vr output sheet details.
	 *
	 * @return the certificate ID of this vr output sheet details
	 */
	public long getCertificateId();

	/**
	 * Sets the certificate ID of this vr output sheet details.
	 *
	 * @param certificateId the certificate ID of this vr output sheet details
	 */
	public void setCertificateId(long certificateId);

	/**
	 * Returns the certificate number of this vr output sheet details.
	 *
	 * @return the certificate number of this vr output sheet details
	 */
	@AutoEscape
	public String getCertificateNumber();

	/**
	 * Sets the certificate number of this vr output sheet details.
	 *
	 * @param certificateNumber the certificate number of this vr output sheet details
	 */
	public void setCertificateNumber(String certificateNumber);

	/**
	 * Returns the certificate date of this vr output sheet details.
	 *
	 * @return the certificate date of this vr output sheet details
	 */
	public Date getCertificateDate();

	/**
	 * Sets the certificate date of this vr output sheet details.
	 *
	 * @param certificateDate the certificate date of this vr output sheet details
	 */
	public void setCertificateDate(Date certificateDate);

	/**
	 * Returns the vehicle class of this vr output sheet details.
	 *
	 * @return the vehicle class of this vr output sheet details
	 */
	@AutoEscape
	public String getVehicleClass();

	/**
	 * Sets the vehicle class of this vr output sheet details.
	 *
	 * @param vehicleClass the vehicle class of this vr output sheet details
	 */
	public void setVehicleClass(String vehicleClass);

	/**
	 * Returns the stamp type of this vr output sheet details.
	 *
	 * @return the stamp type of this vr output sheet details
	 */
	@AutoEscape
	public String getStampType();

	/**
	 * Sets the stamp type of this vr output sheet details.
	 *
	 * @param stampType the stamp type of this vr output sheet details
	 */
	public void setStampType(String stampType);

	/**
	 * Returns the stamp short no of this vr output sheet details.
	 *
	 * @return the stamp short no of this vr output sheet details
	 */
	@AutoEscape
	public String getStampShortNo();

	/**
	 * Sets the stamp short no of this vr output sheet details.
	 *
	 * @param stampShortNo the stamp short no of this vr output sheet details
	 */
	public void setStampShortNo(String stampShortNo);

	/**
	 * Returns the serial start no of this vr output sheet details.
	 *
	 * @return the serial start no of this vr output sheet details
	 */
	public long getSerialStartNo();

	/**
	 * Sets the serial start no of this vr output sheet details.
	 *
	 * @param serialStartNo the serial start no of this vr output sheet details
	 */
	public void setSerialStartNo(long serialStartNo);

	/**
	 * Returns the serial end no of this vr output sheet details.
	 *
	 * @return the serial end no of this vr output sheet details
	 */
	public long getSerialEndNo();

	/**
	 * Sets the serial end no of this vr output sheet details.
	 *
	 * @param serialEndNo the serial end no of this vr output sheet details
	 */
	public void setSerialEndNo(long serialEndNo);

	/**
	 * Returns the sub total in document of this vr output sheet details.
	 *
	 * @return the sub total in document of this vr output sheet details
	 */
	public long getSubTotalInDocument();

	/**
	 * Sets the sub total in document of this vr output sheet details.
	 *
	 * @param subTotalInDocument the sub total in document of this vr output sheet details
	 */
	public void setSubTotalInDocument(long subTotalInDocument);

	/**
	 * Returns the sub total quantities of this vr output sheet details.
	 *
	 * @return the sub total quantities of this vr output sheet details
	 */
	public long getSubTotalQuantities();

	/**
	 * Sets the sub total quantities of this vr output sheet details.
	 *
	 * @param subTotalQuantities the sub total quantities of this vr output sheet details
	 */
	public void setSubTotalQuantities(long subTotalQuantities);

	/**
	 * Returns the unit price of this vr output sheet details.
	 *
	 * @return the unit price of this vr output sheet details
	 */
	public long getUnitPrice();

	/**
	 * Sets the unit price of this vr output sheet details.
	 *
	 * @param unitPrice the unit price of this vr output sheet details
	 */
	public void setUnitPrice(long unitPrice);

	/**
	 * Returns the total amount of this vr output sheet details.
	 *
	 * @return the total amount of this vr output sheet details
	 */
	public long getTotalAmount();

	/**
	 * Sets the total amount of this vr output sheet details.
	 *
	 * @param totalAmount the total amount of this vr output sheet details
	 */
	public void setTotalAmount(long totalAmount);

	/**
	 * Returns the total in use of this vr output sheet details.
	 *
	 * @return the total in use of this vr output sheet details
	 */
	public long getTotalInUse();

	/**
	 * Sets the total in use of this vr output sheet details.
	 *
	 * @param totalInUse the total in use of this vr output sheet details
	 */
	public void setTotalInUse(long totalInUse);

	/**
	 * Returns the total not used of this vr output sheet details.
	 *
	 * @return the total not used of this vr output sheet details
	 */
	public long getTotalNotUsed();

	/**
	 * Sets the total not used of this vr output sheet details.
	 *
	 * @param totalNotUsed the total not used of this vr output sheet details
	 */
	public void setTotalNotUsed(long totalNotUsed);

	/**
	 * Returns the total lost of this vr output sheet details.
	 *
	 * @return the total lost of this vr output sheet details
	 */
	public long getTotalLost();

	/**
	 * Sets the total lost of this vr output sheet details.
	 *
	 * @param totalLost the total lost of this vr output sheet details
	 */
	public void setTotalLost(long totalLost);

	/**
	 * Returns the total cancelled of this vr output sheet details.
	 *
	 * @return the total cancelled of this vr output sheet details
	 */
	public long getTotalCancelled();

	/**
	 * Sets the total cancelled of this vr output sheet details.
	 *
	 * @param totalCancelled the total cancelled of this vr output sheet details
	 */
	public void setTotalCancelled(long totalCancelled);

	/**
	 * Returns the total returned of this vr output sheet details.
	 *
	 * @return the total returned of this vr output sheet details
	 */
	public long getTotalReturned();

	/**
	 * Sets the total returned of this vr output sheet details.
	 *
	 * @param totalReturned the total returned of this vr output sheet details
	 */
	public void setTotalReturned(long totalReturned);

	/**
	 * Returns the remark of this vr output sheet details.
	 *
	 * @return the remark of this vr output sheet details
	 */
	@AutoEscape
	public String getRemark();

	/**
	 * Sets the remark of this vr output sheet details.
	 *
	 * @param remark the remark of this vr output sheet details
	 */
	public void setRemark(String remark);

	/**
	 * Returns the modify date of this vr output sheet details.
	 *
	 * @return the modify date of this vr output sheet details
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr output sheet details.
	 *
	 * @param modifyDate the modify date of this vr output sheet details
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr output sheet details.
	 *
	 * @return the sync date of this vr output sheet details
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr output sheet details.
	 *
	 * @param syncDate the sync date of this vr output sheet details
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VROutputSheetDetails vrOutputSheetDetails);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VROutputSheetDetails> toCacheModel();

	@Override
	public VROutputSheetDetails toEscapedModel();

	@Override
	public VROutputSheetDetails toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}