/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRRPDossierStatistics service. Represents a row in the &quot;vr_rp_dossierstatistics&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRRPDossierStatisticsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRRPDossierStatisticsImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRRPDossierStatistics
 * @see com.fds.vr.business.model.impl.VRRPDossierStatisticsImpl
 * @see com.fds.vr.business.model.impl.VRRPDossierStatisticsModelImpl
 * @generated
 */
@ProviderType
public interface VRRPDossierStatisticsModel extends BaseModel<VRRPDossierStatistics> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vrrp dossier statistics model instance should use the {@link VRRPDossierStatistics} interface instead.
	 */

	/**
	 * Returns the primary key of this vrrp dossier statistics.
	 *
	 * @return the primary key of this vrrp dossier statistics
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vrrp dossier statistics.
	 *
	 * @param primaryKey the primary key of this vrrp dossier statistics
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vrrp dossier statistics.
	 *
	 * @return the ID of this vrrp dossier statistics
	 */
	public long getId();

	/**
	 * Sets the ID of this vrrp dossier statistics.
	 *
	 * @param id the ID of this vrrp dossier statistics
	 */
	public void setId(long id);

	/**
	 * Returns the dossierid of this vrrp dossier statistics.
	 *
	 * @return the dossierid of this vrrp dossier statistics
	 */
	public long getDossierid();

	/**
	 * Sets the dossierid of this vrrp dossier statistics.
	 *
	 * @param dossierid the dossierid of this vrrp dossier statistics
	 */
	public void setDossierid(long dossierid);

	/**
	 * Returns the dossier ID ctn of this vrrp dossier statistics.
	 *
	 * @return the dossier ID ctn of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vrrp dossier statistics.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vrrp dossier statistics
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the dossierno of this vrrp dossier statistics.
	 *
	 * @return the dossierno of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossierno();

	/**
	 * Sets the dossierno of this vrrp dossier statistics.
	 *
	 * @param dossierno the dossierno of this vrrp dossier statistics
	 */
	public void setDossierno(String dossierno);

	/**
	 * Returns the dossiersendingdate of this vrrp dossier statistics.
	 *
	 * @return the dossiersendingdate of this vrrp dossier statistics
	 */
	public Date getDossiersendingdate();

	/**
	 * Sets the dossiersendingdate of this vrrp dossier statistics.
	 *
	 * @param dossiersendingdate the dossiersendingdate of this vrrp dossier statistics
	 */
	public void setDossiersendingdate(Date dossiersendingdate);

	/**
	 * Returns the dossierreceivingdate of this vrrp dossier statistics.
	 *
	 * @return the dossierreceivingdate of this vrrp dossier statistics
	 */
	public Date getDossierreceivingdate();

	/**
	 * Sets the dossierreceivingdate of this vrrp dossier statistics.
	 *
	 * @param dossierreceivingdate the dossierreceivingdate of this vrrp dossier statistics
	 */
	public void setDossierreceivingdate(Date dossierreceivingdate);

	/**
	 * Returns the dossierfirstupdatingdate of this vrrp dossier statistics.
	 *
	 * @return the dossierfirstupdatingdate of this vrrp dossier statistics
	 */
	public Date getDossierfirstupdatingdate();

	/**
	 * Sets the dossierfirstupdatingdate of this vrrp dossier statistics.
	 *
	 * @param dossierfirstupdatingdate the dossierfirstupdatingdate of this vrrp dossier statistics
	 */
	public void setDossierfirstupdatingdate(Date dossierfirstupdatingdate);

	/**
	 * Returns the dossierlastupdatingdate of this vrrp dossier statistics.
	 *
	 * @return the dossierlastupdatingdate of this vrrp dossier statistics
	 */
	public Date getDossierlastupdatingdate();

	/**
	 * Sets the dossierlastupdatingdate of this vrrp dossier statistics.
	 *
	 * @param dossierlastupdatingdate the dossierlastupdatingdate of this vrrp dossier statistics
	 */
	public void setDossierlastupdatingdate(Date dossierlastupdatingdate);

	/**
	 * Returns the dossierendorsementdate of this vrrp dossier statistics.
	 *
	 * @return the dossierendorsementdate of this vrrp dossier statistics
	 */
	public Date getDossierendorsementdate();

	/**
	 * Sets the dossierendorsementdate of this vrrp dossier statistics.
	 *
	 * @param dossierendorsementdate the dossierendorsementdate of this vrrp dossier statistics
	 */
	public void setDossierendorsementdate(Date dossierendorsementdate);

	/**
	 * Returns the dossiersubmittingdate of this vrrp dossier statistics.
	 *
	 * @return the dossiersubmittingdate of this vrrp dossier statistics
	 */
	public Date getDossiersubmittingdate();

	/**
	 * Sets the dossiersubmittingdate of this vrrp dossier statistics.
	 *
	 * @param dossiersubmittingdate the dossiersubmittingdate of this vrrp dossier statistics
	 */
	public void setDossiersubmittingdate(Date dossiersubmittingdate);

	/**
	 * Returns the dossierfirstcertificatesigndate of this vrrp dossier statistics.
	 *
	 * @return the dossierfirstcertificatesigndate of this vrrp dossier statistics
	 */
	public Date getDossierfirstcertificatesigndate();

	/**
	 * Sets the dossierfirstcertificatesigndate of this vrrp dossier statistics.
	 *
	 * @param dossierfirstcertificatesigndate the dossierfirstcertificatesigndate of this vrrp dossier statistics
	 */
	public void setDossierfirstcertificatesigndate(
		Date dossierfirstcertificatesigndate);

	/**
	 * Returns the dossierfirstassignmentdate of this vrrp dossier statistics.
	 *
	 * @return the dossierfirstassignmentdate of this vrrp dossier statistics
	 */
	public Date getDossierfirstassignmentdate();

	/**
	 * Sets the dossierfirstassignmentdate of this vrrp dossier statistics.
	 *
	 * @param dossierfirstassignmentdate the dossierfirstassignmentdate of this vrrp dossier statistics
	 */
	public void setDossierfirstassignmentdate(Date dossierfirstassignmentdate);

	/**
	 * Returns the dossierfirstreviewdate of this vrrp dossier statistics.
	 *
	 * @return the dossierfirstreviewdate of this vrrp dossier statistics
	 */
	public Date getDossierfirstreviewdate();

	/**
	 * Sets the dossierfirstreviewdate of this vrrp dossier statistics.
	 *
	 * @param dossierfirstreviewdate the dossierfirstreviewdate of this vrrp dossier statistics
	 */
	public void setDossierfirstreviewdate(Date dossierfirstreviewdate);

	/**
	 * Returns the dossiernexttreviewdate of this vrrp dossier statistics.
	 *
	 * @return the dossiernexttreviewdate of this vrrp dossier statistics
	 */
	public Date getDossiernexttreviewdate();

	/**
	 * Sets the dossiernexttreviewdate of this vrrp dossier statistics.
	 *
	 * @param dossiernexttreviewdate the dossiernexttreviewdate of this vrrp dossier statistics
	 */
	public void setDossiernexttreviewdate(Date dossiernexttreviewdate);

	/**
	 * Returns the dossierlastassignmentdate of this vrrp dossier statistics.
	 *
	 * @return the dossierlastassignmentdate of this vrrp dossier statistics
	 */
	public Date getDossierlastassignmentdate();

	/**
	 * Sets the dossierlastassignmentdate of this vrrp dossier statistics.
	 *
	 * @param dossierlastassignmentdate the dossierlastassignmentdate of this vrrp dossier statistics
	 */
	public void setDossierlastassignmentdate(Date dossierlastassignmentdate);

	/**
	 * Returns the dossierreviewadjustdate of this vrrp dossier statistics.
	 *
	 * @return the dossierreviewadjustdate of this vrrp dossier statistics
	 */
	public Date getDossierreviewadjustdate();

	/**
	 * Sets the dossierreviewadjustdate of this vrrp dossier statistics.
	 *
	 * @param dossierreviewadjustdate the dossierreviewadjustdate of this vrrp dossier statistics
	 */
	public void setDossierreviewadjustdate(Date dossierreviewadjustdate);

	/**
	 * Returns the dossierlastreviewadjustdate of this vrrp dossier statistics.
	 *
	 * @return the dossierlastreviewadjustdate of this vrrp dossier statistics
	 */
	public Date getDossierlastreviewadjustdate();

	/**
	 * Sets the dossierlastreviewadjustdate of this vrrp dossier statistics.
	 *
	 * @param dossierlastreviewadjustdate the dossierlastreviewadjustdate of this vrrp dossier statistics
	 */
	public void setDossierlastreviewadjustdate(Date dossierlastreviewadjustdate);

	/**
	 * Returns the dossierlastcertificatesigndate of this vrrp dossier statistics.
	 *
	 * @return the dossierlastcertificatesigndate of this vrrp dossier statistics
	 */
	public Date getDossierlastcertificatesigndate();

	/**
	 * Sets the dossierlastcertificatesigndate of this vrrp dossier statistics.
	 *
	 * @param dossierlastcertificatesigndate the dossierlastcertificatesigndate of this vrrp dossier statistics
	 */
	public void setDossierlastcertificatesigndate(
		Date dossierlastcertificatesigndate);

	/**
	 * Returns the dossierdeadline of this vrrp dossier statistics.
	 *
	 * @return the dossierdeadline of this vrrp dossier statistics
	 */
	public Date getDossierdeadline();

	/**
	 * Sets the dossierdeadline of this vrrp dossier statistics.
	 *
	 * @param dossierdeadline the dossierdeadline of this vrrp dossier statistics
	 */
	public void setDossierdeadline(Date dossierdeadline);

	/**
	 * Returns the dossierfinisheddate of this vrrp dossier statistics.
	 *
	 * @return the dossierfinisheddate of this vrrp dossier statistics
	 */
	public Date getDossierfinisheddate();

	/**
	 * Sets the dossierfinisheddate of this vrrp dossier statistics.
	 *
	 * @param dossierfinisheddate the dossierfinisheddate of this vrrp dossier statistics
	 */
	public void setDossierfinisheddate(Date dossierfinisheddate);

	/**
	 * Returns the dossiercancellingdate of this vrrp dossier statistics.
	 *
	 * @return the dossiercancellingdate of this vrrp dossier statistics
	 */
	public Date getDossiercancellingdate();

	/**
	 * Sets the dossiercancellingdate of this vrrp dossier statistics.
	 *
	 * @param dossiercancellingdate the dossiercancellingdate of this vrrp dossier statistics
	 */
	public void setDossiercancellingdate(Date dossiercancellingdate);

	/**
	 * Returns the dossierexpiredate of this vrrp dossier statistics.
	 *
	 * @return the dossierexpiredate of this vrrp dossier statistics
	 */
	public Date getDossierexpiredate();

	/**
	 * Sets the dossierexpiredate of this vrrp dossier statistics.
	 *
	 * @param dossierexpiredate the dossierexpiredate of this vrrp dossier statistics
	 */
	public void setDossierexpiredate(Date dossierexpiredate);

	/**
	 * Returns the dossierviolatingdate of this vrrp dossier statistics.
	 *
	 * @return the dossierviolatingdate of this vrrp dossier statistics
	 */
	public Date getDossierviolatingdate();

	/**
	 * Sets the dossierviolatingdate of this vrrp dossier statistics.
	 *
	 * @param dossierviolatingdate the dossierviolatingdate of this vrrp dossier statistics
	 */
	public void setDossierviolatingdate(Date dossierviolatingdate);

	/**
	 * Returns the dossierviolatingfromdate of this vrrp dossier statistics.
	 *
	 * @return the dossierviolatingfromdate of this vrrp dossier statistics
	 */
	public Date getDossierviolatingfromdate();

	/**
	 * Sets the dossierviolatingfromdate of this vrrp dossier statistics.
	 *
	 * @param dossierviolatingfromdate the dossierviolatingfromdate of this vrrp dossier statistics
	 */
	public void setDossierviolatingfromdate(Date dossierviolatingfromdate);

	/**
	 * Returns the dossierviolatingtodate of this vrrp dossier statistics.
	 *
	 * @return the dossierviolatingtodate of this vrrp dossier statistics
	 */
	public Date getDossierviolatingtodate();

	/**
	 * Sets the dossierviolatingtodate of this vrrp dossier statistics.
	 *
	 * @param dossierviolatingtodate the dossierviolatingtodate of this vrrp dossier statistics
	 */
	public void setDossierviolatingtodate(Date dossierviolatingtodate);

	/**
	 * Returns the dossiertype of this vrrp dossier statistics.
	 *
	 * @return the dossiertype of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossiertype();

	/**
	 * Sets the dossiertype of this vrrp dossier statistics.
	 *
	 * @param dossiertype the dossiertype of this vrrp dossier statistics
	 */
	public void setDossiertype(String dossiertype);

	/**
	 * Returns the dossiertype_endorsed of this vrrp dossier statistics.
	 *
	 * @return the dossiertype_endorsed of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossiertype_endorsed();

	/**
	 * Sets the dossiertype_endorsed of this vrrp dossier statistics.
	 *
	 * @param dossiertype_endorsed the dossiertype_endorsed of this vrrp dossier statistics
	 */
	public void setDossiertype_endorsed(String dossiertype_endorsed);

	/**
	 * Returns the dossiertype_expired of this vrrp dossier statistics.
	 *
	 * @return the dossiertype_expired of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossiertype_expired();

	/**
	 * Sets the dossiertype_expired of this vrrp dossier statistics.
	 *
	 * @param dossiertype_expired the dossiertype_expired of this vrrp dossier statistics
	 */
	public void setDossiertype_expired(String dossiertype_expired);

	/**
	 * Returns the dossiertype_updated of this vrrp dossier statistics.
	 *
	 * @return the dossiertype_updated of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossiertype_updated();

	/**
	 * Sets the dossiertype_updated of this vrrp dossier statistics.
	 *
	 * @param dossiertype_updated the dossiertype_updated of this vrrp dossier statistics
	 */
	public void setDossiertype_updated(String dossiertype_updated);

	/**
	 * Returns the dossiertype_delayed of this vrrp dossier statistics.
	 *
	 * @return the dossiertype_delayed of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossiertype_delayed();

	/**
	 * Sets the dossiertype_delayed of this vrrp dossier statistics.
	 *
	 * @param dossiertype_delayed the dossiertype_delayed of this vrrp dossier statistics
	 */
	public void setDossiertype_delayed(String dossiertype_delayed);

	/**
	 * Returns the dossierdelayday of this vrrp dossier statistics.
	 *
	 * @return the dossierdelayday of this vrrp dossier statistics
	 */
	public int getDossierdelayday();

	/**
	 * Sets the dossierdelayday of this vrrp dossier statistics.
	 *
	 * @param dossierdelayday the dossierdelayday of this vrrp dossier statistics
	 */
	public void setDossierdelayday(int dossierdelayday);

	/**
	 * Returns the dossierdelayreason of this vrrp dossier statistics.
	 *
	 * @return the dossierdelayreason of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossierdelayreason();

	/**
	 * Sets the dossierdelayreason of this vrrp dossier statistics.
	 *
	 * @param dossierdelayreason the dossierdelayreason of this vrrp dossier statistics
	 */
	public void setDossierdelayreason(String dossierdelayreason);

	/**
	 * Returns the dossierstatus_processing of this vrrp dossier statistics.
	 *
	 * @return the dossierstatus_processing of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossierstatus_processing();

	/**
	 * Sets the dossierstatus_processing of this vrrp dossier statistics.
	 *
	 * @param dossierstatus_processing the dossierstatus_processing of this vrrp dossier statistics
	 */
	public void setDossierstatus_processing(String dossierstatus_processing);

	/**
	 * Returns the dossiersubstatus of this vrrp dossier statistics.
	 *
	 * @return the dossiersubstatus of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossiersubstatus();

	/**
	 * Sets the dossiersubstatus of this vrrp dossier statistics.
	 *
	 * @param dossiersubstatus the dossiersubstatus of this vrrp dossier statistics
	 */
	public void setDossiersubstatus(String dossiersubstatus);

	/**
	 * Returns the dossierresult of this vrrp dossier statistics.
	 *
	 * @return the dossierresult of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDossierresult();

	/**
	 * Sets the dossierresult of this vrrp dossier statistics.
	 *
	 * @param dossierresult the dossierresult of this vrrp dossier statistics
	 */
	public void setDossierresult(String dossierresult);

	/**
	 * Returns the remark to update of this vrrp dossier statistics.
	 *
	 * @return the remark to update of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getRemarkToUpdate();

	/**
	 * Sets the remark to update of this vrrp dossier statistics.
	 *
	 * @param remarkToUpdate the remark to update of this vrrp dossier statistics
	 */
	public void setRemarkToUpdate(String remarkToUpdate);

	/**
	 * Returns the remark to result of this vrrp dossier statistics.
	 *
	 * @return the remark to result of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getRemarkToResult();

	/**
	 * Sets the remark to result of this vrrp dossier statistics.
	 *
	 * @param remarkToResult the remark to result of this vrrp dossier statistics
	 */
	public void setRemarkToResult(String remarkToResult);

	/**
	 * Returns the resultdescription1 of this vrrp dossier statistics.
	 *
	 * @return the resultdescription1 of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getResultdescription1();

	/**
	 * Sets the resultdescription1 of this vrrp dossier statistics.
	 *
	 * @param resultdescription1 the resultdescription1 of this vrrp dossier statistics
	 */
	public void setResultdescription1(String resultdescription1);

	/**
	 * Returns the resultdescription2 of this vrrp dossier statistics.
	 *
	 * @return the resultdescription2 of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getResultdescription2();

	/**
	 * Sets the resultdescription2 of this vrrp dossier statistics.
	 *
	 * @param resultdescription2 the resultdescription2 of this vrrp dossier statistics
	 */
	public void setResultdescription2(String resultdescription2);

	/**
	 * Returns the resultdescription3 of this vrrp dossier statistics.
	 *
	 * @return the resultdescription3 of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getResultdescription3();

	/**
	 * Sets the resultdescription3 of this vrrp dossier statistics.
	 *
	 * @param resultdescription3 the resultdescription3 of this vrrp dossier statistics
	 */
	public void setResultdescription3(String resultdescription3);

	/**
	 * Returns the applicant no of this vrrp dossier statistics.
	 *
	 * @return the applicant no of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getApplicantNo();

	/**
	 * Sets the applicant no of this vrrp dossier statistics.
	 *
	 * @param applicantNo the applicant no of this vrrp dossier statistics
	 */
	public void setApplicantNo(String applicantNo);

	/**
	 * Returns the applicantname of this vrrp dossier statistics.
	 *
	 * @return the applicantname of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getApplicantname();

	/**
	 * Sets the applicantname of this vrrp dossier statistics.
	 *
	 * @param applicantname the applicantname of this vrrp dossier statistics
	 */
	public void setApplicantname(String applicantname);

	/**
	 * Returns the applicantaddress of this vrrp dossier statistics.
	 *
	 * @return the applicantaddress of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getApplicantaddress();

	/**
	 * Sets the applicantaddress of this vrrp dossier statistics.
	 *
	 * @param applicantaddress the applicantaddress of this vrrp dossier statistics
	 */
	public void setApplicantaddress(String applicantaddress);

	/**
	 * Returns the productionplantname of this vrrp dossier statistics.
	 *
	 * @return the productionplantname of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getProductionplantname();

	/**
	 * Sets the productionplantname of this vrrp dossier statistics.
	 *
	 * @param productionplantname the productionplantname of this vrrp dossier statistics
	 */
	public void setProductionplantname(String productionplantname);

	/**
	 * Returns the productionplantaddress of this vrrp dossier statistics.
	 *
	 * @return the productionplantaddress of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getProductionplantaddress();

	/**
	 * Sets the productionplantaddress of this vrrp dossier statistics.
	 *
	 * @param productionplantaddress the productionplantaddress of this vrrp dossier statistics
	 */
	public void setProductionplantaddress(String productionplantaddress);

	/**
	 * Returns the domestic fdi of this vrrp dossier statistics.
	 *
	 * @return the domestic fdi of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getDomesticFDI();

	/**
	 * Sets the domestic fdi of this vrrp dossier statistics.
	 *
	 * @param domesticFDI the domestic fdi of this vrrp dossier statistics
	 */
	public void setDomesticFDI(String domesticFDI);

	/**
	 * Returns the vehicleclass of this vrrp dossier statistics.
	 *
	 * @return the vehicleclass of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getVehicleclass();

	/**
	 * Sets the vehicleclass of this vrrp dossier statistics.
	 *
	 * @param vehicleclass the vehicleclass of this vrrp dossier statistics
	 */
	public void setVehicleclass(String vehicleclass);

	/**
	 * Returns the certifiedvehicletype of this vrrp dossier statistics.
	 *
	 * @return the certifiedvehicletype of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertifiedvehicletype();

	/**
	 * Sets the certifiedvehicletype of this vrrp dossier statistics.
	 *
	 * @param certifiedvehicletype the certifiedvehicletype of this vrrp dossier statistics
	 */
	public void setCertifiedvehicletype(String certifiedvehicletype);

	/**
	 * Returns the certifiedvehicletypedescription of this vrrp dossier statistics.
	 *
	 * @return the certifiedvehicletypedescription of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertifiedvehicletypedescription();

	/**
	 * Sets the certifiedvehicletypedescription of this vrrp dossier statistics.
	 *
	 * @param certifiedvehicletypedescription the certifiedvehicletypedescription of this vrrp dossier statistics
	 */
	public void setCertifiedvehicletypedescription(
		String certifiedvehicletypedescription);

	/**
	 * Returns the certifiedtrademark of this vrrp dossier statistics.
	 *
	 * @return the certifiedtrademark of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertifiedtrademark();

	/**
	 * Sets the certifiedtrademark of this vrrp dossier statistics.
	 *
	 * @param certifiedtrademark the certifiedtrademark of this vrrp dossier statistics
	 */
	public void setCertifiedtrademark(String certifiedtrademark);

	/**
	 * Returns the certifiedtrademarkname of this vrrp dossier statistics.
	 *
	 * @return the certifiedtrademarkname of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertifiedtrademarkname();

	/**
	 * Sets the certifiedtrademarkname of this vrrp dossier statistics.
	 *
	 * @param certifiedtrademarkname the certifiedtrademarkname of this vrrp dossier statistics
	 */
	public void setCertifiedtrademarkname(String certifiedtrademarkname);

	/**
	 * Returns the certifiedcommercialname of this vrrp dossier statistics.
	 *
	 * @return the certifiedcommercialname of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertifiedcommercialname();

	/**
	 * Sets the certifiedcommercialname of this vrrp dossier statistics.
	 *
	 * @param certifiedcommercialname the certifiedcommercialname of this vrrp dossier statistics
	 */
	public void setCertifiedcommercialname(String certifiedcommercialname);

	/**
	 * Returns the certifiedmodelcode of this vrrp dossier statistics.
	 *
	 * @return the certifiedmodelcode of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertifiedmodelcode();

	/**
	 * Sets the certifiedmodelcode of this vrrp dossier statistics.
	 *
	 * @param certifiedmodelcode the certifiedmodelcode of this vrrp dossier statistics
	 */
	public void setCertifiedmodelcode(String certifiedmodelcode);

	/**
	 * Returns the certifiedassemblytype of this vrrp dossier statistics.
	 *
	 * @return the certifiedassemblytype of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertifiedassemblytype();

	/**
	 * Sets the certifiedassemblytype of this vrrp dossier statistics.
	 *
	 * @param certifiedassemblytype the certifiedassemblytype of this vrrp dossier statistics
	 */
	public void setCertifiedassemblytype(String certifiedassemblytype);

	/**
	 * Returns the certifiedassemblytypedescription of this vrrp dossier statistics.
	 *
	 * @return the certifiedassemblytypedescription of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertifiedassemblytypedescription();

	/**
	 * Sets the certifiedassemblytypedescription of this vrrp dossier statistics.
	 *
	 * @param certifiedassemblytypedescription the certifiedassemblytypedescription of this vrrp dossier statistics
	 */
	public void setCertifiedassemblytypedescription(
		String certifiedassemblytypedescription);

	/**
	 * Returns the equipmentimportquantity of this vrrp dossier statistics.
	 *
	 * @return the equipmentimportquantity of this vrrp dossier statistics
	 */
	public int getEquipmentimportquantity();

	/**
	 * Sets the equipmentimportquantity of this vrrp dossier statistics.
	 *
	 * @param equipmentimportquantity the equipmentimportquantity of this vrrp dossier statistics
	 */
	public void setEquipmentimportquantity(int equipmentimportquantity);

	/**
	 * Returns the seat number of this vrrp dossier statistics.
	 *
	 * @return the seat number of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getSeatNumber();

	/**
	 * Sets the seat number of this vrrp dossier statistics.
	 *
	 * @param SeatNumber the seat number of this vrrp dossier statistics
	 */
	public void setSeatNumber(String SeatNumber);

	/**
	 * Returns the engine type of this vrrp dossier statistics.
	 *
	 * @return the engine type of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getEngineType();

	/**
	 * Sets the engine type of this vrrp dossier statistics.
	 *
	 * @param EngineType the engine type of this vrrp dossier statistics
	 */
	public void setEngineType(String EngineType);

	/**
	 * Returns the engine type description of this vrrp dossier statistics.
	 *
	 * @return the engine type description of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getEngineTypeDescription();

	/**
	 * Sets the engine type description of this vrrp dossier statistics.
	 *
	 * @param EngineTypeDescription the engine type description of this vrrp dossier statistics
	 */
	public void setEngineTypeDescription(String EngineTypeDescription);

	/**
	 * Returns the certificaterecordno_new of this vrrp dossier statistics.
	 *
	 * @return the certificaterecordno_new of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertificaterecordno_new();

	/**
	 * Sets the certificaterecordno_new of this vrrp dossier statistics.
	 *
	 * @param certificaterecordno_new the certificaterecordno_new of this vrrp dossier statistics
	 */
	public void setCertificaterecordno_new(String certificaterecordno_new);

	/**
	 * Returns the certificaterecordno_renew of this vrrp dossier statistics.
	 *
	 * @return the certificaterecordno_renew of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertificaterecordno_renew();

	/**
	 * Sets the certificaterecordno_renew of this vrrp dossier statistics.
	 *
	 * @param certificaterecordno_renew the certificaterecordno_renew of this vrrp dossier statistics
	 */
	public void setCertificaterecordno_renew(String certificaterecordno_renew);

	/**
	 * Returns the certificateyear of this vrrp dossier statistics.
	 *
	 * @return the certificateyear of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCertificateyear();

	/**
	 * Sets the certificateyear of this vrrp dossier statistics.
	 *
	 * @param certificateyear the certificateyear of this vrrp dossier statistics
	 */
	public void setCertificateyear(String certificateyear);

	/**
	 * Returns the certificatemonth of this vrrp dossier statistics.
	 *
	 * @return the certificatemonth of this vrrp dossier statistics
	 */
	public int getCertificatemonth();

	/**
	 * Sets the certificatemonth of this vrrp dossier statistics.
	 *
	 * @param certificatemonth the certificatemonth of this vrrp dossier statistics
	 */
	public void setCertificatemonth(int certificatemonth);

	/**
	 * Returns the corporation ID of this vrrp dossier statistics.
	 *
	 * @return the corporation ID of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getCorporationId();

	/**
	 * Sets the corporation ID of this vrrp dossier statistics.
	 *
	 * @param corporationId the corporation ID of this vrrp dossier statistics
	 */
	public void setCorporationId(String corporationId);

	/**
	 * Returns the inspectorcode of this vrrp dossier statistics.
	 *
	 * @return the inspectorcode of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getInspectorcode();

	/**
	 * Sets the inspectorcode of this vrrp dossier statistics.
	 *
	 * @param inspectorcode the inspectorcode of this vrrp dossier statistics
	 */
	public void setInspectorcode(String inspectorcode);

	/**
	 * Returns the inspectorname of this vrrp dossier statistics.
	 *
	 * @return the inspectorname of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getInspectorname();

	/**
	 * Sets the inspectorname of this vrrp dossier statistics.
	 *
	 * @param inspectorname the inspectorname of this vrrp dossier statistics
	 */
	public void setInspectorname(String inspectorname);

	/**
	 * Returns the leadername of this vrrp dossier statistics.
	 *
	 * @return the leadername of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getLeadername();

	/**
	 * Sets the leadername of this vrrp dossier statistics.
	 *
	 * @param leadername the leadername of this vrrp dossier statistics
	 */
	public void setLeadername(String leadername);

	/**
	 * Returns the men2receiving of this vrrp dossier statistics.
	 *
	 * @return the men2receiving of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2receiving();

	/**
	 * Sets the men2receiving of this vrrp dossier statistics.
	 *
	 * @param men2receiving the men2receiving of this vrrp dossier statistics
	 */
	public void setMen2receiving(String men2receiving);

	/**
	 * Returns the men2firstupdating of this vrrp dossier statistics.
	 *
	 * @return the men2firstupdating of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2firstupdating();

	/**
	 * Sets the men2firstupdating of this vrrp dossier statistics.
	 *
	 * @param men2firstupdating the men2firstupdating of this vrrp dossier statistics
	 */
	public void setMen2firstupdating(String men2firstupdating);

	/**
	 * Returns the men2lastupdating of this vrrp dossier statistics.
	 *
	 * @return the men2lastupdating of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2lastupdating();

	/**
	 * Sets the men2lastupdating of this vrrp dossier statistics.
	 *
	 * @param men2lastupdating the men2lastupdating of this vrrp dossier statistics
	 */
	public void setMen2lastupdating(String men2lastupdating);

	/**
	 * Returns the men2endorsement of this vrrp dossier statistics.
	 *
	 * @return the men2endorsement of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2endorsement();

	/**
	 * Sets the men2endorsement of this vrrp dossier statistics.
	 *
	 * @param men2endorsement the men2endorsement of this vrrp dossier statistics
	 */
	public void setMen2endorsement(String men2endorsement);

	/**
	 * Returns the men2submitting of this vrrp dossier statistics.
	 *
	 * @return the men2submitting of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2submitting();

	/**
	 * Sets the men2submitting of this vrrp dossier statistics.
	 *
	 * @param men2submitting the men2submitting of this vrrp dossier statistics
	 */
	public void setMen2submitting(String men2submitting);

	/**
	 * Returns the men2firstcertificate of this vrrp dossier statistics.
	 *
	 * @return the men2firstcertificate of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2firstcertificate();

	/**
	 * Sets the men2firstcertificate of this vrrp dossier statistics.
	 *
	 * @param men2firstcertificate the men2firstcertificate of this vrrp dossier statistics
	 */
	public void setMen2firstcertificate(String men2firstcertificate);

	/**
	 * Returns the men2firstassignment of this vrrp dossier statistics.
	 *
	 * @return the men2firstassignment of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2firstassignment();

	/**
	 * Sets the men2firstassignment of this vrrp dossier statistics.
	 *
	 * @param men2firstassignment the men2firstassignment of this vrrp dossier statistics
	 */
	public void setMen2firstassignment(String men2firstassignment);

	/**
	 * Returns the men2firstreview of this vrrp dossier statistics.
	 *
	 * @return the men2firstreview of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2firstreview();

	/**
	 * Sets the men2firstreview of this vrrp dossier statistics.
	 *
	 * @param men2firstreview the men2firstreview of this vrrp dossier statistics
	 */
	public void setMen2firstreview(String men2firstreview);

	/**
	 * Returns the men2nexttreview of this vrrp dossier statistics.
	 *
	 * @return the men2nexttreview of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2nexttreview();

	/**
	 * Sets the men2nexttreview of this vrrp dossier statistics.
	 *
	 * @param men2nexttreview the men2nexttreview of this vrrp dossier statistics
	 */
	public void setMen2nexttreview(String men2nexttreview);

	/**
	 * Returns the men2lastassignment of this vrrp dossier statistics.
	 *
	 * @return the men2lastassignment of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2lastassignment();

	/**
	 * Sets the men2lastassignment of this vrrp dossier statistics.
	 *
	 * @param men2lastassignment the men2lastassignment of this vrrp dossier statistics
	 */
	public void setMen2lastassignment(String men2lastassignment);

	/**
	 * Returns the men2reviewadjust of this vrrp dossier statistics.
	 *
	 * @return the men2reviewadjust of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2reviewadjust();

	/**
	 * Sets the men2reviewadjust of this vrrp dossier statistics.
	 *
	 * @param men2reviewadjust the men2reviewadjust of this vrrp dossier statistics
	 */
	public void setMen2reviewadjust(String men2reviewadjust);

	/**
	 * Returns the men2lastreviewadjust of this vrrp dossier statistics.
	 *
	 * @return the men2lastreviewadjust of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2lastreviewadjust();

	/**
	 * Sets the men2lastreviewadjust of this vrrp dossier statistics.
	 *
	 * @param men2lastreviewadjust the men2lastreviewadjust of this vrrp dossier statistics
	 */
	public void setMen2lastreviewadjust(String men2lastreviewadjust);

	/**
	 * Returns the men2lastcertificatesign of this vrrp dossier statistics.
	 *
	 * @return the men2lastcertificatesign of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2lastcertificatesign();

	/**
	 * Sets the men2lastcertificatesign of this vrrp dossier statistics.
	 *
	 * @param men2lastcertificatesign the men2lastcertificatesign of this vrrp dossier statistics
	 */
	public void setMen2lastcertificatesign(String men2lastcertificatesign);

	/**
	 * Returns the men2finished of this vrrp dossier statistics.
	 *
	 * @return the men2finished of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2finished();

	/**
	 * Sets the men2finished of this vrrp dossier statistics.
	 *
	 * @param men2finished the men2finished of this vrrp dossier statistics
	 */
	public void setMen2finished(String men2finished);

	/**
	 * Returns the men2cancelled of this vrrp dossier statistics.
	 *
	 * @return the men2cancelled of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2cancelled();

	/**
	 * Sets the men2cancelled of this vrrp dossier statistics.
	 *
	 * @param men2cancelled the men2cancelled of this vrrp dossier statistics
	 */
	public void setMen2cancelled(String men2cancelled);

	/**
	 * Returns the men2expired of this vrrp dossier statistics.
	 *
	 * @return the men2expired of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2expired();

	/**
	 * Sets the men2expired of this vrrp dossier statistics.
	 *
	 * @param men2expired the men2expired of this vrrp dossier statistics
	 */
	public void setMen2expired(String men2expired);

	/**
	 * Returns the men2violated of this vrrp dossier statistics.
	 *
	 * @return the men2violated of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2violated();

	/**
	 * Sets the men2violated of this vrrp dossier statistics.
	 *
	 * @param men2violated the men2violated of this vrrp dossier statistics
	 */
	public void setMen2violated(String men2violated);

	/**
	 * Returns the dossier payment date of this vrrp dossier statistics.
	 *
	 * @return the dossier payment date of this vrrp dossier statistics
	 */
	public Date getDossierPaymentDate();

	/**
	 * Sets the dossier payment date of this vrrp dossier statistics.
	 *
	 * @param dossierPaymentDate the dossier payment date of this vrrp dossier statistics
	 */
	public void setDossierPaymentDate(Date dossierPaymentDate);

	/**
	 * Returns the men2 payment approval of this vrrp dossier statistics.
	 *
	 * @return the men2 payment approval of this vrrp dossier statistics
	 */
	@AutoEscape
	public String getMen2PaymentApproval();

	/**
	 * Sets the men2 payment approval of this vrrp dossier statistics.
	 *
	 * @param men2PaymentApproval the men2 payment approval of this vrrp dossier statistics
	 */
	public void setMen2PaymentApproval(String men2PaymentApproval);

	/**
	 * Returns the modify date of this vrrp dossier statistics.
	 *
	 * @return the modify date of this vrrp dossier statistics
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vrrp dossier statistics.
	 *
	 * @param modifyDate the modify date of this vrrp dossier statistics
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vrrp dossier statistics.
	 *
	 * @return the sync date of this vrrp dossier statistics
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vrrp dossier statistics.
	 *
	 * @param syncDate the sync date of this vrrp dossier statistics
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRRPDossierStatistics vrrpDossierStatistics);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRRPDossierStatistics> toCacheModel();

	@Override
	public VRRPDossierStatistics toEscapedModel();

	@Override
	public VRRPDossierStatistics toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}