/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_XCG service. Represents a row in the &quot;vr_technicalspec_xcg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCGModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCGImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XCG
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCGImpl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCGModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_XCGModel extends BaseModel<VRTechnicalSpec_XCG> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_xcg model instance should use the {@link VRTechnicalSpec_XCG} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_xcg.
	 *
	 * @return the primary key of this vr technical spec_xcg
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_xcg.
	 *
	 * @param primaryKey the primary key of this vr technical spec_xcg
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_xcg.
	 *
	 * @return the ID of this vr technical spec_xcg
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_xcg.
	 *
	 * @param id the ID of this vr technical spec_xcg
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_xcg.
	 *
	 * @return the mt core of this vr technical spec_xcg
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_xcg.
	 *
	 * @param mtCore the mt core of this vr technical spec_xcg
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_xcg.
	 *
	 * @return the convert assemble ID of this vr technical spec_xcg
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_xcg.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_xcg
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_xcg.
	 *
	 * @return the dossier ID of this vr technical spec_xcg
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_xcg.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_xcg
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_xcg.
	 *
	 * @return the dossier no of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_xcg.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_xcg
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_xcg.
	 *
	 * @return the reference uid of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_xcg.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_xcg
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_xcg.
	 *
	 * @return the dossier ID ctn of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_xcg.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_xcg
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_xcg.
	 *
	 * @return the deliverable code of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_xcg.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_xcg
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_xcg.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_xcg
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_xcg.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_xcg
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the xcg01070 of this vr technical spec_xcg.
	 *
	 * @return the xcg01070 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01070();

	/**
	 * Sets the xcg01070 of this vr technical spec_xcg.
	 *
	 * @param XCG01070 the xcg01070 of this vr technical spec_xcg
	 */
	public void setXCG01070(String XCG01070);

	/**
	 * Returns the xcg01072 of this vr technical spec_xcg.
	 *
	 * @return the xcg01072 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01072();

	/**
	 * Sets the xcg01072 of this vr technical spec_xcg.
	 *
	 * @param XCG01072 the xcg01072 of this vr technical spec_xcg
	 */
	public void setXCG01072(String XCG01072);

	/**
	 * Returns the xcg01083 of this vr technical spec_xcg.
	 *
	 * @return the xcg01083 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01083();

	/**
	 * Sets the xcg01083 of this vr technical spec_xcg.
	 *
	 * @param XCG01083 the xcg01083 of this vr technical spec_xcg
	 */
	public void setXCG01083(String XCG01083);

	/**
	 * Returns the xcg01084 of this vr technical spec_xcg.
	 *
	 * @return the xcg01084 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01084();

	/**
	 * Sets the xcg01084 of this vr technical spec_xcg.
	 *
	 * @param XCG01084 the xcg01084 of this vr technical spec_xcg
	 */
	public void setXCG01084(String XCG01084);

	/**
	 * Returns the xcg01085 of this vr technical spec_xcg.
	 *
	 * @return the xcg01085 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01085();

	/**
	 * Sets the xcg01085 of this vr technical spec_xcg.
	 *
	 * @param XCG01085 the xcg01085 of this vr technical spec_xcg
	 */
	public void setXCG01085(String XCG01085);

	/**
	 * Returns the xcg01086 of this vr technical spec_xcg.
	 *
	 * @return the xcg01086 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01086();

	/**
	 * Sets the xcg01086 of this vr technical spec_xcg.
	 *
	 * @param XCG01086 the xcg01086 of this vr technical spec_xcg
	 */
	public void setXCG01086(String XCG01086);

	/**
	 * Returns the xcg01087 of this vr technical spec_xcg.
	 *
	 * @return the xcg01087 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01087();

	/**
	 * Sets the xcg01087 of this vr technical spec_xcg.
	 *
	 * @param XCG01087 the xcg01087 of this vr technical spec_xcg
	 */
	public void setXCG01087(String XCG01087);

	/**
	 * Returns the xcg01088 of this vr technical spec_xcg.
	 *
	 * @return the xcg01088 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01088();

	/**
	 * Sets the xcg01088 of this vr technical spec_xcg.
	 *
	 * @param XCG01088 the xcg01088 of this vr technical spec_xcg
	 */
	public void setXCG01088(String XCG01088);

	/**
	 * Returns the xcg01090 of this vr technical spec_xcg.
	 *
	 * @return the xcg01090 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01090();

	/**
	 * Sets the xcg01090 of this vr technical spec_xcg.
	 *
	 * @param XCG01090 the xcg01090 of this vr technical spec_xcg
	 */
	public void setXCG01090(String XCG01090);

	/**
	 * Returns the xcg01091 of this vr technical spec_xcg.
	 *
	 * @return the xcg01091 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01091();

	/**
	 * Sets the xcg01091 of this vr technical spec_xcg.
	 *
	 * @param XCG01091 the xcg01091 of this vr technical spec_xcg
	 */
	public void setXCG01091(String XCG01091);

	/**
	 * Returns the xcg01092 of this vr technical spec_xcg.
	 *
	 * @return the xcg01092 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01092();

	/**
	 * Sets the xcg01092 of this vr technical spec_xcg.
	 *
	 * @param XCG01092 the xcg01092 of this vr technical spec_xcg
	 */
	public void setXCG01092(String XCG01092);

	/**
	 * Returns the xcg01123 of this vr technical spec_xcg.
	 *
	 * @return the xcg01123 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01123();

	/**
	 * Sets the xcg01123 of this vr technical spec_xcg.
	 *
	 * @param XCG01123 the xcg01123 of this vr technical spec_xcg
	 */
	public void setXCG01123(String XCG01123);

	/**
	 * Returns the xcg01124 of this vr technical spec_xcg.
	 *
	 * @return the xcg01124 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01124();

	/**
	 * Sets the xcg01124 of this vr technical spec_xcg.
	 *
	 * @param XCG01124 the xcg01124 of this vr technical spec_xcg
	 */
	public void setXCG01124(String XCG01124);

	/**
	 * Returns the xcg01125 of this vr technical spec_xcg.
	 *
	 * @return the xcg01125 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01125();

	/**
	 * Sets the xcg01125 of this vr technical spec_xcg.
	 *
	 * @param XCG01125 the xcg01125 of this vr technical spec_xcg
	 */
	public void setXCG01125(String XCG01125);

	/**
	 * Returns the xcg01156 of this vr technical spec_xcg.
	 *
	 * @return the xcg01156 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01156();

	/**
	 * Sets the xcg01156 of this vr technical spec_xcg.
	 *
	 * @param XCG01156 the xcg01156 of this vr technical spec_xcg
	 */
	public void setXCG01156(String XCG01156);

	/**
	 * Returns the xcg01157 of this vr technical spec_xcg.
	 *
	 * @return the xcg01157 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01157();

	/**
	 * Sets the xcg01157 of this vr technical spec_xcg.
	 *
	 * @param XCG01157 the xcg01157 of this vr technical spec_xcg
	 */
	public void setXCG01157(String XCG01157);

	/**
	 * Returns the xcg01163 of this vr technical spec_xcg.
	 *
	 * @return the xcg01163 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01163();

	/**
	 * Sets the xcg01163 of this vr technical spec_xcg.
	 *
	 * @param XCG01163 the xcg01163 of this vr technical spec_xcg
	 */
	public void setXCG01163(String XCG01163);

	/**
	 * Returns the xcg01169 of this vr technical spec_xcg.
	 *
	 * @return the xcg01169 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01169();

	/**
	 * Sets the xcg01169 of this vr technical spec_xcg.
	 *
	 * @param XCG01169 the xcg01169 of this vr technical spec_xcg
	 */
	public void setXCG01169(String XCG01169);

	/**
	 * Returns the xcg01170 of this vr technical spec_xcg.
	 *
	 * @return the xcg01170 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01170();

	/**
	 * Sets the xcg01170 of this vr technical spec_xcg.
	 *
	 * @param XCG01170 the xcg01170 of this vr technical spec_xcg
	 */
	public void setXCG01170(String XCG01170);

	/**
	 * Returns the xcg01171 of this vr technical spec_xcg.
	 *
	 * @return the xcg01171 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01171();

	/**
	 * Sets the xcg01171 of this vr technical spec_xcg.
	 *
	 * @param XCG01171 the xcg01171 of this vr technical spec_xcg
	 */
	public void setXCG01171(String XCG01171);

	/**
	 * Returns the xcg01172 of this vr technical spec_xcg.
	 *
	 * @return the xcg01172 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01172();

	/**
	 * Sets the xcg01172 of this vr technical spec_xcg.
	 *
	 * @param XCG01172 the xcg01172 of this vr technical spec_xcg
	 */
	public void setXCG01172(String XCG01172);

	/**
	 * Returns the xcg01173 of this vr technical spec_xcg.
	 *
	 * @return the xcg01173 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01173();

	/**
	 * Sets the xcg01173 of this vr technical spec_xcg.
	 *
	 * @param XCG01173 the xcg01173 of this vr technical spec_xcg
	 */
	public void setXCG01173(String XCG01173);

	/**
	 * Returns the xcg01182 of this vr technical spec_xcg.
	 *
	 * @return the xcg01182 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01182();

	/**
	 * Sets the xcg01182 of this vr technical spec_xcg.
	 *
	 * @param XCG01182 the xcg01182 of this vr technical spec_xcg
	 */
	public void setXCG01182(String XCG01182);

	/**
	 * Returns the xcg01183 of this vr technical spec_xcg.
	 *
	 * @return the xcg01183 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01183();

	/**
	 * Sets the xcg01183 of this vr technical spec_xcg.
	 *
	 * @param XCG01183 the xcg01183 of this vr technical spec_xcg
	 */
	public void setXCG01183(String XCG01183);

	/**
	 * Returns the xcg01192 of this vr technical spec_xcg.
	 *
	 * @return the xcg01192 of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getXCG01192();

	/**
	 * Sets the xcg01192 of this vr technical spec_xcg.
	 *
	 * @param XCG01192 the xcg01192 of this vr technical spec_xcg
	 */
	public void setXCG01192(String XCG01192);

	/**
	 * Returns the loai_dong_co of this vr technical spec_xcg.
	 *
	 * @return the loai_dong_co of this vr technical spec_xcg
	 */
	@AutoEscape
	public String getLoai_dong_co();

	/**
	 * Sets the loai_dong_co of this vr technical spec_xcg.
	 *
	 * @param loai_dong_co the loai_dong_co of this vr technical spec_xcg
	 */
	public void setLoai_dong_co(String loai_dong_co);

	/**
	 * Returns the modify date of this vr technical spec_xcg.
	 *
	 * @return the modify date of this vr technical spec_xcg
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_xcg.
	 *
	 * @param modifyDate the modify date of this vr technical spec_xcg
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_xcg.
	 *
	 * @return the sync date of this vr technical spec_xcg
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_xcg.
	 *
	 * @param syncDate the sync date of this vr technical spec_xcg
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_XCG vrTechnicalSpec_XCG);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_XCG> toCacheModel();

	@Override
	public VRTechnicalSpec_XCG toEscapedModel();

	@Override
	public VRTechnicalSpec_XCG toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}