/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_XCGPart1 service. Represents a row in the &quot;vr_technicalspec_xcg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart1ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart1Impl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XCGPart1
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart1Impl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart1ModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_XCGPart1Model extends BaseModel<VRTechnicalSpec_XCGPart1> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_xcg part1 model instance should use the {@link VRTechnicalSpec_XCGPart1} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_xcg part1.
	 *
	 * @return the primary key of this vr technical spec_xcg part1
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_xcg part1.
	 *
	 * @param primaryKey the primary key of this vr technical spec_xcg part1
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_xcg part1.
	 *
	 * @return the ID of this vr technical spec_xcg part1
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_xcg part1.
	 *
	 * @param id the ID of this vr technical spec_xcg part1
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_xcg part1.
	 *
	 * @return the mt core of this vr technical spec_xcg part1
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_xcg part1.
	 *
	 * @param mtCore the mt core of this vr technical spec_xcg part1
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_xcg part1.
	 *
	 * @return the convert assemble ID of this vr technical spec_xcg part1
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_xcg part1.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_xcg part1
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_xcg part1.
	 *
	 * @return the dossier ID of this vr technical spec_xcg part1
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_xcg part1.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_xcg part1
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_xcg part1.
	 *
	 * @return the dossier no of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_xcg part1.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_xcg part1
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_xcg part1.
	 *
	 * @return the reference uid of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_xcg part1.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_xcg part1
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_xcg part1.
	 *
	 * @return the dossier ID ctn of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_xcg part1.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_xcg part1
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_xcg part1.
	 *
	 * @return the deliverable code of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_xcg part1.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_xcg part1
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_xcg part1.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_xcg part1
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_xcg part1.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_xcg part1
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the loai_dong_co of this vr technical spec_xcg part1.
	 *
	 * @return the loai_dong_co of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getLoai_dong_co();

	/**
	 * Sets the loai_dong_co of this vr technical spec_xcg part1.
	 *
	 * @param loai_dong_co the loai_dong_co of this vr technical spec_xcg part1
	 */
	public void setLoai_dong_co(String loai_dong_co);

	/**
	 * Returns the xcg01001 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01001 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01001();

	/**
	 * Sets the xcg01001 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01001 the xcg01001 of this vr technical spec_xcg part1
	 */
	public void setXCG01001(String XCG01001);

	/**
	 * Returns the xcg01002 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01002 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01002();

	/**
	 * Sets the xcg01002 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01002 the xcg01002 of this vr technical spec_xcg part1
	 */
	public void setXCG01002(String XCG01002);

	/**
	 * Returns the xcg01003 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01003 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01003();

	/**
	 * Sets the xcg01003 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01003 the xcg01003 of this vr technical spec_xcg part1
	 */
	public void setXCG01003(String XCG01003);

	/**
	 * Returns the xcg01004 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01004 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01004();

	/**
	 * Sets the xcg01004 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01004 the xcg01004 of this vr technical spec_xcg part1
	 */
	public void setXCG01004(String XCG01004);

	/**
	 * Returns the xcg01005 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01005 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01005();

	/**
	 * Sets the xcg01005 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01005 the xcg01005 of this vr technical spec_xcg part1
	 */
	public void setXCG01005(String XCG01005);

	/**
	 * Returns the xcg01006 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01006 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01006();

	/**
	 * Sets the xcg01006 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01006 the xcg01006 of this vr technical spec_xcg part1
	 */
	public void setXCG01006(String XCG01006);

	/**
	 * Returns the xcg01007 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01007 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01007();

	/**
	 * Sets the xcg01007 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01007 the xcg01007 of this vr technical spec_xcg part1
	 */
	public void setXCG01007(String XCG01007);

	/**
	 * Returns the xcg01008 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01008 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01008();

	/**
	 * Sets the xcg01008 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01008 the xcg01008 of this vr technical spec_xcg part1
	 */
	public void setXCG01008(String XCG01008);

	/**
	 * Returns the xcg01009 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01009 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01009();

	/**
	 * Sets the xcg01009 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01009 the xcg01009 of this vr technical spec_xcg part1
	 */
	public void setXCG01009(String XCG01009);

	/**
	 * Returns the xcg01010 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01010 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01010();

	/**
	 * Sets the xcg01010 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01010 the xcg01010 of this vr technical spec_xcg part1
	 */
	public void setXCG01010(String XCG01010);

	/**
	 * Returns the xcg01011 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01011 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01011();

	/**
	 * Sets the xcg01011 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01011 the xcg01011 of this vr technical spec_xcg part1
	 */
	public void setXCG01011(String XCG01011);

	/**
	 * Returns the xcg01012 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01012 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01012();

	/**
	 * Sets the xcg01012 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01012 the xcg01012 of this vr technical spec_xcg part1
	 */
	public void setXCG01012(String XCG01012);

	/**
	 * Returns the xcg01013 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01013 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01013();

	/**
	 * Sets the xcg01013 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01013 the xcg01013 of this vr technical spec_xcg part1
	 */
	public void setXCG01013(String XCG01013);

	/**
	 * Returns the xcg01014 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01014 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01014();

	/**
	 * Sets the xcg01014 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01014 the xcg01014 of this vr technical spec_xcg part1
	 */
	public void setXCG01014(String XCG01014);

	/**
	 * Returns the xcg01016 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01016 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01016();

	/**
	 * Sets the xcg01016 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01016 the xcg01016 of this vr technical spec_xcg part1
	 */
	public void setXCG01016(String XCG01016);

	/**
	 * Returns the xcg01017 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01017 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01017();

	/**
	 * Sets the xcg01017 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01017 the xcg01017 of this vr technical spec_xcg part1
	 */
	public void setXCG01017(String XCG01017);

	/**
	 * Returns the xcg01019 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01019 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01019();

	/**
	 * Sets the xcg01019 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01019 the xcg01019 of this vr technical spec_xcg part1
	 */
	public void setXCG01019(String XCG01019);

	/**
	 * Returns the xcg01020 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01020 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01020();

	/**
	 * Sets the xcg01020 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01020 the xcg01020 of this vr technical spec_xcg part1
	 */
	public void setXCG01020(String XCG01020);

	/**
	 * Returns the xcg01021 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01021 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01021();

	/**
	 * Sets the xcg01021 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01021 the xcg01021 of this vr technical spec_xcg part1
	 */
	public void setXCG01021(String XCG01021);

	/**
	 * Returns the xcg01022 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01022 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01022();

	/**
	 * Sets the xcg01022 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01022 the xcg01022 of this vr technical spec_xcg part1
	 */
	public void setXCG01022(String XCG01022);

	/**
	 * Returns the xcg01024 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01024 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01024();

	/**
	 * Sets the xcg01024 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01024 the xcg01024 of this vr technical spec_xcg part1
	 */
	public void setXCG01024(String XCG01024);

	/**
	 * Returns the xcg01025 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01025 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01025();

	/**
	 * Sets the xcg01025 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01025 the xcg01025 of this vr technical spec_xcg part1
	 */
	public void setXCG01025(String XCG01025);

	/**
	 * Returns the xcg01026 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01026 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01026();

	/**
	 * Sets the xcg01026 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01026 the xcg01026 of this vr technical spec_xcg part1
	 */
	public void setXCG01026(String XCG01026);

	/**
	 * Returns the xcg01027 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01027 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01027();

	/**
	 * Sets the xcg01027 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01027 the xcg01027 of this vr technical spec_xcg part1
	 */
	public void setXCG01027(String XCG01027);

	/**
	 * Returns the xcg01028 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01028 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01028();

	/**
	 * Sets the xcg01028 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01028 the xcg01028 of this vr technical spec_xcg part1
	 */
	public void setXCG01028(String XCG01028);

	/**
	 * Returns the xcg01030 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01030 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01030();

	/**
	 * Sets the xcg01030 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01030 the xcg01030 of this vr technical spec_xcg part1
	 */
	public void setXCG01030(String XCG01030);

	/**
	 * Returns the xcg01031 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01031 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01031();

	/**
	 * Sets the xcg01031 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01031 the xcg01031 of this vr technical spec_xcg part1
	 */
	public void setXCG01031(String XCG01031);

	/**
	 * Returns the xcg01032 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01032 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01032();

	/**
	 * Sets the xcg01032 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01032 the xcg01032 of this vr technical spec_xcg part1
	 */
	public void setXCG01032(String XCG01032);

	/**
	 * Returns the xcg01033 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01033 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01033();

	/**
	 * Sets the xcg01033 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01033 the xcg01033 of this vr technical spec_xcg part1
	 */
	public void setXCG01033(String XCG01033);

	/**
	 * Returns the xcg01034 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01034 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01034();

	/**
	 * Sets the xcg01034 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01034 the xcg01034 of this vr technical spec_xcg part1
	 */
	public void setXCG01034(String XCG01034);

	/**
	 * Returns the xcg01035 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01035 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01035();

	/**
	 * Sets the xcg01035 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01035 the xcg01035 of this vr technical spec_xcg part1
	 */
	public void setXCG01035(String XCG01035);

	/**
	 * Returns the xcg01036 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01036 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01036();

	/**
	 * Sets the xcg01036 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01036 the xcg01036 of this vr technical spec_xcg part1
	 */
	public void setXCG01036(String XCG01036);

	/**
	 * Returns the xcg01037 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01037 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01037();

	/**
	 * Sets the xcg01037 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01037 the xcg01037 of this vr technical spec_xcg part1
	 */
	public void setXCG01037(String XCG01037);

	/**
	 * Returns the xcg01038 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01038 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01038();

	/**
	 * Sets the xcg01038 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01038 the xcg01038 of this vr technical spec_xcg part1
	 */
	public void setXCG01038(String XCG01038);

	/**
	 * Returns the xcg01039 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01039 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01039();

	/**
	 * Sets the xcg01039 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01039 the xcg01039 of this vr technical spec_xcg part1
	 */
	public void setXCG01039(String XCG01039);

	/**
	 * Returns the xcg01040 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01040 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01040();

	/**
	 * Sets the xcg01040 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01040 the xcg01040 of this vr technical spec_xcg part1
	 */
	public void setXCG01040(String XCG01040);

	/**
	 * Returns the xcg01041 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01041 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01041();

	/**
	 * Sets the xcg01041 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01041 the xcg01041 of this vr technical spec_xcg part1
	 */
	public void setXCG01041(String XCG01041);

	/**
	 * Returns the xcg01042 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01042 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01042();

	/**
	 * Sets the xcg01042 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01042 the xcg01042 of this vr technical spec_xcg part1
	 */
	public void setXCG01042(String XCG01042);

	/**
	 * Returns the xcg01043 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01043 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01043();

	/**
	 * Sets the xcg01043 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01043 the xcg01043 of this vr technical spec_xcg part1
	 */
	public void setXCG01043(String XCG01043);

	/**
	 * Returns the xcg01044 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01044 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01044();

	/**
	 * Sets the xcg01044 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01044 the xcg01044 of this vr technical spec_xcg part1
	 */
	public void setXCG01044(String XCG01044);

	/**
	 * Returns the xcg01045 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01045 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01045();

	/**
	 * Sets the xcg01045 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01045 the xcg01045 of this vr technical spec_xcg part1
	 */
	public void setXCG01045(String XCG01045);

	/**
	 * Returns the xcg01046 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01046 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01046();

	/**
	 * Sets the xcg01046 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01046 the xcg01046 of this vr technical spec_xcg part1
	 */
	public void setXCG01046(String XCG01046);

	/**
	 * Returns the xcg01047 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01047 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01047();

	/**
	 * Sets the xcg01047 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01047 the xcg01047 of this vr technical spec_xcg part1
	 */
	public void setXCG01047(String XCG01047);

	/**
	 * Returns the xcg01049 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01049 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01049();

	/**
	 * Sets the xcg01049 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01049 the xcg01049 of this vr technical spec_xcg part1
	 */
	public void setXCG01049(String XCG01049);

	/**
	 * Returns the xcg01050 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01050 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01050();

	/**
	 * Sets the xcg01050 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01050 the xcg01050 of this vr technical spec_xcg part1
	 */
	public void setXCG01050(String XCG01050);

	/**
	 * Returns the xcg01051 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01051 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01051();

	/**
	 * Sets the xcg01051 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01051 the xcg01051 of this vr technical spec_xcg part1
	 */
	public void setXCG01051(String XCG01051);

	/**
	 * Returns the xcg01052 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01052 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01052();

	/**
	 * Sets the xcg01052 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01052 the xcg01052 of this vr technical spec_xcg part1
	 */
	public void setXCG01052(String XCG01052);

	/**
	 * Returns the xcg01053 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01053 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01053();

	/**
	 * Sets the xcg01053 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01053 the xcg01053 of this vr technical spec_xcg part1
	 */
	public void setXCG01053(String XCG01053);

	/**
	 * Returns the xcg01054 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01054 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01054();

	/**
	 * Sets the xcg01054 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01054 the xcg01054 of this vr technical spec_xcg part1
	 */
	public void setXCG01054(String XCG01054);

	/**
	 * Returns the xcg01055 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01055 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01055();

	/**
	 * Sets the xcg01055 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01055 the xcg01055 of this vr technical spec_xcg part1
	 */
	public void setXCG01055(String XCG01055);

	/**
	 * Returns the xcg01056 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01056 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01056();

	/**
	 * Sets the xcg01056 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01056 the xcg01056 of this vr technical spec_xcg part1
	 */
	public void setXCG01056(String XCG01056);

	/**
	 * Returns the xcg01057 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01057 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01057();

	/**
	 * Sets the xcg01057 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01057 the xcg01057 of this vr technical spec_xcg part1
	 */
	public void setXCG01057(String XCG01057);

	/**
	 * Returns the xcg01058 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01058 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01058();

	/**
	 * Sets the xcg01058 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01058 the xcg01058 of this vr technical spec_xcg part1
	 */
	public void setXCG01058(String XCG01058);

	/**
	 * Returns the xcg01059 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01059 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01059();

	/**
	 * Sets the xcg01059 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01059 the xcg01059 of this vr technical spec_xcg part1
	 */
	public void setXCG01059(String XCG01059);

	/**
	 * Returns the xcg01060 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01060 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01060();

	/**
	 * Sets the xcg01060 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01060 the xcg01060 of this vr technical spec_xcg part1
	 */
	public void setXCG01060(String XCG01060);

	/**
	 * Returns the xcg01062 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01062 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01062();

	/**
	 * Sets the xcg01062 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01062 the xcg01062 of this vr technical spec_xcg part1
	 */
	public void setXCG01062(String XCG01062);

	/**
	 * Returns the xcg01063 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01063 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01063();

	/**
	 * Sets the xcg01063 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01063 the xcg01063 of this vr technical spec_xcg part1
	 */
	public void setXCG01063(String XCG01063);

	/**
	 * Returns the xcg01064 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01064 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01064();

	/**
	 * Sets the xcg01064 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01064 the xcg01064 of this vr technical spec_xcg part1
	 */
	public void setXCG01064(String XCG01064);

	/**
	 * Returns the xcg01065 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01065 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01065();

	/**
	 * Sets the xcg01065 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01065 the xcg01065 of this vr technical spec_xcg part1
	 */
	public void setXCG01065(String XCG01065);

	/**
	 * Returns the xcg01066 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01066 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01066();

	/**
	 * Sets the xcg01066 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01066 the xcg01066 of this vr technical spec_xcg part1
	 */
	public void setXCG01066(String XCG01066);

	/**
	 * Returns the xcg01067 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01067 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01067();

	/**
	 * Sets the xcg01067 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01067 the xcg01067 of this vr technical spec_xcg part1
	 */
	public void setXCG01067(String XCG01067);

	/**
	 * Returns the xcg01068 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01068 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01068();

	/**
	 * Sets the xcg01068 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01068 the xcg01068 of this vr technical spec_xcg part1
	 */
	public void setXCG01068(String XCG01068);

	/**
	 * Returns the xcg01069 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01069 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01069();

	/**
	 * Sets the xcg01069 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01069 the xcg01069 of this vr technical spec_xcg part1
	 */
	public void setXCG01069(String XCG01069);

	/**
	 * Returns the xcg01070 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01070 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01070();

	/**
	 * Sets the xcg01070 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01070 the xcg01070 of this vr technical spec_xcg part1
	 */
	public void setXCG01070(String XCG01070);

	/**
	 * Returns the xcg01072 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01072 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01072();

	/**
	 * Sets the xcg01072 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01072 the xcg01072 of this vr technical spec_xcg part1
	 */
	public void setXCG01072(String XCG01072);

	/**
	 * Returns the xcg01073 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01073 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01073();

	/**
	 * Sets the xcg01073 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01073 the xcg01073 of this vr technical spec_xcg part1
	 */
	public void setXCG01073(String XCG01073);

	/**
	 * Returns the xcg01074 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01074 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01074();

	/**
	 * Sets the xcg01074 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01074 the xcg01074 of this vr technical spec_xcg part1
	 */
	public void setXCG01074(String XCG01074);

	/**
	 * Returns the xcg01075 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01075 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01075();

	/**
	 * Sets the xcg01075 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01075 the xcg01075 of this vr technical spec_xcg part1
	 */
	public void setXCG01075(String XCG01075);

	/**
	 * Returns the xcg01076 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01076 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01076();

	/**
	 * Sets the xcg01076 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01076 the xcg01076 of this vr technical spec_xcg part1
	 */
	public void setXCG01076(String XCG01076);

	/**
	 * Returns the xcg01077 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01077 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01077();

	/**
	 * Sets the xcg01077 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01077 the xcg01077 of this vr technical spec_xcg part1
	 */
	public void setXCG01077(String XCG01077);

	/**
	 * Returns the xcg01078 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01078 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01078();

	/**
	 * Sets the xcg01078 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01078 the xcg01078 of this vr technical spec_xcg part1
	 */
	public void setXCG01078(String XCG01078);

	/**
	 * Returns the xcg01079 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01079 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01079();

	/**
	 * Sets the xcg01079 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01079 the xcg01079 of this vr technical spec_xcg part1
	 */
	public void setXCG01079(String XCG01079);

	/**
	 * Returns the xcg01080 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01080 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01080();

	/**
	 * Sets the xcg01080 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01080 the xcg01080 of this vr technical spec_xcg part1
	 */
	public void setXCG01080(String XCG01080);

	/**
	 * Returns the xcg01081 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01081 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01081();

	/**
	 * Sets the xcg01081 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01081 the xcg01081 of this vr technical spec_xcg part1
	 */
	public void setXCG01081(String XCG01081);

	/**
	 * Returns the xcg01082 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01082 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01082();

	/**
	 * Sets the xcg01082 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01082 the xcg01082 of this vr technical spec_xcg part1
	 */
	public void setXCG01082(String XCG01082);

	/**
	 * Returns the xcg01083 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01083 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01083();

	/**
	 * Sets the xcg01083 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01083 the xcg01083 of this vr technical spec_xcg part1
	 */
	public void setXCG01083(String XCG01083);

	/**
	 * Returns the xcg01084 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01084 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01084();

	/**
	 * Sets the xcg01084 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01084 the xcg01084 of this vr technical spec_xcg part1
	 */
	public void setXCG01084(String XCG01084);

	/**
	 * Returns the xcg01085 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01085 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01085();

	/**
	 * Sets the xcg01085 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01085 the xcg01085 of this vr technical spec_xcg part1
	 */
	public void setXCG01085(String XCG01085);

	/**
	 * Returns the xcg01086 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01086 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01086();

	/**
	 * Sets the xcg01086 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01086 the xcg01086 of this vr technical spec_xcg part1
	 */
	public void setXCG01086(String XCG01086);

	/**
	 * Returns the xcg01087 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01087 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01087();

	/**
	 * Sets the xcg01087 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01087 the xcg01087 of this vr technical spec_xcg part1
	 */
	public void setXCG01087(String XCG01087);

	/**
	 * Returns the xcg01088 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01088 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01088();

	/**
	 * Sets the xcg01088 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01088 the xcg01088 of this vr technical spec_xcg part1
	 */
	public void setXCG01088(String XCG01088);

	/**
	 * Returns the xcg01089 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01089 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01089();

	/**
	 * Sets the xcg01089 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01089 the xcg01089 of this vr technical spec_xcg part1
	 */
	public void setXCG01089(String XCG01089);

	/**
	 * Returns the xcg01090 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01090 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01090();

	/**
	 * Sets the xcg01090 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01090 the xcg01090 of this vr technical spec_xcg part1
	 */
	public void setXCG01090(String XCG01090);

	/**
	 * Returns the xcg01091 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01091 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01091();

	/**
	 * Sets the xcg01091 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01091 the xcg01091 of this vr technical spec_xcg part1
	 */
	public void setXCG01091(String XCG01091);

	/**
	 * Returns the xcg01092 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01092 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01092();

	/**
	 * Sets the xcg01092 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01092 the xcg01092 of this vr technical spec_xcg part1
	 */
	public void setXCG01092(String XCG01092);

	/**
	 * Returns the xcg01093 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01093 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01093();

	/**
	 * Sets the xcg01093 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01093 the xcg01093 of this vr technical spec_xcg part1
	 */
	public void setXCG01093(String XCG01093);

	/**
	 * Returns the xcg01094 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01094 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01094();

	/**
	 * Sets the xcg01094 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01094 the xcg01094 of this vr technical spec_xcg part1
	 */
	public void setXCG01094(String XCG01094);

	/**
	 * Returns the xcg01095 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01095 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01095();

	/**
	 * Sets the xcg01095 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01095 the xcg01095 of this vr technical spec_xcg part1
	 */
	public void setXCG01095(String XCG01095);

	/**
	 * Returns the xcg01096 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01096 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01096();

	/**
	 * Sets the xcg01096 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01096 the xcg01096 of this vr technical spec_xcg part1
	 */
	public void setXCG01096(String XCG01096);

	/**
	 * Returns the xcg01097 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01097 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01097();

	/**
	 * Sets the xcg01097 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01097 the xcg01097 of this vr technical spec_xcg part1
	 */
	public void setXCG01097(String XCG01097);

	/**
	 * Returns the xcg01098 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01098 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01098();

	/**
	 * Sets the xcg01098 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01098 the xcg01098 of this vr technical spec_xcg part1
	 */
	public void setXCG01098(String XCG01098);

	/**
	 * Returns the xcg01099 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01099 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01099();

	/**
	 * Sets the xcg01099 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01099 the xcg01099 of this vr technical spec_xcg part1
	 */
	public void setXCG01099(String XCG01099);

	/**
	 * Returns the xcg01100 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01100 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01100();

	/**
	 * Sets the xcg01100 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01100 the xcg01100 of this vr technical spec_xcg part1
	 */
	public void setXCG01100(String XCG01100);

	/**
	 * Returns the xcg01101 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01101 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01101();

	/**
	 * Sets the xcg01101 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01101 the xcg01101 of this vr technical spec_xcg part1
	 */
	public void setXCG01101(String XCG01101);

	/**
	 * Returns the xcg01102 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01102 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01102();

	/**
	 * Sets the xcg01102 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01102 the xcg01102 of this vr technical spec_xcg part1
	 */
	public void setXCG01102(String XCG01102);

	/**
	 * Returns the xcg01103 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01103 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01103();

	/**
	 * Sets the xcg01103 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01103 the xcg01103 of this vr technical spec_xcg part1
	 */
	public void setXCG01103(String XCG01103);

	/**
	 * Returns the xcg01104 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01104 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01104();

	/**
	 * Sets the xcg01104 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01104 the xcg01104 of this vr technical spec_xcg part1
	 */
	public void setXCG01104(String XCG01104);

	/**
	 * Returns the xcg01105 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01105 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01105();

	/**
	 * Sets the xcg01105 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01105 the xcg01105 of this vr technical spec_xcg part1
	 */
	public void setXCG01105(String XCG01105);

	/**
	 * Returns the xcg01106 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01106 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01106();

	/**
	 * Sets the xcg01106 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01106 the xcg01106 of this vr technical spec_xcg part1
	 */
	public void setXCG01106(String XCG01106);

	/**
	 * Returns the xcg01107 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01107 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01107();

	/**
	 * Sets the xcg01107 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01107 the xcg01107 of this vr technical spec_xcg part1
	 */
	public void setXCG01107(String XCG01107);

	/**
	 * Returns the xcg01108 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01108 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01108();

	/**
	 * Sets the xcg01108 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01108 the xcg01108 of this vr technical spec_xcg part1
	 */
	public void setXCG01108(String XCG01108);

	/**
	 * Returns the xcg01109 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01109 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01109();

	/**
	 * Sets the xcg01109 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01109 the xcg01109 of this vr technical spec_xcg part1
	 */
	public void setXCG01109(String XCG01109);

	/**
	 * Returns the xcg01110 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01110 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01110();

	/**
	 * Sets the xcg01110 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01110 the xcg01110 of this vr technical spec_xcg part1
	 */
	public void setXCG01110(String XCG01110);

	/**
	 * Returns the xcg01111 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01111 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01111();

	/**
	 * Sets the xcg01111 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01111 the xcg01111 of this vr technical spec_xcg part1
	 */
	public void setXCG01111(String XCG01111);

	/**
	 * Returns the xcg01112 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01112 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01112();

	/**
	 * Sets the xcg01112 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01112 the xcg01112 of this vr technical spec_xcg part1
	 */
	public void setXCG01112(String XCG01112);

	/**
	 * Returns the xcg01113 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01113 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01113();

	/**
	 * Sets the xcg01113 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01113 the xcg01113 of this vr technical spec_xcg part1
	 */
	public void setXCG01113(String XCG01113);

	/**
	 * Returns the xcg01114 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01114 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01114();

	/**
	 * Sets the xcg01114 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01114 the xcg01114 of this vr technical spec_xcg part1
	 */
	public void setXCG01114(String XCG01114);

	/**
	 * Returns the xcg01115 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01115 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01115();

	/**
	 * Sets the xcg01115 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01115 the xcg01115 of this vr technical spec_xcg part1
	 */
	public void setXCG01115(String XCG01115);

	/**
	 * Returns the xcg01116 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01116 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01116();

	/**
	 * Sets the xcg01116 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01116 the xcg01116 of this vr technical spec_xcg part1
	 */
	public void setXCG01116(String XCG01116);

	/**
	 * Returns the xcg01117 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01117 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01117();

	/**
	 * Sets the xcg01117 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01117 the xcg01117 of this vr technical spec_xcg part1
	 */
	public void setXCG01117(String XCG01117);

	/**
	 * Returns the xcg01118 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01118 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01118();

	/**
	 * Sets the xcg01118 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01118 the xcg01118 of this vr technical spec_xcg part1
	 */
	public void setXCG01118(String XCG01118);

	/**
	 * Returns the xcg01119 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01119 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01119();

	/**
	 * Sets the xcg01119 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01119 the xcg01119 of this vr technical spec_xcg part1
	 */
	public void setXCG01119(String XCG01119);

	/**
	 * Returns the xcg01120 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01120 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01120();

	/**
	 * Sets the xcg01120 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01120 the xcg01120 of this vr technical spec_xcg part1
	 */
	public void setXCG01120(String XCG01120);

	/**
	 * Returns the xcg01121 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01121 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01121();

	/**
	 * Sets the xcg01121 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01121 the xcg01121 of this vr technical spec_xcg part1
	 */
	public void setXCG01121(String XCG01121);

	/**
	 * Returns the xcg01122 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01122 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01122();

	/**
	 * Sets the xcg01122 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01122 the xcg01122 of this vr technical spec_xcg part1
	 */
	public void setXCG01122(String XCG01122);

	/**
	 * Returns the xcg01123 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01123 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01123();

	/**
	 * Sets the xcg01123 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01123 the xcg01123 of this vr technical spec_xcg part1
	 */
	public void setXCG01123(String XCG01123);

	/**
	 * Returns the xcg01124 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01124 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01124();

	/**
	 * Sets the xcg01124 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01124 the xcg01124 of this vr technical spec_xcg part1
	 */
	public void setXCG01124(String XCG01124);

	/**
	 * Returns the xcg01125 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01125 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01125();

	/**
	 * Sets the xcg01125 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01125 the xcg01125 of this vr technical spec_xcg part1
	 */
	public void setXCG01125(String XCG01125);

	/**
	 * Returns the xcg01126 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01126 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01126();

	/**
	 * Sets the xcg01126 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01126 the xcg01126 of this vr technical spec_xcg part1
	 */
	public void setXCG01126(String XCG01126);

	/**
	 * Returns the xcg01127 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01127 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01127();

	/**
	 * Sets the xcg01127 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01127 the xcg01127 of this vr technical spec_xcg part1
	 */
	public void setXCG01127(String XCG01127);

	/**
	 * Returns the xcg01128 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01128 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01128();

	/**
	 * Sets the xcg01128 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01128 the xcg01128 of this vr technical spec_xcg part1
	 */
	public void setXCG01128(String XCG01128);

	/**
	 * Returns the xcg01129 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01129 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01129();

	/**
	 * Sets the xcg01129 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01129 the xcg01129 of this vr technical spec_xcg part1
	 */
	public void setXCG01129(String XCG01129);

	/**
	 * Returns the xcg01130 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01130 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01130();

	/**
	 * Sets the xcg01130 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01130 the xcg01130 of this vr technical spec_xcg part1
	 */
	public void setXCG01130(String XCG01130);

	/**
	 * Returns the xcg01131 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01131 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01131();

	/**
	 * Sets the xcg01131 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01131 the xcg01131 of this vr technical spec_xcg part1
	 */
	public void setXCG01131(String XCG01131);

	/**
	 * Returns the xcg01132 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01132 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01132();

	/**
	 * Sets the xcg01132 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01132 the xcg01132 of this vr technical spec_xcg part1
	 */
	public void setXCG01132(String XCG01132);

	/**
	 * Returns the xcg01133 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01133 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01133();

	/**
	 * Sets the xcg01133 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01133 the xcg01133 of this vr technical spec_xcg part1
	 */
	public void setXCG01133(String XCG01133);

	/**
	 * Returns the xcg01134 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01134 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01134();

	/**
	 * Sets the xcg01134 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01134 the xcg01134 of this vr technical spec_xcg part1
	 */
	public void setXCG01134(String XCG01134);

	/**
	 * Returns the xcg01135 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01135 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01135();

	/**
	 * Sets the xcg01135 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01135 the xcg01135 of this vr technical spec_xcg part1
	 */
	public void setXCG01135(String XCG01135);

	/**
	 * Returns the xcg01136 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01136 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01136();

	/**
	 * Sets the xcg01136 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01136 the xcg01136 of this vr technical spec_xcg part1
	 */
	public void setXCG01136(String XCG01136);

	/**
	 * Returns the xcg01137 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01137 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01137();

	/**
	 * Sets the xcg01137 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01137 the xcg01137 of this vr technical spec_xcg part1
	 */
	public void setXCG01137(String XCG01137);

	/**
	 * Returns the xcg01138 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01138 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01138();

	/**
	 * Sets the xcg01138 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01138 the xcg01138 of this vr technical spec_xcg part1
	 */
	public void setXCG01138(String XCG01138);

	/**
	 * Returns the xcg01139 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01139 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01139();

	/**
	 * Sets the xcg01139 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01139 the xcg01139 of this vr technical spec_xcg part1
	 */
	public void setXCG01139(String XCG01139);

	/**
	 * Returns the xcg01140 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01140 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01140();

	/**
	 * Sets the xcg01140 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01140 the xcg01140 of this vr technical spec_xcg part1
	 */
	public void setXCG01140(String XCG01140);

	/**
	 * Returns the xcg01141 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01141 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01141();

	/**
	 * Sets the xcg01141 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01141 the xcg01141 of this vr technical spec_xcg part1
	 */
	public void setXCG01141(String XCG01141);

	/**
	 * Returns the xcg01142 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01142 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01142();

	/**
	 * Sets the xcg01142 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01142 the xcg01142 of this vr technical spec_xcg part1
	 */
	public void setXCG01142(String XCG01142);

	/**
	 * Returns the xcg01143 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01143 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01143();

	/**
	 * Sets the xcg01143 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01143 the xcg01143 of this vr technical spec_xcg part1
	 */
	public void setXCG01143(String XCG01143);

	/**
	 * Returns the xcg01144 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01144 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01144();

	/**
	 * Sets the xcg01144 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01144 the xcg01144 of this vr technical spec_xcg part1
	 */
	public void setXCG01144(String XCG01144);

	/**
	 * Returns the xcg01145 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01145 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01145();

	/**
	 * Sets the xcg01145 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01145 the xcg01145 of this vr technical spec_xcg part1
	 */
	public void setXCG01145(String XCG01145);

	/**
	 * Returns the xcg01146 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01146 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01146();

	/**
	 * Sets the xcg01146 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01146 the xcg01146 of this vr technical spec_xcg part1
	 */
	public void setXCG01146(String XCG01146);

	/**
	 * Returns the xcg01147 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01147 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01147();

	/**
	 * Sets the xcg01147 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01147 the xcg01147 of this vr technical spec_xcg part1
	 */
	public void setXCG01147(String XCG01147);

	/**
	 * Returns the xcg01148 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01148 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01148();

	/**
	 * Sets the xcg01148 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01148 the xcg01148 of this vr technical spec_xcg part1
	 */
	public void setXCG01148(String XCG01148);

	/**
	 * Returns the xcg01149 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01149 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01149();

	/**
	 * Sets the xcg01149 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01149 the xcg01149 of this vr technical spec_xcg part1
	 */
	public void setXCG01149(String XCG01149);

	/**
	 * Returns the xcg01150 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01150 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01150();

	/**
	 * Sets the xcg01150 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01150 the xcg01150 of this vr technical spec_xcg part1
	 */
	public void setXCG01150(String XCG01150);

	/**
	 * Returns the xcg01151 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01151 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01151();

	/**
	 * Sets the xcg01151 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01151 the xcg01151 of this vr technical spec_xcg part1
	 */
	public void setXCG01151(String XCG01151);

	/**
	 * Returns the xcg01152 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01152 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01152();

	/**
	 * Sets the xcg01152 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01152 the xcg01152 of this vr technical spec_xcg part1
	 */
	public void setXCG01152(String XCG01152);

	/**
	 * Returns the xcg01153 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01153 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01153();

	/**
	 * Sets the xcg01153 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01153 the xcg01153 of this vr technical spec_xcg part1
	 */
	public void setXCG01153(String XCG01153);

	/**
	 * Returns the xcg01154 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01154 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01154();

	/**
	 * Sets the xcg01154 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01154 the xcg01154 of this vr technical spec_xcg part1
	 */
	public void setXCG01154(String XCG01154);

	/**
	 * Returns the xcg01155 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01155 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01155();

	/**
	 * Sets the xcg01155 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01155 the xcg01155 of this vr technical spec_xcg part1
	 */
	public void setXCG01155(String XCG01155);

	/**
	 * Returns the xcg01156 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01156 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01156();

	/**
	 * Sets the xcg01156 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01156 the xcg01156 of this vr technical spec_xcg part1
	 */
	public void setXCG01156(String XCG01156);

	/**
	 * Returns the xcg01157 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01157 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01157();

	/**
	 * Sets the xcg01157 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01157 the xcg01157 of this vr technical spec_xcg part1
	 */
	public void setXCG01157(String XCG01157);

	/**
	 * Returns the xcg01158 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01158 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01158();

	/**
	 * Sets the xcg01158 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01158 the xcg01158 of this vr technical spec_xcg part1
	 */
	public void setXCG01158(String XCG01158);

	/**
	 * Returns the xcg01159 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01159 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01159();

	/**
	 * Sets the xcg01159 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01159 the xcg01159 of this vr technical spec_xcg part1
	 */
	public void setXCG01159(String XCG01159);

	/**
	 * Returns the xcg01160 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01160 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01160();

	/**
	 * Sets the xcg01160 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01160 the xcg01160 of this vr technical spec_xcg part1
	 */
	public void setXCG01160(String XCG01160);

	/**
	 * Returns the xcg01161 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01161 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01161();

	/**
	 * Sets the xcg01161 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01161 the xcg01161 of this vr technical spec_xcg part1
	 */
	public void setXCG01161(String XCG01161);

	/**
	 * Returns the xcg01162 of this vr technical spec_xcg part1.
	 *
	 * @return the xcg01162 of this vr technical spec_xcg part1
	 */
	@AutoEscape
	public String getXCG01162();

	/**
	 * Sets the xcg01162 of this vr technical spec_xcg part1.
	 *
	 * @param XCG01162 the xcg01162 of this vr technical spec_xcg part1
	 */
	public void setXCG01162(String XCG01162);

	/**
	 * Returns the modify date of this vr technical spec_xcg part1.
	 *
	 * @return the modify date of this vr technical spec_xcg part1
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_xcg part1.
	 *
	 * @param modifyDate the modify date of this vr technical spec_xcg part1
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_xcg part1.
	 *
	 * @return the sync date of this vr technical spec_xcg part1
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_xcg part1.
	 *
	 * @param syncDate the sync date of this vr technical spec_xcg part1
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_XCGPart1 vrTechnicalSpec_XCGPart1);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_XCGPart1> toCacheModel();

	@Override
	public VRTechnicalSpec_XCGPart1 toEscapedModel();

	@Override
	public VRTechnicalSpec_XCGPart1 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}