/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the VRTemplateNo service. Represents a row in the &quot;vr_templateno&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTemplateNoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTemplateNoImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRTemplateNo
 * @see com.fds.vr.business.model.impl.VRTemplateNoImpl
 * @see com.fds.vr.business.model.impl.VRTemplateNoModelImpl
 * @generated
 */
@ProviderType
public interface VRTemplateNoModel extends BaseModel<VRTemplateNo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr template no model instance should use the {@link VRTemplateNo} interface instead.
	 */

	/**
	 * Returns the primary key of this vr template no.
	 *
	 * @return the primary key of this vr template no
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr template no.
	 *
	 * @param primaryKey the primary key of this vr template no
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr template no.
	 *
	 * @return the ID of this vr template no
	 */
	public long getId();

	/**
	 * Sets the ID of this vr template no.
	 *
	 * @param id the ID of this vr template no
	 */
	public void setId(long id);

	/**
	 * Returns the pattern no of this vr template no.
	 *
	 * @return the pattern no of this vr template no
	 */
	@AutoEscape
	public String getPatternNo();

	/**
	 * Sets the pattern no of this vr template no.
	 *
	 * @param patternNo the pattern no of this vr template no
	 */
	public void setPatternNo(String patternNo);

	/**
	 * Returns the year of this vr template no.
	 *
	 * @return the year of this vr template no
	 */
	public int getYear();

	/**
	 * Sets the year of this vr template no.
	 *
	 * @param year the year of this vr template no
	 */
	public void setYear(int year);

	/**
	 * Returns the init number of this vr template no.
	 *
	 * @return the init number of this vr template no
	 */
	public int getInitNumber();

	/**
	 * Sets the init number of this vr template no.
	 *
	 * @param initNumber the init number of this vr template no
	 */
	public void setInitNumber(int initNumber);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTemplateNo vrTemplateNo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTemplateNo> toCacheModel();

	@Override
	public VRTemplateNo toEscapedModel();

	@Override
	public VRTemplateNo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}