/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_XCGPart3 service. Represents a row in the &quot;vr_technicalspec_xcg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart3ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart3Impl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XCGPart3
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart3Impl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart3ModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_XCGPart3Model extends BaseModel<VRTechnicalSpec_XCGPart3> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_xcg part3 model instance should use the {@link VRTechnicalSpec_XCGPart3} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_xcg part3.
	 *
	 * @return the primary key of this vr technical spec_xcg part3
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_xcg part3.
	 *
	 * @param primaryKey the primary key of this vr technical spec_xcg part3
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_xcg part3.
	 *
	 * @return the ID of this vr technical spec_xcg part3
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_xcg part3.
	 *
	 * @param id the ID of this vr technical spec_xcg part3
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_xcg part3.
	 *
	 * @return the mt core of this vr technical spec_xcg part3
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_xcg part3.
	 *
	 * @param mtCore the mt core of this vr technical spec_xcg part3
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_xcg part3.
	 *
	 * @return the convert assemble ID of this vr technical spec_xcg part3
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_xcg part3.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_xcg part3
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_xcg part3.
	 *
	 * @return the dossier ID of this vr technical spec_xcg part3
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_xcg part3.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_xcg part3
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_xcg part3.
	 *
	 * @return the dossier no of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_xcg part3.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_xcg part3
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_xcg part3.
	 *
	 * @return the reference uid of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_xcg part3.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_xcg part3
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_xcg part3.
	 *
	 * @return the dossier ID ctn of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_xcg part3.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_xcg part3
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_xcg part3.
	 *
	 * @return the deliverable code of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_xcg part3.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_xcg part3
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_xcg part3.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_xcg part3
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_xcg part3.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_xcg part3
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the xcg01310 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01310 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01310();

	/**
	 * Sets the xcg01310 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01310 the xcg01310 of this vr technical spec_xcg part3
	 */
	public void setXCG01310(String XCG01310);

	/**
	 * Returns the xcg01311 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01311 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01311();

	/**
	 * Sets the xcg01311 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01311 the xcg01311 of this vr technical spec_xcg part3
	 */
	public void setXCG01311(String XCG01311);

	/**
	 * Returns the xcg01312 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01312 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01312();

	/**
	 * Sets the xcg01312 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01312 the xcg01312 of this vr technical spec_xcg part3
	 */
	public void setXCG01312(String XCG01312);

	/**
	 * Returns the xcg01313 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01313 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01313();

	/**
	 * Sets the xcg01313 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01313 the xcg01313 of this vr technical spec_xcg part3
	 */
	public void setXCG01313(String XCG01313);

	/**
	 * Returns the xcg01314 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01314 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01314();

	/**
	 * Sets the xcg01314 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01314 the xcg01314 of this vr technical spec_xcg part3
	 */
	public void setXCG01314(String XCG01314);

	/**
	 * Returns the xcg01315 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01315 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01315();

	/**
	 * Sets the xcg01315 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01315 the xcg01315 of this vr technical spec_xcg part3
	 */
	public void setXCG01315(String XCG01315);

	/**
	 * Returns the xcg01316 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01316 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01316();

	/**
	 * Sets the xcg01316 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01316 the xcg01316 of this vr technical spec_xcg part3
	 */
	public void setXCG01316(String XCG01316);

	/**
	 * Returns the xcg01317 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01317 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01317();

	/**
	 * Sets the xcg01317 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01317 the xcg01317 of this vr technical spec_xcg part3
	 */
	public void setXCG01317(String XCG01317);

	/**
	 * Returns the xcg01318 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01318 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01318();

	/**
	 * Sets the xcg01318 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01318 the xcg01318 of this vr technical spec_xcg part3
	 */
	public void setXCG01318(String XCG01318);

	/**
	 * Returns the xcg01319 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01319 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01319();

	/**
	 * Sets the xcg01319 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01319 the xcg01319 of this vr technical spec_xcg part3
	 */
	public void setXCG01319(String XCG01319);

	/**
	 * Returns the xcg01320 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01320 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01320();

	/**
	 * Sets the xcg01320 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01320 the xcg01320 of this vr technical spec_xcg part3
	 */
	public void setXCG01320(String XCG01320);

	/**
	 * Returns the xcg01321 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01321 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01321();

	/**
	 * Sets the xcg01321 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01321 the xcg01321 of this vr technical spec_xcg part3
	 */
	public void setXCG01321(String XCG01321);

	/**
	 * Returns the xcg01322 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01322 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01322();

	/**
	 * Sets the xcg01322 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01322 the xcg01322 of this vr technical spec_xcg part3
	 */
	public void setXCG01322(String XCG01322);

	/**
	 * Returns the xcg01323 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01323 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01323();

	/**
	 * Sets the xcg01323 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01323 the xcg01323 of this vr technical spec_xcg part3
	 */
	public void setXCG01323(String XCG01323);

	/**
	 * Returns the xcg01324 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01324 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01324();

	/**
	 * Sets the xcg01324 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01324 the xcg01324 of this vr technical spec_xcg part3
	 */
	public void setXCG01324(String XCG01324);

	/**
	 * Returns the xcg01325 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01325 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01325();

	/**
	 * Sets the xcg01325 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01325 the xcg01325 of this vr technical spec_xcg part3
	 */
	public void setXCG01325(String XCG01325);

	/**
	 * Returns the xcg01326 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01326 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01326();

	/**
	 * Sets the xcg01326 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01326 the xcg01326 of this vr technical spec_xcg part3
	 */
	public void setXCG01326(String XCG01326);

	/**
	 * Returns the xcg01327 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01327 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01327();

	/**
	 * Sets the xcg01327 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01327 the xcg01327 of this vr technical spec_xcg part3
	 */
	public void setXCG01327(String XCG01327);

	/**
	 * Returns the xcg01328 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01328 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01328();

	/**
	 * Sets the xcg01328 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01328 the xcg01328 of this vr technical spec_xcg part3
	 */
	public void setXCG01328(String XCG01328);

	/**
	 * Returns the xcg01330 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01330 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01330();

	/**
	 * Sets the xcg01330 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01330 the xcg01330 of this vr technical spec_xcg part3
	 */
	public void setXCG01330(String XCG01330);

	/**
	 * Returns the xcg01331 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01331 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01331();

	/**
	 * Sets the xcg01331 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01331 the xcg01331 of this vr technical spec_xcg part3
	 */
	public void setXCG01331(String XCG01331);

	/**
	 * Returns the xcg01332 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01332 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01332();

	/**
	 * Sets the xcg01332 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01332 the xcg01332 of this vr technical spec_xcg part3
	 */
	public void setXCG01332(String XCG01332);

	/**
	 * Returns the xcg01333 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01333 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01333();

	/**
	 * Sets the xcg01333 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01333 the xcg01333 of this vr technical spec_xcg part3
	 */
	public void setXCG01333(String XCG01333);

	/**
	 * Returns the xcg01334 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01334 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01334();

	/**
	 * Sets the xcg01334 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01334 the xcg01334 of this vr technical spec_xcg part3
	 */
	public void setXCG01334(String XCG01334);

	/**
	 * Returns the xcg01335 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01335 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01335();

	/**
	 * Sets the xcg01335 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01335 the xcg01335 of this vr technical spec_xcg part3
	 */
	public void setXCG01335(String XCG01335);

	/**
	 * Returns the xcg01336 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01336 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01336();

	/**
	 * Sets the xcg01336 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01336 the xcg01336 of this vr technical spec_xcg part3
	 */
	public void setXCG01336(String XCG01336);

	/**
	 * Returns the xcg01337 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01337 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01337();

	/**
	 * Sets the xcg01337 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01337 the xcg01337 of this vr technical spec_xcg part3
	 */
	public void setXCG01337(String XCG01337);

	/**
	 * Returns the xcg01338 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01338 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01338();

	/**
	 * Sets the xcg01338 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01338 the xcg01338 of this vr technical spec_xcg part3
	 */
	public void setXCG01338(String XCG01338);

	/**
	 * Returns the xcg01339 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01339 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01339();

	/**
	 * Sets the xcg01339 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01339 the xcg01339 of this vr technical spec_xcg part3
	 */
	public void setXCG01339(String XCG01339);

	/**
	 * Returns the xcg01340 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01340 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01340();

	/**
	 * Sets the xcg01340 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01340 the xcg01340 of this vr technical spec_xcg part3
	 */
	public void setXCG01340(String XCG01340);

	/**
	 * Returns the xcg01341 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01341 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01341();

	/**
	 * Sets the xcg01341 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01341 the xcg01341 of this vr technical spec_xcg part3
	 */
	public void setXCG01341(String XCG01341);

	/**
	 * Returns the xcg01342 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01342 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01342();

	/**
	 * Sets the xcg01342 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01342 the xcg01342 of this vr technical spec_xcg part3
	 */
	public void setXCG01342(String XCG01342);

	/**
	 * Returns the xcg01343 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01343 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01343();

	/**
	 * Sets the xcg01343 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01343 the xcg01343 of this vr technical spec_xcg part3
	 */
	public void setXCG01343(String XCG01343);

	/**
	 * Returns the xcg01344 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01344 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01344();

	/**
	 * Sets the xcg01344 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01344 the xcg01344 of this vr technical spec_xcg part3
	 */
	public void setXCG01344(String XCG01344);

	/**
	 * Returns the xcg01345 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01345 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01345();

	/**
	 * Sets the xcg01345 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01345 the xcg01345 of this vr technical spec_xcg part3
	 */
	public void setXCG01345(String XCG01345);

	/**
	 * Returns the xcg01346 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01346 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01346();

	/**
	 * Sets the xcg01346 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01346 the xcg01346 of this vr technical spec_xcg part3
	 */
	public void setXCG01346(String XCG01346);

	/**
	 * Returns the xcg01347 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01347 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01347();

	/**
	 * Sets the xcg01347 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01347 the xcg01347 of this vr technical spec_xcg part3
	 */
	public void setXCG01347(String XCG01347);

	/**
	 * Returns the xcg01348 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01348 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01348();

	/**
	 * Sets the xcg01348 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01348 the xcg01348 of this vr technical spec_xcg part3
	 */
	public void setXCG01348(String XCG01348);

	/**
	 * Returns the xcg01349 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01349 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01349();

	/**
	 * Sets the xcg01349 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01349 the xcg01349 of this vr technical spec_xcg part3
	 */
	public void setXCG01349(String XCG01349);

	/**
	 * Returns the xcg01350 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01350 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01350();

	/**
	 * Sets the xcg01350 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01350 the xcg01350 of this vr technical spec_xcg part3
	 */
	public void setXCG01350(String XCG01350);

	/**
	 * Returns the xcg01351 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01351 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01351();

	/**
	 * Sets the xcg01351 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01351 the xcg01351 of this vr technical spec_xcg part3
	 */
	public void setXCG01351(String XCG01351);

	/**
	 * Returns the xcg01352 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01352 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01352();

	/**
	 * Sets the xcg01352 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01352 the xcg01352 of this vr technical spec_xcg part3
	 */
	public void setXCG01352(String XCG01352);

	/**
	 * Returns the xcg01353 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01353 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01353();

	/**
	 * Sets the xcg01353 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01353 the xcg01353 of this vr technical spec_xcg part3
	 */
	public void setXCG01353(String XCG01353);

	/**
	 * Returns the xcg01354 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01354 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01354();

	/**
	 * Sets the xcg01354 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01354 the xcg01354 of this vr technical spec_xcg part3
	 */
	public void setXCG01354(String XCG01354);

	/**
	 * Returns the xcg01355 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01355 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01355();

	/**
	 * Sets the xcg01355 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01355 the xcg01355 of this vr technical spec_xcg part3
	 */
	public void setXCG01355(String XCG01355);

	/**
	 * Returns the xcg01356 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01356 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01356();

	/**
	 * Sets the xcg01356 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01356 the xcg01356 of this vr technical spec_xcg part3
	 */
	public void setXCG01356(String XCG01356);

	/**
	 * Returns the xcg01357 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01357 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01357();

	/**
	 * Sets the xcg01357 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01357 the xcg01357 of this vr technical spec_xcg part3
	 */
	public void setXCG01357(String XCG01357);

	/**
	 * Returns the xcg01358 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01358 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01358();

	/**
	 * Sets the xcg01358 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01358 the xcg01358 of this vr technical spec_xcg part3
	 */
	public void setXCG01358(String XCG01358);

	/**
	 * Returns the xcg01359 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01359 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01359();

	/**
	 * Sets the xcg01359 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01359 the xcg01359 of this vr technical spec_xcg part3
	 */
	public void setXCG01359(String XCG01359);

	/**
	 * Returns the xcg01360 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01360 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01360();

	/**
	 * Sets the xcg01360 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01360 the xcg01360 of this vr technical spec_xcg part3
	 */
	public void setXCG01360(String XCG01360);

	/**
	 * Returns the xcg01361 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01361 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01361();

	/**
	 * Sets the xcg01361 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01361 the xcg01361 of this vr technical spec_xcg part3
	 */
	public void setXCG01361(String XCG01361);

	/**
	 * Returns the xcg01362 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01362 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01362();

	/**
	 * Sets the xcg01362 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01362 the xcg01362 of this vr technical spec_xcg part3
	 */
	public void setXCG01362(String XCG01362);

	/**
	 * Returns the xcg01363 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01363 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01363();

	/**
	 * Sets the xcg01363 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01363 the xcg01363 of this vr technical spec_xcg part3
	 */
	public void setXCG01363(String XCG01363);

	/**
	 * Returns the xcg01364 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01364 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01364();

	/**
	 * Sets the xcg01364 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01364 the xcg01364 of this vr technical spec_xcg part3
	 */
	public void setXCG01364(String XCG01364);

	/**
	 * Returns the xcg01365 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01365 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01365();

	/**
	 * Sets the xcg01365 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01365 the xcg01365 of this vr technical spec_xcg part3
	 */
	public void setXCG01365(String XCG01365);

	/**
	 * Returns the xcg01366 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01366 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01366();

	/**
	 * Sets the xcg01366 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01366 the xcg01366 of this vr technical spec_xcg part3
	 */
	public void setXCG01366(String XCG01366);

	/**
	 * Returns the xcg01367 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01367 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01367();

	/**
	 * Sets the xcg01367 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01367 the xcg01367 of this vr technical spec_xcg part3
	 */
	public void setXCG01367(String XCG01367);

	/**
	 * Returns the xcg01368 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01368 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01368();

	/**
	 * Sets the xcg01368 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01368 the xcg01368 of this vr technical spec_xcg part3
	 */
	public void setXCG01368(String XCG01368);

	/**
	 * Returns the xcg01369 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01369 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01369();

	/**
	 * Sets the xcg01369 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01369 the xcg01369 of this vr technical spec_xcg part3
	 */
	public void setXCG01369(String XCG01369);

	/**
	 * Returns the xcg01370 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01370 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01370();

	/**
	 * Sets the xcg01370 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01370 the xcg01370 of this vr technical spec_xcg part3
	 */
	public void setXCG01370(String XCG01370);

	/**
	 * Returns the xcg01371 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01371 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01371();

	/**
	 * Sets the xcg01371 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01371 the xcg01371 of this vr technical spec_xcg part3
	 */
	public void setXCG01371(String XCG01371);

	/**
	 * Returns the xcg01372 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01372 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01372();

	/**
	 * Sets the xcg01372 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01372 the xcg01372 of this vr technical spec_xcg part3
	 */
	public void setXCG01372(String XCG01372);

	/**
	 * Returns the xcg01373 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01373 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01373();

	/**
	 * Sets the xcg01373 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01373 the xcg01373 of this vr technical spec_xcg part3
	 */
	public void setXCG01373(String XCG01373);

	/**
	 * Returns the xcg01374 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01374 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01374();

	/**
	 * Sets the xcg01374 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01374 the xcg01374 of this vr technical spec_xcg part3
	 */
	public void setXCG01374(String XCG01374);

	/**
	 * Returns the xcg01375 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01375 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01375();

	/**
	 * Sets the xcg01375 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01375 the xcg01375 of this vr technical spec_xcg part3
	 */
	public void setXCG01375(String XCG01375);

	/**
	 * Returns the xcg01376 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01376 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01376();

	/**
	 * Sets the xcg01376 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01376 the xcg01376 of this vr technical spec_xcg part3
	 */
	public void setXCG01376(String XCG01376);

	/**
	 * Returns the xcg01377 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01377 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01377();

	/**
	 * Sets the xcg01377 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01377 the xcg01377 of this vr technical spec_xcg part3
	 */
	public void setXCG01377(String XCG01377);

	/**
	 * Returns the xcg01378 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01378 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01378();

	/**
	 * Sets the xcg01378 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01378 the xcg01378 of this vr technical spec_xcg part3
	 */
	public void setXCG01378(String XCG01378);

	/**
	 * Returns the xcg01379 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01379 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01379();

	/**
	 * Sets the xcg01379 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01379 the xcg01379 of this vr technical spec_xcg part3
	 */
	public void setXCG01379(String XCG01379);

	/**
	 * Returns the xcg01381 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01381 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01381();

	/**
	 * Sets the xcg01381 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01381 the xcg01381 of this vr technical spec_xcg part3
	 */
	public void setXCG01381(String XCG01381);

	/**
	 * Returns the xcg01382 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01382 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01382();

	/**
	 * Sets the xcg01382 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01382 the xcg01382 of this vr technical spec_xcg part3
	 */
	public void setXCG01382(String XCG01382);

	/**
	 * Returns the xcg01383 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01383 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01383();

	/**
	 * Sets the xcg01383 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01383 the xcg01383 of this vr technical spec_xcg part3
	 */
	public void setXCG01383(String XCG01383);

	/**
	 * Returns the xcg01384 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01384 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01384();

	/**
	 * Sets the xcg01384 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01384 the xcg01384 of this vr technical spec_xcg part3
	 */
	public void setXCG01384(String XCG01384);

	/**
	 * Returns the xcg01385 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01385 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01385();

	/**
	 * Sets the xcg01385 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01385 the xcg01385 of this vr technical spec_xcg part3
	 */
	public void setXCG01385(String XCG01385);

	/**
	 * Returns the xcg01386 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01386 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01386();

	/**
	 * Sets the xcg01386 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01386 the xcg01386 of this vr technical spec_xcg part3
	 */
	public void setXCG01386(String XCG01386);

	/**
	 * Returns the xcg01387 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01387 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01387();

	/**
	 * Sets the xcg01387 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01387 the xcg01387 of this vr technical spec_xcg part3
	 */
	public void setXCG01387(String XCG01387);

	/**
	 * Returns the xcg01388 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01388 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01388();

	/**
	 * Sets the xcg01388 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01388 the xcg01388 of this vr technical spec_xcg part3
	 */
	public void setXCG01388(String XCG01388);

	/**
	 * Returns the xcg01389 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01389 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01389();

	/**
	 * Sets the xcg01389 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01389 the xcg01389 of this vr technical spec_xcg part3
	 */
	public void setXCG01389(String XCG01389);

	/**
	 * Returns the xcg01390 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01390 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01390();

	/**
	 * Sets the xcg01390 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01390 the xcg01390 of this vr technical spec_xcg part3
	 */
	public void setXCG01390(String XCG01390);

	/**
	 * Returns the xcg01391 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01391 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01391();

	/**
	 * Sets the xcg01391 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01391 the xcg01391 of this vr technical spec_xcg part3
	 */
	public void setXCG01391(String XCG01391);

	/**
	 * Returns the xcg01392 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01392 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01392();

	/**
	 * Sets the xcg01392 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01392 the xcg01392 of this vr technical spec_xcg part3
	 */
	public void setXCG01392(String XCG01392);

	/**
	 * Returns the xcg01393 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01393 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01393();

	/**
	 * Sets the xcg01393 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01393 the xcg01393 of this vr technical spec_xcg part3
	 */
	public void setXCG01393(String XCG01393);

	/**
	 * Returns the xcg01394 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01394 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01394();

	/**
	 * Sets the xcg01394 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01394 the xcg01394 of this vr technical spec_xcg part3
	 */
	public void setXCG01394(String XCG01394);

	/**
	 * Returns the xcg01395 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01395 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01395();

	/**
	 * Sets the xcg01395 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01395 the xcg01395 of this vr technical spec_xcg part3
	 */
	public void setXCG01395(String XCG01395);

	/**
	 * Returns the xcg01396 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01396 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01396();

	/**
	 * Sets the xcg01396 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01396 the xcg01396 of this vr technical spec_xcg part3
	 */
	public void setXCG01396(String XCG01396);

	/**
	 * Returns the xcg01397 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01397 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01397();

	/**
	 * Sets the xcg01397 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01397 the xcg01397 of this vr technical spec_xcg part3
	 */
	public void setXCG01397(String XCG01397);

	/**
	 * Returns the xcg01398 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01398 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01398();

	/**
	 * Sets the xcg01398 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01398 the xcg01398 of this vr technical spec_xcg part3
	 */
	public void setXCG01398(String XCG01398);

	/**
	 * Returns the xcg01399 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01399 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01399();

	/**
	 * Sets the xcg01399 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01399 the xcg01399 of this vr technical spec_xcg part3
	 */
	public void setXCG01399(String XCG01399);

	/**
	 * Returns the xcg01400 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01400 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01400();

	/**
	 * Sets the xcg01400 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01400 the xcg01400 of this vr technical spec_xcg part3
	 */
	public void setXCG01400(String XCG01400);

	/**
	 * Returns the xcg01402 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01402 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01402();

	/**
	 * Sets the xcg01402 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01402 the xcg01402 of this vr technical spec_xcg part3
	 */
	public void setXCG01402(String XCG01402);

	/**
	 * Returns the xcg01403 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01403 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01403();

	/**
	 * Sets the xcg01403 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01403 the xcg01403 of this vr technical spec_xcg part3
	 */
	public void setXCG01403(String XCG01403);

	/**
	 * Returns the xcg01404 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01404 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01404();

	/**
	 * Sets the xcg01404 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01404 the xcg01404 of this vr technical spec_xcg part3
	 */
	public void setXCG01404(String XCG01404);

	/**
	 * Returns the xcg01405 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01405 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01405();

	/**
	 * Sets the xcg01405 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01405 the xcg01405 of this vr technical spec_xcg part3
	 */
	public void setXCG01405(String XCG01405);

	/**
	 * Returns the xcg01406 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01406 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01406();

	/**
	 * Sets the xcg01406 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01406 the xcg01406 of this vr technical spec_xcg part3
	 */
	public void setXCG01406(String XCG01406);

	/**
	 * Returns the xcg01407 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01407 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01407();

	/**
	 * Sets the xcg01407 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01407 the xcg01407 of this vr technical spec_xcg part3
	 */
	public void setXCG01407(String XCG01407);

	/**
	 * Returns the xcg01408 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01408 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01408();

	/**
	 * Sets the xcg01408 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01408 the xcg01408 of this vr technical spec_xcg part3
	 */
	public void setXCG01408(String XCG01408);

	/**
	 * Returns the xcg01409 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01409 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01409();

	/**
	 * Sets the xcg01409 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01409 the xcg01409 of this vr technical spec_xcg part3
	 */
	public void setXCG01409(String XCG01409);

	/**
	 * Returns the xcg01410 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01410 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01410();

	/**
	 * Sets the xcg01410 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01410 the xcg01410 of this vr technical spec_xcg part3
	 */
	public void setXCG01410(String XCG01410);

	/**
	 * Returns the xcg01411 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01411 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01411();

	/**
	 * Sets the xcg01411 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01411 the xcg01411 of this vr technical spec_xcg part3
	 */
	public void setXCG01411(String XCG01411);

	/**
	 * Returns the xcg01412 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01412 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01412();

	/**
	 * Sets the xcg01412 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01412 the xcg01412 of this vr technical spec_xcg part3
	 */
	public void setXCG01412(String XCG01412);

	/**
	 * Returns the xcg01413 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01413 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01413();

	/**
	 * Sets the xcg01413 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01413 the xcg01413 of this vr technical spec_xcg part3
	 */
	public void setXCG01413(String XCG01413);

	/**
	 * Returns the xcg01414 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01414 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01414();

	/**
	 * Sets the xcg01414 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01414 the xcg01414 of this vr technical spec_xcg part3
	 */
	public void setXCG01414(String XCG01414);

	/**
	 * Returns the xcg01415 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01415 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01415();

	/**
	 * Sets the xcg01415 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01415 the xcg01415 of this vr technical spec_xcg part3
	 */
	public void setXCG01415(String XCG01415);

	/**
	 * Returns the xcg01416 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01416 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01416();

	/**
	 * Sets the xcg01416 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01416 the xcg01416 of this vr technical spec_xcg part3
	 */
	public void setXCG01416(String XCG01416);

	/**
	 * Returns the xcg01417 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01417 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01417();

	/**
	 * Sets the xcg01417 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01417 the xcg01417 of this vr technical spec_xcg part3
	 */
	public void setXCG01417(String XCG01417);

	/**
	 * Returns the xcg01418 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01418 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01418();

	/**
	 * Sets the xcg01418 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01418 the xcg01418 of this vr technical spec_xcg part3
	 */
	public void setXCG01418(String XCG01418);

	/**
	 * Returns the xcg01419 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01419 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01419();

	/**
	 * Sets the xcg01419 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01419 the xcg01419 of this vr technical spec_xcg part3
	 */
	public void setXCG01419(String XCG01419);

	/**
	 * Returns the xcg01420 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01420 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01420();

	/**
	 * Sets the xcg01420 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01420 the xcg01420 of this vr technical spec_xcg part3
	 */
	public void setXCG01420(String XCG01420);

	/**
	 * Returns the xcg01421 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01421 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01421();

	/**
	 * Sets the xcg01421 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01421 the xcg01421 of this vr technical spec_xcg part3
	 */
	public void setXCG01421(String XCG01421);

	/**
	 * Returns the xcg01422 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01422 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01422();

	/**
	 * Sets the xcg01422 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01422 the xcg01422 of this vr technical spec_xcg part3
	 */
	public void setXCG01422(String XCG01422);

	/**
	 * Returns the xcg01423 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01423 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01423();

	/**
	 * Sets the xcg01423 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01423 the xcg01423 of this vr technical spec_xcg part3
	 */
	public void setXCG01423(String XCG01423);

	/**
	 * Returns the xcg01424 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01424 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01424();

	/**
	 * Sets the xcg01424 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01424 the xcg01424 of this vr technical spec_xcg part3
	 */
	public void setXCG01424(String XCG01424);

	/**
	 * Returns the xcg01425 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01425 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01425();

	/**
	 * Sets the xcg01425 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01425 the xcg01425 of this vr technical spec_xcg part3
	 */
	public void setXCG01425(String XCG01425);

	/**
	 * Returns the xcg01426 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01426 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01426();

	/**
	 * Sets the xcg01426 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01426 the xcg01426 of this vr technical spec_xcg part3
	 */
	public void setXCG01426(String XCG01426);

	/**
	 * Returns the xcg01427 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01427 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01427();

	/**
	 * Sets the xcg01427 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01427 the xcg01427 of this vr technical spec_xcg part3
	 */
	public void setXCG01427(String XCG01427);

	/**
	 * Returns the xcg01428 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01428 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01428();

	/**
	 * Sets the xcg01428 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01428 the xcg01428 of this vr technical spec_xcg part3
	 */
	public void setXCG01428(String XCG01428);

	/**
	 * Returns the xcg01437 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01437 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01437();

	/**
	 * Sets the xcg01437 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01437 the xcg01437 of this vr technical spec_xcg part3
	 */
	public void setXCG01437(String XCG01437);

	/**
	 * Returns the xcg01429 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01429 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01429();

	/**
	 * Sets the xcg01429 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01429 the xcg01429 of this vr technical spec_xcg part3
	 */
	public void setXCG01429(String XCG01429);

	/**
	 * Returns the xcg01430 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01430 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01430();

	/**
	 * Sets the xcg01430 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01430 the xcg01430 of this vr technical spec_xcg part3
	 */
	public void setXCG01430(String XCG01430);

	/**
	 * Returns the xcg01431 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01431 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01431();

	/**
	 * Sets the xcg01431 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01431 the xcg01431 of this vr technical spec_xcg part3
	 */
	public void setXCG01431(String XCG01431);

	/**
	 * Returns the xcg01432 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01432 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01432();

	/**
	 * Sets the xcg01432 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01432 the xcg01432 of this vr technical spec_xcg part3
	 */
	public void setXCG01432(String XCG01432);

	/**
	 * Returns the xcg01433 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01433 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01433();

	/**
	 * Sets the xcg01433 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01433 the xcg01433 of this vr technical spec_xcg part3
	 */
	public void setXCG01433(String XCG01433);

	/**
	 * Returns the xcg01434 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01434 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01434();

	/**
	 * Sets the xcg01434 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01434 the xcg01434 of this vr technical spec_xcg part3
	 */
	public void setXCG01434(String XCG01434);

	/**
	 * Returns the xcg01435 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01435 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01435();

	/**
	 * Sets the xcg01435 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01435 the xcg01435 of this vr technical spec_xcg part3
	 */
	public void setXCG01435(String XCG01435);

	/**
	 * Returns the xcg01436 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01436 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01436();

	/**
	 * Sets the xcg01436 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01436 the xcg01436 of this vr technical spec_xcg part3
	 */
	public void setXCG01436(String XCG01436);

	/**
	 * Returns the xcg01439 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01439 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01439();

	/**
	 * Sets the xcg01439 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01439 the xcg01439 of this vr technical spec_xcg part3
	 */
	public void setXCG01439(String XCG01439);

	/**
	 * Returns the xcg01440 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01440 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01440();

	/**
	 * Sets the xcg01440 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01440 the xcg01440 of this vr technical spec_xcg part3
	 */
	public void setXCG01440(String XCG01440);

	/**
	 * Returns the xcg01441 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01441 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01441();

	/**
	 * Sets the xcg01441 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01441 the xcg01441 of this vr technical spec_xcg part3
	 */
	public void setXCG01441(String XCG01441);

	/**
	 * Returns the xcg01442 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01442 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01442();

	/**
	 * Sets the xcg01442 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01442 the xcg01442 of this vr technical spec_xcg part3
	 */
	public void setXCG01442(String XCG01442);

	/**
	 * Returns the xcg01443 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01443 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01443();

	/**
	 * Sets the xcg01443 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01443 the xcg01443 of this vr technical spec_xcg part3
	 */
	public void setXCG01443(String XCG01443);

	/**
	 * Returns the xcg01445 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01445 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01445();

	/**
	 * Sets the xcg01445 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01445 the xcg01445 of this vr technical spec_xcg part3
	 */
	public void setXCG01445(String XCG01445);

	/**
	 * Returns the xcg01446 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01446 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01446();

	/**
	 * Sets the xcg01446 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01446 the xcg01446 of this vr technical spec_xcg part3
	 */
	public void setXCG01446(String XCG01446);

	/**
	 * Returns the xcg01447 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01447 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01447();

	/**
	 * Sets the xcg01447 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01447 the xcg01447 of this vr technical spec_xcg part3
	 */
	public void setXCG01447(String XCG01447);

	/**
	 * Returns the xcg01448 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01448 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01448();

	/**
	 * Sets the xcg01448 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01448 the xcg01448 of this vr technical spec_xcg part3
	 */
	public void setXCG01448(String XCG01448);

	/**
	 * Returns the xcg01449 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01449 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01449();

	/**
	 * Sets the xcg01449 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01449 the xcg01449 of this vr technical spec_xcg part3
	 */
	public void setXCG01449(String XCG01449);

	/**
	 * Returns the xcg01450 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01450 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01450();

	/**
	 * Sets the xcg01450 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01450 the xcg01450 of this vr technical spec_xcg part3
	 */
	public void setXCG01450(String XCG01450);

	/**
	 * Returns the xcg01451 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01451 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01451();

	/**
	 * Sets the xcg01451 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01451 the xcg01451 of this vr technical spec_xcg part3
	 */
	public void setXCG01451(String XCG01451);

	/**
	 * Returns the xcg01452 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01452 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01452();

	/**
	 * Sets the xcg01452 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01452 the xcg01452 of this vr technical spec_xcg part3
	 */
	public void setXCG01452(String XCG01452);

	/**
	 * Returns the xcg01453 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01453 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01453();

	/**
	 * Sets the xcg01453 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01453 the xcg01453 of this vr technical spec_xcg part3
	 */
	public void setXCG01453(String XCG01453);

	/**
	 * Returns the xcg01454 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01454 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01454();

	/**
	 * Sets the xcg01454 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01454 the xcg01454 of this vr technical spec_xcg part3
	 */
	public void setXCG01454(String XCG01454);

	/**
	 * Returns the xcg01455 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01455 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01455();

	/**
	 * Sets the xcg01455 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01455 the xcg01455 of this vr technical spec_xcg part3
	 */
	public void setXCG01455(String XCG01455);

	/**
	 * Returns the xcg01456 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01456 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01456();

	/**
	 * Sets the xcg01456 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01456 the xcg01456 of this vr technical spec_xcg part3
	 */
	public void setXCG01456(String XCG01456);

	/**
	 * Returns the xcg01457 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01457 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01457();

	/**
	 * Sets the xcg01457 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01457 the xcg01457 of this vr technical spec_xcg part3
	 */
	public void setXCG01457(String XCG01457);

	/**
	 * Returns the xcg01458 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01458 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01458();

	/**
	 * Sets the xcg01458 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01458 the xcg01458 of this vr technical spec_xcg part3
	 */
	public void setXCG01458(String XCG01458);

	/**
	 * Returns the xcg01459 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01459 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01459();

	/**
	 * Sets the xcg01459 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01459 the xcg01459 of this vr technical spec_xcg part3
	 */
	public void setXCG01459(String XCG01459);

	/**
	 * Returns the xcg01460 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01460 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01460();

	/**
	 * Sets the xcg01460 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01460 the xcg01460 of this vr technical spec_xcg part3
	 */
	public void setXCG01460(String XCG01460);

	/**
	 * Returns the xcg01461 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01461 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01461();

	/**
	 * Sets the xcg01461 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01461 the xcg01461 of this vr technical spec_xcg part3
	 */
	public void setXCG01461(String XCG01461);

	/**
	 * Returns the xcg01462 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01462 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01462();

	/**
	 * Sets the xcg01462 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01462 the xcg01462 of this vr technical spec_xcg part3
	 */
	public void setXCG01462(String XCG01462);

	/**
	 * Returns the xcg01463 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01463 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01463();

	/**
	 * Sets the xcg01463 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01463 the xcg01463 of this vr technical spec_xcg part3
	 */
	public void setXCG01463(String XCG01463);

	/**
	 * Returns the xcg01464 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01464 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01464();

	/**
	 * Sets the xcg01464 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01464 the xcg01464 of this vr technical spec_xcg part3
	 */
	public void setXCG01464(String XCG01464);

	/**
	 * Returns the xcg01465 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01465 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01465();

	/**
	 * Sets the xcg01465 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01465 the xcg01465 of this vr technical spec_xcg part3
	 */
	public void setXCG01465(String XCG01465);

	/**
	 * Returns the xcg01466 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01466 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01466();

	/**
	 * Sets the xcg01466 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01466 the xcg01466 of this vr technical spec_xcg part3
	 */
	public void setXCG01466(String XCG01466);

	/**
	 * Returns the xcg01467 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01467 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01467();

	/**
	 * Sets the xcg01467 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01467 the xcg01467 of this vr technical spec_xcg part3
	 */
	public void setXCG01467(String XCG01467);

	/**
	 * Returns the xcg01468 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01468 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01468();

	/**
	 * Sets the xcg01468 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01468 the xcg01468 of this vr technical spec_xcg part3
	 */
	public void setXCG01468(String XCG01468);

	/**
	 * Returns the xcg01469 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01469 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01469();

	/**
	 * Sets the xcg01469 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01469 the xcg01469 of this vr technical spec_xcg part3
	 */
	public void setXCG01469(String XCG01469);

	/**
	 * Returns the xcg01470 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01470 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01470();

	/**
	 * Sets the xcg01470 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01470 the xcg01470 of this vr technical spec_xcg part3
	 */
	public void setXCG01470(String XCG01470);

	/**
	 * Returns the xcg01471 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01471 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01471();

	/**
	 * Sets the xcg01471 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01471 the xcg01471 of this vr technical spec_xcg part3
	 */
	public void setXCG01471(String XCG01471);

	/**
	 * Returns the xcg01472 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01472 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01472();

	/**
	 * Sets the xcg01472 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01472 the xcg01472 of this vr technical spec_xcg part3
	 */
	public void setXCG01472(String XCG01472);

	/**
	 * Returns the xcg01473 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01473 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01473();

	/**
	 * Sets the xcg01473 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01473 the xcg01473 of this vr technical spec_xcg part3
	 */
	public void setXCG01473(String XCG01473);

	/**
	 * Returns the xcg01474 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01474 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01474();

	/**
	 * Sets the xcg01474 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01474 the xcg01474 of this vr technical spec_xcg part3
	 */
	public void setXCG01474(String XCG01474);

	/**
	 * Returns the xcg01475 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01475 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01475();

	/**
	 * Sets the xcg01475 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01475 the xcg01475 of this vr technical spec_xcg part3
	 */
	public void setXCG01475(String XCG01475);

	/**
	 * Returns the xcg01476 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01476 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01476();

	/**
	 * Sets the xcg01476 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01476 the xcg01476 of this vr technical spec_xcg part3
	 */
	public void setXCG01476(String XCG01476);

	/**
	 * Returns the xcg01477 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01477 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01477();

	/**
	 * Sets the xcg01477 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01477 the xcg01477 of this vr technical spec_xcg part3
	 */
	public void setXCG01477(String XCG01477);

	/**
	 * Returns the xcg01478 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01478 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01478();

	/**
	 * Sets the xcg01478 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01478 the xcg01478 of this vr technical spec_xcg part3
	 */
	public void setXCG01478(String XCG01478);

	/**
	 * Returns the xcg01479 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01479 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01479();

	/**
	 * Sets the xcg01479 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01479 the xcg01479 of this vr technical spec_xcg part3
	 */
	public void setXCG01479(String XCG01479);

	/**
	 * Returns the xcg01480 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01480 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01480();

	/**
	 * Sets the xcg01480 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01480 the xcg01480 of this vr technical spec_xcg part3
	 */
	public void setXCG01480(String XCG01480);

	/**
	 * Returns the xcg01481 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01481 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01481();

	/**
	 * Sets the xcg01481 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01481 the xcg01481 of this vr technical spec_xcg part3
	 */
	public void setXCG01481(String XCG01481);

	/**
	 * Returns the xcg01482 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01482 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01482();

	/**
	 * Sets the xcg01482 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01482 the xcg01482 of this vr technical spec_xcg part3
	 */
	public void setXCG01482(String XCG01482);

	/**
	 * Returns the xcg01483 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01483 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01483();

	/**
	 * Sets the xcg01483 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01483 the xcg01483 of this vr technical spec_xcg part3
	 */
	public void setXCG01483(String XCG01483);

	/**
	 * Returns the xcg01484 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01484 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01484();

	/**
	 * Sets the xcg01484 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01484 the xcg01484 of this vr technical spec_xcg part3
	 */
	public void setXCG01484(String XCG01484);

	/**
	 * Returns the xcg01485 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01485 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01485();

	/**
	 * Sets the xcg01485 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01485 the xcg01485 of this vr technical spec_xcg part3
	 */
	public void setXCG01485(String XCG01485);

	/**
	 * Returns the xcg01486 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01486 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01486();

	/**
	 * Sets the xcg01486 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01486 the xcg01486 of this vr technical spec_xcg part3
	 */
	public void setXCG01486(String XCG01486);

	/**
	 * Returns the xcg01487 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01487 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01487();

	/**
	 * Sets the xcg01487 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01487 the xcg01487 of this vr technical spec_xcg part3
	 */
	public void setXCG01487(String XCG01487);

	/**
	 * Returns the xcg01488 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01488 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01488();

	/**
	 * Sets the xcg01488 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01488 the xcg01488 of this vr technical spec_xcg part3
	 */
	public void setXCG01488(String XCG01488);

	/**
	 * Returns the xcg01489 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01489 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01489();

	/**
	 * Sets the xcg01489 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01489 the xcg01489 of this vr technical spec_xcg part3
	 */
	public void setXCG01489(String XCG01489);

	/**
	 * Returns the xcg01490 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01490 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01490();

	/**
	 * Sets the xcg01490 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01490 the xcg01490 of this vr technical spec_xcg part3
	 */
	public void setXCG01490(String XCG01490);

	/**
	 * Returns the xcg01491 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01491 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01491();

	/**
	 * Sets the xcg01491 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01491 the xcg01491 of this vr technical spec_xcg part3
	 */
	public void setXCG01491(String XCG01491);

	/**
	 * Returns the xcg01492 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01492 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01492();

	/**
	 * Sets the xcg01492 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01492 the xcg01492 of this vr technical spec_xcg part3
	 */
	public void setXCG01492(String XCG01492);

	/**
	 * Returns the xcg01493 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01493 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01493();

	/**
	 * Sets the xcg01493 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01493 the xcg01493 of this vr technical spec_xcg part3
	 */
	public void setXCG01493(String XCG01493);

	/**
	 * Returns the xcg01494 of this vr technical spec_xcg part3.
	 *
	 * @return the xcg01494 of this vr technical spec_xcg part3
	 */
	@AutoEscape
	public String getXCG01494();

	/**
	 * Sets the xcg01494 of this vr technical spec_xcg part3.
	 *
	 * @param XCG01494 the xcg01494 of this vr technical spec_xcg part3
	 */
	public void setXCG01494(String XCG01494);

	/**
	 * Returns the modify date of this vr technical spec_xcg part3.
	 *
	 * @return the modify date of this vr technical spec_xcg part3
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_xcg part3.
	 *
	 * @param modifyDate the modify date of this vr technical spec_xcg part3
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_xcg part3.
	 *
	 * @return the sync date of this vr technical spec_xcg part3
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_xcg part3.
	 *
	 * @param syncDate the sync date of this vr technical spec_xcg part3
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_XCGPart3 vrTechnicalSpec_XCGPart3);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_XCGPart3> toCacheModel();

	@Override
	public VRTechnicalSpec_XCGPart3 toEscapedModel();

	@Override
	public VRTechnicalSpec_XCGPart3 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}