/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_XCNPart3 service. Represents a row in the &quot;vr_technicalspec_xcnbb&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCNPart3ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCNPart3Impl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XCNPart3
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCNPart3Impl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCNPart3ModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_XCNPart3Model extends BaseModel<VRTechnicalSpec_XCNPart3> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_xcn part3 model instance should use the {@link VRTechnicalSpec_XCNPart3} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_xcn part3.
	 *
	 * @return the primary key of this vr technical spec_xcn part3
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_xcn part3.
	 *
	 * @param primaryKey the primary key of this vr technical spec_xcn part3
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_xcn part3.
	 *
	 * @return the ID of this vr technical spec_xcn part3
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_xcn part3.
	 *
	 * @param id the ID of this vr technical spec_xcn part3
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_xcn part3.
	 *
	 * @return the mt core of this vr technical spec_xcn part3
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_xcn part3.
	 *
	 * @param mtCore the mt core of this vr technical spec_xcn part3
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_xcn part3.
	 *
	 * @return the convert assemble ID of this vr technical spec_xcn part3
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_xcn part3.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_xcn part3
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_xcn part3.
	 *
	 * @return the dossier ID of this vr technical spec_xcn part3
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_xcn part3.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_xcn part3
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_xcn part3.
	 *
	 * @return the dossier no of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_xcn part3.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_xcn part3
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_xcn part3.
	 *
	 * @return the reference uid of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_xcn part3.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_xcn part3
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_xcn part3.
	 *
	 * @return the dossier ID ctn of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_xcn part3.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_xcn part3
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_xcn part3.
	 *
	 * @return the deliverable code of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_xcn part3.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_xcn part3
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_xcn part3.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_xcn part3
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_xcn part3.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_xcn part3
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the xcn01336 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01336 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01336();

	/**
	 * Sets the xcn01336 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01336 the xcn01336 of this vr technical spec_xcn part3
	 */
	public void setXCN01336(String XCN01336);

	/**
	 * Returns the xcn01337 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01337 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01337();

	/**
	 * Sets the xcn01337 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01337 the xcn01337 of this vr technical spec_xcn part3
	 */
	public void setXCN01337(String XCN01337);

	/**
	 * Returns the xcn01338 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01338 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01338();

	/**
	 * Sets the xcn01338 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01338 the xcn01338 of this vr technical spec_xcn part3
	 */
	public void setXCN01338(String XCN01338);

	/**
	 * Returns the xcn01339 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01339 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01339();

	/**
	 * Sets the xcn01339 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01339 the xcn01339 of this vr technical spec_xcn part3
	 */
	public void setXCN01339(String XCN01339);

	/**
	 * Returns the xcn01340 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01340 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01340();

	/**
	 * Sets the xcn01340 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01340 the xcn01340 of this vr technical spec_xcn part3
	 */
	public void setXCN01340(String XCN01340);

	/**
	 * Returns the xcn01341 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01341 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01341();

	/**
	 * Sets the xcn01341 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01341 the xcn01341 of this vr technical spec_xcn part3
	 */
	public void setXCN01341(String XCN01341);

	/**
	 * Returns the xcn01342 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01342 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01342();

	/**
	 * Sets the xcn01342 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01342 the xcn01342 of this vr technical spec_xcn part3
	 */
	public void setXCN01342(String XCN01342);

	/**
	 * Returns the xcn01343 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01343 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01343();

	/**
	 * Sets the xcn01343 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01343 the xcn01343 of this vr technical spec_xcn part3
	 */
	public void setXCN01343(String XCN01343);

	/**
	 * Returns the xcn01344 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01344 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01344();

	/**
	 * Sets the xcn01344 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01344 the xcn01344 of this vr technical spec_xcn part3
	 */
	public void setXCN01344(String XCN01344);

	/**
	 * Returns the xcn01345 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01345 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01345();

	/**
	 * Sets the xcn01345 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01345 the xcn01345 of this vr technical spec_xcn part3
	 */
	public void setXCN01345(String XCN01345);

	/**
	 * Returns the xcn01346 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01346 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01346();

	/**
	 * Sets the xcn01346 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01346 the xcn01346 of this vr technical spec_xcn part3
	 */
	public void setXCN01346(String XCN01346);

	/**
	 * Returns the xcn01347 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01347 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01347();

	/**
	 * Sets the xcn01347 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01347 the xcn01347 of this vr technical spec_xcn part3
	 */
	public void setXCN01347(String XCN01347);

	/**
	 * Returns the xcn01348 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01348 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01348();

	/**
	 * Sets the xcn01348 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01348 the xcn01348 of this vr technical spec_xcn part3
	 */
	public void setXCN01348(String XCN01348);

	/**
	 * Returns the xcn01349 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01349 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01349();

	/**
	 * Sets the xcn01349 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01349 the xcn01349 of this vr technical spec_xcn part3
	 */
	public void setXCN01349(String XCN01349);

	/**
	 * Returns the xcn01350 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01350 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01350();

	/**
	 * Sets the xcn01350 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01350 the xcn01350 of this vr technical spec_xcn part3
	 */
	public void setXCN01350(String XCN01350);

	/**
	 * Returns the xcn01351 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01351 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01351();

	/**
	 * Sets the xcn01351 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01351 the xcn01351 of this vr technical spec_xcn part3
	 */
	public void setXCN01351(String XCN01351);

	/**
	 * Returns the xcn01352 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01352 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01352();

	/**
	 * Sets the xcn01352 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01352 the xcn01352 of this vr technical spec_xcn part3
	 */
	public void setXCN01352(String XCN01352);

	/**
	 * Returns the xcn01353 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01353 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01353();

	/**
	 * Sets the xcn01353 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01353 the xcn01353 of this vr technical spec_xcn part3
	 */
	public void setXCN01353(String XCN01353);

	/**
	 * Returns the xcn01354 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01354 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01354();

	/**
	 * Sets the xcn01354 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01354 the xcn01354 of this vr technical spec_xcn part3
	 */
	public void setXCN01354(String XCN01354);

	/**
	 * Returns the xcn01355 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01355 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01355();

	/**
	 * Sets the xcn01355 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01355 the xcn01355 of this vr technical spec_xcn part3
	 */
	public void setXCN01355(String XCN01355);

	/**
	 * Returns the xcn01356 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01356 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01356();

	/**
	 * Sets the xcn01356 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01356 the xcn01356 of this vr technical spec_xcn part3
	 */
	public void setXCN01356(String XCN01356);

	/**
	 * Returns the xcn01357 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01357 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01357();

	/**
	 * Sets the xcn01357 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01357 the xcn01357 of this vr technical spec_xcn part3
	 */
	public void setXCN01357(String XCN01357);

	/**
	 * Returns the xcn01358 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01358 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01358();

	/**
	 * Sets the xcn01358 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01358 the xcn01358 of this vr technical spec_xcn part3
	 */
	public void setXCN01358(String XCN01358);

	/**
	 * Returns the xcn01359 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01359 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01359();

	/**
	 * Sets the xcn01359 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01359 the xcn01359 of this vr technical spec_xcn part3
	 */
	public void setXCN01359(String XCN01359);

	/**
	 * Returns the xcn01360 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01360 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01360();

	/**
	 * Sets the xcn01360 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01360 the xcn01360 of this vr technical spec_xcn part3
	 */
	public void setXCN01360(String XCN01360);

	/**
	 * Returns the xcn01361 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01361 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01361();

	/**
	 * Sets the xcn01361 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01361 the xcn01361 of this vr technical spec_xcn part3
	 */
	public void setXCN01361(String XCN01361);

	/**
	 * Returns the xcn01362 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01362 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01362();

	/**
	 * Sets the xcn01362 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01362 the xcn01362 of this vr technical spec_xcn part3
	 */
	public void setXCN01362(String XCN01362);

	/**
	 * Returns the xcn01363 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01363 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01363();

	/**
	 * Sets the xcn01363 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01363 the xcn01363 of this vr technical spec_xcn part3
	 */
	public void setXCN01363(String XCN01363);

	/**
	 * Returns the xcn01364 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01364 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01364();

	/**
	 * Sets the xcn01364 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01364 the xcn01364 of this vr technical spec_xcn part3
	 */
	public void setXCN01364(String XCN01364);

	/**
	 * Returns the xcn01365 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01365 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01365();

	/**
	 * Sets the xcn01365 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01365 the xcn01365 of this vr technical spec_xcn part3
	 */
	public void setXCN01365(String XCN01365);

	/**
	 * Returns the xcn01366 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01366 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01366();

	/**
	 * Sets the xcn01366 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01366 the xcn01366 of this vr technical spec_xcn part3
	 */
	public void setXCN01366(String XCN01366);

	/**
	 * Returns the xcn01367 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01367 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01367();

	/**
	 * Sets the xcn01367 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01367 the xcn01367 of this vr technical spec_xcn part3
	 */
	public void setXCN01367(String XCN01367);

	/**
	 * Returns the xcn01368 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01368 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01368();

	/**
	 * Sets the xcn01368 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01368 the xcn01368 of this vr technical spec_xcn part3
	 */
	public void setXCN01368(String XCN01368);

	/**
	 * Returns the xcn01369 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01369 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01369();

	/**
	 * Sets the xcn01369 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01369 the xcn01369 of this vr technical spec_xcn part3
	 */
	public void setXCN01369(String XCN01369);

	/**
	 * Returns the xcn01370 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01370 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01370();

	/**
	 * Sets the xcn01370 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01370 the xcn01370 of this vr technical spec_xcn part3
	 */
	public void setXCN01370(String XCN01370);

	/**
	 * Returns the xcn01371 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01371 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01371();

	/**
	 * Sets the xcn01371 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01371 the xcn01371 of this vr technical spec_xcn part3
	 */
	public void setXCN01371(String XCN01371);

	/**
	 * Returns the xcn01372 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01372 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01372();

	/**
	 * Sets the xcn01372 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01372 the xcn01372 of this vr technical spec_xcn part3
	 */
	public void setXCN01372(String XCN01372);

	/**
	 * Returns the xcn01373 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01373 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01373();

	/**
	 * Sets the xcn01373 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01373 the xcn01373 of this vr technical spec_xcn part3
	 */
	public void setXCN01373(String XCN01373);

	/**
	 * Returns the xcn01374 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01374 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01374();

	/**
	 * Sets the xcn01374 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01374 the xcn01374 of this vr technical spec_xcn part3
	 */
	public void setXCN01374(String XCN01374);

	/**
	 * Returns the xcn01375 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01375 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01375();

	/**
	 * Sets the xcn01375 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01375 the xcn01375 of this vr technical spec_xcn part3
	 */
	public void setXCN01375(String XCN01375);

	/**
	 * Returns the xcn01376 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01376 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01376();

	/**
	 * Sets the xcn01376 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01376 the xcn01376 of this vr technical spec_xcn part3
	 */
	public void setXCN01376(String XCN01376);

	/**
	 * Returns the xcn01377 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01377 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01377();

	/**
	 * Sets the xcn01377 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01377 the xcn01377 of this vr technical spec_xcn part3
	 */
	public void setXCN01377(String XCN01377);

	/**
	 * Returns the xcn01378 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01378 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01378();

	/**
	 * Sets the xcn01378 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01378 the xcn01378 of this vr technical spec_xcn part3
	 */
	public void setXCN01378(String XCN01378);

	/**
	 * Returns the xcn01379 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01379 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01379();

	/**
	 * Sets the xcn01379 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01379 the xcn01379 of this vr technical spec_xcn part3
	 */
	public void setXCN01379(String XCN01379);

	/**
	 * Returns the xcn01380 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01380 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01380();

	/**
	 * Sets the xcn01380 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01380 the xcn01380 of this vr technical spec_xcn part3
	 */
	public void setXCN01380(String XCN01380);

	/**
	 * Returns the xcn01381 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01381 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01381();

	/**
	 * Sets the xcn01381 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01381 the xcn01381 of this vr technical spec_xcn part3
	 */
	public void setXCN01381(String XCN01381);

	/**
	 * Returns the xcn01382 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01382 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01382();

	/**
	 * Sets the xcn01382 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01382 the xcn01382 of this vr technical spec_xcn part3
	 */
	public void setXCN01382(String XCN01382);

	/**
	 * Returns the xcn01383 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01383 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01383();

	/**
	 * Sets the xcn01383 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01383 the xcn01383 of this vr technical spec_xcn part3
	 */
	public void setXCN01383(String XCN01383);

	/**
	 * Returns the xcn01384 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01384 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01384();

	/**
	 * Sets the xcn01384 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01384 the xcn01384 of this vr technical spec_xcn part3
	 */
	public void setXCN01384(String XCN01384);

	/**
	 * Returns the xcn01385 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01385 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01385();

	/**
	 * Sets the xcn01385 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01385 the xcn01385 of this vr technical spec_xcn part3
	 */
	public void setXCN01385(String XCN01385);

	/**
	 * Returns the xcn01386 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01386 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01386();

	/**
	 * Sets the xcn01386 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01386 the xcn01386 of this vr technical spec_xcn part3
	 */
	public void setXCN01386(String XCN01386);

	/**
	 * Returns the xcn01387 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01387 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01387();

	/**
	 * Sets the xcn01387 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01387 the xcn01387 of this vr technical spec_xcn part3
	 */
	public void setXCN01387(String XCN01387);

	/**
	 * Returns the xcn01388 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01388 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01388();

	/**
	 * Sets the xcn01388 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01388 the xcn01388 of this vr technical spec_xcn part3
	 */
	public void setXCN01388(String XCN01388);

	/**
	 * Returns the xcn01389 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01389 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01389();

	/**
	 * Sets the xcn01389 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01389 the xcn01389 of this vr technical spec_xcn part3
	 */
	public void setXCN01389(String XCN01389);

	/**
	 * Returns the xcn01390 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01390 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01390();

	/**
	 * Sets the xcn01390 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01390 the xcn01390 of this vr technical spec_xcn part3
	 */
	public void setXCN01390(String XCN01390);

	/**
	 * Returns the xcn01391 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01391 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01391();

	/**
	 * Sets the xcn01391 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01391 the xcn01391 of this vr technical spec_xcn part3
	 */
	public void setXCN01391(String XCN01391);

	/**
	 * Returns the xcn01392 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01392 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01392();

	/**
	 * Sets the xcn01392 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01392 the xcn01392 of this vr technical spec_xcn part3
	 */
	public void setXCN01392(String XCN01392);

	/**
	 * Returns the xcn01393 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01393 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01393();

	/**
	 * Sets the xcn01393 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01393 the xcn01393 of this vr technical spec_xcn part3
	 */
	public void setXCN01393(String XCN01393);

	/**
	 * Returns the xcn01394 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01394 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01394();

	/**
	 * Sets the xcn01394 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01394 the xcn01394 of this vr technical spec_xcn part3
	 */
	public void setXCN01394(String XCN01394);

	/**
	 * Returns the xcn01395 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01395 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01395();

	/**
	 * Sets the xcn01395 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01395 the xcn01395 of this vr technical spec_xcn part3
	 */
	public void setXCN01395(String XCN01395);

	/**
	 * Returns the xcn01396 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01396 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01396();

	/**
	 * Sets the xcn01396 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01396 the xcn01396 of this vr technical spec_xcn part3
	 */
	public void setXCN01396(String XCN01396);

	/**
	 * Returns the xcn01397 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01397 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01397();

	/**
	 * Sets the xcn01397 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01397 the xcn01397 of this vr technical spec_xcn part3
	 */
	public void setXCN01397(String XCN01397);

	/**
	 * Returns the xcn01398 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01398 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01398();

	/**
	 * Sets the xcn01398 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01398 the xcn01398 of this vr technical spec_xcn part3
	 */
	public void setXCN01398(String XCN01398);

	/**
	 * Returns the xcn01399 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01399 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01399();

	/**
	 * Sets the xcn01399 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01399 the xcn01399 of this vr technical spec_xcn part3
	 */
	public void setXCN01399(String XCN01399);

	/**
	 * Returns the xcn01400 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01400 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01400();

	/**
	 * Sets the xcn01400 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01400 the xcn01400 of this vr technical spec_xcn part3
	 */
	public void setXCN01400(String XCN01400);

	/**
	 * Returns the xcn01401 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01401 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01401();

	/**
	 * Sets the xcn01401 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01401 the xcn01401 of this vr technical spec_xcn part3
	 */
	public void setXCN01401(String XCN01401);

	/**
	 * Returns the xcn01402 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01402 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01402();

	/**
	 * Sets the xcn01402 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01402 the xcn01402 of this vr technical spec_xcn part3
	 */
	public void setXCN01402(String XCN01402);

	/**
	 * Returns the xcn01403 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01403 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01403();

	/**
	 * Sets the xcn01403 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01403 the xcn01403 of this vr technical spec_xcn part3
	 */
	public void setXCN01403(String XCN01403);

	/**
	 * Returns the xcn01404 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01404 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01404();

	/**
	 * Sets the xcn01404 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01404 the xcn01404 of this vr technical spec_xcn part3
	 */
	public void setXCN01404(String XCN01404);

	/**
	 * Returns the xcn01405 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01405 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01405();

	/**
	 * Sets the xcn01405 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01405 the xcn01405 of this vr technical spec_xcn part3
	 */
	public void setXCN01405(String XCN01405);

	/**
	 * Returns the xcn01406 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01406 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01406();

	/**
	 * Sets the xcn01406 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01406 the xcn01406 of this vr technical spec_xcn part3
	 */
	public void setXCN01406(String XCN01406);

	/**
	 * Returns the xcn01407 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01407 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01407();

	/**
	 * Sets the xcn01407 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01407 the xcn01407 of this vr technical spec_xcn part3
	 */
	public void setXCN01407(String XCN01407);

	/**
	 * Returns the xcn01408 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01408 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01408();

	/**
	 * Sets the xcn01408 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01408 the xcn01408 of this vr technical spec_xcn part3
	 */
	public void setXCN01408(String XCN01408);

	/**
	 * Returns the xcn01409 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01409 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01409();

	/**
	 * Sets the xcn01409 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01409 the xcn01409 of this vr technical spec_xcn part3
	 */
	public void setXCN01409(String XCN01409);

	/**
	 * Returns the xcn01410 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01410 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01410();

	/**
	 * Sets the xcn01410 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01410 the xcn01410 of this vr technical spec_xcn part3
	 */
	public void setXCN01410(String XCN01410);

	/**
	 * Returns the xcn01411 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01411 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01411();

	/**
	 * Sets the xcn01411 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01411 the xcn01411 of this vr technical spec_xcn part3
	 */
	public void setXCN01411(String XCN01411);

	/**
	 * Returns the xcn01412 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01412 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01412();

	/**
	 * Sets the xcn01412 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01412 the xcn01412 of this vr technical spec_xcn part3
	 */
	public void setXCN01412(String XCN01412);

	/**
	 * Returns the xcn01413 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01413 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01413();

	/**
	 * Sets the xcn01413 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01413 the xcn01413 of this vr technical spec_xcn part3
	 */
	public void setXCN01413(String XCN01413);

	/**
	 * Returns the xcn01414 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01414 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01414();

	/**
	 * Sets the xcn01414 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01414 the xcn01414 of this vr technical spec_xcn part3
	 */
	public void setXCN01414(String XCN01414);

	/**
	 * Returns the xcn01415 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01415 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01415();

	/**
	 * Sets the xcn01415 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01415 the xcn01415 of this vr technical spec_xcn part3
	 */
	public void setXCN01415(String XCN01415);

	/**
	 * Returns the xcn01416 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01416 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01416();

	/**
	 * Sets the xcn01416 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01416 the xcn01416 of this vr technical spec_xcn part3
	 */
	public void setXCN01416(String XCN01416);

	/**
	 * Returns the xcn01417 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01417 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01417();

	/**
	 * Sets the xcn01417 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01417 the xcn01417 of this vr technical spec_xcn part3
	 */
	public void setXCN01417(String XCN01417);

	/**
	 * Returns the xcn01418 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01418 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01418();

	/**
	 * Sets the xcn01418 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01418 the xcn01418 of this vr technical spec_xcn part3
	 */
	public void setXCN01418(String XCN01418);

	/**
	 * Returns the xcn01419 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01419 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01419();

	/**
	 * Sets the xcn01419 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01419 the xcn01419 of this vr technical spec_xcn part3
	 */
	public void setXCN01419(String XCN01419);

	/**
	 * Returns the xcn01420 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01420 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01420();

	/**
	 * Sets the xcn01420 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01420 the xcn01420 of this vr technical spec_xcn part3
	 */
	public void setXCN01420(String XCN01420);

	/**
	 * Returns the xcn01421 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01421 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01421();

	/**
	 * Sets the xcn01421 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01421 the xcn01421 of this vr technical spec_xcn part3
	 */
	public void setXCN01421(String XCN01421);

	/**
	 * Returns the xcn01422 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01422 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01422();

	/**
	 * Sets the xcn01422 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01422 the xcn01422 of this vr technical spec_xcn part3
	 */
	public void setXCN01422(String XCN01422);

	/**
	 * Returns the xcn01423 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01423 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01423();

	/**
	 * Sets the xcn01423 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01423 the xcn01423 of this vr technical spec_xcn part3
	 */
	public void setXCN01423(String XCN01423);

	/**
	 * Returns the xcn01424 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01424 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01424();

	/**
	 * Sets the xcn01424 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01424 the xcn01424 of this vr technical spec_xcn part3
	 */
	public void setXCN01424(String XCN01424);

	/**
	 * Returns the xcn01425 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01425 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01425();

	/**
	 * Sets the xcn01425 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01425 the xcn01425 of this vr technical spec_xcn part3
	 */
	public void setXCN01425(String XCN01425);

	/**
	 * Returns the xcn01426 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01426 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01426();

	/**
	 * Sets the xcn01426 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01426 the xcn01426 of this vr technical spec_xcn part3
	 */
	public void setXCN01426(String XCN01426);

	/**
	 * Returns the xcn01427 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01427 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01427();

	/**
	 * Sets the xcn01427 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01427 the xcn01427 of this vr technical spec_xcn part3
	 */
	public void setXCN01427(String XCN01427);

	/**
	 * Returns the xcn01428 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01428 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01428();

	/**
	 * Sets the xcn01428 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01428 the xcn01428 of this vr technical spec_xcn part3
	 */
	public void setXCN01428(String XCN01428);

	/**
	 * Returns the xcn01429 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01429 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01429();

	/**
	 * Sets the xcn01429 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01429 the xcn01429 of this vr technical spec_xcn part3
	 */
	public void setXCN01429(String XCN01429);

	/**
	 * Returns the xcn01430 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01430 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01430();

	/**
	 * Sets the xcn01430 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01430 the xcn01430 of this vr technical spec_xcn part3
	 */
	public void setXCN01430(String XCN01430);

	/**
	 * Returns the xcn01431 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01431 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01431();

	/**
	 * Sets the xcn01431 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01431 the xcn01431 of this vr technical spec_xcn part3
	 */
	public void setXCN01431(String XCN01431);

	/**
	 * Returns the xcn01432 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01432 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01432();

	/**
	 * Sets the xcn01432 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01432 the xcn01432 of this vr technical spec_xcn part3
	 */
	public void setXCN01432(String XCN01432);

	/**
	 * Returns the xcn01433 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01433 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01433();

	/**
	 * Sets the xcn01433 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01433 the xcn01433 of this vr technical spec_xcn part3
	 */
	public void setXCN01433(String XCN01433);

	/**
	 * Returns the xcn01434 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01434 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01434();

	/**
	 * Sets the xcn01434 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01434 the xcn01434 of this vr technical spec_xcn part3
	 */
	public void setXCN01434(String XCN01434);

	/**
	 * Returns the xcn01435 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01435 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01435();

	/**
	 * Sets the xcn01435 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01435 the xcn01435 of this vr technical spec_xcn part3
	 */
	public void setXCN01435(String XCN01435);

	/**
	 * Returns the xcn01436 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01436 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01436();

	/**
	 * Sets the xcn01436 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01436 the xcn01436 of this vr technical spec_xcn part3
	 */
	public void setXCN01436(String XCN01436);

	/**
	 * Returns the xcn01437 of this vr technical spec_xcn part3.
	 *
	 * @return the xcn01437 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getXCN01437();

	/**
	 * Sets the xcn01437 of this vr technical spec_xcn part3.
	 *
	 * @param XCN01437 the xcn01437 of this vr technical spec_xcn part3
	 */
	public void setXCN01437(String XCN01437);

	/**
	 * Returns the bbcnclklxcn001 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn001 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN001();

	/**
	 * Sets the bbcnclklxcn001 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN001 the bbcnclklxcn001 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN001(String BBCNCLKLXCN001);

	/**
	 * Returns the bbcnclklxcn002 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn002 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN002();

	/**
	 * Sets the bbcnclklxcn002 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN002 the bbcnclklxcn002 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN002(String BBCNCLKLXCN002);

	/**
	 * Returns the bbcnclklxcn003 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn003 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN003();

	/**
	 * Sets the bbcnclklxcn003 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN003 the bbcnclklxcn003 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN003(String BBCNCLKLXCN003);

	/**
	 * Returns the bbcnclklxcn004 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn004 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN004();

	/**
	 * Sets the bbcnclklxcn004 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN004 the bbcnclklxcn004 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN004(String BBCNCLKLXCN004);

	/**
	 * Returns the bbcnclklxcn005 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn005 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN005();

	/**
	 * Sets the bbcnclklxcn005 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN005 the bbcnclklxcn005 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN005(String BBCNCLKLXCN005);

	/**
	 * Returns the bbcnclklxcn006 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn006 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN006();

	/**
	 * Sets the bbcnclklxcn006 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN006 the bbcnclklxcn006 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN006(String BBCNCLKLXCN006);

	/**
	 * Returns the bbcnclklxcn012 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn012 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN012();

	/**
	 * Sets the bbcnclklxcn012 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN012 the bbcnclklxcn012 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN012(String BBCNCLKLXCN012);

	/**
	 * Returns the bbcnclklxcn013 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn013 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN013();

	/**
	 * Sets the bbcnclklxcn013 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN013 the bbcnclklxcn013 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN013(String BBCNCLKLXCN013);

	/**
	 * Returns the bbcnclklxcn014 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn014 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN014();

	/**
	 * Sets the bbcnclklxcn014 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN014 the bbcnclklxcn014 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN014(String BBCNCLKLXCN014);

	/**
	 * Returns the bbcnclklxcn015 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn015 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN015();

	/**
	 * Sets the bbcnclklxcn015 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN015 the bbcnclklxcn015 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN015(String BBCNCLKLXCN015);

	/**
	 * Returns the bbcnclklxcn016 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn016 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN016();

	/**
	 * Sets the bbcnclklxcn016 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN016 the bbcnclklxcn016 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN016(String BBCNCLKLXCN016);

	/**
	 * Returns the bbcnclklxcn017 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn017 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN017();

	/**
	 * Sets the bbcnclklxcn017 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN017 the bbcnclklxcn017 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN017(String BBCNCLKLXCN017);

	/**
	 * Returns the bbcnclklxcn018 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn018 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN018();

	/**
	 * Sets the bbcnclklxcn018 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN018 the bbcnclklxcn018 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN018(String BBCNCLKLXCN018);

	/**
	 * Returns the bbcnclklxcn019 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn019 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN019();

	/**
	 * Sets the bbcnclklxcn019 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN019 the bbcnclklxcn019 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN019(String BBCNCLKLXCN019);

	/**
	 * Returns the bbcnclklxcn020 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn020 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN020();

	/**
	 * Sets the bbcnclklxcn020 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN020 the bbcnclklxcn020 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN020(String BBCNCLKLXCN020);

	/**
	 * Returns the bbcnclklxcn021 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn021 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN021();

	/**
	 * Sets the bbcnclklxcn021 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN021 the bbcnclklxcn021 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN021(String BBCNCLKLXCN021);

	/**
	 * Returns the bbcnclklxcn022 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn022 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN022();

	/**
	 * Sets the bbcnclklxcn022 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN022 the bbcnclklxcn022 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN022(String BBCNCLKLXCN022);

	/**
	 * Returns the bbcnclklxcn026 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn026 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN026();

	/**
	 * Sets the bbcnclklxcn026 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN026 the bbcnclklxcn026 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN026(String BBCNCLKLXCN026);

	/**
	 * Returns the bbcnclklxcn027 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn027 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN027();

	/**
	 * Sets the bbcnclklxcn027 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN027 the bbcnclklxcn027 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN027(String BBCNCLKLXCN027);

	/**
	 * Returns the bbcnclklxcn028 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn028 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN028();

	/**
	 * Sets the bbcnclklxcn028 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN028 the bbcnclklxcn028 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN028(String BBCNCLKLXCN028);

	/**
	 * Returns the bbcnclklxcn033 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn033 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN033();

	/**
	 * Sets the bbcnclklxcn033 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN033 the bbcnclklxcn033 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN033(String BBCNCLKLXCN033);

	/**
	 * Returns the bbcnclklxcn034 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn034 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN034();

	/**
	 * Sets the bbcnclklxcn034 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN034 the bbcnclklxcn034 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN034(String BBCNCLKLXCN034);

	/**
	 * Returns the bbcnclklxcn037 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn037 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN037();

	/**
	 * Sets the bbcnclklxcn037 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN037 the bbcnclklxcn037 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN037(String BBCNCLKLXCN037);

	/**
	 * Returns the bbcnclklxcn038 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn038 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN038();

	/**
	 * Sets the bbcnclklxcn038 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN038 the bbcnclklxcn038 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN038(String BBCNCLKLXCN038);

	/**
	 * Returns the bbcnclklxcn039 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn039 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN039();

	/**
	 * Sets the bbcnclklxcn039 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN039 the bbcnclklxcn039 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN039(String BBCNCLKLXCN039);

	/**
	 * Returns the bbcnclklxcn040 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn040 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN040();

	/**
	 * Sets the bbcnclklxcn040 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN040 the bbcnclklxcn040 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN040(String BBCNCLKLXCN040);

	/**
	 * Returns the bbcnclklxcn041 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn041 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN041();

	/**
	 * Sets the bbcnclklxcn041 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN041 the bbcnclklxcn041 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN041(String BBCNCLKLXCN041);

	/**
	 * Returns the bbcnclklxcn042 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn042 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN042();

	/**
	 * Sets the bbcnclklxcn042 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN042 the bbcnclklxcn042 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN042(String BBCNCLKLXCN042);

	/**
	 * Returns the bbcnclklxcn043 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn043 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN043();

	/**
	 * Sets the bbcnclklxcn043 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN043 the bbcnclklxcn043 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN043(String BBCNCLKLXCN043);

	/**
	 * Returns the bbcnclklxcn044 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn044 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN044();

	/**
	 * Sets the bbcnclklxcn044 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN044 the bbcnclklxcn044 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN044(String BBCNCLKLXCN044);

	/**
	 * Returns the bbcnclklxcn045 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn045 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN045();

	/**
	 * Sets the bbcnclklxcn045 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN045 the bbcnclklxcn045 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN045(String BBCNCLKLXCN045);

	/**
	 * Returns the bbcnclklxcn046 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn046 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN046();

	/**
	 * Sets the bbcnclklxcn046 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN046 the bbcnclklxcn046 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN046(String BBCNCLKLXCN046);

	/**
	 * Returns the bbcnclklxcn047 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn047 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN047();

	/**
	 * Sets the bbcnclklxcn047 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN047 the bbcnclklxcn047 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN047(String BBCNCLKLXCN047);

	/**
	 * Returns the bbcnclklxcn053 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn053 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN053();

	/**
	 * Sets the bbcnclklxcn053 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN053 the bbcnclklxcn053 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN053(String BBCNCLKLXCN053);

	/**
	 * Returns the bbcnclklxcn054 of this vr technical spec_xcn part3.
	 *
	 * @return the bbcnclklxcn054 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBCNCLKLXCN054();

	/**
	 * Sets the bbcnclklxcn054 of this vr technical spec_xcn part3.
	 *
	 * @param BBCNCLKLXCN054 the bbcnclklxcn054 of this vr technical spec_xcn part3
	 */
	public void setBBCNCLKLXCN054(String BBCNCLKLXCN054);

	/**
	 * Returns the bbktspmxcn001 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn001 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN001();

	/**
	 * Sets the bbktspmxcn001 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN001 the bbktspmxcn001 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN001(String BBKTSPMXCN001);

	/**
	 * Returns the bbktspmxcn002 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn002 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN002();

	/**
	 * Sets the bbktspmxcn002 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN002 the bbktspmxcn002 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN002(String BBKTSPMXCN002);

	/**
	 * Returns the bbktspmxcn003 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn003 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN003();

	/**
	 * Sets the bbktspmxcn003 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN003 the bbktspmxcn003 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN003(String BBKTSPMXCN003);

	/**
	 * Returns the bbktspmxcn004 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn004 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN004();

	/**
	 * Sets the bbktspmxcn004 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN004 the bbktspmxcn004 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN004(String BBKTSPMXCN004);

	/**
	 * Returns the bbktspmxcn005 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn005 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN005();

	/**
	 * Sets the bbktspmxcn005 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN005 the bbktspmxcn005 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN005(String BBKTSPMXCN005);

	/**
	 * Returns the bbktspmxcn006 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn006 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN006();

	/**
	 * Sets the bbktspmxcn006 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN006 the bbktspmxcn006 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN006(String BBKTSPMXCN006);

	/**
	 * Returns the bbktspmxcn007 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn007 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN007();

	/**
	 * Sets the bbktspmxcn007 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN007 the bbktspmxcn007 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN007(String BBKTSPMXCN007);

	/**
	 * Returns the bbktspmxcn008 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn008 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN008();

	/**
	 * Sets the bbktspmxcn008 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN008 the bbktspmxcn008 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN008(String BBKTSPMXCN008);

	/**
	 * Returns the bbktspmxcn009 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn009 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN009();

	/**
	 * Sets the bbktspmxcn009 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN009 the bbktspmxcn009 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN009(String BBKTSPMXCN009);

	/**
	 * Returns the bbktspmxcn012 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn012 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN012();

	/**
	 * Sets the bbktspmxcn012 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN012 the bbktspmxcn012 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN012(String BBKTSPMXCN012);

	/**
	 * Returns the bbktspmxcn013 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn013 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN013();

	/**
	 * Sets the bbktspmxcn013 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN013 the bbktspmxcn013 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN013(String BBKTSPMXCN013);

	/**
	 * Returns the bbktspmxcn014 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn014 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN014();

	/**
	 * Sets the bbktspmxcn014 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN014 the bbktspmxcn014 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN014(String BBKTSPMXCN014);

	/**
	 * Returns the bbktspmxcn015 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn015 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN015();

	/**
	 * Sets the bbktspmxcn015 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN015 the bbktspmxcn015 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN015(String BBKTSPMXCN015);

	/**
	 * Returns the bbktspmxcn016 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn016 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN016();

	/**
	 * Sets the bbktspmxcn016 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN016 the bbktspmxcn016 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN016(String BBKTSPMXCN016);

	/**
	 * Returns the bbktspmxcn017 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn017 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN017();

	/**
	 * Sets the bbktspmxcn017 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN017 the bbktspmxcn017 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN017(String BBKTSPMXCN017);

	/**
	 * Returns the bbktspmxcn018 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn018 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN018();

	/**
	 * Sets the bbktspmxcn018 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN018 the bbktspmxcn018 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN018(String BBKTSPMXCN018);

	/**
	 * Returns the bbktspmxcn019 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn019 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN019();

	/**
	 * Sets the bbktspmxcn019 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN019 the bbktspmxcn019 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN019(String BBKTSPMXCN019);

	/**
	 * Returns the bbktspmxcn020 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn020 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN020();

	/**
	 * Sets the bbktspmxcn020 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN020 the bbktspmxcn020 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN020(String BBKTSPMXCN020);

	/**
	 * Returns the bbktspmxcn021 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn021 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN021();

	/**
	 * Sets the bbktspmxcn021 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN021 the bbktspmxcn021 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN021(String BBKTSPMXCN021);

	/**
	 * Returns the bbktspmxcn022 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn022 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN022();

	/**
	 * Sets the bbktspmxcn022 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN022 the bbktspmxcn022 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN022(String BBKTSPMXCN022);

	/**
	 * Returns the bbktspmxcn023 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn023 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN023();

	/**
	 * Sets the bbktspmxcn023 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN023 the bbktspmxcn023 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN023(String BBKTSPMXCN023);

	/**
	 * Returns the bbktspmxcn024 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn024 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN024();

	/**
	 * Sets the bbktspmxcn024 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN024 the bbktspmxcn024 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN024(String BBKTSPMXCN024);

	/**
	 * Returns the bbktspmxcn025 of this vr technical spec_xcn part3.
	 *
	 * @return the bbktspmxcn025 of this vr technical spec_xcn part3
	 */
	@AutoEscape
	public String getBBKTSPMXCN025();

	/**
	 * Sets the bbktspmxcn025 of this vr technical spec_xcn part3.
	 *
	 * @param BBKTSPMXCN025 the bbktspmxcn025 of this vr technical spec_xcn part3
	 */
	public void setBBKTSPMXCN025(String BBKTSPMXCN025);

	/**
	 * Returns the modify date of this vr technical spec_xcn part3.
	 *
	 * @return the modify date of this vr technical spec_xcn part3
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_xcn part3.
	 *
	 * @param modifyDate the modify date of this vr technical spec_xcn part3
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_xcn part3.
	 *
	 * @return the sync date of this vr technical spec_xcn part3
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_xcn part3.
	 *
	 * @param syncDate the sync date of this vr technical spec_xcn part3
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_XCNPart3 vrTechnicalSpec_XCNPart3);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_XCNPart3> toCacheModel();

	@Override
	public VRTechnicalSpec_XCNPart3 toEscapedModel();

	@Override
	public VRTechnicalSpec_XCNPart3 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}