/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_LKXCG service. Represents a row in the &quot;vr_technicalspec_lkxcg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_LKXCGModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_LKXCGImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_LKXCG
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_LKXCGImpl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_LKXCGModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_LKXCGModel extends BaseModel<VRTechnicalSpec_LKXCG> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_lkxcg model instance should use the {@link VRTechnicalSpec_LKXCG} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_lkxcg.
	 *
	 * @return the primary key of this vr technical spec_lkxcg
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_lkxcg.
	 *
	 * @param primaryKey the primary key of this vr technical spec_lkxcg
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_lkxcg.
	 *
	 * @return the ID of this vr technical spec_lkxcg
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_lkxcg.
	 *
	 * @param id the ID of this vr technical spec_lkxcg
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_lkxcg.
	 *
	 * @return the mt core of this vr technical spec_lkxcg
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_lkxcg.
	 *
	 * @param mtCore the mt core of this vr technical spec_lkxcg
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_lkxcg.
	 *
	 * @return the convert assemble ID of this vr technical spec_lkxcg
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_lkxcg.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_lkxcg
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_lkxcg.
	 *
	 * @return the dossier ID of this vr technical spec_lkxcg
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_lkxcg.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_lkxcg
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_lkxcg.
	 *
	 * @return the dossier no of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_lkxcg.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_lkxcg
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_lkxcg.
	 *
	 * @return the reference uid of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_lkxcg.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_lkxcg
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_lkxcg.
	 *
	 * @return the dossier ID ctn of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_lkxcg.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_lkxcg
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_lkxcg.
	 *
	 * @return the deliverable code of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_lkxcg.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_lkxcg
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_lkxcg.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_lkxcg
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_lkxcg.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_lkxcg
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the xcg01001 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01001 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01001();

	/**
	 * Sets the xcg01001 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01001 the xcg01001 of this vr technical spec_lkxcg
	 */
	public void setXCG01001(String XCG01001);

	/**
	 * Returns the xcg01002 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01002 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01002();

	/**
	 * Sets the xcg01002 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01002 the xcg01002 of this vr technical spec_lkxcg
	 */
	public void setXCG01002(String XCG01002);

	/**
	 * Returns the xcg01003 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01003 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01003();

	/**
	 * Sets the xcg01003 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01003 the xcg01003 of this vr technical spec_lkxcg
	 */
	public void setXCG01003(String XCG01003);

	/**
	 * Returns the xcg01004 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01004 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01004();

	/**
	 * Sets the xcg01004 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01004 the xcg01004 of this vr technical spec_lkxcg
	 */
	public void setXCG01004(String XCG01004);

	/**
	 * Returns the xcg01005 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01005 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01005();

	/**
	 * Sets the xcg01005 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01005 the xcg01005 of this vr technical spec_lkxcg
	 */
	public void setXCG01005(String XCG01005);

	/**
	 * Returns the xcg01006 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01006 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01006();

	/**
	 * Sets the xcg01006 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01006 the xcg01006 of this vr technical spec_lkxcg
	 */
	public void setXCG01006(String XCG01006);

	/**
	 * Returns the xcg01007 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01007 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01007();

	/**
	 * Sets the xcg01007 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01007 the xcg01007 of this vr technical spec_lkxcg
	 */
	public void setXCG01007(String XCG01007);

	/**
	 * Returns the xcg01008 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01008 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01008();

	/**
	 * Sets the xcg01008 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01008 the xcg01008 of this vr technical spec_lkxcg
	 */
	public void setXCG01008(String XCG01008);

	/**
	 * Returns the xcg01009 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01009 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01009();

	/**
	 * Sets the xcg01009 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01009 the xcg01009 of this vr technical spec_lkxcg
	 */
	public void setXCG01009(String XCG01009);

	/**
	 * Returns the xcg01010 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01010 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01010();

	/**
	 * Sets the xcg01010 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01010 the xcg01010 of this vr technical spec_lkxcg
	 */
	public void setXCG01010(String XCG01010);

	/**
	 * Returns the xcg01011 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01011 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01011();

	/**
	 * Sets the xcg01011 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01011 the xcg01011 of this vr technical spec_lkxcg
	 */
	public void setXCG01011(String XCG01011);

	/**
	 * Returns the xcg01012 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01012 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01012();

	/**
	 * Sets the xcg01012 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01012 the xcg01012 of this vr technical spec_lkxcg
	 */
	public void setXCG01012(String XCG01012);

	/**
	 * Returns the xcg01013 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01013 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01013();

	/**
	 * Sets the xcg01013 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01013 the xcg01013 of this vr technical spec_lkxcg
	 */
	public void setXCG01013(String XCG01013);

	/**
	 * Returns the xcg01014 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01014 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01014();

	/**
	 * Sets the xcg01014 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01014 the xcg01014 of this vr technical spec_lkxcg
	 */
	public void setXCG01014(String XCG01014);

	/**
	 * Returns the xcg01016 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01016 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01016();

	/**
	 * Sets the xcg01016 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01016 the xcg01016 of this vr technical spec_lkxcg
	 */
	public void setXCG01016(String XCG01016);

	/**
	 * Returns the xcg01017 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01017 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01017();

	/**
	 * Sets the xcg01017 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01017 the xcg01017 of this vr technical spec_lkxcg
	 */
	public void setXCG01017(String XCG01017);

	/**
	 * Returns the xcg01019 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01019 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01019();

	/**
	 * Sets the xcg01019 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01019 the xcg01019 of this vr technical spec_lkxcg
	 */
	public void setXCG01019(String XCG01019);

	/**
	 * Returns the xcg01020 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01020 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01020();

	/**
	 * Sets the xcg01020 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01020 the xcg01020 of this vr technical spec_lkxcg
	 */
	public void setXCG01020(String XCG01020);

	/**
	 * Returns the xcg01021 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01021 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01021();

	/**
	 * Sets the xcg01021 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01021 the xcg01021 of this vr technical spec_lkxcg
	 */
	public void setXCG01021(String XCG01021);

	/**
	 * Returns the xcg01022 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01022 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01022();

	/**
	 * Sets the xcg01022 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01022 the xcg01022 of this vr technical spec_lkxcg
	 */
	public void setXCG01022(String XCG01022);

	/**
	 * Returns the xcg01024 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01024 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01024();

	/**
	 * Sets the xcg01024 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01024 the xcg01024 of this vr technical spec_lkxcg
	 */
	public void setXCG01024(String XCG01024);

	/**
	 * Returns the xcg01025 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01025 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01025();

	/**
	 * Sets the xcg01025 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01025 the xcg01025 of this vr technical spec_lkxcg
	 */
	public void setXCG01025(String XCG01025);

	/**
	 * Returns the xcg01026 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01026 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01026();

	/**
	 * Sets the xcg01026 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01026 the xcg01026 of this vr technical spec_lkxcg
	 */
	public void setXCG01026(String XCG01026);

	/**
	 * Returns the xcg01027 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01027 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01027();

	/**
	 * Sets the xcg01027 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01027 the xcg01027 of this vr technical spec_lkxcg
	 */
	public void setXCG01027(String XCG01027);

	/**
	 * Returns the xcg01028 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01028 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01028();

	/**
	 * Sets the xcg01028 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01028 the xcg01028 of this vr technical spec_lkxcg
	 */
	public void setXCG01028(String XCG01028);

	/**
	 * Returns the xcg01030 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01030 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01030();

	/**
	 * Sets the xcg01030 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01030 the xcg01030 of this vr technical spec_lkxcg
	 */
	public void setXCG01030(String XCG01030);

	/**
	 * Returns the xcg01031 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01031 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01031();

	/**
	 * Sets the xcg01031 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01031 the xcg01031 of this vr technical spec_lkxcg
	 */
	public void setXCG01031(String XCG01031);

	/**
	 * Returns the xcg01032 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01032 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01032();

	/**
	 * Sets the xcg01032 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01032 the xcg01032 of this vr technical spec_lkxcg
	 */
	public void setXCG01032(String XCG01032);

	/**
	 * Returns the xcg01033 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01033 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01033();

	/**
	 * Sets the xcg01033 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01033 the xcg01033 of this vr technical spec_lkxcg
	 */
	public void setXCG01033(String XCG01033);

	/**
	 * Returns the xcg01034 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01034 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01034();

	/**
	 * Sets the xcg01034 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01034 the xcg01034 of this vr technical spec_lkxcg
	 */
	public void setXCG01034(String XCG01034);

	/**
	 * Returns the xcg01035 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01035 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01035();

	/**
	 * Sets the xcg01035 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01035 the xcg01035 of this vr technical spec_lkxcg
	 */
	public void setXCG01035(String XCG01035);

	/**
	 * Returns the xcg01036 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01036 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01036();

	/**
	 * Sets the xcg01036 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01036 the xcg01036 of this vr technical spec_lkxcg
	 */
	public void setXCG01036(String XCG01036);

	/**
	 * Returns the xcg01037 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01037 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01037();

	/**
	 * Sets the xcg01037 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01037 the xcg01037 of this vr technical spec_lkxcg
	 */
	public void setXCG01037(String XCG01037);

	/**
	 * Returns the xcg01038 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01038 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01038();

	/**
	 * Sets the xcg01038 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01038 the xcg01038 of this vr technical spec_lkxcg
	 */
	public void setXCG01038(String XCG01038);

	/**
	 * Returns the xcg01039 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01039 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01039();

	/**
	 * Sets the xcg01039 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01039 the xcg01039 of this vr technical spec_lkxcg
	 */
	public void setXCG01039(String XCG01039);

	/**
	 * Returns the xcg01040 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01040 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01040();

	/**
	 * Sets the xcg01040 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01040 the xcg01040 of this vr technical spec_lkxcg
	 */
	public void setXCG01040(String XCG01040);

	/**
	 * Returns the xcg01041 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01041 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01041();

	/**
	 * Sets the xcg01041 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01041 the xcg01041 of this vr technical spec_lkxcg
	 */
	public void setXCG01041(String XCG01041);

	/**
	 * Returns the xcg01042 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01042 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01042();

	/**
	 * Sets the xcg01042 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01042 the xcg01042 of this vr technical spec_lkxcg
	 */
	public void setXCG01042(String XCG01042);

	/**
	 * Returns the xcg01043 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01043 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01043();

	/**
	 * Sets the xcg01043 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01043 the xcg01043 of this vr technical spec_lkxcg
	 */
	public void setXCG01043(String XCG01043);

	/**
	 * Returns the xcg01044 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01044 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01044();

	/**
	 * Sets the xcg01044 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01044 the xcg01044 of this vr technical spec_lkxcg
	 */
	public void setXCG01044(String XCG01044);

	/**
	 * Returns the xcg01045 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01045 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01045();

	/**
	 * Sets the xcg01045 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01045 the xcg01045 of this vr technical spec_lkxcg
	 */
	public void setXCG01045(String XCG01045);

	/**
	 * Returns the xcg01046 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01046 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01046();

	/**
	 * Sets the xcg01046 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01046 the xcg01046 of this vr technical spec_lkxcg
	 */
	public void setXCG01046(String XCG01046);

	/**
	 * Returns the xcg01047 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01047 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01047();

	/**
	 * Sets the xcg01047 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01047 the xcg01047 of this vr technical spec_lkxcg
	 */
	public void setXCG01047(String XCG01047);

	/**
	 * Returns the xcg01049 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01049 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01049();

	/**
	 * Sets the xcg01049 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01049 the xcg01049 of this vr technical spec_lkxcg
	 */
	public void setXCG01049(String XCG01049);

	/**
	 * Returns the xcg01050 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01050 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01050();

	/**
	 * Sets the xcg01050 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01050 the xcg01050 of this vr technical spec_lkxcg
	 */
	public void setXCG01050(String XCG01050);

	/**
	 * Returns the xcg01051 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01051 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01051();

	/**
	 * Sets the xcg01051 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01051 the xcg01051 of this vr technical spec_lkxcg
	 */
	public void setXCG01051(String XCG01051);

	/**
	 * Returns the xcg01052 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01052 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01052();

	/**
	 * Sets the xcg01052 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01052 the xcg01052 of this vr technical spec_lkxcg
	 */
	public void setXCG01052(String XCG01052);

	/**
	 * Returns the xcg01053 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01053 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01053();

	/**
	 * Sets the xcg01053 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01053 the xcg01053 of this vr technical spec_lkxcg
	 */
	public void setXCG01053(String XCG01053);

	/**
	 * Returns the xcg01054 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01054 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01054();

	/**
	 * Sets the xcg01054 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01054 the xcg01054 of this vr technical spec_lkxcg
	 */
	public void setXCG01054(String XCG01054);

	/**
	 * Returns the xcg01055 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01055 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01055();

	/**
	 * Sets the xcg01055 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01055 the xcg01055 of this vr technical spec_lkxcg
	 */
	public void setXCG01055(String XCG01055);

	/**
	 * Returns the xcg01056 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01056 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01056();

	/**
	 * Sets the xcg01056 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01056 the xcg01056 of this vr technical spec_lkxcg
	 */
	public void setXCG01056(String XCG01056);

	/**
	 * Returns the xcg01057 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01057 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01057();

	/**
	 * Sets the xcg01057 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01057 the xcg01057 of this vr technical spec_lkxcg
	 */
	public void setXCG01057(String XCG01057);

	/**
	 * Returns the xcg01058 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01058 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01058();

	/**
	 * Sets the xcg01058 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01058 the xcg01058 of this vr technical spec_lkxcg
	 */
	public void setXCG01058(String XCG01058);

	/**
	 * Returns the xcg01059 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01059 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01059();

	/**
	 * Sets the xcg01059 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01059 the xcg01059 of this vr technical spec_lkxcg
	 */
	public void setXCG01059(String XCG01059);

	/**
	 * Returns the xcg01060 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01060 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01060();

	/**
	 * Sets the xcg01060 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01060 the xcg01060 of this vr technical spec_lkxcg
	 */
	public void setXCG01060(String XCG01060);

	/**
	 * Returns the xcg01062 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01062 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01062();

	/**
	 * Sets the xcg01062 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01062 the xcg01062 of this vr technical spec_lkxcg
	 */
	public void setXCG01062(String XCG01062);

	/**
	 * Returns the xcg01063 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01063 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01063();

	/**
	 * Sets the xcg01063 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01063 the xcg01063 of this vr technical spec_lkxcg
	 */
	public void setXCG01063(String XCG01063);

	/**
	 * Returns the xcg01064 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01064 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01064();

	/**
	 * Sets the xcg01064 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01064 the xcg01064 of this vr technical spec_lkxcg
	 */
	public void setXCG01064(String XCG01064);

	/**
	 * Returns the xcg01065 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01065 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01065();

	/**
	 * Sets the xcg01065 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01065 the xcg01065 of this vr technical spec_lkxcg
	 */
	public void setXCG01065(String XCG01065);

	/**
	 * Returns the xcg01066 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01066 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01066();

	/**
	 * Sets the xcg01066 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01066 the xcg01066 of this vr technical spec_lkxcg
	 */
	public void setXCG01066(String XCG01066);

	/**
	 * Returns the xcg01067 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01067 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01067();

	/**
	 * Sets the xcg01067 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01067 the xcg01067 of this vr technical spec_lkxcg
	 */
	public void setXCG01067(String XCG01067);

	/**
	 * Returns the xcg01068 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01068 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01068();

	/**
	 * Sets the xcg01068 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01068 the xcg01068 of this vr technical spec_lkxcg
	 */
	public void setXCG01068(String XCG01068);

	/**
	 * Returns the xcg01069 of this vr technical spec_lkxcg.
	 *
	 * @return the xcg01069 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getXCG01069();

	/**
	 * Sets the xcg01069 of this vr technical spec_lkxcg.
	 *
	 * @param XCG01069 the xcg01069 of this vr technical spec_lkxcg
	 */
	public void setXCG01069(String XCG01069);

	/**
	 * Returns the lkxcg0407 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0407 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0407();

	/**
	 * Sets the lkxcg0407 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0407 the lkxcg0407 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0407(String LKXCG0407);

	/**
	 * Returns the lkxcg0408 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0408 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0408();

	/**
	 * Sets the lkxcg0408 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0408 the lkxcg0408 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0408(String LKXCG0408);

	/**
	 * Returns the lkxcg0409 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0409 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0409();

	/**
	 * Sets the lkxcg0409 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0409 the lkxcg0409 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0409(String LKXCG0409);

	/**
	 * Returns the lkxcg0410 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0410 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0410();

	/**
	 * Sets the lkxcg0410 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0410 the lkxcg0410 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0410(String LKXCG0410);

	/**
	 * Returns the lkxcg0411 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0411 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0411();

	/**
	 * Sets the lkxcg0411 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0411 the lkxcg0411 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0411(String LKXCG0411);

	/**
	 * Returns the lkxcg0412 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0412 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0412();

	/**
	 * Sets the lkxcg0412 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0412 the lkxcg0412 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0412(String LKXCG0412);

	/**
	 * Returns the lkxcg0413 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0413 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0413();

	/**
	 * Sets the lkxcg0413 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0413 the lkxcg0413 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0413(String LKXCG0413);

	/**
	 * Returns the lkxcg0414 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0414 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0414();

	/**
	 * Sets the lkxcg0414 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0414 the lkxcg0414 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0414(String LKXCG0414);

	/**
	 * Returns the lkxcg0415 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0415 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0415();

	/**
	 * Sets the lkxcg0415 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0415 the lkxcg0415 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0415(String LKXCG0415);

	/**
	 * Returns the lkxcg0416 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0416 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0416();

	/**
	 * Sets the lkxcg0416 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0416 the lkxcg0416 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0416(String LKXCG0416);

	/**
	 * Returns the lkxcg0507 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0507 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0507();

	/**
	 * Sets the lkxcg0507 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0507 the lkxcg0507 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0507(String LKXCG0507);

	/**
	 * Returns the lkxcg0508 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0508 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0508();

	/**
	 * Sets the lkxcg0508 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0508 the lkxcg0508 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0508(String LKXCG0508);

	/**
	 * Returns the lkxcg0509 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0509 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0509();

	/**
	 * Sets the lkxcg0509 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0509 the lkxcg0509 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0509(String LKXCG0509);

	/**
	 * Returns the lkxcg0510 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0510 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0510();

	/**
	 * Sets the lkxcg0510 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0510 the lkxcg0510 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0510(String LKXCG0510);

	/**
	 * Returns the lkxcg0511 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0511 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0511();

	/**
	 * Sets the lkxcg0511 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0511 the lkxcg0511 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0511(String LKXCG0511);

	/**
	 * Returns the lkxcg0512 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0512 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0512();

	/**
	 * Sets the lkxcg0512 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0512 the lkxcg0512 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0512(String LKXCG0512);

	/**
	 * Returns the lkxcg0708 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0708 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0708();

	/**
	 * Sets the lkxcg0708 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0708 the lkxcg0708 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0708(String LKXCG0708);

	/**
	 * Returns the lkxcg0709 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0709 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0709();

	/**
	 * Sets the lkxcg0709 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0709 the lkxcg0709 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0709(String LKXCG0709);

	/**
	 * Returns the lkxcg0710 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0710 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0710();

	/**
	 * Sets the lkxcg0710 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0710 the lkxcg0710 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0710(String LKXCG0710);

	/**
	 * Returns the lkxcg0711 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0711 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0711();

	/**
	 * Sets the lkxcg0711 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0711 the lkxcg0711 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0711(String LKXCG0711);

	/**
	 * Returns the lkxcg0713 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0713 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0713();

	/**
	 * Sets the lkxcg0713 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0713 the lkxcg0713 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0713(String LKXCG0713);

	/**
	 * Returns the lkxcg0714 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0714 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0714();

	/**
	 * Sets the lkxcg0714 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0714 the lkxcg0714 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0714(String LKXCG0714);

	/**
	 * Returns the lkxcg0715 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0715 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0715();

	/**
	 * Sets the lkxcg0715 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0715 the lkxcg0715 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0715(String LKXCG0715);

	/**
	 * Returns the lkxcg0716 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0716 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0716();

	/**
	 * Sets the lkxcg0716 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0716 the lkxcg0716 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0716(String LKXCG0716);

	/**
	 * Returns the lkxcg0717 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0717 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0717();

	/**
	 * Sets the lkxcg0717 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0717 the lkxcg0717 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0717(String LKXCG0717);

	/**
	 * Returns the lkxcg0718 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0718 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0718();

	/**
	 * Sets the lkxcg0718 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0718 the lkxcg0718 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0718(String LKXCG0718);

	/**
	 * Returns the lkxcg0719 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0719 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0719();

	/**
	 * Sets the lkxcg0719 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0719 the lkxcg0719 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0719(String LKXCG0719);

	/**
	 * Returns the lkxcg0720 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0720 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0720();

	/**
	 * Sets the lkxcg0720 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0720 the lkxcg0720 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0720(String LKXCG0720);

	/**
	 * Returns the lkxcg0721 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0721 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0721();

	/**
	 * Sets the lkxcg0721 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0721 the lkxcg0721 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0721(String LKXCG0721);

	/**
	 * Returns the lkxcg0722 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0722 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0722();

	/**
	 * Sets the lkxcg0722 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0722 the lkxcg0722 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0722(String LKXCG0722);

	/**
	 * Returns the lkxcg0723 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0723 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0723();

	/**
	 * Sets the lkxcg0723 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0723 the lkxcg0723 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0723(String LKXCG0723);

	/**
	 * Returns the lkxcg0724 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0724 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0724();

	/**
	 * Sets the lkxcg0724 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0724 the lkxcg0724 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0724(String LKXCG0724);

	/**
	 * Returns the lkxcg0725 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0725 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0725();

	/**
	 * Sets the lkxcg0725 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0725 the lkxcg0725 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0725(String LKXCG0725);

	/**
	 * Returns the lkxcg0726 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0726 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0726();

	/**
	 * Sets the lkxcg0726 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0726 the lkxcg0726 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0726(String LKXCG0726);

	/**
	 * Returns the lkxcg0727 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0727 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0727();

	/**
	 * Sets the lkxcg0727 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0727 the lkxcg0727 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0727(String LKXCG0727);

	/**
	 * Returns the lkxcg0728 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0728 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0728();

	/**
	 * Sets the lkxcg0728 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0728 the lkxcg0728 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0728(String LKXCG0728);

	/**
	 * Returns the lkxcg0606 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0606 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0606();

	/**
	 * Sets the lkxcg0606 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0606 the lkxcg0606 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0606(String LKXCG0606);

	/**
	 * Returns the lkxcg0607 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0607 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0607();

	/**
	 * Sets the lkxcg0607 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0607 the lkxcg0607 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0607(String LKXCG0607);

	/**
	 * Returns the lkxcg0608 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0608 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0608();

	/**
	 * Sets the lkxcg0608 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0608 the lkxcg0608 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0608(String LKXCG0608);

	/**
	 * Returns the lkxcg0609 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0609 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0609();

	/**
	 * Sets the lkxcg0609 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0609 the lkxcg0609 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0609(String LKXCG0609);

	/**
	 * Returns the lkxcg0610 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0610 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0610();

	/**
	 * Sets the lkxcg0610 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0610 the lkxcg0610 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0610(String LKXCG0610);

	/**
	 * Returns the lkxcg0611 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0611 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0611();

	/**
	 * Sets the lkxcg0611 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0611 the lkxcg0611 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0611(String LKXCG0611);

	/**
	 * Returns the lkxcg0612 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0612 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0612();

	/**
	 * Sets the lkxcg0612 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0612 the lkxcg0612 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0612(String LKXCG0612);

	/**
	 * Returns the lkxcg0613 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0613 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0613();

	/**
	 * Sets the lkxcg0613 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0613 the lkxcg0613 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0613(String LKXCG0613);

	/**
	 * Returns the lkxcg0614 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0614 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0614();

	/**
	 * Sets the lkxcg0614 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0614 the lkxcg0614 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0614(String LKXCG0614);

	/**
	 * Returns the lkxcg0615 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0615 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0615();

	/**
	 * Sets the lkxcg0615 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0615 the lkxcg0615 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0615(String LKXCG0615);

	/**
	 * Returns the lkxcg0616 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0616 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0616();

	/**
	 * Sets the lkxcg0616 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0616 the lkxcg0616 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0616(String LKXCG0616);

	/**
	 * Returns the lkxcg0620 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0620 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0620();

	/**
	 * Sets the lkxcg0620 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0620 the lkxcg0620 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0620(String LKXCG0620);

	/**
	 * Returns the lkxcg0807 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0807 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0807();

	/**
	 * Sets the lkxcg0807 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0807 the lkxcg0807 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0807(String LKXCG0807);

	/**
	 * Returns the lkxcg0808 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0808 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0808();

	/**
	 * Sets the lkxcg0808 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0808 the lkxcg0808 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0808(String LKXCG0808);

	/**
	 * Returns the lkxcg0809 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0809 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0809();

	/**
	 * Sets the lkxcg0809 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0809 the lkxcg0809 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0809(String LKXCG0809);

	/**
	 * Returns the lkxcg0810 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0810 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0810();

	/**
	 * Sets the lkxcg0810 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0810 the lkxcg0810 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0810(String LKXCG0810);

	/**
	 * Returns the lkxcg0812 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0812 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0812();

	/**
	 * Sets the lkxcg0812 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0812 the lkxcg0812 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0812(String LKXCG0812);

	/**
	 * Returns the lkxcg0813 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0813 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0813();

	/**
	 * Sets the lkxcg0813 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0813 the lkxcg0813 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0813(String LKXCG0813);

	/**
	 * Returns the lkxcg0814 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0814 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0814();

	/**
	 * Sets the lkxcg0814 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0814 the lkxcg0814 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0814(String LKXCG0814);

	/**
	 * Returns the lkxcg0815 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0815 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0815();

	/**
	 * Sets the lkxcg0815 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0815 the lkxcg0815 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0815(String LKXCG0815);

	/**
	 * Returns the lkxcg0816 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0816 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0816();

	/**
	 * Sets the lkxcg0816 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0816 the lkxcg0816 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0816(String LKXCG0816);

	/**
	 * Returns the lkxcg0817 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0817 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0817();

	/**
	 * Sets the lkxcg0817 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0817 the lkxcg0817 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0817(String LKXCG0817);

	/**
	 * Returns the lkxcg0818 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0818 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0818();

	/**
	 * Sets the lkxcg0818 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0818 the lkxcg0818 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0818(String LKXCG0818);

	/**
	 * Returns the lkxcg0819 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0819 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0819();

	/**
	 * Sets the lkxcg0819 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0819 the lkxcg0819 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0819(String LKXCG0819);

	/**
	 * Returns the lkxcg0820 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0820 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0820();

	/**
	 * Sets the lkxcg0820 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0820 the lkxcg0820 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0820(String LKXCG0820);

	/**
	 * Returns the lkxcg0907 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0907 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0907();

	/**
	 * Sets the lkxcg0907 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0907 the lkxcg0907 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0907(String LKXCG0907);

	/**
	 * Returns the lkxcg0908 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0908 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0908();

	/**
	 * Sets the lkxcg0908 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0908 the lkxcg0908 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0908(String LKXCG0908);

	/**
	 * Returns the lkxcg0909 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0909 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0909();

	/**
	 * Sets the lkxcg0909 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0909 the lkxcg0909 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0909(String LKXCG0909);

	/**
	 * Returns the lkxcg0910 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0910 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0910();

	/**
	 * Sets the lkxcg0910 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0910 the lkxcg0910 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0910(String LKXCG0910);

	/**
	 * Returns the lkxcg0911 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0911 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0911();

	/**
	 * Sets the lkxcg0911 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0911 the lkxcg0911 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0911(String LKXCG0911);

	/**
	 * Returns the lkxcg0912 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0912 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0912();

	/**
	 * Sets the lkxcg0912 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0912 the lkxcg0912 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0912(String LKXCG0912);

	/**
	 * Returns the lkxcg0913 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0913 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0913();

	/**
	 * Sets the lkxcg0913 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0913 the lkxcg0913 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0913(String LKXCG0913);

	/**
	 * Returns the lkxcg0914 of this vr technical spec_lkxcg.
	 *
	 * @return the lkxcg0914 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getLKXCG0914();

	/**
	 * Sets the lkxcg0914 of this vr technical spec_lkxcg.
	 *
	 * @param LKXCG0914 the lkxcg0914 of this vr technical spec_lkxcg
	 */
	public void setLKXCG0914(String LKXCG0914);

	/**
	 * Returns the bblkxcg001 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg001 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG001();

	/**
	 * Sets the bblkxcg001 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG001 the bblkxcg001 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG001(String BBLKXCG001);

	/**
	 * Returns the bblkxcg002 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg002 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG002();

	/**
	 * Sets the bblkxcg002 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG002 the bblkxcg002 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG002(String BBLKXCG002);

	/**
	 * Returns the bblkxcg003 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg003 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG003();

	/**
	 * Sets the bblkxcg003 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG003 the bblkxcg003 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG003(String BBLKXCG003);

	/**
	 * Returns the bblkxcg004 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg004 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG004();

	/**
	 * Sets the bblkxcg004 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG004 the bblkxcg004 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG004(String BBLKXCG004);

	/**
	 * Returns the bblkxcg005 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg005 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG005();

	/**
	 * Sets the bblkxcg005 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG005 the bblkxcg005 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG005(String BBLKXCG005);

	/**
	 * Returns the bblkxcg006 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg006 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG006();

	/**
	 * Sets the bblkxcg006 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG006 the bblkxcg006 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG006(String BBLKXCG006);

	/**
	 * Returns the bblkxcg007 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg007 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG007();

	/**
	 * Sets the bblkxcg007 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG007 the bblkxcg007 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG007(String BBLKXCG007);

	/**
	 * Returns the bblkxcg008 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg008 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG008();

	/**
	 * Sets the bblkxcg008 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG008 the bblkxcg008 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG008(String BBLKXCG008);

	/**
	 * Returns the bblkxcg009 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg009 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG009();

	/**
	 * Sets the bblkxcg009 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG009 the bblkxcg009 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG009(String BBLKXCG009);

	/**
	 * Returns the bblkxcg010 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg010 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG010();

	/**
	 * Sets the bblkxcg010 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG010 the bblkxcg010 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG010(String BBLKXCG010);

	/**
	 * Returns the bblkxcg011 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg011 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG011();

	/**
	 * Sets the bblkxcg011 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG011 the bblkxcg011 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG011(String BBLKXCG011);

	/**
	 * Returns the bblkxcg012 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg012 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG012();

	/**
	 * Sets the bblkxcg012 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG012 the bblkxcg012 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG012(String BBLKXCG012);

	/**
	 * Returns the bblkxcg013 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg013 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG013();

	/**
	 * Sets the bblkxcg013 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG013 the bblkxcg013 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG013(String BBLKXCG013);

	/**
	 * Returns the bblkxcg014 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg014 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG014();

	/**
	 * Sets the bblkxcg014 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG014 the bblkxcg014 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG014(String BBLKXCG014);

	/**
	 * Returns the bblkxcg015 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg015 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG015();

	/**
	 * Sets the bblkxcg015 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG015 the bblkxcg015 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG015(String BBLKXCG015);

	/**
	 * Returns the bblkxcg016 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg016 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG016();

	/**
	 * Sets the bblkxcg016 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG016 the bblkxcg016 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG016(String BBLKXCG016);

	/**
	 * Returns the bblkxcg017 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg017 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG017();

	/**
	 * Sets the bblkxcg017 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG017 the bblkxcg017 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG017(String BBLKXCG017);

	/**
	 * Returns the bblkxcg018 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg018 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG018();

	/**
	 * Sets the bblkxcg018 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG018 the bblkxcg018 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG018(String BBLKXCG018);

	/**
	 * Returns the bblkxcg019 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg019 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG019();

	/**
	 * Sets the bblkxcg019 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG019 the bblkxcg019 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG019(String BBLKXCG019);

	/**
	 * Returns the bblkxcg020 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg020 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG020();

	/**
	 * Sets the bblkxcg020 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG020 the bblkxcg020 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG020(String BBLKXCG020);

	/**
	 * Returns the bblkxcg021 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg021 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG021();

	/**
	 * Sets the bblkxcg021 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG021 the bblkxcg021 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG021(String BBLKXCG021);

	/**
	 * Returns the bblkxcg022 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg022 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG022();

	/**
	 * Sets the bblkxcg022 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG022 the bblkxcg022 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG022(String BBLKXCG022);

	/**
	 * Returns the bblkxcg023 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg023 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG023();

	/**
	 * Sets the bblkxcg023 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG023 the bblkxcg023 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG023(String BBLKXCG023);

	/**
	 * Returns the bblkxcg024 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg024 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG024();

	/**
	 * Sets the bblkxcg024 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG024 the bblkxcg024 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG024(String BBLKXCG024);

	/**
	 * Returns the bblkxcg025 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg025 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG025();

	/**
	 * Sets the bblkxcg025 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG025 the bblkxcg025 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG025(String BBLKXCG025);

	/**
	 * Returns the bblkxcg026 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg026 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG026();

	/**
	 * Sets the bblkxcg026 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG026 the bblkxcg026 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG026(String BBLKXCG026);

	/**
	 * Returns the bblkxcg027 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg027 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG027();

	/**
	 * Sets the bblkxcg027 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG027 the bblkxcg027 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG027(String BBLKXCG027);

	/**
	 * Returns the bblkxcg028 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg028 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG028();

	/**
	 * Sets the bblkxcg028 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG028 the bblkxcg028 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG028(String BBLKXCG028);

	/**
	 * Returns the bblkxcg029 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg029 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG029();

	/**
	 * Sets the bblkxcg029 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG029 the bblkxcg029 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG029(String BBLKXCG029);

	/**
	 * Returns the bblkxcg030 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg030 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG030();

	/**
	 * Sets the bblkxcg030 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG030 the bblkxcg030 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG030(String BBLKXCG030);

	/**
	 * Returns the bblkxcg031 of this vr technical spec_lkxcg.
	 *
	 * @return the bblkxcg031 of this vr technical spec_lkxcg
	 */
	@AutoEscape
	public String getBBLKXCG031();

	/**
	 * Sets the bblkxcg031 of this vr technical spec_lkxcg.
	 *
	 * @param BBLKXCG031 the bblkxcg031 of this vr technical spec_lkxcg
	 */
	public void setBBLKXCG031(String BBLKXCG031);

	/**
	 * Returns the modify date of this vr technical spec_lkxcg.
	 *
	 * @return the modify date of this vr technical spec_lkxcg
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_lkxcg.
	 *
	 * @param modifyDate the modify date of this vr technical spec_lkxcg
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_lkxcg.
	 *
	 * @return the sync date of this vr technical spec_lkxcg
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_lkxcg.
	 *
	 * @param syncDate the sync date of this vr technical spec_lkxcg
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_LKXCG vrTechnicalSpec_LKXCG);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_LKXCG> toCacheModel();

	@Override
	public VRTechnicalSpec_LKXCG toEscapedModel();

	@Override
	public VRTechnicalSpec_LKXCG toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}