/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_XCGPart2 service. Represents a row in the &quot;vr_technicalspec_xcg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart2ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart2Impl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XCGPart2
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart2Impl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCGPart2ModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_XCGPart2Model extends BaseModel<VRTechnicalSpec_XCGPart2> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_xcg part2 model instance should use the {@link VRTechnicalSpec_XCGPart2} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_xcg part2.
	 *
	 * @return the primary key of this vr technical spec_xcg part2
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_xcg part2.
	 *
	 * @param primaryKey the primary key of this vr technical spec_xcg part2
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_xcg part2.
	 *
	 * @return the ID of this vr technical spec_xcg part2
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_xcg part2.
	 *
	 * @param id the ID of this vr technical spec_xcg part2
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_xcg part2.
	 *
	 * @return the mt core of this vr technical spec_xcg part2
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_xcg part2.
	 *
	 * @param mtCore the mt core of this vr technical spec_xcg part2
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_xcg part2.
	 *
	 * @return the convert assemble ID of this vr technical spec_xcg part2
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_xcg part2.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_xcg part2
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_xcg part2.
	 *
	 * @return the dossier ID of this vr technical spec_xcg part2
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_xcg part2.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_xcg part2
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_xcg part2.
	 *
	 * @return the dossier no of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_xcg part2.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_xcg part2
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_xcg part2.
	 *
	 * @return the reference uid of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_xcg part2.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_xcg part2
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_xcg part2.
	 *
	 * @return the dossier ID ctn of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_xcg part2.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_xcg part2
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_xcg part2.
	 *
	 * @return the deliverable code of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_xcg part2.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_xcg part2
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_xcg part2.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_xcg part2
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_xcg part2.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_xcg part2
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the xcg01163 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01163 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01163();

	/**
	 * Sets the xcg01163 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01163 the xcg01163 of this vr technical spec_xcg part2
	 */
	public void setXCG01163(String XCG01163);

	/**
	 * Returns the xcg01164 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01164 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01164();

	/**
	 * Sets the xcg01164 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01164 the xcg01164 of this vr technical spec_xcg part2
	 */
	public void setXCG01164(String XCG01164);

	/**
	 * Returns the xcg01165 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01165 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01165();

	/**
	 * Sets the xcg01165 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01165 the xcg01165 of this vr technical spec_xcg part2
	 */
	public void setXCG01165(String XCG01165);

	/**
	 * Returns the xcg01166 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01166 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01166();

	/**
	 * Sets the xcg01166 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01166 the xcg01166 of this vr technical spec_xcg part2
	 */
	public void setXCG01166(String XCG01166);

	/**
	 * Returns the xcg01167 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01167 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01167();

	/**
	 * Sets the xcg01167 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01167 the xcg01167 of this vr technical spec_xcg part2
	 */
	public void setXCG01167(String XCG01167);

	/**
	 * Returns the xcg01169 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01169 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01169();

	/**
	 * Sets the xcg01169 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01169 the xcg01169 of this vr technical spec_xcg part2
	 */
	public void setXCG01169(String XCG01169);

	/**
	 * Returns the xcg01170 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01170 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01170();

	/**
	 * Sets the xcg01170 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01170 the xcg01170 of this vr technical spec_xcg part2
	 */
	public void setXCG01170(String XCG01170);

	/**
	 * Returns the xcg01171 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01171 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01171();

	/**
	 * Sets the xcg01171 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01171 the xcg01171 of this vr technical spec_xcg part2
	 */
	public void setXCG01171(String XCG01171);

	/**
	 * Returns the xcg01172 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01172 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01172();

	/**
	 * Sets the xcg01172 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01172 the xcg01172 of this vr technical spec_xcg part2
	 */
	public void setXCG01172(String XCG01172);

	/**
	 * Returns the xcg01173 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01173 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01173();

	/**
	 * Sets the xcg01173 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01173 the xcg01173 of this vr technical spec_xcg part2
	 */
	public void setXCG01173(String XCG01173);

	/**
	 * Returns the xcg01174 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01174 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01174();

	/**
	 * Sets the xcg01174 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01174 the xcg01174 of this vr technical spec_xcg part2
	 */
	public void setXCG01174(String XCG01174);

	/**
	 * Returns the xcg01175 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01175 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01175();

	/**
	 * Sets the xcg01175 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01175 the xcg01175 of this vr technical spec_xcg part2
	 */
	public void setXCG01175(String XCG01175);

	/**
	 * Returns the xcg01176 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01176 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01176();

	/**
	 * Sets the xcg01176 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01176 the xcg01176 of this vr technical spec_xcg part2
	 */
	public void setXCG01176(String XCG01176);

	/**
	 * Returns the xcg01177 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01177 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01177();

	/**
	 * Sets the xcg01177 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01177 the xcg01177 of this vr technical spec_xcg part2
	 */
	public void setXCG01177(String XCG01177);

	/**
	 * Returns the xcg01178 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01178 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01178();

	/**
	 * Sets the xcg01178 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01178 the xcg01178 of this vr technical spec_xcg part2
	 */
	public void setXCG01178(String XCG01178);

	/**
	 * Returns the xcg01179 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01179 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01179();

	/**
	 * Sets the xcg01179 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01179 the xcg01179 of this vr technical spec_xcg part2
	 */
	public void setXCG01179(String XCG01179);

	/**
	 * Returns the xcg01180 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01180 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01180();

	/**
	 * Sets the xcg01180 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01180 the xcg01180 of this vr technical spec_xcg part2
	 */
	public void setXCG01180(String XCG01180);

	/**
	 * Returns the xcg01181 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01181 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01181();

	/**
	 * Sets the xcg01181 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01181 the xcg01181 of this vr technical spec_xcg part2
	 */
	public void setXCG01181(String XCG01181);

	/**
	 * Returns the xcg01182 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01182 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01182();

	/**
	 * Sets the xcg01182 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01182 the xcg01182 of this vr technical spec_xcg part2
	 */
	public void setXCG01182(String XCG01182);

	/**
	 * Returns the xcg01183 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01183 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01183();

	/**
	 * Sets the xcg01183 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01183 the xcg01183 of this vr technical spec_xcg part2
	 */
	public void setXCG01183(String XCG01183);

	/**
	 * Returns the xcg01184 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01184 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01184();

	/**
	 * Sets the xcg01184 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01184 the xcg01184 of this vr technical spec_xcg part2
	 */
	public void setXCG01184(String XCG01184);

	/**
	 * Returns the xcg01185 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01185 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01185();

	/**
	 * Sets the xcg01185 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01185 the xcg01185 of this vr technical spec_xcg part2
	 */
	public void setXCG01185(String XCG01185);

	/**
	 * Returns the xcg01186 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01186 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01186();

	/**
	 * Sets the xcg01186 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01186 the xcg01186 of this vr technical spec_xcg part2
	 */
	public void setXCG01186(String XCG01186);

	/**
	 * Returns the xcg01187 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01187 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01187();

	/**
	 * Sets the xcg01187 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01187 the xcg01187 of this vr technical spec_xcg part2
	 */
	public void setXCG01187(String XCG01187);

	/**
	 * Returns the xcg01188 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01188 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01188();

	/**
	 * Sets the xcg01188 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01188 the xcg01188 of this vr technical spec_xcg part2
	 */
	public void setXCG01188(String XCG01188);

	/**
	 * Returns the xcg01189 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01189 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01189();

	/**
	 * Sets the xcg01189 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01189 the xcg01189 of this vr technical spec_xcg part2
	 */
	public void setXCG01189(String XCG01189);

	/**
	 * Returns the xcg01190 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01190 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01190();

	/**
	 * Sets the xcg01190 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01190 the xcg01190 of this vr technical spec_xcg part2
	 */
	public void setXCG01190(String XCG01190);

	/**
	 * Returns the xcg01191 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01191 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01191();

	/**
	 * Sets the xcg01191 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01191 the xcg01191 of this vr technical spec_xcg part2
	 */
	public void setXCG01191(String XCG01191);

	/**
	 * Returns the xcg01192 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01192 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01192();

	/**
	 * Sets the xcg01192 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01192 the xcg01192 of this vr technical spec_xcg part2
	 */
	public void setXCG01192(String XCG01192);

	/**
	 * Returns the xcg01193 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01193 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01193();

	/**
	 * Sets the xcg01193 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01193 the xcg01193 of this vr technical spec_xcg part2
	 */
	public void setXCG01193(String XCG01193);

	/**
	 * Returns the xcg01194 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01194 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01194();

	/**
	 * Sets the xcg01194 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01194 the xcg01194 of this vr technical spec_xcg part2
	 */
	public void setXCG01194(String XCG01194);

	/**
	 * Returns the xcg01195 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01195 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01195();

	/**
	 * Sets the xcg01195 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01195 the xcg01195 of this vr technical spec_xcg part2
	 */
	public void setXCG01195(String XCG01195);

	/**
	 * Returns the xcg01196 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01196 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01196();

	/**
	 * Sets the xcg01196 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01196 the xcg01196 of this vr technical spec_xcg part2
	 */
	public void setXCG01196(String XCG01196);

	/**
	 * Returns the xcg01197 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01197 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01197();

	/**
	 * Sets the xcg01197 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01197 the xcg01197 of this vr technical spec_xcg part2
	 */
	public void setXCG01197(String XCG01197);

	/**
	 * Returns the xcg01198 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01198 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01198();

	/**
	 * Sets the xcg01198 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01198 the xcg01198 of this vr technical spec_xcg part2
	 */
	public void setXCG01198(String XCG01198);

	/**
	 * Returns the xcg01199 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01199 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01199();

	/**
	 * Sets the xcg01199 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01199 the xcg01199 of this vr technical spec_xcg part2
	 */
	public void setXCG01199(String XCG01199);

	/**
	 * Returns the xcg01200 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01200 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01200();

	/**
	 * Sets the xcg01200 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01200 the xcg01200 of this vr technical spec_xcg part2
	 */
	public void setXCG01200(String XCG01200);

	/**
	 * Returns the xcg01202 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01202 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01202();

	/**
	 * Sets the xcg01202 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01202 the xcg01202 of this vr technical spec_xcg part2
	 */
	public void setXCG01202(String XCG01202);

	/**
	 * Returns the xcg01203 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01203 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01203();

	/**
	 * Sets the xcg01203 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01203 the xcg01203 of this vr technical spec_xcg part2
	 */
	public void setXCG01203(String XCG01203);

	/**
	 * Returns the xcg01204 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01204 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01204();

	/**
	 * Sets the xcg01204 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01204 the xcg01204 of this vr technical spec_xcg part2
	 */
	public void setXCG01204(String XCG01204);

	/**
	 * Returns the xcg01205 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01205 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01205();

	/**
	 * Sets the xcg01205 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01205 the xcg01205 of this vr technical spec_xcg part2
	 */
	public void setXCG01205(String XCG01205);

	/**
	 * Returns the xcg01206 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01206 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01206();

	/**
	 * Sets the xcg01206 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01206 the xcg01206 of this vr technical spec_xcg part2
	 */
	public void setXCG01206(String XCG01206);

	/**
	 * Returns the xcg01207 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01207 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01207();

	/**
	 * Sets the xcg01207 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01207 the xcg01207 of this vr technical spec_xcg part2
	 */
	public void setXCG01207(String XCG01207);

	/**
	 * Returns the xcg01208 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01208 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01208();

	/**
	 * Sets the xcg01208 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01208 the xcg01208 of this vr technical spec_xcg part2
	 */
	public void setXCG01208(String XCG01208);

	/**
	 * Returns the xcg01209 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01209 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01209();

	/**
	 * Sets the xcg01209 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01209 the xcg01209 of this vr technical spec_xcg part2
	 */
	public void setXCG01209(String XCG01209);

	/**
	 * Returns the xcg01210 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01210 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01210();

	/**
	 * Sets the xcg01210 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01210 the xcg01210 of this vr technical spec_xcg part2
	 */
	public void setXCG01210(String XCG01210);

	/**
	 * Returns the xcg01212 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01212 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01212();

	/**
	 * Sets the xcg01212 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01212 the xcg01212 of this vr technical spec_xcg part2
	 */
	public void setXCG01212(String XCG01212);

	/**
	 * Returns the xcg01213 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01213 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01213();

	/**
	 * Sets the xcg01213 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01213 the xcg01213 of this vr technical spec_xcg part2
	 */
	public void setXCG01213(String XCG01213);

	/**
	 * Returns the xcg01214 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01214 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01214();

	/**
	 * Sets the xcg01214 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01214 the xcg01214 of this vr technical spec_xcg part2
	 */
	public void setXCG01214(String XCG01214);

	/**
	 * Returns the xcg01215 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01215 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01215();

	/**
	 * Sets the xcg01215 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01215 the xcg01215 of this vr technical spec_xcg part2
	 */
	public void setXCG01215(String XCG01215);

	/**
	 * Returns the xcg01216 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01216 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01216();

	/**
	 * Sets the xcg01216 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01216 the xcg01216 of this vr technical spec_xcg part2
	 */
	public void setXCG01216(String XCG01216);

	/**
	 * Returns the xcg01217 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01217 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01217();

	/**
	 * Sets the xcg01217 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01217 the xcg01217 of this vr technical spec_xcg part2
	 */
	public void setXCG01217(String XCG01217);

	/**
	 * Returns the xcg01218 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01218 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01218();

	/**
	 * Sets the xcg01218 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01218 the xcg01218 of this vr technical spec_xcg part2
	 */
	public void setXCG01218(String XCG01218);

	/**
	 * Returns the xcg01219 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01219 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01219();

	/**
	 * Sets the xcg01219 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01219 the xcg01219 of this vr technical spec_xcg part2
	 */
	public void setXCG01219(String XCG01219);

	/**
	 * Returns the xcg01220 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01220 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01220();

	/**
	 * Sets the xcg01220 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01220 the xcg01220 of this vr technical spec_xcg part2
	 */
	public void setXCG01220(String XCG01220);

	/**
	 * Returns the xcg01221 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01221 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01221();

	/**
	 * Sets the xcg01221 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01221 the xcg01221 of this vr technical spec_xcg part2
	 */
	public void setXCG01221(String XCG01221);

	/**
	 * Returns the xcg01222 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01222 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01222();

	/**
	 * Sets the xcg01222 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01222 the xcg01222 of this vr technical spec_xcg part2
	 */
	public void setXCG01222(String XCG01222);

	/**
	 * Returns the xcg01223 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01223 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01223();

	/**
	 * Sets the xcg01223 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01223 the xcg01223 of this vr technical spec_xcg part2
	 */
	public void setXCG01223(String XCG01223);

	/**
	 * Returns the xcg01224 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01224 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01224();

	/**
	 * Sets the xcg01224 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01224 the xcg01224 of this vr technical spec_xcg part2
	 */
	public void setXCG01224(String XCG01224);

	/**
	 * Returns the xcg01225 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01225 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01225();

	/**
	 * Sets the xcg01225 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01225 the xcg01225 of this vr technical spec_xcg part2
	 */
	public void setXCG01225(String XCG01225);

	/**
	 * Returns the xcg01226 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01226 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01226();

	/**
	 * Sets the xcg01226 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01226 the xcg01226 of this vr technical spec_xcg part2
	 */
	public void setXCG01226(String XCG01226);

	/**
	 * Returns the xcg01228 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01228 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01228();

	/**
	 * Sets the xcg01228 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01228 the xcg01228 of this vr technical spec_xcg part2
	 */
	public void setXCG01228(String XCG01228);

	/**
	 * Returns the xcg01230 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01230 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01230();

	/**
	 * Sets the xcg01230 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01230 the xcg01230 of this vr technical spec_xcg part2
	 */
	public void setXCG01230(String XCG01230);

	/**
	 * Returns the xcg01231 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01231 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01231();

	/**
	 * Sets the xcg01231 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01231 the xcg01231 of this vr technical spec_xcg part2
	 */
	public void setXCG01231(String XCG01231);

	/**
	 * Returns the xcg01232 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01232 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01232();

	/**
	 * Sets the xcg01232 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01232 the xcg01232 of this vr technical spec_xcg part2
	 */
	public void setXCG01232(String XCG01232);

	/**
	 * Returns the xcg01234 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01234 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01234();

	/**
	 * Sets the xcg01234 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01234 the xcg01234 of this vr technical spec_xcg part2
	 */
	public void setXCG01234(String XCG01234);

	/**
	 * Returns the xcg01236 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01236 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01236();

	/**
	 * Sets the xcg01236 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01236 the xcg01236 of this vr technical spec_xcg part2
	 */
	public void setXCG01236(String XCG01236);

	/**
	 * Returns the xcg01237 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01237 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01237();

	/**
	 * Sets the xcg01237 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01237 the xcg01237 of this vr technical spec_xcg part2
	 */
	public void setXCG01237(String XCG01237);

	/**
	 * Returns the xcg01229 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01229 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01229();

	/**
	 * Sets the xcg01229 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01229 the xcg01229 of this vr technical spec_xcg part2
	 */
	public void setXCG01229(String XCG01229);

	/**
	 * Returns the xcg01238 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01238 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01238();

	/**
	 * Sets the xcg01238 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01238 the xcg01238 of this vr technical spec_xcg part2
	 */
	public void setXCG01238(String XCG01238);

	/**
	 * Returns the xcg01239 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01239 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01239();

	/**
	 * Sets the xcg01239 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01239 the xcg01239 of this vr technical spec_xcg part2
	 */
	public void setXCG01239(String XCG01239);

	/**
	 * Returns the xcg01240 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01240 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01240();

	/**
	 * Sets the xcg01240 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01240 the xcg01240 of this vr technical spec_xcg part2
	 */
	public void setXCG01240(String XCG01240);

	/**
	 * Returns the xcg01241 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01241 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01241();

	/**
	 * Sets the xcg01241 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01241 the xcg01241 of this vr technical spec_xcg part2
	 */
	public void setXCG01241(String XCG01241);

	/**
	 * Returns the xcg01242 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01242 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01242();

	/**
	 * Sets the xcg01242 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01242 the xcg01242 of this vr technical spec_xcg part2
	 */
	public void setXCG01242(String XCG01242);

	/**
	 * Returns the xcg01243 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01243 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01243();

	/**
	 * Sets the xcg01243 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01243 the xcg01243 of this vr technical spec_xcg part2
	 */
	public void setXCG01243(String XCG01243);

	/**
	 * Returns the xcg01235 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01235 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01235();

	/**
	 * Sets the xcg01235 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01235 the xcg01235 of this vr technical spec_xcg part2
	 */
	public void setXCG01235(String XCG01235);

	/**
	 * Returns the xcg01244 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01244 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01244();

	/**
	 * Sets the xcg01244 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01244 the xcg01244 of this vr technical spec_xcg part2
	 */
	public void setXCG01244(String XCG01244);

	/**
	 * Returns the xcg01245 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01245 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01245();

	/**
	 * Sets the xcg01245 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01245 the xcg01245 of this vr technical spec_xcg part2
	 */
	public void setXCG01245(String XCG01245);

	/**
	 * Returns the xcg01246 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01246 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01246();

	/**
	 * Sets the xcg01246 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01246 the xcg01246 of this vr technical spec_xcg part2
	 */
	public void setXCG01246(String XCG01246);

	/**
	 * Returns the xcg01247 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01247 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01247();

	/**
	 * Sets the xcg01247 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01247 the xcg01247 of this vr technical spec_xcg part2
	 */
	public void setXCG01247(String XCG01247);

	/**
	 * Returns the xcg01248 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01248 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01248();

	/**
	 * Sets the xcg01248 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01248 the xcg01248 of this vr technical spec_xcg part2
	 */
	public void setXCG01248(String XCG01248);

	/**
	 * Returns the xcg01249 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01249 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01249();

	/**
	 * Sets the xcg01249 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01249 the xcg01249 of this vr technical spec_xcg part2
	 */
	public void setXCG01249(String XCG01249);

	/**
	 * Returns the xcg11248 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg11248 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG11248();

	/**
	 * Sets the xcg11248 of this vr technical spec_xcg part2.
	 *
	 * @param XCG11248 the xcg11248 of this vr technical spec_xcg part2
	 */
	public void setXCG11248(String XCG11248);

	/**
	 * Returns the xcg11249 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg11249 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG11249();

	/**
	 * Sets the xcg11249 of this vr technical spec_xcg part2.
	 *
	 * @param XCG11249 the xcg11249 of this vr technical spec_xcg part2
	 */
	public void setXCG11249(String XCG11249);

	/**
	 * Returns the xcg01250 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01250 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01250();

	/**
	 * Sets the xcg01250 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01250 the xcg01250 of this vr technical spec_xcg part2
	 */
	public void setXCG01250(String XCG01250);

	/**
	 * Returns the xcg01251 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01251 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01251();

	/**
	 * Sets the xcg01251 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01251 the xcg01251 of this vr technical spec_xcg part2
	 */
	public void setXCG01251(String XCG01251);

	/**
	 * Returns the xcg01252 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01252 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01252();

	/**
	 * Sets the xcg01252 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01252 the xcg01252 of this vr technical spec_xcg part2
	 */
	public void setXCG01252(String XCG01252);

	/**
	 * Returns the xcg01253 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01253 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01253();

	/**
	 * Sets the xcg01253 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01253 the xcg01253 of this vr technical spec_xcg part2
	 */
	public void setXCG01253(String XCG01253);

	/**
	 * Returns the xcg01255 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01255 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01255();

	/**
	 * Sets the xcg01255 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01255 the xcg01255 of this vr technical spec_xcg part2
	 */
	public void setXCG01255(String XCG01255);

	/**
	 * Returns the xcg01256 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01256 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01256();

	/**
	 * Sets the xcg01256 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01256 the xcg01256 of this vr technical spec_xcg part2
	 */
	public void setXCG01256(String XCG01256);

	/**
	 * Returns the xcg01257 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01257 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01257();

	/**
	 * Sets the xcg01257 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01257 the xcg01257 of this vr technical spec_xcg part2
	 */
	public void setXCG01257(String XCG01257);

	/**
	 * Returns the xcg01258 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01258 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01258();

	/**
	 * Sets the xcg01258 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01258 the xcg01258 of this vr technical spec_xcg part2
	 */
	public void setXCG01258(String XCG01258);

	/**
	 * Returns the xcg01259 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01259 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01259();

	/**
	 * Sets the xcg01259 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01259 the xcg01259 of this vr technical spec_xcg part2
	 */
	public void setXCG01259(String XCG01259);

	/**
	 * Returns the xcg01260 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01260 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01260();

	/**
	 * Sets the xcg01260 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01260 the xcg01260 of this vr technical spec_xcg part2
	 */
	public void setXCG01260(String XCG01260);

	/**
	 * Returns the xcg01261 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01261 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01261();

	/**
	 * Sets the xcg01261 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01261 the xcg01261 of this vr technical spec_xcg part2
	 */
	public void setXCG01261(String XCG01261);

	/**
	 * Returns the xcg01262 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01262 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01262();

	/**
	 * Sets the xcg01262 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01262 the xcg01262 of this vr technical spec_xcg part2
	 */
	public void setXCG01262(String XCG01262);

	/**
	 * Returns the xcg11253 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg11253 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG11253();

	/**
	 * Sets the xcg11253 of this vr technical spec_xcg part2.
	 *
	 * @param XCG11253 the xcg11253 of this vr technical spec_xcg part2
	 */
	public void setXCG11253(String XCG11253);

	/**
	 * Returns the xcg01263 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01263 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01263();

	/**
	 * Sets the xcg01263 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01263 the xcg01263 of this vr technical spec_xcg part2
	 */
	public void setXCG01263(String XCG01263);

	/**
	 * Returns the xcg01264 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01264 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01264();

	/**
	 * Sets the xcg01264 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01264 the xcg01264 of this vr technical spec_xcg part2
	 */
	public void setXCG01264(String XCG01264);

	/**
	 * Returns the xcg01265 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01265 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01265();

	/**
	 * Sets the xcg01265 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01265 the xcg01265 of this vr technical spec_xcg part2
	 */
	public void setXCG01265(String XCG01265);

	/**
	 * Returns the xcg01266 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01266 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01266();

	/**
	 * Sets the xcg01266 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01266 the xcg01266 of this vr technical spec_xcg part2
	 */
	public void setXCG01266(String XCG01266);

	/**
	 * Returns the xcg01901 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01901 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01901();

	/**
	 * Sets the xcg01901 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01901 the xcg01901 of this vr technical spec_xcg part2
	 */
	public void setXCG01901(String XCG01901);

	/**
	 * Returns the xcg01267 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01267 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01267();

	/**
	 * Sets the xcg01267 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01267 the xcg01267 of this vr technical spec_xcg part2
	 */
	public void setXCG01267(String XCG01267);

	/**
	 * Returns the xcg01902 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01902 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01902();

	/**
	 * Sets the xcg01902 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01902 the xcg01902 of this vr technical spec_xcg part2
	 */
	public void setXCG01902(String XCG01902);

	/**
	 * Returns the xcg01268 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01268 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01268();

	/**
	 * Sets the xcg01268 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01268 the xcg01268 of this vr technical spec_xcg part2
	 */
	public void setXCG01268(String XCG01268);

	/**
	 * Returns the xcg01269 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01269 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01269();

	/**
	 * Sets the xcg01269 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01269 the xcg01269 of this vr technical spec_xcg part2
	 */
	public void setXCG01269(String XCG01269);

	/**
	 * Returns the xcg01903 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01903 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01903();

	/**
	 * Sets the xcg01903 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01903 the xcg01903 of this vr technical spec_xcg part2
	 */
	public void setXCG01903(String XCG01903);

	/**
	 * Returns the xcg01270 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01270 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01270();

	/**
	 * Sets the xcg01270 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01270 the xcg01270 of this vr technical spec_xcg part2
	 */
	public void setXCG01270(String XCG01270);

	/**
	 * Returns the xcg01271 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01271 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01271();

	/**
	 * Sets the xcg01271 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01271 the xcg01271 of this vr technical spec_xcg part2
	 */
	public void setXCG01271(String XCG01271);

	/**
	 * Returns the xcg01273 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01273 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01273();

	/**
	 * Sets the xcg01273 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01273 the xcg01273 of this vr technical spec_xcg part2
	 */
	public void setXCG01273(String XCG01273);

	/**
	 * Returns the xcg01274 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01274 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01274();

	/**
	 * Sets the xcg01274 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01274 the xcg01274 of this vr technical spec_xcg part2
	 */
	public void setXCG01274(String XCG01274);

	/**
	 * Returns the xcg01275 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01275 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01275();

	/**
	 * Sets the xcg01275 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01275 the xcg01275 of this vr technical spec_xcg part2
	 */
	public void setXCG01275(String XCG01275);

	/**
	 * Returns the xcg01276 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01276 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01276();

	/**
	 * Sets the xcg01276 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01276 the xcg01276 of this vr technical spec_xcg part2
	 */
	public void setXCG01276(String XCG01276);

	/**
	 * Returns the xcg01277 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01277 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01277();

	/**
	 * Sets the xcg01277 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01277 the xcg01277 of this vr technical spec_xcg part2
	 */
	public void setXCG01277(String XCG01277);

	/**
	 * Returns the xcg01278 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01278 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01278();

	/**
	 * Sets the xcg01278 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01278 the xcg01278 of this vr technical spec_xcg part2
	 */
	public void setXCG01278(String XCG01278);

	/**
	 * Returns the xcg01279 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01279 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01279();

	/**
	 * Sets the xcg01279 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01279 the xcg01279 of this vr technical spec_xcg part2
	 */
	public void setXCG01279(String XCG01279);

	/**
	 * Returns the xcg01280 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01280 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01280();

	/**
	 * Sets the xcg01280 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01280 the xcg01280 of this vr technical spec_xcg part2
	 */
	public void setXCG01280(String XCG01280);

	/**
	 * Returns the xcg01281 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01281 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01281();

	/**
	 * Sets the xcg01281 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01281 the xcg01281 of this vr technical spec_xcg part2
	 */
	public void setXCG01281(String XCG01281);

	/**
	 * Returns the xcg01282 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01282 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01282();

	/**
	 * Sets the xcg01282 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01282 the xcg01282 of this vr technical spec_xcg part2
	 */
	public void setXCG01282(String XCG01282);

	/**
	 * Returns the xcg01283 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01283 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01283();

	/**
	 * Sets the xcg01283 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01283 the xcg01283 of this vr technical spec_xcg part2
	 */
	public void setXCG01283(String XCG01283);

	/**
	 * Returns the xcg01284 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01284 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01284();

	/**
	 * Sets the xcg01284 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01284 the xcg01284 of this vr technical spec_xcg part2
	 */
	public void setXCG01284(String XCG01284);

	/**
	 * Returns the xcg01285 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01285 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01285();

	/**
	 * Sets the xcg01285 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01285 the xcg01285 of this vr technical spec_xcg part2
	 */
	public void setXCG01285(String XCG01285);

	/**
	 * Returns the xcg01286 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01286 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01286();

	/**
	 * Sets the xcg01286 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01286 the xcg01286 of this vr technical spec_xcg part2
	 */
	public void setXCG01286(String XCG01286);

	/**
	 * Returns the xcg01287 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01287 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01287();

	/**
	 * Sets the xcg01287 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01287 the xcg01287 of this vr technical spec_xcg part2
	 */
	public void setXCG01287(String XCG01287);

	/**
	 * Returns the xcg01288 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01288 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01288();

	/**
	 * Sets the xcg01288 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01288 the xcg01288 of this vr technical spec_xcg part2
	 */
	public void setXCG01288(String XCG01288);

	/**
	 * Returns the xcg01289 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01289 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01289();

	/**
	 * Sets the xcg01289 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01289 the xcg01289 of this vr technical spec_xcg part2
	 */
	public void setXCG01289(String XCG01289);

	/**
	 * Returns the xcg01290 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01290 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01290();

	/**
	 * Sets the xcg01290 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01290 the xcg01290 of this vr technical spec_xcg part2
	 */
	public void setXCG01290(String XCG01290);

	/**
	 * Returns the xcg01291 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01291 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01291();

	/**
	 * Sets the xcg01291 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01291 the xcg01291 of this vr technical spec_xcg part2
	 */
	public void setXCG01291(String XCG01291);

	/**
	 * Returns the xcg01292 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01292 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01292();

	/**
	 * Sets the xcg01292 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01292 the xcg01292 of this vr technical spec_xcg part2
	 */
	public void setXCG01292(String XCG01292);

	/**
	 * Returns the xcg01293 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01293 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01293();

	/**
	 * Sets the xcg01293 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01293 the xcg01293 of this vr technical spec_xcg part2
	 */
	public void setXCG01293(String XCG01293);

	/**
	 * Returns the xcg01294 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01294 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01294();

	/**
	 * Sets the xcg01294 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01294 the xcg01294 of this vr technical spec_xcg part2
	 */
	public void setXCG01294(String XCG01294);

	/**
	 * Returns the xcg01295 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01295 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01295();

	/**
	 * Sets the xcg01295 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01295 the xcg01295 of this vr technical spec_xcg part2
	 */
	public void setXCG01295(String XCG01295);

	/**
	 * Returns the xcg01296 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01296 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01296();

	/**
	 * Sets the xcg01296 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01296 the xcg01296 of this vr technical spec_xcg part2
	 */
	public void setXCG01296(String XCG01296);

	/**
	 * Returns the xcg01297 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01297 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01297();

	/**
	 * Sets the xcg01297 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01297 the xcg01297 of this vr technical spec_xcg part2
	 */
	public void setXCG01297(String XCG01297);

	/**
	 * Returns the xcg01298 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01298 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01298();

	/**
	 * Sets the xcg01298 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01298 the xcg01298 of this vr technical spec_xcg part2
	 */
	public void setXCG01298(String XCG01298);

	/**
	 * Returns the xcg01300 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01300 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01300();

	/**
	 * Sets the xcg01300 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01300 the xcg01300 of this vr technical spec_xcg part2
	 */
	public void setXCG01300(String XCG01300);

	/**
	 * Returns the xcg01301 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01301 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01301();

	/**
	 * Sets the xcg01301 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01301 the xcg01301 of this vr technical spec_xcg part2
	 */
	public void setXCG01301(String XCG01301);

	/**
	 * Returns the xcg01302 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01302 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01302();

	/**
	 * Sets the xcg01302 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01302 the xcg01302 of this vr technical spec_xcg part2
	 */
	public void setXCG01302(String XCG01302);

	/**
	 * Returns the xcg01303 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01303 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01303();

	/**
	 * Sets the xcg01303 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01303 the xcg01303 of this vr technical spec_xcg part2
	 */
	public void setXCG01303(String XCG01303);

	/**
	 * Returns the xcg01304 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01304 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01304();

	/**
	 * Sets the xcg01304 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01304 the xcg01304 of this vr technical spec_xcg part2
	 */
	public void setXCG01304(String XCG01304);

	/**
	 * Returns the xcg01305 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01305 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01305();

	/**
	 * Sets the xcg01305 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01305 the xcg01305 of this vr technical spec_xcg part2
	 */
	public void setXCG01305(String XCG01305);

	/**
	 * Returns the xcg01306 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01306 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01306();

	/**
	 * Sets the xcg01306 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01306 the xcg01306 of this vr technical spec_xcg part2
	 */
	public void setXCG01306(String XCG01306);

	/**
	 * Returns the xcg01307 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01307 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01307();

	/**
	 * Sets the xcg01307 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01307 the xcg01307 of this vr technical spec_xcg part2
	 */
	public void setXCG01307(String XCG01307);

	/**
	 * Returns the xcg01308 of this vr technical spec_xcg part2.
	 *
	 * @return the xcg01308 of this vr technical spec_xcg part2
	 */
	@AutoEscape
	public String getXCG01308();

	/**
	 * Sets the xcg01308 of this vr technical spec_xcg part2.
	 *
	 * @param XCG01308 the xcg01308 of this vr technical spec_xcg part2
	 */
	public void setXCG01308(String XCG01308);

	/**
	 * Returns the modify date of this vr technical spec_xcg part2.
	 *
	 * @return the modify date of this vr technical spec_xcg part2
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_xcg part2.
	 *
	 * @param modifyDate the modify date of this vr technical spec_xcg part2
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_xcg part2.
	 *
	 * @return the sync date of this vr technical spec_xcg part2
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_xcg part2.
	 *
	 * @param syncDate the sync date of this vr technical spec_xcg part2
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_XCGPart2 vrTechnicalSpec_XCGPart2);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_XCGPart2> toCacheModel();

	@Override
	public VRTechnicalSpec_XCGPart2 toEscapedModel();

	@Override
	public VRTechnicalSpec_XCGPart2 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}