/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_XMY service. Represents a row in the &quot;vr_technicalspec_xmy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XMYModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XMYImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XMY
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XMYImpl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XMYModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_XMYModel extends BaseModel<VRTechnicalSpec_XMY> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_xmy model instance should use the {@link VRTechnicalSpec_XMY} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_xmy.
	 *
	 * @return the primary key of this vr technical spec_xmy
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_xmy.
	 *
	 * @param primaryKey the primary key of this vr technical spec_xmy
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_xmy.
	 *
	 * @return the ID of this vr technical spec_xmy
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_xmy.
	 *
	 * @param id the ID of this vr technical spec_xmy
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_xmy.
	 *
	 * @return the mt core of this vr technical spec_xmy
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_xmy.
	 *
	 * @param mtCore the mt core of this vr technical spec_xmy
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_xmy.
	 *
	 * @return the convert assemble ID of this vr technical spec_xmy
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_xmy.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_xmy
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_xmy.
	 *
	 * @return the dossier ID of this vr technical spec_xmy
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_xmy.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_xmy
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_xmy.
	 *
	 * @return the dossier no of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_xmy.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_xmy
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_xmy.
	 *
	 * @return the reference uid of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_xmy.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_xmy
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_xmy.
	 *
	 * @return the dossier ID ctn of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_xmy.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_xmy
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_xmy.
	 *
	 * @return the deliverable code of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_xmy.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_xmy
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_xmy.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_xmy
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_xmy.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_xmy
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the loai_dong_co of this vr technical spec_xmy.
	 *
	 * @return the loai_dong_co of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getLoai_dong_co();

	/**
	 * Sets the loai_dong_co of this vr technical spec_xmy.
	 *
	 * @param loai_dong_co the loai_dong_co of this vr technical spec_xmy
	 */
	public void setLoai_dong_co(String loai_dong_co);

	/**
	 * Returns the xmy01001 of this vr technical spec_xmy.
	 *
	 * @return the xmy01001 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01001();

	/**
	 * Sets the xmy01001 of this vr technical spec_xmy.
	 *
	 * @param XMY01001 the xmy01001 of this vr technical spec_xmy
	 */
	public void setXMY01001(String XMY01001);

	/**
	 * Returns the xmy01002 of this vr technical spec_xmy.
	 *
	 * @return the xmy01002 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01002();

	/**
	 * Sets the xmy01002 of this vr technical spec_xmy.
	 *
	 * @param XMY01002 the xmy01002 of this vr technical spec_xmy
	 */
	public void setXMY01002(String XMY01002);

	/**
	 * Returns the xmy01003 of this vr technical spec_xmy.
	 *
	 * @return the xmy01003 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01003();

	/**
	 * Sets the xmy01003 of this vr technical spec_xmy.
	 *
	 * @param XMY01003 the xmy01003 of this vr technical spec_xmy
	 */
	public void setXMY01003(String XMY01003);

	/**
	 * Returns the xmy01004 of this vr technical spec_xmy.
	 *
	 * @return the xmy01004 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01004();

	/**
	 * Sets the xmy01004 of this vr technical spec_xmy.
	 *
	 * @param XMY01004 the xmy01004 of this vr technical spec_xmy
	 */
	public void setXMY01004(String XMY01004);

	/**
	 * Returns the xmy01005 of this vr technical spec_xmy.
	 *
	 * @return the xmy01005 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01005();

	/**
	 * Sets the xmy01005 of this vr technical spec_xmy.
	 *
	 * @param XMY01005 the xmy01005 of this vr technical spec_xmy
	 */
	public void setXMY01005(String XMY01005);

	/**
	 * Returns the xmy01006 of this vr technical spec_xmy.
	 *
	 * @return the xmy01006 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01006();

	/**
	 * Sets the xmy01006 of this vr technical spec_xmy.
	 *
	 * @param XMY01006 the xmy01006 of this vr technical spec_xmy
	 */
	public void setXMY01006(String XMY01006);

	/**
	 * Returns the xmy01007 of this vr technical spec_xmy.
	 *
	 * @return the xmy01007 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01007();

	/**
	 * Sets the xmy01007 of this vr technical spec_xmy.
	 *
	 * @param XMY01007 the xmy01007 of this vr technical spec_xmy
	 */
	public void setXMY01007(String XMY01007);

	/**
	 * Returns the xmy01008 of this vr technical spec_xmy.
	 *
	 * @return the xmy01008 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01008();

	/**
	 * Sets the xmy01008 of this vr technical spec_xmy.
	 *
	 * @param XMY01008 the xmy01008 of this vr technical spec_xmy
	 */
	public void setXMY01008(String XMY01008);

	/**
	 * Returns the xmy01009 of this vr technical spec_xmy.
	 *
	 * @return the xmy01009 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01009();

	/**
	 * Sets the xmy01009 of this vr technical spec_xmy.
	 *
	 * @param XMY01009 the xmy01009 of this vr technical spec_xmy
	 */
	public void setXMY01009(String XMY01009);

	/**
	 * Returns the xmy01010 of this vr technical spec_xmy.
	 *
	 * @return the xmy01010 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01010();

	/**
	 * Sets the xmy01010 of this vr technical spec_xmy.
	 *
	 * @param XMY01010 the xmy01010 of this vr technical spec_xmy
	 */
	public void setXMY01010(String XMY01010);

	/**
	 * Returns the xmy01011 of this vr technical spec_xmy.
	 *
	 * @return the xmy01011 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01011();

	/**
	 * Sets the xmy01011 of this vr technical spec_xmy.
	 *
	 * @param XMY01011 the xmy01011 of this vr technical spec_xmy
	 */
	public void setXMY01011(String XMY01011);

	/**
	 * Returns the xmy01012 of this vr technical spec_xmy.
	 *
	 * @return the xmy01012 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01012();

	/**
	 * Sets the xmy01012 of this vr technical spec_xmy.
	 *
	 * @param XMY01012 the xmy01012 of this vr technical spec_xmy
	 */
	public void setXMY01012(String XMY01012);

	/**
	 * Returns the xmy01013 of this vr technical spec_xmy.
	 *
	 * @return the xmy01013 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01013();

	/**
	 * Sets the xmy01013 of this vr technical spec_xmy.
	 *
	 * @param XMY01013 the xmy01013 of this vr technical spec_xmy
	 */
	public void setXMY01013(String XMY01013);

	/**
	 * Returns the xmy01014 of this vr technical spec_xmy.
	 *
	 * @return the xmy01014 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01014();

	/**
	 * Sets the xmy01014 of this vr technical spec_xmy.
	 *
	 * @param XMY01014 the xmy01014 of this vr technical spec_xmy
	 */
	public void setXMY01014(String XMY01014);

	/**
	 * Returns the xmy01016 of this vr technical spec_xmy.
	 *
	 * @return the xmy01016 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01016();

	/**
	 * Sets the xmy01016 of this vr technical spec_xmy.
	 *
	 * @param XMY01016 the xmy01016 of this vr technical spec_xmy
	 */
	public void setXMY01016(String XMY01016);

	/**
	 * Returns the xmy01017 of this vr technical spec_xmy.
	 *
	 * @return the xmy01017 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01017();

	/**
	 * Sets the xmy01017 of this vr technical spec_xmy.
	 *
	 * @param XMY01017 the xmy01017 of this vr technical spec_xmy
	 */
	public void setXMY01017(String XMY01017);

	/**
	 * Returns the xmy01019 of this vr technical spec_xmy.
	 *
	 * @return the xmy01019 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01019();

	/**
	 * Sets the xmy01019 of this vr technical spec_xmy.
	 *
	 * @param XMY01019 the xmy01019 of this vr technical spec_xmy
	 */
	public void setXMY01019(String XMY01019);

	/**
	 * Returns the xmy01020 of this vr technical spec_xmy.
	 *
	 * @return the xmy01020 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01020();

	/**
	 * Sets the xmy01020 of this vr technical spec_xmy.
	 *
	 * @param XMY01020 the xmy01020 of this vr technical spec_xmy
	 */
	public void setXMY01020(String XMY01020);

	/**
	 * Returns the xmy01021 of this vr technical spec_xmy.
	 *
	 * @return the xmy01021 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01021();

	/**
	 * Sets the xmy01021 of this vr technical spec_xmy.
	 *
	 * @param XMY01021 the xmy01021 of this vr technical spec_xmy
	 */
	public void setXMY01021(String XMY01021);

	/**
	 * Returns the xmy01022 of this vr technical spec_xmy.
	 *
	 * @return the xmy01022 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01022();

	/**
	 * Sets the xmy01022 of this vr technical spec_xmy.
	 *
	 * @param XMY01022 the xmy01022 of this vr technical spec_xmy
	 */
	public void setXMY01022(String XMY01022);

	/**
	 * Returns the xmy01030 of this vr technical spec_xmy.
	 *
	 * @return the xmy01030 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01030();

	/**
	 * Sets the xmy01030 of this vr technical spec_xmy.
	 *
	 * @param XMY01030 the xmy01030 of this vr technical spec_xmy
	 */
	public void setXMY01030(String XMY01030);

	/**
	 * Returns the xmy01031 of this vr technical spec_xmy.
	 *
	 * @return the xmy01031 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01031();

	/**
	 * Sets the xmy01031 of this vr technical spec_xmy.
	 *
	 * @param XMY01031 the xmy01031 of this vr technical spec_xmy
	 */
	public void setXMY01031(String XMY01031);

	/**
	 * Returns the xmy01032 of this vr technical spec_xmy.
	 *
	 * @return the xmy01032 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01032();

	/**
	 * Sets the xmy01032 of this vr technical spec_xmy.
	 *
	 * @param XMY01032 the xmy01032 of this vr technical spec_xmy
	 */
	public void setXMY01032(String XMY01032);

	/**
	 * Returns the xmy01033 of this vr technical spec_xmy.
	 *
	 * @return the xmy01033 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01033();

	/**
	 * Sets the xmy01033 of this vr technical spec_xmy.
	 *
	 * @param XMY01033 the xmy01033 of this vr technical spec_xmy
	 */
	public void setXMY01033(String XMY01033);

	/**
	 * Returns the xmy01034 of this vr technical spec_xmy.
	 *
	 * @return the xmy01034 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01034();

	/**
	 * Sets the xmy01034 of this vr technical spec_xmy.
	 *
	 * @param XMY01034 the xmy01034 of this vr technical spec_xmy
	 */
	public void setXMY01034(String XMY01034);

	/**
	 * Returns the xmy01035 of this vr technical spec_xmy.
	 *
	 * @return the xmy01035 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01035();

	/**
	 * Sets the xmy01035 of this vr technical spec_xmy.
	 *
	 * @param XMY01035 the xmy01035 of this vr technical spec_xmy
	 */
	public void setXMY01035(String XMY01035);

	/**
	 * Returns the xmy01036 of this vr technical spec_xmy.
	 *
	 * @return the xmy01036 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01036();

	/**
	 * Sets the xmy01036 of this vr technical spec_xmy.
	 *
	 * @param XMY01036 the xmy01036 of this vr technical spec_xmy
	 */
	public void setXMY01036(String XMY01036);

	/**
	 * Returns the xmy01037 of this vr technical spec_xmy.
	 *
	 * @return the xmy01037 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01037();

	/**
	 * Sets the xmy01037 of this vr technical spec_xmy.
	 *
	 * @param XMY01037 the xmy01037 of this vr technical spec_xmy
	 */
	public void setXMY01037(String XMY01037);

	/**
	 * Returns the xmy01038 of this vr technical spec_xmy.
	 *
	 * @return the xmy01038 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01038();

	/**
	 * Sets the xmy01038 of this vr technical spec_xmy.
	 *
	 * @param XMY01038 the xmy01038 of this vr technical spec_xmy
	 */
	public void setXMY01038(String XMY01038);

	/**
	 * Returns the xmy01039 of this vr technical spec_xmy.
	 *
	 * @return the xmy01039 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01039();

	/**
	 * Sets the xmy01039 of this vr technical spec_xmy.
	 *
	 * @param XMY01039 the xmy01039 of this vr technical spec_xmy
	 */
	public void setXMY01039(String XMY01039);

	/**
	 * Returns the xmy01040 of this vr technical spec_xmy.
	 *
	 * @return the xmy01040 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01040();

	/**
	 * Sets the xmy01040 of this vr technical spec_xmy.
	 *
	 * @param XMY01040 the xmy01040 of this vr technical spec_xmy
	 */
	public void setXMY01040(String XMY01040);

	/**
	 * Returns the xmy01041 of this vr technical spec_xmy.
	 *
	 * @return the xmy01041 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01041();

	/**
	 * Sets the xmy01041 of this vr technical spec_xmy.
	 *
	 * @param XMY01041 the xmy01041 of this vr technical spec_xmy
	 */
	public void setXMY01041(String XMY01041);

	/**
	 * Returns the xmy01042 of this vr technical spec_xmy.
	 *
	 * @return the xmy01042 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01042();

	/**
	 * Sets the xmy01042 of this vr technical spec_xmy.
	 *
	 * @param XMY01042 the xmy01042 of this vr technical spec_xmy
	 */
	public void setXMY01042(String XMY01042);

	/**
	 * Returns the xmy01043 of this vr technical spec_xmy.
	 *
	 * @return the xmy01043 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01043();

	/**
	 * Sets the xmy01043 of this vr technical spec_xmy.
	 *
	 * @param XMY01043 the xmy01043 of this vr technical spec_xmy
	 */
	public void setXMY01043(String XMY01043);

	/**
	 * Returns the xmy01044 of this vr technical spec_xmy.
	 *
	 * @return the xmy01044 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01044();

	/**
	 * Sets the xmy01044 of this vr technical spec_xmy.
	 *
	 * @param XMY01044 the xmy01044 of this vr technical spec_xmy
	 */
	public void setXMY01044(String XMY01044);

	/**
	 * Returns the xmy01045 of this vr technical spec_xmy.
	 *
	 * @return the xmy01045 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01045();

	/**
	 * Sets the xmy01045 of this vr technical spec_xmy.
	 *
	 * @param XMY01045 the xmy01045 of this vr technical spec_xmy
	 */
	public void setXMY01045(String XMY01045);

	/**
	 * Returns the xmy01046 of this vr technical spec_xmy.
	 *
	 * @return the xmy01046 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01046();

	/**
	 * Sets the xmy01046 of this vr technical spec_xmy.
	 *
	 * @param XMY01046 the xmy01046 of this vr technical spec_xmy
	 */
	public void setXMY01046(String XMY01046);

	/**
	 * Returns the xmy01047 of this vr technical spec_xmy.
	 *
	 * @return the xmy01047 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01047();

	/**
	 * Sets the xmy01047 of this vr technical spec_xmy.
	 *
	 * @param XMY01047 the xmy01047 of this vr technical spec_xmy
	 */
	public void setXMY01047(String XMY01047);

	/**
	 * Returns the xmy01050 of this vr technical spec_xmy.
	 *
	 * @return the xmy01050 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01050();

	/**
	 * Sets the xmy01050 of this vr technical spec_xmy.
	 *
	 * @param XMY01050 the xmy01050 of this vr technical spec_xmy
	 */
	public void setXMY01050(String XMY01050);

	/**
	 * Returns the xmy01051 of this vr technical spec_xmy.
	 *
	 * @return the xmy01051 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01051();

	/**
	 * Sets the xmy01051 of this vr technical spec_xmy.
	 *
	 * @param XMY01051 the xmy01051 of this vr technical spec_xmy
	 */
	public void setXMY01051(String XMY01051);

	/**
	 * Returns the xmy01052 of this vr technical spec_xmy.
	 *
	 * @return the xmy01052 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01052();

	/**
	 * Sets the xmy01052 of this vr technical spec_xmy.
	 *
	 * @param XMY01052 the xmy01052 of this vr technical spec_xmy
	 */
	public void setXMY01052(String XMY01052);

	/**
	 * Returns the xmy01053 of this vr technical spec_xmy.
	 *
	 * @return the xmy01053 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01053();

	/**
	 * Sets the xmy01053 of this vr technical spec_xmy.
	 *
	 * @param XMY01053 the xmy01053 of this vr technical spec_xmy
	 */
	public void setXMY01053(String XMY01053);

	/**
	 * Returns the xmy01054 of this vr technical spec_xmy.
	 *
	 * @return the xmy01054 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01054();

	/**
	 * Sets the xmy01054 of this vr technical spec_xmy.
	 *
	 * @param XMY01054 the xmy01054 of this vr technical spec_xmy
	 */
	public void setXMY01054(String XMY01054);

	/**
	 * Returns the xmy01055 of this vr technical spec_xmy.
	 *
	 * @return the xmy01055 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01055();

	/**
	 * Sets the xmy01055 of this vr technical spec_xmy.
	 *
	 * @param XMY01055 the xmy01055 of this vr technical spec_xmy
	 */
	public void setXMY01055(String XMY01055);

	/**
	 * Returns the xmy01056 of this vr technical spec_xmy.
	 *
	 * @return the xmy01056 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01056();

	/**
	 * Sets the xmy01056 of this vr technical spec_xmy.
	 *
	 * @param XMY01056 the xmy01056 of this vr technical spec_xmy
	 */
	public void setXMY01056(String XMY01056);

	/**
	 * Returns the xmy01057 of this vr technical spec_xmy.
	 *
	 * @return the xmy01057 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01057();

	/**
	 * Sets the xmy01057 of this vr technical spec_xmy.
	 *
	 * @param XMY01057 the xmy01057 of this vr technical spec_xmy
	 */
	public void setXMY01057(String XMY01057);

	/**
	 * Returns the xmy01058 of this vr technical spec_xmy.
	 *
	 * @return the xmy01058 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01058();

	/**
	 * Sets the xmy01058 of this vr technical spec_xmy.
	 *
	 * @param XMY01058 the xmy01058 of this vr technical spec_xmy
	 */
	public void setXMY01058(String XMY01058);

	/**
	 * Returns the xmy01059 of this vr technical spec_xmy.
	 *
	 * @return the xmy01059 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01059();

	/**
	 * Sets the xmy01059 of this vr technical spec_xmy.
	 *
	 * @param XMY01059 the xmy01059 of this vr technical spec_xmy
	 */
	public void setXMY01059(String XMY01059);

	/**
	 * Returns the xmy01060 of this vr technical spec_xmy.
	 *
	 * @return the xmy01060 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01060();

	/**
	 * Sets the xmy01060 of this vr technical spec_xmy.
	 *
	 * @param XMY01060 the xmy01060 of this vr technical spec_xmy
	 */
	public void setXMY01060(String XMY01060);

	/**
	 * Returns the xmy01062 of this vr technical spec_xmy.
	 *
	 * @return the xmy01062 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01062();

	/**
	 * Sets the xmy01062 of this vr technical spec_xmy.
	 *
	 * @param XMY01062 the xmy01062 of this vr technical spec_xmy
	 */
	public void setXMY01062(String XMY01062);

	/**
	 * Returns the xmy01063 of this vr technical spec_xmy.
	 *
	 * @return the xmy01063 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01063();

	/**
	 * Sets the xmy01063 of this vr technical spec_xmy.
	 *
	 * @param XMY01063 the xmy01063 of this vr technical spec_xmy
	 */
	public void setXMY01063(String XMY01063);

	/**
	 * Returns the xmy01064 of this vr technical spec_xmy.
	 *
	 * @return the xmy01064 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01064();

	/**
	 * Sets the xmy01064 of this vr technical spec_xmy.
	 *
	 * @param XMY01064 the xmy01064 of this vr technical spec_xmy
	 */
	public void setXMY01064(String XMY01064);

	/**
	 * Returns the xmy01065 of this vr technical spec_xmy.
	 *
	 * @return the xmy01065 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01065();

	/**
	 * Sets the xmy01065 of this vr technical spec_xmy.
	 *
	 * @param XMY01065 the xmy01065 of this vr technical spec_xmy
	 */
	public void setXMY01065(String XMY01065);

	/**
	 * Returns the xmy01670 of this vr technical spec_xmy.
	 *
	 * @return the xmy01670 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01670();

	/**
	 * Sets the xmy01670 of this vr technical spec_xmy.
	 *
	 * @param XMY01670 the xmy01670 of this vr technical spec_xmy
	 */
	public void setXMY01670(String XMY01670);

	/**
	 * Returns the xmy01671 of this vr technical spec_xmy.
	 *
	 * @return the xmy01671 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01671();

	/**
	 * Sets the xmy01671 of this vr technical spec_xmy.
	 *
	 * @param XMY01671 the xmy01671 of this vr technical spec_xmy
	 */
	public void setXMY01671(String XMY01671);

	/**
	 * Returns the xmy01672 of this vr technical spec_xmy.
	 *
	 * @return the xmy01672 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01672();

	/**
	 * Sets the xmy01672 of this vr technical spec_xmy.
	 *
	 * @param XMY01672 the xmy01672 of this vr technical spec_xmy
	 */
	public void setXMY01672(String XMY01672);

	/**
	 * Returns the xmy01673 of this vr technical spec_xmy.
	 *
	 * @return the xmy01673 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01673();

	/**
	 * Sets the xmy01673 of this vr technical spec_xmy.
	 *
	 * @param XMY01673 the xmy01673 of this vr technical spec_xmy
	 */
	public void setXMY01673(String XMY01673);

	/**
	 * Returns the xmy01674 of this vr technical spec_xmy.
	 *
	 * @return the xmy01674 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01674();

	/**
	 * Sets the xmy01674 of this vr technical spec_xmy.
	 *
	 * @param XMY01674 the xmy01674 of this vr technical spec_xmy
	 */
	public void setXMY01674(String XMY01674);

	/**
	 * Returns the xmy01675 of this vr technical spec_xmy.
	 *
	 * @return the xmy01675 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01675();

	/**
	 * Sets the xmy01675 of this vr technical spec_xmy.
	 *
	 * @param XMY01675 the xmy01675 of this vr technical spec_xmy
	 */
	public void setXMY01675(String XMY01675);

	/**
	 * Returns the xmy01676 of this vr technical spec_xmy.
	 *
	 * @return the xmy01676 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01676();

	/**
	 * Sets the xmy01676 of this vr technical spec_xmy.
	 *
	 * @param XMY01676 the xmy01676 of this vr technical spec_xmy
	 */
	public void setXMY01676(String XMY01676);

	/**
	 * Returns the xmy01677 of this vr technical spec_xmy.
	 *
	 * @return the xmy01677 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01677();

	/**
	 * Sets the xmy01677 of this vr technical spec_xmy.
	 *
	 * @param XMY01677 the xmy01677 of this vr technical spec_xmy
	 */
	public void setXMY01677(String XMY01677);

	/**
	 * Returns the xmy01678 of this vr technical spec_xmy.
	 *
	 * @return the xmy01678 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01678();

	/**
	 * Sets the xmy01678 of this vr technical spec_xmy.
	 *
	 * @param XMY01678 the xmy01678 of this vr technical spec_xmy
	 */
	public void setXMY01678(String XMY01678);

	/**
	 * Returns the xmy01679 of this vr technical spec_xmy.
	 *
	 * @return the xmy01679 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01679();

	/**
	 * Sets the xmy01679 of this vr technical spec_xmy.
	 *
	 * @param XMY01679 the xmy01679 of this vr technical spec_xmy
	 */
	public void setXMY01679(String XMY01679);

	/**
	 * Returns the xmy01680 of this vr technical spec_xmy.
	 *
	 * @return the xmy01680 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01680();

	/**
	 * Sets the xmy01680 of this vr technical spec_xmy.
	 *
	 * @param XMY01680 the xmy01680 of this vr technical spec_xmy
	 */
	public void setXMY01680(String XMY01680);

	/**
	 * Returns the xmy01681 of this vr technical spec_xmy.
	 *
	 * @return the xmy01681 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01681();

	/**
	 * Sets the xmy01681 of this vr technical spec_xmy.
	 *
	 * @param XMY01681 the xmy01681 of this vr technical spec_xmy
	 */
	public void setXMY01681(String XMY01681);

	/**
	 * Returns the xmy01682 of this vr technical spec_xmy.
	 *
	 * @return the xmy01682 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01682();

	/**
	 * Sets the xmy01682 of this vr technical spec_xmy.
	 *
	 * @param XMY01682 the xmy01682 of this vr technical spec_xmy
	 */
	public void setXMY01682(String XMY01682);

	/**
	 * Returns the xmy01683 of this vr technical spec_xmy.
	 *
	 * @return the xmy01683 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01683();

	/**
	 * Sets the xmy01683 of this vr technical spec_xmy.
	 *
	 * @param XMY01683 the xmy01683 of this vr technical spec_xmy
	 */
	public void setXMY01683(String XMY01683);

	/**
	 * Returns the xmy01684 of this vr technical spec_xmy.
	 *
	 * @return the xmy01684 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01684();

	/**
	 * Sets the xmy01684 of this vr technical spec_xmy.
	 *
	 * @param XMY01684 the xmy01684 of this vr technical spec_xmy
	 */
	public void setXMY01684(String XMY01684);

	/**
	 * Returns the xmy01685 of this vr technical spec_xmy.
	 *
	 * @return the xmy01685 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01685();

	/**
	 * Sets the xmy01685 of this vr technical spec_xmy.
	 *
	 * @param XMY01685 the xmy01685 of this vr technical spec_xmy
	 */
	public void setXMY01685(String XMY01685);

	/**
	 * Returns the xmy01686 of this vr technical spec_xmy.
	 *
	 * @return the xmy01686 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01686();

	/**
	 * Sets the xmy01686 of this vr technical spec_xmy.
	 *
	 * @param XMY01686 the xmy01686 of this vr technical spec_xmy
	 */
	public void setXMY01686(String XMY01686);

	/**
	 * Returns the xmy01687 of this vr technical spec_xmy.
	 *
	 * @return the xmy01687 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01687();

	/**
	 * Sets the xmy01687 of this vr technical spec_xmy.
	 *
	 * @param XMY01687 the xmy01687 of this vr technical spec_xmy
	 */
	public void setXMY01687(String XMY01687);

	/**
	 * Returns the xmy01688 of this vr technical spec_xmy.
	 *
	 * @return the xmy01688 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01688();

	/**
	 * Sets the xmy01688 of this vr technical spec_xmy.
	 *
	 * @param XMY01688 the xmy01688 of this vr technical spec_xmy
	 */
	public void setXMY01688(String XMY01688);

	/**
	 * Returns the xmy01689 of this vr technical spec_xmy.
	 *
	 * @return the xmy01689 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01689();

	/**
	 * Sets the xmy01689 of this vr technical spec_xmy.
	 *
	 * @param XMY01689 the xmy01689 of this vr technical spec_xmy
	 */
	public void setXMY01689(String XMY01689);

	/**
	 * Returns the xmy01690 of this vr technical spec_xmy.
	 *
	 * @return the xmy01690 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01690();

	/**
	 * Sets the xmy01690 of this vr technical spec_xmy.
	 *
	 * @param XMY01690 the xmy01690 of this vr technical spec_xmy
	 */
	public void setXMY01690(String XMY01690);

	/**
	 * Returns the xmy01691 of this vr technical spec_xmy.
	 *
	 * @return the xmy01691 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01691();

	/**
	 * Sets the xmy01691 of this vr technical spec_xmy.
	 *
	 * @param XMY01691 the xmy01691 of this vr technical spec_xmy
	 */
	public void setXMY01691(String XMY01691);

	/**
	 * Returns the xmy01692 of this vr technical spec_xmy.
	 *
	 * @return the xmy01692 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01692();

	/**
	 * Sets the xmy01692 of this vr technical spec_xmy.
	 *
	 * @param XMY01692 the xmy01692 of this vr technical spec_xmy
	 */
	public void setXMY01692(String XMY01692);

	/**
	 * Returns the xmy01693 of this vr technical spec_xmy.
	 *
	 * @return the xmy01693 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01693();

	/**
	 * Sets the xmy01693 of this vr technical spec_xmy.
	 *
	 * @param XMY01693 the xmy01693 of this vr technical spec_xmy
	 */
	public void setXMY01693(String XMY01693);

	/**
	 * Returns the xmy01694 of this vr technical spec_xmy.
	 *
	 * @return the xmy01694 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01694();

	/**
	 * Sets the xmy01694 of this vr technical spec_xmy.
	 *
	 * @param XMY01694 the xmy01694 of this vr technical spec_xmy
	 */
	public void setXMY01694(String XMY01694);

	/**
	 * Returns the xmy01695 of this vr technical spec_xmy.
	 *
	 * @return the xmy01695 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01695();

	/**
	 * Sets the xmy01695 of this vr technical spec_xmy.
	 *
	 * @param XMY01695 the xmy01695 of this vr technical spec_xmy
	 */
	public void setXMY01695(String XMY01695);

	/**
	 * Returns the xmy01696 of this vr technical spec_xmy.
	 *
	 * @return the xmy01696 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01696();

	/**
	 * Sets the xmy01696 of this vr technical spec_xmy.
	 *
	 * @param XMY01696 the xmy01696 of this vr technical spec_xmy
	 */
	public void setXMY01696(String XMY01696);

	/**
	 * Returns the xmy01697 of this vr technical spec_xmy.
	 *
	 * @return the xmy01697 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01697();

	/**
	 * Sets the xmy01697 of this vr technical spec_xmy.
	 *
	 * @param XMY01697 the xmy01697 of this vr technical spec_xmy
	 */
	public void setXMY01697(String XMY01697);

	/**
	 * Returns the xmy01698 of this vr technical spec_xmy.
	 *
	 * @return the xmy01698 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01698();

	/**
	 * Sets the xmy01698 of this vr technical spec_xmy.
	 *
	 * @param XMY01698 the xmy01698 of this vr technical spec_xmy
	 */
	public void setXMY01698(String XMY01698);

	/**
	 * Returns the xmy01699 of this vr technical spec_xmy.
	 *
	 * @return the xmy01699 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01699();

	/**
	 * Sets the xmy01699 of this vr technical spec_xmy.
	 *
	 * @param XMY01699 the xmy01699 of this vr technical spec_xmy
	 */
	public void setXMY01699(String XMY01699);

	/**
	 * Returns the xmy01700 of this vr technical spec_xmy.
	 *
	 * @return the xmy01700 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01700();

	/**
	 * Sets the xmy01700 of this vr technical spec_xmy.
	 *
	 * @param XMY01700 the xmy01700 of this vr technical spec_xmy
	 */
	public void setXMY01700(String XMY01700);

	/**
	 * Returns the xmy01701 of this vr technical spec_xmy.
	 *
	 * @return the xmy01701 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01701();

	/**
	 * Sets the xmy01701 of this vr technical spec_xmy.
	 *
	 * @param XMY01701 the xmy01701 of this vr technical spec_xmy
	 */
	public void setXMY01701(String XMY01701);

	/**
	 * Returns the xmy01702 of this vr technical spec_xmy.
	 *
	 * @return the xmy01702 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01702();

	/**
	 * Sets the xmy01702 of this vr technical spec_xmy.
	 *
	 * @param XMY01702 the xmy01702 of this vr technical spec_xmy
	 */
	public void setXMY01702(String XMY01702);

	/**
	 * Returns the xmy01703 of this vr technical spec_xmy.
	 *
	 * @return the xmy01703 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01703();

	/**
	 * Sets the xmy01703 of this vr technical spec_xmy.
	 *
	 * @param XMY01703 the xmy01703 of this vr technical spec_xmy
	 */
	public void setXMY01703(String XMY01703);

	/**
	 * Returns the xmy01704 of this vr technical spec_xmy.
	 *
	 * @return the xmy01704 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01704();

	/**
	 * Sets the xmy01704 of this vr technical spec_xmy.
	 *
	 * @param XMY01704 the xmy01704 of this vr technical spec_xmy
	 */
	public void setXMY01704(String XMY01704);

	/**
	 * Returns the xmy01705 of this vr technical spec_xmy.
	 *
	 * @return the xmy01705 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01705();

	/**
	 * Sets the xmy01705 of this vr technical spec_xmy.
	 *
	 * @param XMY01705 the xmy01705 of this vr technical spec_xmy
	 */
	public void setXMY01705(String XMY01705);

	/**
	 * Returns the xmy01706 of this vr technical spec_xmy.
	 *
	 * @return the xmy01706 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01706();

	/**
	 * Sets the xmy01706 of this vr technical spec_xmy.
	 *
	 * @param XMY01706 the xmy01706 of this vr technical spec_xmy
	 */
	public void setXMY01706(String XMY01706);

	/**
	 * Returns the xmy01707 of this vr technical spec_xmy.
	 *
	 * @return the xmy01707 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01707();

	/**
	 * Sets the xmy01707 of this vr technical spec_xmy.
	 *
	 * @param XMY01707 the xmy01707 of this vr technical spec_xmy
	 */
	public void setXMY01707(String XMY01707);

	/**
	 * Returns the xmy01708 of this vr technical spec_xmy.
	 *
	 * @return the xmy01708 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01708();

	/**
	 * Sets the xmy01708 of this vr technical spec_xmy.
	 *
	 * @param XMY01708 the xmy01708 of this vr technical spec_xmy
	 */
	public void setXMY01708(String XMY01708);

	/**
	 * Returns the xmy01709 of this vr technical spec_xmy.
	 *
	 * @return the xmy01709 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01709();

	/**
	 * Sets the xmy01709 of this vr technical spec_xmy.
	 *
	 * @param XMY01709 the xmy01709 of this vr technical spec_xmy
	 */
	public void setXMY01709(String XMY01709);

	/**
	 * Returns the xmy01710 of this vr technical spec_xmy.
	 *
	 * @return the xmy01710 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01710();

	/**
	 * Sets the xmy01710 of this vr technical spec_xmy.
	 *
	 * @param XMY01710 the xmy01710 of this vr technical spec_xmy
	 */
	public void setXMY01710(String XMY01710);

	/**
	 * Returns the xmy01711 of this vr technical spec_xmy.
	 *
	 * @return the xmy01711 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01711();

	/**
	 * Sets the xmy01711 of this vr technical spec_xmy.
	 *
	 * @param XMY01711 the xmy01711 of this vr technical spec_xmy
	 */
	public void setXMY01711(String XMY01711);

	/**
	 * Returns the xmy01712 of this vr technical spec_xmy.
	 *
	 * @return the xmy01712 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01712();

	/**
	 * Sets the xmy01712 of this vr technical spec_xmy.
	 *
	 * @param XMY01712 the xmy01712 of this vr technical spec_xmy
	 */
	public void setXMY01712(String XMY01712);

	/**
	 * Returns the xmy01713 of this vr technical spec_xmy.
	 *
	 * @return the xmy01713 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01713();

	/**
	 * Sets the xmy01713 of this vr technical spec_xmy.
	 *
	 * @param XMY01713 the xmy01713 of this vr technical spec_xmy
	 */
	public void setXMY01713(String XMY01713);

	/**
	 * Returns the xmy01714 of this vr technical spec_xmy.
	 *
	 * @return the xmy01714 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01714();

	/**
	 * Sets the xmy01714 of this vr technical spec_xmy.
	 *
	 * @param XMY01714 the xmy01714 of this vr technical spec_xmy
	 */
	public void setXMY01714(String XMY01714);

	/**
	 * Returns the xmy01715 of this vr technical spec_xmy.
	 *
	 * @return the xmy01715 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01715();

	/**
	 * Sets the xmy01715 of this vr technical spec_xmy.
	 *
	 * @param XMY01715 the xmy01715 of this vr technical spec_xmy
	 */
	public void setXMY01715(String XMY01715);

	/**
	 * Returns the xmy01716 of this vr technical spec_xmy.
	 *
	 * @return the xmy01716 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01716();

	/**
	 * Sets the xmy01716 of this vr technical spec_xmy.
	 *
	 * @param XMY01716 the xmy01716 of this vr technical spec_xmy
	 */
	public void setXMY01716(String XMY01716);

	/**
	 * Returns the xmy01717 of this vr technical spec_xmy.
	 *
	 * @return the xmy01717 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01717();

	/**
	 * Sets the xmy01717 of this vr technical spec_xmy.
	 *
	 * @param XMY01717 the xmy01717 of this vr technical spec_xmy
	 */
	public void setXMY01717(String XMY01717);

	/**
	 * Returns the xmy01718 of this vr technical spec_xmy.
	 *
	 * @return the xmy01718 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01718();

	/**
	 * Sets the xmy01718 of this vr technical spec_xmy.
	 *
	 * @param XMY01718 the xmy01718 of this vr technical spec_xmy
	 */
	public void setXMY01718(String XMY01718);

	/**
	 * Returns the xmy01719 of this vr technical spec_xmy.
	 *
	 * @return the xmy01719 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01719();

	/**
	 * Sets the xmy01719 of this vr technical spec_xmy.
	 *
	 * @param XMY01719 the xmy01719 of this vr technical spec_xmy
	 */
	public void setXMY01719(String XMY01719);

	/**
	 * Returns the xmy01720 of this vr technical spec_xmy.
	 *
	 * @return the xmy01720 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01720();

	/**
	 * Sets the xmy01720 of this vr technical spec_xmy.
	 *
	 * @param XMY01720 the xmy01720 of this vr technical spec_xmy
	 */
	public void setXMY01720(String XMY01720);

	/**
	 * Returns the xmy01721 of this vr technical spec_xmy.
	 *
	 * @return the xmy01721 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01721();

	/**
	 * Sets the xmy01721 of this vr technical spec_xmy.
	 *
	 * @param XMY01721 the xmy01721 of this vr technical spec_xmy
	 */
	public void setXMY01721(String XMY01721);

	/**
	 * Returns the xmy01722 of this vr technical spec_xmy.
	 *
	 * @return the xmy01722 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01722();

	/**
	 * Sets the xmy01722 of this vr technical spec_xmy.
	 *
	 * @param XMY01722 the xmy01722 of this vr technical spec_xmy
	 */
	public void setXMY01722(String XMY01722);

	/**
	 * Returns the xmy01723 of this vr technical spec_xmy.
	 *
	 * @return the xmy01723 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01723();

	/**
	 * Sets the xmy01723 of this vr technical spec_xmy.
	 *
	 * @param XMY01723 the xmy01723 of this vr technical spec_xmy
	 */
	public void setXMY01723(String XMY01723);

	/**
	 * Returns the xmy01724 of this vr technical spec_xmy.
	 *
	 * @return the xmy01724 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01724();

	/**
	 * Sets the xmy01724 of this vr technical spec_xmy.
	 *
	 * @param XMY01724 the xmy01724 of this vr technical spec_xmy
	 */
	public void setXMY01724(String XMY01724);

	/**
	 * Returns the xmy01725 of this vr technical spec_xmy.
	 *
	 * @return the xmy01725 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01725();

	/**
	 * Sets the xmy01725 of this vr technical spec_xmy.
	 *
	 * @param XMY01725 the xmy01725 of this vr technical spec_xmy
	 */
	public void setXMY01725(String XMY01725);

	/**
	 * Returns the xmy01726 of this vr technical spec_xmy.
	 *
	 * @return the xmy01726 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01726();

	/**
	 * Sets the xmy01726 of this vr technical spec_xmy.
	 *
	 * @param XMY01726 the xmy01726 of this vr technical spec_xmy
	 */
	public void setXMY01726(String XMY01726);

	/**
	 * Returns the xmy01729 of this vr technical spec_xmy.
	 *
	 * @return the xmy01729 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01729();

	/**
	 * Sets the xmy01729 of this vr technical spec_xmy.
	 *
	 * @param XMY01729 the xmy01729 of this vr technical spec_xmy
	 */
	public void setXMY01729(String XMY01729);

	/**
	 * Returns the xmy01730 of this vr technical spec_xmy.
	 *
	 * @return the xmy01730 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01730();

	/**
	 * Sets the xmy01730 of this vr technical spec_xmy.
	 *
	 * @param XMY01730 the xmy01730 of this vr technical spec_xmy
	 */
	public void setXMY01730(String XMY01730);

	/**
	 * Returns the xmy01731 of this vr technical spec_xmy.
	 *
	 * @return the xmy01731 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01731();

	/**
	 * Sets the xmy01731 of this vr technical spec_xmy.
	 *
	 * @param XMY01731 the xmy01731 of this vr technical spec_xmy
	 */
	public void setXMY01731(String XMY01731);

	/**
	 * Returns the xmy01732 of this vr technical spec_xmy.
	 *
	 * @return the xmy01732 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01732();

	/**
	 * Sets the xmy01732 of this vr technical spec_xmy.
	 *
	 * @param XMY01732 the xmy01732 of this vr technical spec_xmy
	 */
	public void setXMY01732(String XMY01732);

	/**
	 * Returns the xmy01733 of this vr technical spec_xmy.
	 *
	 * @return the xmy01733 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01733();

	/**
	 * Sets the xmy01733 of this vr technical spec_xmy.
	 *
	 * @param XMY01733 the xmy01733 of this vr technical spec_xmy
	 */
	public void setXMY01733(String XMY01733);

	/**
	 * Returns the xmy01734 of this vr technical spec_xmy.
	 *
	 * @return the xmy01734 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01734();

	/**
	 * Sets the xmy01734 of this vr technical spec_xmy.
	 *
	 * @param XMY01734 the xmy01734 of this vr technical spec_xmy
	 */
	public void setXMY01734(String XMY01734);

	/**
	 * Returns the xmy01735 of this vr technical spec_xmy.
	 *
	 * @return the xmy01735 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01735();

	/**
	 * Sets the xmy01735 of this vr technical spec_xmy.
	 *
	 * @param XMY01735 the xmy01735 of this vr technical spec_xmy
	 */
	public void setXMY01735(String XMY01735);

	/**
	 * Returns the xmy01736 of this vr technical spec_xmy.
	 *
	 * @return the xmy01736 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01736();

	/**
	 * Sets the xmy01736 of this vr technical spec_xmy.
	 *
	 * @param XMY01736 the xmy01736 of this vr technical spec_xmy
	 */
	public void setXMY01736(String XMY01736);

	/**
	 * Returns the xmy01737 of this vr technical spec_xmy.
	 *
	 * @return the xmy01737 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01737();

	/**
	 * Sets the xmy01737 of this vr technical spec_xmy.
	 *
	 * @param XMY01737 the xmy01737 of this vr technical spec_xmy
	 */
	public void setXMY01737(String XMY01737);

	/**
	 * Returns the xmy01738 of this vr technical spec_xmy.
	 *
	 * @return the xmy01738 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01738();

	/**
	 * Sets the xmy01738 of this vr technical spec_xmy.
	 *
	 * @param XMY01738 the xmy01738 of this vr technical spec_xmy
	 */
	public void setXMY01738(String XMY01738);

	/**
	 * Returns the xmy01739 of this vr technical spec_xmy.
	 *
	 * @return the xmy01739 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01739();

	/**
	 * Sets the xmy01739 of this vr technical spec_xmy.
	 *
	 * @param XMY01739 the xmy01739 of this vr technical spec_xmy
	 */
	public void setXMY01739(String XMY01739);

	/**
	 * Returns the xmy01740 of this vr technical spec_xmy.
	 *
	 * @return the xmy01740 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01740();

	/**
	 * Sets the xmy01740 of this vr technical spec_xmy.
	 *
	 * @param XMY01740 the xmy01740 of this vr technical spec_xmy
	 */
	public void setXMY01740(String XMY01740);

	/**
	 * Returns the xmy01741 of this vr technical spec_xmy.
	 *
	 * @return the xmy01741 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01741();

	/**
	 * Sets the xmy01741 of this vr technical spec_xmy.
	 *
	 * @param XMY01741 the xmy01741 of this vr technical spec_xmy
	 */
	public void setXMY01741(String XMY01741);

	/**
	 * Returns the xmy01742 of this vr technical spec_xmy.
	 *
	 * @return the xmy01742 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01742();

	/**
	 * Sets the xmy01742 of this vr technical spec_xmy.
	 *
	 * @param XMY01742 the xmy01742 of this vr technical spec_xmy
	 */
	public void setXMY01742(String XMY01742);

	/**
	 * Returns the xmy01744 of this vr technical spec_xmy.
	 *
	 * @return the xmy01744 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01744();

	/**
	 * Sets the xmy01744 of this vr technical spec_xmy.
	 *
	 * @param XMY01744 the xmy01744 of this vr technical spec_xmy
	 */
	public void setXMY01744(String XMY01744);

	/**
	 * Returns the xmy01745 of this vr technical spec_xmy.
	 *
	 * @return the xmy01745 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01745();

	/**
	 * Sets the xmy01745 of this vr technical spec_xmy.
	 *
	 * @param XMY01745 the xmy01745 of this vr technical spec_xmy
	 */
	public void setXMY01745(String XMY01745);

	/**
	 * Returns the xmy01746 of this vr technical spec_xmy.
	 *
	 * @return the xmy01746 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01746();

	/**
	 * Sets the xmy01746 of this vr technical spec_xmy.
	 *
	 * @param XMY01746 the xmy01746 of this vr technical spec_xmy
	 */
	public void setXMY01746(String XMY01746);

	/**
	 * Returns the xmy01747 of this vr technical spec_xmy.
	 *
	 * @return the xmy01747 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01747();

	/**
	 * Sets the xmy01747 of this vr technical spec_xmy.
	 *
	 * @param XMY01747 the xmy01747 of this vr technical spec_xmy
	 */
	public void setXMY01747(String XMY01747);

	/**
	 * Returns the xmy01748 of this vr technical spec_xmy.
	 *
	 * @return the xmy01748 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01748();

	/**
	 * Sets the xmy01748 of this vr technical spec_xmy.
	 *
	 * @param XMY01748 the xmy01748 of this vr technical spec_xmy
	 */
	public void setXMY01748(String XMY01748);

	/**
	 * Returns the xmy01749 of this vr technical spec_xmy.
	 *
	 * @return the xmy01749 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01749();

	/**
	 * Sets the xmy01749 of this vr technical spec_xmy.
	 *
	 * @param XMY01749 the xmy01749 of this vr technical spec_xmy
	 */
	public void setXMY01749(String XMY01749);

	/**
	 * Returns the xmy01758 of this vr technical spec_xmy.
	 *
	 * @return the xmy01758 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01758();

	/**
	 * Sets the xmy01758 of this vr technical spec_xmy.
	 *
	 * @param XMY01758 the xmy01758 of this vr technical spec_xmy
	 */
	public void setXMY01758(String XMY01758);

	/**
	 * Returns the xmy01759 of this vr technical spec_xmy.
	 *
	 * @return the xmy01759 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01759();

	/**
	 * Sets the xmy01759 of this vr technical spec_xmy.
	 *
	 * @param XMY01759 the xmy01759 of this vr technical spec_xmy
	 */
	public void setXMY01759(String XMY01759);

	/**
	 * Returns the xmy01760 of this vr technical spec_xmy.
	 *
	 * @return the xmy01760 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01760();

	/**
	 * Sets the xmy01760 of this vr technical spec_xmy.
	 *
	 * @param XMY01760 the xmy01760 of this vr technical spec_xmy
	 */
	public void setXMY01760(String XMY01760);

	/**
	 * Returns the xmy01761 of this vr technical spec_xmy.
	 *
	 * @return the xmy01761 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01761();

	/**
	 * Sets the xmy01761 of this vr technical spec_xmy.
	 *
	 * @param XMY01761 the xmy01761 of this vr technical spec_xmy
	 */
	public void setXMY01761(String XMY01761);

	/**
	 * Returns the xmy01762 of this vr technical spec_xmy.
	 *
	 * @return the xmy01762 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01762();

	/**
	 * Sets the xmy01762 of this vr technical spec_xmy.
	 *
	 * @param XMY01762 the xmy01762 of this vr technical spec_xmy
	 */
	public void setXMY01762(String XMY01762);

	/**
	 * Returns the xmy01763 of this vr technical spec_xmy.
	 *
	 * @return the xmy01763 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01763();

	/**
	 * Sets the xmy01763 of this vr technical spec_xmy.
	 *
	 * @param XMY01763 the xmy01763 of this vr technical spec_xmy
	 */
	public void setXMY01763(String XMY01763);

	/**
	 * Returns the xmy01764 of this vr technical spec_xmy.
	 *
	 * @return the xmy01764 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01764();

	/**
	 * Sets the xmy01764 of this vr technical spec_xmy.
	 *
	 * @param XMY01764 the xmy01764 of this vr technical spec_xmy
	 */
	public void setXMY01764(String XMY01764);

	/**
	 * Returns the xmy01779 of this vr technical spec_xmy.
	 *
	 * @return the xmy01779 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01779();

	/**
	 * Sets the xmy01779 of this vr technical spec_xmy.
	 *
	 * @param XMY01779 the xmy01779 of this vr technical spec_xmy
	 */
	public void setXMY01779(String XMY01779);

	/**
	 * Returns the xmy01780 of this vr technical spec_xmy.
	 *
	 * @return the xmy01780 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01780();

	/**
	 * Sets the xmy01780 of this vr technical spec_xmy.
	 *
	 * @param XMY01780 the xmy01780 of this vr technical spec_xmy
	 */
	public void setXMY01780(String XMY01780);

	/**
	 * Returns the xmy01781 of this vr technical spec_xmy.
	 *
	 * @return the xmy01781 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01781();

	/**
	 * Sets the xmy01781 of this vr technical spec_xmy.
	 *
	 * @param XMY01781 the xmy01781 of this vr technical spec_xmy
	 */
	public void setXMY01781(String XMY01781);

	/**
	 * Returns the xmy01782 of this vr technical spec_xmy.
	 *
	 * @return the xmy01782 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01782();

	/**
	 * Sets the xmy01782 of this vr technical spec_xmy.
	 *
	 * @param XMY01782 the xmy01782 of this vr technical spec_xmy
	 */
	public void setXMY01782(String XMY01782);

	/**
	 * Returns the xmy01783 of this vr technical spec_xmy.
	 *
	 * @return the xmy01783 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01783();

	/**
	 * Sets the xmy01783 of this vr technical spec_xmy.
	 *
	 * @param XMY01783 the xmy01783 of this vr technical spec_xmy
	 */
	public void setXMY01783(String XMY01783);

	/**
	 * Returns the xmy01785 of this vr technical spec_xmy.
	 *
	 * @return the xmy01785 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01785();

	/**
	 * Sets the xmy01785 of this vr technical spec_xmy.
	 *
	 * @param XMY01785 the xmy01785 of this vr technical spec_xmy
	 */
	public void setXMY01785(String XMY01785);

	/**
	 * Returns the xmy01786 of this vr technical spec_xmy.
	 *
	 * @return the xmy01786 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01786();

	/**
	 * Sets the xmy01786 of this vr technical spec_xmy.
	 *
	 * @param XMY01786 the xmy01786 of this vr technical spec_xmy
	 */
	public void setXMY01786(String XMY01786);

	/**
	 * Returns the xmy01787 of this vr technical spec_xmy.
	 *
	 * @return the xmy01787 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01787();

	/**
	 * Sets the xmy01787 of this vr technical spec_xmy.
	 *
	 * @param XMY01787 the xmy01787 of this vr technical spec_xmy
	 */
	public void setXMY01787(String XMY01787);

	/**
	 * Returns the xmy01788 of this vr technical spec_xmy.
	 *
	 * @return the xmy01788 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01788();

	/**
	 * Sets the xmy01788 of this vr technical spec_xmy.
	 *
	 * @param XMY01788 the xmy01788 of this vr technical spec_xmy
	 */
	public void setXMY01788(String XMY01788);

	/**
	 * Returns the xmy01789 of this vr technical spec_xmy.
	 *
	 * @return the xmy01789 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01789();

	/**
	 * Sets the xmy01789 of this vr technical spec_xmy.
	 *
	 * @param XMY01789 the xmy01789 of this vr technical spec_xmy
	 */
	public void setXMY01789(String XMY01789);

	/**
	 * Returns the xmy01790 of this vr technical spec_xmy.
	 *
	 * @return the xmy01790 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01790();

	/**
	 * Sets the xmy01790 of this vr technical spec_xmy.
	 *
	 * @param XMY01790 the xmy01790 of this vr technical spec_xmy
	 */
	public void setXMY01790(String XMY01790);

	/**
	 * Returns the xmy01791 of this vr technical spec_xmy.
	 *
	 * @return the xmy01791 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01791();

	/**
	 * Sets the xmy01791 of this vr technical spec_xmy.
	 *
	 * @param XMY01791 the xmy01791 of this vr technical spec_xmy
	 */
	public void setXMY01791(String XMY01791);

	/**
	 * Returns the xmy01792 of this vr technical spec_xmy.
	 *
	 * @return the xmy01792 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01792();

	/**
	 * Sets the xmy01792 of this vr technical spec_xmy.
	 *
	 * @param XMY01792 the xmy01792 of this vr technical spec_xmy
	 */
	public void setXMY01792(String XMY01792);

	/**
	 * Returns the xmy01793 of this vr technical spec_xmy.
	 *
	 * @return the xmy01793 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01793();

	/**
	 * Sets the xmy01793 of this vr technical spec_xmy.
	 *
	 * @param XMY01793 the xmy01793 of this vr technical spec_xmy
	 */
	public void setXMY01793(String XMY01793);

	/**
	 * Returns the xmy01794 of this vr technical spec_xmy.
	 *
	 * @return the xmy01794 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01794();

	/**
	 * Sets the xmy01794 of this vr technical spec_xmy.
	 *
	 * @param XMY01794 the xmy01794 of this vr technical spec_xmy
	 */
	public void setXMY01794(String XMY01794);

	/**
	 * Returns the xmy01795 of this vr technical spec_xmy.
	 *
	 * @return the xmy01795 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01795();

	/**
	 * Sets the xmy01795 of this vr technical spec_xmy.
	 *
	 * @param XMY01795 the xmy01795 of this vr technical spec_xmy
	 */
	public void setXMY01795(String XMY01795);

	/**
	 * Returns the xmy01796 of this vr technical spec_xmy.
	 *
	 * @return the xmy01796 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01796();

	/**
	 * Sets the xmy01796 of this vr technical spec_xmy.
	 *
	 * @param XMY01796 the xmy01796 of this vr technical spec_xmy
	 */
	public void setXMY01796(String XMY01796);

	/**
	 * Returns the xmy01797 of this vr technical spec_xmy.
	 *
	 * @return the xmy01797 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01797();

	/**
	 * Sets the xmy01797 of this vr technical spec_xmy.
	 *
	 * @param XMY01797 the xmy01797 of this vr technical spec_xmy
	 */
	public void setXMY01797(String XMY01797);

	/**
	 * Returns the xmy01798 of this vr technical spec_xmy.
	 *
	 * @return the xmy01798 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01798();

	/**
	 * Sets the xmy01798 of this vr technical spec_xmy.
	 *
	 * @param XMY01798 the xmy01798 of this vr technical spec_xmy
	 */
	public void setXMY01798(String XMY01798);

	/**
	 * Returns the xmy01799 of this vr technical spec_xmy.
	 *
	 * @return the xmy01799 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01799();

	/**
	 * Sets the xmy01799 of this vr technical spec_xmy.
	 *
	 * @param XMY01799 the xmy01799 of this vr technical spec_xmy
	 */
	public void setXMY01799(String XMY01799);

	/**
	 * Returns the xmy01800 of this vr technical spec_xmy.
	 *
	 * @return the xmy01800 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01800();

	/**
	 * Sets the xmy01800 of this vr technical spec_xmy.
	 *
	 * @param XMY01800 the xmy01800 of this vr technical spec_xmy
	 */
	public void setXMY01800(String XMY01800);

	/**
	 * Returns the xmy01801 of this vr technical spec_xmy.
	 *
	 * @return the xmy01801 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01801();

	/**
	 * Sets the xmy01801 of this vr technical spec_xmy.
	 *
	 * @param XMY01801 the xmy01801 of this vr technical spec_xmy
	 */
	public void setXMY01801(String XMY01801);

	/**
	 * Returns the xmy01802 of this vr technical spec_xmy.
	 *
	 * @return the xmy01802 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01802();

	/**
	 * Sets the xmy01802 of this vr technical spec_xmy.
	 *
	 * @param XMY01802 the xmy01802 of this vr technical spec_xmy
	 */
	public void setXMY01802(String XMY01802);

	/**
	 * Returns the xmy01804 of this vr technical spec_xmy.
	 *
	 * @return the xmy01804 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01804();

	/**
	 * Sets the xmy01804 of this vr technical spec_xmy.
	 *
	 * @param XMY01804 the xmy01804 of this vr technical spec_xmy
	 */
	public void setXMY01804(String XMY01804);

	/**
	 * Returns the xmy01805 of this vr technical spec_xmy.
	 *
	 * @return the xmy01805 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01805();

	/**
	 * Sets the xmy01805 of this vr technical spec_xmy.
	 *
	 * @param XMY01805 the xmy01805 of this vr technical spec_xmy
	 */
	public void setXMY01805(String XMY01805);

	/**
	 * Returns the xmy01806 of this vr technical spec_xmy.
	 *
	 * @return the xmy01806 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01806();

	/**
	 * Sets the xmy01806 of this vr technical spec_xmy.
	 *
	 * @param XMY01806 the xmy01806 of this vr technical spec_xmy
	 */
	public void setXMY01806(String XMY01806);

	/**
	 * Returns the xmy01807 of this vr technical spec_xmy.
	 *
	 * @return the xmy01807 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01807();

	/**
	 * Sets the xmy01807 of this vr technical spec_xmy.
	 *
	 * @param XMY01807 the xmy01807 of this vr technical spec_xmy
	 */
	public void setXMY01807(String XMY01807);

	/**
	 * Returns the xmy01808 of this vr technical spec_xmy.
	 *
	 * @return the xmy01808 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01808();

	/**
	 * Sets the xmy01808 of this vr technical spec_xmy.
	 *
	 * @param XMY01808 the xmy01808 of this vr technical spec_xmy
	 */
	public void setXMY01808(String XMY01808);

	/**
	 * Returns the xmy01809 of this vr technical spec_xmy.
	 *
	 * @return the xmy01809 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01809();

	/**
	 * Sets the xmy01809 of this vr technical spec_xmy.
	 *
	 * @param XMY01809 the xmy01809 of this vr technical spec_xmy
	 */
	public void setXMY01809(String XMY01809);

	/**
	 * Returns the xmy01810 of this vr technical spec_xmy.
	 *
	 * @return the xmy01810 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01810();

	/**
	 * Sets the xmy01810 of this vr technical spec_xmy.
	 *
	 * @param XMY01810 the xmy01810 of this vr technical spec_xmy
	 */
	public void setXMY01810(String XMY01810);

	/**
	 * Returns the xmy01811 of this vr technical spec_xmy.
	 *
	 * @return the xmy01811 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01811();

	/**
	 * Sets the xmy01811 of this vr technical spec_xmy.
	 *
	 * @param XMY01811 the xmy01811 of this vr technical spec_xmy
	 */
	public void setXMY01811(String XMY01811);

	/**
	 * Returns the xmy01812 of this vr technical spec_xmy.
	 *
	 * @return the xmy01812 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01812();

	/**
	 * Sets the xmy01812 of this vr technical spec_xmy.
	 *
	 * @param XMY01812 the xmy01812 of this vr technical spec_xmy
	 */
	public void setXMY01812(String XMY01812);

	/**
	 * Returns the xmy01813 of this vr technical spec_xmy.
	 *
	 * @return the xmy01813 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01813();

	/**
	 * Sets the xmy01813 of this vr technical spec_xmy.
	 *
	 * @param XMY01813 the xmy01813 of this vr technical spec_xmy
	 */
	public void setXMY01813(String XMY01813);

	/**
	 * Returns the xmy01814 of this vr technical spec_xmy.
	 *
	 * @return the xmy01814 of this vr technical spec_xmy
	 */
	@AutoEscape
	public String getXMY01814();

	/**
	 * Sets the xmy01814 of this vr technical spec_xmy.
	 *
	 * @param XMY01814 the xmy01814 of this vr technical spec_xmy
	 */
	public void setXMY01814(String XMY01814);

	/**
	 * Returns the modify date of this vr technical spec_xmy.
	 *
	 * @return the modify date of this vr technical spec_xmy
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_xmy.
	 *
	 * @param modifyDate the modify date of this vr technical spec_xmy
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_xmy.
	 *
	 * @return the sync date of this vr technical spec_xmy
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_xmy.
	 *
	 * @param syncDate the sync date of this vr technical spec_xmy
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_XMY vrTechnicalSpec_XMY);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_XMY> toCacheModel();

	@Override
	public VRTechnicalSpec_XMY toEscapedModel();

	@Override
	public VRTechnicalSpec_XMY toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}