/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_XCNPart2 service. Represents a row in the &quot;vr_technicalspec_xcnbb&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCNPart2ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XCNPart2Impl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XCNPart2
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCNPart2Impl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XCNPart2ModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_XCNPart2Model extends BaseModel<VRTechnicalSpec_XCNPart2> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_xcn part2 model instance should use the {@link VRTechnicalSpec_XCNPart2} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_xcn part2.
	 *
	 * @return the primary key of this vr technical spec_xcn part2
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_xcn part2.
	 *
	 * @param primaryKey the primary key of this vr technical spec_xcn part2
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_xcn part2.
	 *
	 * @return the ID of this vr technical spec_xcn part2
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_xcn part2.
	 *
	 * @param id the ID of this vr technical spec_xcn part2
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_xcn part2.
	 *
	 * @return the mt core of this vr technical spec_xcn part2
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_xcn part2.
	 *
	 * @param mtCore the mt core of this vr technical spec_xcn part2
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_xcn part2.
	 *
	 * @return the convert assemble ID of this vr technical spec_xcn part2
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_xcn part2.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_xcn part2
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_xcn part2.
	 *
	 * @return the dossier ID of this vr technical spec_xcn part2
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_xcn part2.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_xcn part2
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_xcn part2.
	 *
	 * @return the dossier no of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_xcn part2.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_xcn part2
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_xcn part2.
	 *
	 * @return the reference uid of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_xcn part2.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_xcn part2
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_xcn part2.
	 *
	 * @return the dossier ID ctn of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_xcn part2.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_xcn part2
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_xcn part2.
	 *
	 * @return the deliverable code of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_xcn part2.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_xcn part2
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_xcn part2.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_xcn part2
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_xcn part2.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_xcn part2
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the xcn01186 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01186 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01186();

	/**
	 * Sets the xcn01186 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01186 the xcn01186 of this vr technical spec_xcn part2
	 */
	public void setXCN01186(String XCN01186);

	/**
	 * Returns the xcn01187 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01187 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01187();

	/**
	 * Sets the xcn01187 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01187 the xcn01187 of this vr technical spec_xcn part2
	 */
	public void setXCN01187(String XCN01187);

	/**
	 * Returns the xcn01188 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01188 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01188();

	/**
	 * Sets the xcn01188 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01188 the xcn01188 of this vr technical spec_xcn part2
	 */
	public void setXCN01188(String XCN01188);

	/**
	 * Returns the xcn01189 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01189 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01189();

	/**
	 * Sets the xcn01189 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01189 the xcn01189 of this vr technical spec_xcn part2
	 */
	public void setXCN01189(String XCN01189);

	/**
	 * Returns the xcn01190 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01190 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01190();

	/**
	 * Sets the xcn01190 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01190 the xcn01190 of this vr technical spec_xcn part2
	 */
	public void setXCN01190(String XCN01190);

	/**
	 * Returns the xcn01191 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01191 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01191();

	/**
	 * Sets the xcn01191 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01191 the xcn01191 of this vr technical spec_xcn part2
	 */
	public void setXCN01191(String XCN01191);

	/**
	 * Returns the xcn01192 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01192 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01192();

	/**
	 * Sets the xcn01192 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01192 the xcn01192 of this vr technical spec_xcn part2
	 */
	public void setXCN01192(String XCN01192);

	/**
	 * Returns the xcn01193 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01193 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01193();

	/**
	 * Sets the xcn01193 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01193 the xcn01193 of this vr technical spec_xcn part2
	 */
	public void setXCN01193(String XCN01193);

	/**
	 * Returns the xcn01194 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01194 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01194();

	/**
	 * Sets the xcn01194 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01194 the xcn01194 of this vr technical spec_xcn part2
	 */
	public void setXCN01194(String XCN01194);

	/**
	 * Returns the xcn01195 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01195 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01195();

	/**
	 * Sets the xcn01195 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01195 the xcn01195 of this vr technical spec_xcn part2
	 */
	public void setXCN01195(String XCN01195);

	/**
	 * Returns the xcn01196 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01196 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01196();

	/**
	 * Sets the xcn01196 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01196 the xcn01196 of this vr technical spec_xcn part2
	 */
	public void setXCN01196(String XCN01196);

	/**
	 * Returns the xcn01197 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01197 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01197();

	/**
	 * Sets the xcn01197 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01197 the xcn01197 of this vr technical spec_xcn part2
	 */
	public void setXCN01197(String XCN01197);

	/**
	 * Returns the xcn01198 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01198 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01198();

	/**
	 * Sets the xcn01198 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01198 the xcn01198 of this vr technical spec_xcn part2
	 */
	public void setXCN01198(String XCN01198);

	/**
	 * Returns the xcn01199 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01199 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01199();

	/**
	 * Sets the xcn01199 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01199 the xcn01199 of this vr technical spec_xcn part2
	 */
	public void setXCN01199(String XCN01199);

	/**
	 * Returns the xcn01200 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01200 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01200();

	/**
	 * Sets the xcn01200 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01200 the xcn01200 of this vr technical spec_xcn part2
	 */
	public void setXCN01200(String XCN01200);

	/**
	 * Returns the xcn01201 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01201 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01201();

	/**
	 * Sets the xcn01201 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01201 the xcn01201 of this vr technical spec_xcn part2
	 */
	public void setXCN01201(String XCN01201);

	/**
	 * Returns the xcn01202 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01202 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01202();

	/**
	 * Sets the xcn01202 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01202 the xcn01202 of this vr technical spec_xcn part2
	 */
	public void setXCN01202(String XCN01202);

	/**
	 * Returns the xcn01203 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01203 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01203();

	/**
	 * Sets the xcn01203 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01203 the xcn01203 of this vr technical spec_xcn part2
	 */
	public void setXCN01203(String XCN01203);

	/**
	 * Returns the xcn01204 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01204 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01204();

	/**
	 * Sets the xcn01204 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01204 the xcn01204 of this vr technical spec_xcn part2
	 */
	public void setXCN01204(String XCN01204);

	/**
	 * Returns the xcn01205 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01205 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01205();

	/**
	 * Sets the xcn01205 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01205 the xcn01205 of this vr technical spec_xcn part2
	 */
	public void setXCN01205(String XCN01205);

	/**
	 * Returns the xcn01206 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01206 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01206();

	/**
	 * Sets the xcn01206 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01206 the xcn01206 of this vr technical spec_xcn part2
	 */
	public void setXCN01206(String XCN01206);

	/**
	 * Returns the xcn01207 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01207 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01207();

	/**
	 * Sets the xcn01207 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01207 the xcn01207 of this vr technical spec_xcn part2
	 */
	public void setXCN01207(String XCN01207);

	/**
	 * Returns the xcn01208 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01208 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01208();

	/**
	 * Sets the xcn01208 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01208 the xcn01208 of this vr technical spec_xcn part2
	 */
	public void setXCN01208(String XCN01208);

	/**
	 * Returns the xcn01209 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01209 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01209();

	/**
	 * Sets the xcn01209 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01209 the xcn01209 of this vr technical spec_xcn part2
	 */
	public void setXCN01209(String XCN01209);

	/**
	 * Returns the xcn01210 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01210 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01210();

	/**
	 * Sets the xcn01210 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01210 the xcn01210 of this vr technical spec_xcn part2
	 */
	public void setXCN01210(String XCN01210);

	/**
	 * Returns the xcn01211 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01211 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01211();

	/**
	 * Sets the xcn01211 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01211 the xcn01211 of this vr technical spec_xcn part2
	 */
	public void setXCN01211(String XCN01211);

	/**
	 * Returns the xcn01212 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01212 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01212();

	/**
	 * Sets the xcn01212 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01212 the xcn01212 of this vr technical spec_xcn part2
	 */
	public void setXCN01212(String XCN01212);

	/**
	 * Returns the xcn01213 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01213 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01213();

	/**
	 * Sets the xcn01213 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01213 the xcn01213 of this vr technical spec_xcn part2
	 */
	public void setXCN01213(String XCN01213);

	/**
	 * Returns the xcn01214 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01214 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01214();

	/**
	 * Sets the xcn01214 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01214 the xcn01214 of this vr technical spec_xcn part2
	 */
	public void setXCN01214(String XCN01214);

	/**
	 * Returns the xcn01215 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01215 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01215();

	/**
	 * Sets the xcn01215 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01215 the xcn01215 of this vr technical spec_xcn part2
	 */
	public void setXCN01215(String XCN01215);

	/**
	 * Returns the xcn01216 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01216 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01216();

	/**
	 * Sets the xcn01216 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01216 the xcn01216 of this vr technical spec_xcn part2
	 */
	public void setXCN01216(String XCN01216);

	/**
	 * Returns the xcn01217 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01217 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01217();

	/**
	 * Sets the xcn01217 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01217 the xcn01217 of this vr technical spec_xcn part2
	 */
	public void setXCN01217(String XCN01217);

	/**
	 * Returns the xcn01218 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01218 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01218();

	/**
	 * Sets the xcn01218 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01218 the xcn01218 of this vr technical spec_xcn part2
	 */
	public void setXCN01218(String XCN01218);

	/**
	 * Returns the xcn01219 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01219 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01219();

	/**
	 * Sets the xcn01219 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01219 the xcn01219 of this vr technical spec_xcn part2
	 */
	public void setXCN01219(String XCN01219);

	/**
	 * Returns the xcn01220 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01220 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01220();

	/**
	 * Sets the xcn01220 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01220 the xcn01220 of this vr technical spec_xcn part2
	 */
	public void setXCN01220(String XCN01220);

	/**
	 * Returns the xcn01221 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01221 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01221();

	/**
	 * Sets the xcn01221 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01221 the xcn01221 of this vr technical spec_xcn part2
	 */
	public void setXCN01221(String XCN01221);

	/**
	 * Returns the xcn01222 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01222 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01222();

	/**
	 * Sets the xcn01222 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01222 the xcn01222 of this vr technical spec_xcn part2
	 */
	public void setXCN01222(String XCN01222);

	/**
	 * Returns the xcn01223 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01223 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01223();

	/**
	 * Sets the xcn01223 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01223 the xcn01223 of this vr technical spec_xcn part2
	 */
	public void setXCN01223(String XCN01223);

	/**
	 * Returns the xcn01224 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01224 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01224();

	/**
	 * Sets the xcn01224 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01224 the xcn01224 of this vr technical spec_xcn part2
	 */
	public void setXCN01224(String XCN01224);

	/**
	 * Returns the xcn01225 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01225 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01225();

	/**
	 * Sets the xcn01225 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01225 the xcn01225 of this vr technical spec_xcn part2
	 */
	public void setXCN01225(String XCN01225);

	/**
	 * Returns the xcn01226 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01226 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01226();

	/**
	 * Sets the xcn01226 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01226 the xcn01226 of this vr technical spec_xcn part2
	 */
	public void setXCN01226(String XCN01226);

	/**
	 * Returns the xcn01227 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01227 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01227();

	/**
	 * Sets the xcn01227 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01227 the xcn01227 of this vr technical spec_xcn part2
	 */
	public void setXCN01227(String XCN01227);

	/**
	 * Returns the xcn01228 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01228 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01228();

	/**
	 * Sets the xcn01228 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01228 the xcn01228 of this vr technical spec_xcn part2
	 */
	public void setXCN01228(String XCN01228);

	/**
	 * Returns the xcn01229 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01229 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01229();

	/**
	 * Sets the xcn01229 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01229 the xcn01229 of this vr technical spec_xcn part2
	 */
	public void setXCN01229(String XCN01229);

	/**
	 * Returns the xcn01230 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01230 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01230();

	/**
	 * Sets the xcn01230 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01230 the xcn01230 of this vr technical spec_xcn part2
	 */
	public void setXCN01230(String XCN01230);

	/**
	 * Returns the xcn01231 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01231 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01231();

	/**
	 * Sets the xcn01231 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01231 the xcn01231 of this vr technical spec_xcn part2
	 */
	public void setXCN01231(String XCN01231);

	/**
	 * Returns the xcn01232 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01232 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01232();

	/**
	 * Sets the xcn01232 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01232 the xcn01232 of this vr technical spec_xcn part2
	 */
	public void setXCN01232(String XCN01232);

	/**
	 * Returns the xcn01233 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01233 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01233();

	/**
	 * Sets the xcn01233 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01233 the xcn01233 of this vr technical spec_xcn part2
	 */
	public void setXCN01233(String XCN01233);

	/**
	 * Returns the xcn01234 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01234 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01234();

	/**
	 * Sets the xcn01234 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01234 the xcn01234 of this vr technical spec_xcn part2
	 */
	public void setXCN01234(String XCN01234);

	/**
	 * Returns the xcn01235 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01235 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01235();

	/**
	 * Sets the xcn01235 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01235 the xcn01235 of this vr technical spec_xcn part2
	 */
	public void setXCN01235(String XCN01235);

	/**
	 * Returns the xcn01236 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01236 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01236();

	/**
	 * Sets the xcn01236 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01236 the xcn01236 of this vr technical spec_xcn part2
	 */
	public void setXCN01236(String XCN01236);

	/**
	 * Returns the xcn01237 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01237 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01237();

	/**
	 * Sets the xcn01237 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01237 the xcn01237 of this vr technical spec_xcn part2
	 */
	public void setXCN01237(String XCN01237);

	/**
	 * Returns the xcn01238 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01238 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01238();

	/**
	 * Sets the xcn01238 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01238 the xcn01238 of this vr technical spec_xcn part2
	 */
	public void setXCN01238(String XCN01238);

	/**
	 * Returns the xcn01239 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01239 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01239();

	/**
	 * Sets the xcn01239 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01239 the xcn01239 of this vr technical spec_xcn part2
	 */
	public void setXCN01239(String XCN01239);

	/**
	 * Returns the xcn01240 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01240 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01240();

	/**
	 * Sets the xcn01240 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01240 the xcn01240 of this vr technical spec_xcn part2
	 */
	public void setXCN01240(String XCN01240);

	/**
	 * Returns the xcn01241 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01241 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01241();

	/**
	 * Sets the xcn01241 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01241 the xcn01241 of this vr technical spec_xcn part2
	 */
	public void setXCN01241(String XCN01241);

	/**
	 * Returns the xcn01242 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01242 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01242();

	/**
	 * Sets the xcn01242 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01242 the xcn01242 of this vr technical spec_xcn part2
	 */
	public void setXCN01242(String XCN01242);

	/**
	 * Returns the xcn01243 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01243 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01243();

	/**
	 * Sets the xcn01243 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01243 the xcn01243 of this vr technical spec_xcn part2
	 */
	public void setXCN01243(String XCN01243);

	/**
	 * Returns the xcn01244 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01244 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01244();

	/**
	 * Sets the xcn01244 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01244 the xcn01244 of this vr technical spec_xcn part2
	 */
	public void setXCN01244(String XCN01244);

	/**
	 * Returns the xcn01245 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01245 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01245();

	/**
	 * Sets the xcn01245 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01245 the xcn01245 of this vr technical spec_xcn part2
	 */
	public void setXCN01245(String XCN01245);

	/**
	 * Returns the xcn01246 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01246 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01246();

	/**
	 * Sets the xcn01246 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01246 the xcn01246 of this vr technical spec_xcn part2
	 */
	public void setXCN01246(String XCN01246);

	/**
	 * Returns the xcn01247 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01247 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01247();

	/**
	 * Sets the xcn01247 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01247 the xcn01247 of this vr technical spec_xcn part2
	 */
	public void setXCN01247(String XCN01247);

	/**
	 * Returns the xcn01248 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01248 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01248();

	/**
	 * Sets the xcn01248 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01248 the xcn01248 of this vr technical spec_xcn part2
	 */
	public void setXCN01248(String XCN01248);

	/**
	 * Returns the xcn01249 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01249 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01249();

	/**
	 * Sets the xcn01249 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01249 the xcn01249 of this vr technical spec_xcn part2
	 */
	public void setXCN01249(String XCN01249);

	/**
	 * Returns the xcn01250 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01250 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01250();

	/**
	 * Sets the xcn01250 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01250 the xcn01250 of this vr technical spec_xcn part2
	 */
	public void setXCN01250(String XCN01250);

	/**
	 * Returns the xcn01251 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01251 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01251();

	/**
	 * Sets the xcn01251 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01251 the xcn01251 of this vr technical spec_xcn part2
	 */
	public void setXCN01251(String XCN01251);

	/**
	 * Returns the xcn01252 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01252 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01252();

	/**
	 * Sets the xcn01252 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01252 the xcn01252 of this vr technical spec_xcn part2
	 */
	public void setXCN01252(String XCN01252);

	/**
	 * Returns the xcn01253 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01253 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01253();

	/**
	 * Sets the xcn01253 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01253 the xcn01253 of this vr technical spec_xcn part2
	 */
	public void setXCN01253(String XCN01253);

	/**
	 * Returns the xcn01254 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01254 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01254();

	/**
	 * Sets the xcn01254 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01254 the xcn01254 of this vr technical spec_xcn part2
	 */
	public void setXCN01254(String XCN01254);

	/**
	 * Returns the xcn01255 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01255 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01255();

	/**
	 * Sets the xcn01255 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01255 the xcn01255 of this vr technical spec_xcn part2
	 */
	public void setXCN01255(String XCN01255);

	/**
	 * Returns the xcn01256 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01256 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01256();

	/**
	 * Sets the xcn01256 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01256 the xcn01256 of this vr technical spec_xcn part2
	 */
	public void setXCN01256(String XCN01256);

	/**
	 * Returns the xcn01257 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01257 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01257();

	/**
	 * Sets the xcn01257 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01257 the xcn01257 of this vr technical spec_xcn part2
	 */
	public void setXCN01257(String XCN01257);

	/**
	 * Returns the xcn01258 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01258 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01258();

	/**
	 * Sets the xcn01258 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01258 the xcn01258 of this vr technical spec_xcn part2
	 */
	public void setXCN01258(String XCN01258);

	/**
	 * Returns the xcn01259 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01259 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01259();

	/**
	 * Sets the xcn01259 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01259 the xcn01259 of this vr technical spec_xcn part2
	 */
	public void setXCN01259(String XCN01259);

	/**
	 * Returns the xcn01260 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01260 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01260();

	/**
	 * Sets the xcn01260 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01260 the xcn01260 of this vr technical spec_xcn part2
	 */
	public void setXCN01260(String XCN01260);

	/**
	 * Returns the xcn01261 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01261 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01261();

	/**
	 * Sets the xcn01261 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01261 the xcn01261 of this vr technical spec_xcn part2
	 */
	public void setXCN01261(String XCN01261);

	/**
	 * Returns the xcn01262 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01262 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01262();

	/**
	 * Sets the xcn01262 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01262 the xcn01262 of this vr technical spec_xcn part2
	 */
	public void setXCN01262(String XCN01262);

	/**
	 * Returns the xcn01263 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01263 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01263();

	/**
	 * Sets the xcn01263 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01263 the xcn01263 of this vr technical spec_xcn part2
	 */
	public void setXCN01263(String XCN01263);

	/**
	 * Returns the xcn01264 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01264 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01264();

	/**
	 * Sets the xcn01264 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01264 the xcn01264 of this vr technical spec_xcn part2
	 */
	public void setXCN01264(String XCN01264);

	/**
	 * Returns the xcn01265 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01265 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01265();

	/**
	 * Sets the xcn01265 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01265 the xcn01265 of this vr technical spec_xcn part2
	 */
	public void setXCN01265(String XCN01265);

	/**
	 * Returns the xcn01266 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01266 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01266();

	/**
	 * Sets the xcn01266 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01266 the xcn01266 of this vr technical spec_xcn part2
	 */
	public void setXCN01266(String XCN01266);

	/**
	 * Returns the xcn01267 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01267 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01267();

	/**
	 * Sets the xcn01267 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01267 the xcn01267 of this vr technical spec_xcn part2
	 */
	public void setXCN01267(String XCN01267);

	/**
	 * Returns the xcn01268 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01268 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01268();

	/**
	 * Sets the xcn01268 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01268 the xcn01268 of this vr technical spec_xcn part2
	 */
	public void setXCN01268(String XCN01268);

	/**
	 * Returns the xcn01269 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01269 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01269();

	/**
	 * Sets the xcn01269 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01269 the xcn01269 of this vr technical spec_xcn part2
	 */
	public void setXCN01269(String XCN01269);

	/**
	 * Returns the xcn01270 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01270 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01270();

	/**
	 * Sets the xcn01270 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01270 the xcn01270 of this vr technical spec_xcn part2
	 */
	public void setXCN01270(String XCN01270);

	/**
	 * Returns the xcn01271 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01271 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01271();

	/**
	 * Sets the xcn01271 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01271 the xcn01271 of this vr technical spec_xcn part2
	 */
	public void setXCN01271(String XCN01271);

	/**
	 * Returns the xcn01272 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01272 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01272();

	/**
	 * Sets the xcn01272 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01272 the xcn01272 of this vr technical spec_xcn part2
	 */
	public void setXCN01272(String XCN01272);

	/**
	 * Returns the xcn01273 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01273 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01273();

	/**
	 * Sets the xcn01273 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01273 the xcn01273 of this vr technical spec_xcn part2
	 */
	public void setXCN01273(String XCN01273);

	/**
	 * Returns the xcn01274 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01274 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01274();

	/**
	 * Sets the xcn01274 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01274 the xcn01274 of this vr technical spec_xcn part2
	 */
	public void setXCN01274(String XCN01274);

	/**
	 * Returns the xcn01275 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01275 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01275();

	/**
	 * Sets the xcn01275 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01275 the xcn01275 of this vr technical spec_xcn part2
	 */
	public void setXCN01275(String XCN01275);

	/**
	 * Returns the xcn01276 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01276 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01276();

	/**
	 * Sets the xcn01276 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01276 the xcn01276 of this vr technical spec_xcn part2
	 */
	public void setXCN01276(String XCN01276);

	/**
	 * Returns the xcn01277 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01277 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01277();

	/**
	 * Sets the xcn01277 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01277 the xcn01277 of this vr technical spec_xcn part2
	 */
	public void setXCN01277(String XCN01277);

	/**
	 * Returns the xcn01278 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01278 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01278();

	/**
	 * Sets the xcn01278 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01278 the xcn01278 of this vr technical spec_xcn part2
	 */
	public void setXCN01278(String XCN01278);

	/**
	 * Returns the xcn01279 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01279 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01279();

	/**
	 * Sets the xcn01279 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01279 the xcn01279 of this vr technical spec_xcn part2
	 */
	public void setXCN01279(String XCN01279);

	/**
	 * Returns the xcn01280 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01280 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01280();

	/**
	 * Sets the xcn01280 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01280 the xcn01280 of this vr technical spec_xcn part2
	 */
	public void setXCN01280(String XCN01280);

	/**
	 * Returns the xcn01281 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01281 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01281();

	/**
	 * Sets the xcn01281 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01281 the xcn01281 of this vr technical spec_xcn part2
	 */
	public void setXCN01281(String XCN01281);

	/**
	 * Returns the xcn01282 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01282 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01282();

	/**
	 * Sets the xcn01282 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01282 the xcn01282 of this vr technical spec_xcn part2
	 */
	public void setXCN01282(String XCN01282);

	/**
	 * Returns the xcn01283 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01283 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01283();

	/**
	 * Sets the xcn01283 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01283 the xcn01283 of this vr technical spec_xcn part2
	 */
	public void setXCN01283(String XCN01283);

	/**
	 * Returns the xcn01284 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01284 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01284();

	/**
	 * Sets the xcn01284 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01284 the xcn01284 of this vr technical spec_xcn part2
	 */
	public void setXCN01284(String XCN01284);

	/**
	 * Returns the xcn01285 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01285 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01285();

	/**
	 * Sets the xcn01285 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01285 the xcn01285 of this vr technical spec_xcn part2
	 */
	public void setXCN01285(String XCN01285);

	/**
	 * Returns the xcn01286 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01286 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01286();

	/**
	 * Sets the xcn01286 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01286 the xcn01286 of this vr technical spec_xcn part2
	 */
	public void setXCN01286(String XCN01286);

	/**
	 * Returns the xcn01287 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01287 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01287();

	/**
	 * Sets the xcn01287 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01287 the xcn01287 of this vr technical spec_xcn part2
	 */
	public void setXCN01287(String XCN01287);

	/**
	 * Returns the xcn01288 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01288 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01288();

	/**
	 * Sets the xcn01288 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01288 the xcn01288 of this vr technical spec_xcn part2
	 */
	public void setXCN01288(String XCN01288);

	/**
	 * Returns the xcn01289 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01289 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01289();

	/**
	 * Sets the xcn01289 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01289 the xcn01289 of this vr technical spec_xcn part2
	 */
	public void setXCN01289(String XCN01289);

	/**
	 * Returns the xcn01290 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01290 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01290();

	/**
	 * Sets the xcn01290 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01290 the xcn01290 of this vr technical spec_xcn part2
	 */
	public void setXCN01290(String XCN01290);

	/**
	 * Returns the xcn01291 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01291 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01291();

	/**
	 * Sets the xcn01291 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01291 the xcn01291 of this vr technical spec_xcn part2
	 */
	public void setXCN01291(String XCN01291);

	/**
	 * Returns the xcn01292 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01292 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01292();

	/**
	 * Sets the xcn01292 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01292 the xcn01292 of this vr technical spec_xcn part2
	 */
	public void setXCN01292(String XCN01292);

	/**
	 * Returns the xcn01293 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01293 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01293();

	/**
	 * Sets the xcn01293 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01293 the xcn01293 of this vr technical spec_xcn part2
	 */
	public void setXCN01293(String XCN01293);

	/**
	 * Returns the xcn01294 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01294 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01294();

	/**
	 * Sets the xcn01294 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01294 the xcn01294 of this vr technical spec_xcn part2
	 */
	public void setXCN01294(String XCN01294);

	/**
	 * Returns the xcn01295 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01295 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01295();

	/**
	 * Sets the xcn01295 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01295 the xcn01295 of this vr technical spec_xcn part2
	 */
	public void setXCN01295(String XCN01295);

	/**
	 * Returns the xcn01296 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01296 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01296();

	/**
	 * Sets the xcn01296 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01296 the xcn01296 of this vr technical spec_xcn part2
	 */
	public void setXCN01296(String XCN01296);

	/**
	 * Returns the xcn01297 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01297 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01297();

	/**
	 * Sets the xcn01297 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01297 the xcn01297 of this vr technical spec_xcn part2
	 */
	public void setXCN01297(String XCN01297);

	/**
	 * Returns the xcn01298 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01298 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01298();

	/**
	 * Sets the xcn01298 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01298 the xcn01298 of this vr technical spec_xcn part2
	 */
	public void setXCN01298(String XCN01298);

	/**
	 * Returns the xcn01299 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01299 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01299();

	/**
	 * Sets the xcn01299 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01299 the xcn01299 of this vr technical spec_xcn part2
	 */
	public void setXCN01299(String XCN01299);

	/**
	 * Returns the xcn01300 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01300 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01300();

	/**
	 * Sets the xcn01300 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01300 the xcn01300 of this vr technical spec_xcn part2
	 */
	public void setXCN01300(String XCN01300);

	/**
	 * Returns the xcn01301 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01301 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01301();

	/**
	 * Sets the xcn01301 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01301 the xcn01301 of this vr technical spec_xcn part2
	 */
	public void setXCN01301(String XCN01301);

	/**
	 * Returns the xcn01302 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01302 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01302();

	/**
	 * Sets the xcn01302 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01302 the xcn01302 of this vr technical spec_xcn part2
	 */
	public void setXCN01302(String XCN01302);

	/**
	 * Returns the xcn01303 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01303 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01303();

	/**
	 * Sets the xcn01303 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01303 the xcn01303 of this vr technical spec_xcn part2
	 */
	public void setXCN01303(String XCN01303);

	/**
	 * Returns the xcn01304 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01304 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01304();

	/**
	 * Sets the xcn01304 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01304 the xcn01304 of this vr technical spec_xcn part2
	 */
	public void setXCN01304(String XCN01304);

	/**
	 * Returns the xcn01305 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01305 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01305();

	/**
	 * Sets the xcn01305 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01305 the xcn01305 of this vr technical spec_xcn part2
	 */
	public void setXCN01305(String XCN01305);

	/**
	 * Returns the xcn01306 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01306 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01306();

	/**
	 * Sets the xcn01306 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01306 the xcn01306 of this vr technical spec_xcn part2
	 */
	public void setXCN01306(String XCN01306);

	/**
	 * Returns the xcn01307 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01307 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01307();

	/**
	 * Sets the xcn01307 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01307 the xcn01307 of this vr technical spec_xcn part2
	 */
	public void setXCN01307(String XCN01307);

	/**
	 * Returns the xcn01308 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01308 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01308();

	/**
	 * Sets the xcn01308 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01308 the xcn01308 of this vr technical spec_xcn part2
	 */
	public void setXCN01308(String XCN01308);

	/**
	 * Returns the xcn01309 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01309 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01309();

	/**
	 * Sets the xcn01309 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01309 the xcn01309 of this vr technical spec_xcn part2
	 */
	public void setXCN01309(String XCN01309);

	/**
	 * Returns the xcn01310 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01310 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01310();

	/**
	 * Sets the xcn01310 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01310 the xcn01310 of this vr technical spec_xcn part2
	 */
	public void setXCN01310(String XCN01310);

	/**
	 * Returns the xcn01311 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01311 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01311();

	/**
	 * Sets the xcn01311 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01311 the xcn01311 of this vr technical spec_xcn part2
	 */
	public void setXCN01311(String XCN01311);

	/**
	 * Returns the xcn01312 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01312 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01312();

	/**
	 * Sets the xcn01312 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01312 the xcn01312 of this vr technical spec_xcn part2
	 */
	public void setXCN01312(String XCN01312);

	/**
	 * Returns the xcn01313 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01313 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01313();

	/**
	 * Sets the xcn01313 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01313 the xcn01313 of this vr technical spec_xcn part2
	 */
	public void setXCN01313(String XCN01313);

	/**
	 * Returns the xcn01314 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01314 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01314();

	/**
	 * Sets the xcn01314 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01314 the xcn01314 of this vr technical spec_xcn part2
	 */
	public void setXCN01314(String XCN01314);

	/**
	 * Returns the xcn01315 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01315 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01315();

	/**
	 * Sets the xcn01315 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01315 the xcn01315 of this vr technical spec_xcn part2
	 */
	public void setXCN01315(String XCN01315);

	/**
	 * Returns the xcn01316 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01316 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01316();

	/**
	 * Sets the xcn01316 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01316 the xcn01316 of this vr technical spec_xcn part2
	 */
	public void setXCN01316(String XCN01316);

	/**
	 * Returns the xcn01317 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01317 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01317();

	/**
	 * Sets the xcn01317 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01317 the xcn01317 of this vr technical spec_xcn part2
	 */
	public void setXCN01317(String XCN01317);

	/**
	 * Returns the xcn01318 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01318 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01318();

	/**
	 * Sets the xcn01318 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01318 the xcn01318 of this vr technical spec_xcn part2
	 */
	public void setXCN01318(String XCN01318);

	/**
	 * Returns the xcn01319 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01319 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01319();

	/**
	 * Sets the xcn01319 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01319 the xcn01319 of this vr technical spec_xcn part2
	 */
	public void setXCN01319(String XCN01319);

	/**
	 * Returns the xcn01320 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01320 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01320();

	/**
	 * Sets the xcn01320 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01320 the xcn01320 of this vr technical spec_xcn part2
	 */
	public void setXCN01320(String XCN01320);

	/**
	 * Returns the xcn01321 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01321 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01321();

	/**
	 * Sets the xcn01321 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01321 the xcn01321 of this vr technical spec_xcn part2
	 */
	public void setXCN01321(String XCN01321);

	/**
	 * Returns the xcn01322 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01322 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01322();

	/**
	 * Sets the xcn01322 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01322 the xcn01322 of this vr technical spec_xcn part2
	 */
	public void setXCN01322(String XCN01322);

	/**
	 * Returns the xcn01323 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01323 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01323();

	/**
	 * Sets the xcn01323 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01323 the xcn01323 of this vr technical spec_xcn part2
	 */
	public void setXCN01323(String XCN01323);

	/**
	 * Returns the xcn01324 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01324 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01324();

	/**
	 * Sets the xcn01324 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01324 the xcn01324 of this vr technical spec_xcn part2
	 */
	public void setXCN01324(String XCN01324);

	/**
	 * Returns the xcn01325 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01325 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01325();

	/**
	 * Sets the xcn01325 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01325 the xcn01325 of this vr technical spec_xcn part2
	 */
	public void setXCN01325(String XCN01325);

	/**
	 * Returns the xcn01326 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01326 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01326();

	/**
	 * Sets the xcn01326 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01326 the xcn01326 of this vr technical spec_xcn part2
	 */
	public void setXCN01326(String XCN01326);

	/**
	 * Returns the xcn01327 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01327 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01327();

	/**
	 * Sets the xcn01327 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01327 the xcn01327 of this vr technical spec_xcn part2
	 */
	public void setXCN01327(String XCN01327);

	/**
	 * Returns the xcn01328 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01328 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01328();

	/**
	 * Sets the xcn01328 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01328 the xcn01328 of this vr technical spec_xcn part2
	 */
	public void setXCN01328(String XCN01328);

	/**
	 * Returns the xcn01329 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01329 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01329();

	/**
	 * Sets the xcn01329 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01329 the xcn01329 of this vr technical spec_xcn part2
	 */
	public void setXCN01329(String XCN01329);

	/**
	 * Returns the xcn01330 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01330 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01330();

	/**
	 * Sets the xcn01330 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01330 the xcn01330 of this vr technical spec_xcn part2
	 */
	public void setXCN01330(String XCN01330);

	/**
	 * Returns the xcn01331 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01331 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01331();

	/**
	 * Sets the xcn01331 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01331 the xcn01331 of this vr technical spec_xcn part2
	 */
	public void setXCN01331(String XCN01331);

	/**
	 * Returns the xcn01332 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01332 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01332();

	/**
	 * Sets the xcn01332 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01332 the xcn01332 of this vr technical spec_xcn part2
	 */
	public void setXCN01332(String XCN01332);

	/**
	 * Returns the xcn01333 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01333 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01333();

	/**
	 * Sets the xcn01333 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01333 the xcn01333 of this vr technical spec_xcn part2
	 */
	public void setXCN01333(String XCN01333);

	/**
	 * Returns the xcn01334 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01334 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01334();

	/**
	 * Sets the xcn01334 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01334 the xcn01334 of this vr technical spec_xcn part2
	 */
	public void setXCN01334(String XCN01334);

	/**
	 * Returns the xcn01335 of this vr technical spec_xcn part2.
	 *
	 * @return the xcn01335 of this vr technical spec_xcn part2
	 */
	@AutoEscape
	public String getXCN01335();

	/**
	 * Sets the xcn01335 of this vr technical spec_xcn part2.
	 *
	 * @param XCN01335 the xcn01335 of this vr technical spec_xcn part2
	 */
	public void setXCN01335(String XCN01335);

	/**
	 * Returns the modify date of this vr technical spec_xcn part2.
	 *
	 * @return the modify date of this vr technical spec_xcn part2
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_xcn part2.
	 *
	 * @param modifyDate the modify date of this vr technical spec_xcn part2
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_xcn part2.
	 *
	 * @return the sync date of this vr technical spec_xcn part2
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_xcn part2.
	 *
	 * @param syncDate the sync date of this vr technical spec_xcn part2
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_XCNPart2 vrTechnicalSpec_XCNPart2);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_XCNPart2> toCacheModel();

	@Override
	public VRTechnicalSpec_XCNPart2 toEscapedModel();

	@Override
	public VRTechnicalSpec_XCNPart2 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}