/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTechnicalSpec_XMYPart3 service. Represents a row in the &quot;vr_technicalspec_xmy&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XMYPart3ModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTechnicalSpec_XMYPart3Impl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XMYPart3
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XMYPart3Impl
 * @see com.fds.vr.business.model.impl.VRTechnicalSpec_XMYPart3ModelImpl
 * @generated
 */
@ProviderType
public interface VRTechnicalSpec_XMYPart3Model extends BaseModel<VRTechnicalSpec_XMYPart3> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr technical spec_xmy part3 model instance should use the {@link VRTechnicalSpec_XMYPart3} interface instead.
	 */

	/**
	 * Returns the primary key of this vr technical spec_xmy part3.
	 *
	 * @return the primary key of this vr technical spec_xmy part3
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr technical spec_xmy part3.
	 *
	 * @param primaryKey the primary key of this vr technical spec_xmy part3
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr technical spec_xmy part3.
	 *
	 * @return the ID of this vr technical spec_xmy part3
	 */
	public long getId();

	/**
	 * Sets the ID of this vr technical spec_xmy part3.
	 *
	 * @param id the ID of this vr technical spec_xmy part3
	 */
	public void setId(long id);

	/**
	 * Returns the mt core of this vr technical spec_xmy part3.
	 *
	 * @return the mt core of this vr technical spec_xmy part3
	 */
	public long getMtCore();

	/**
	 * Sets the mt core of this vr technical spec_xmy part3.
	 *
	 * @param mtCore the mt core of this vr technical spec_xmy part3
	 */
	public void setMtCore(long mtCore);

	/**
	 * Returns the convert assemble ID of this vr technical spec_xmy part3.
	 *
	 * @return the convert assemble ID of this vr technical spec_xmy part3
	 */
	public long getConvertAssembleId();

	/**
	 * Sets the convert assemble ID of this vr technical spec_xmy part3.
	 *
	 * @param convertAssembleId the convert assemble ID of this vr technical spec_xmy part3
	 */
	public void setConvertAssembleId(long convertAssembleId);

	/**
	 * Returns the dossier ID of this vr technical spec_xmy part3.
	 *
	 * @return the dossier ID of this vr technical spec_xmy part3
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr technical spec_xmy part3.
	 *
	 * @param dossierId the dossier ID of this vr technical spec_xmy part3
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier no of this vr technical spec_xmy part3.
	 *
	 * @return the dossier no of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr technical spec_xmy part3.
	 *
	 * @param dossierNo the dossier no of this vr technical spec_xmy part3
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the reference uid of this vr technical spec_xmy part3.
	 *
	 * @return the reference uid of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getReferenceUid();

	/**
	 * Sets the reference uid of this vr technical spec_xmy part3.
	 *
	 * @param referenceUid the reference uid of this vr technical spec_xmy part3
	 */
	public void setReferenceUid(String referenceUid);

	/**
	 * Returns the dossier ID ctn of this vr technical spec_xmy part3.
	 *
	 * @return the dossier ID ctn of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr technical spec_xmy part3.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr technical spec_xmy part3
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the deliverable code of this vr technical spec_xmy part3.
	 *
	 * @return the deliverable code of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getDeliverableCode();

	/**
	 * Sets the deliverable code of this vr technical spec_xmy part3.
	 *
	 * @param deliverableCode the deliverable code of this vr technical spec_xmy part3
	 */
	public void setDeliverableCode(String deliverableCode);

	/**
	 * Returns the vehicle type certificate ID of this vr technical spec_xmy part3.
	 *
	 * @return the vehicle type certificate ID of this vr technical spec_xmy part3
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr technical spec_xmy part3.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr technical spec_xmy part3
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the xmy0149 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0149 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0149();

	/**
	 * Sets the xmy0149 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0149 the xmy0149 of this vr technical spec_xmy part3
	 */
	public void setXMY0149(String XMY0149);

	/**
	 * Returns the xmy0150 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0150 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0150();

	/**
	 * Sets the xmy0150 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0150 the xmy0150 of this vr technical spec_xmy part3
	 */
	public void setXMY0150(String XMY0150);

	/**
	 * Returns the xmy0151 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0151 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0151();

	/**
	 * Sets the xmy0151 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0151 the xmy0151 of this vr technical spec_xmy part3
	 */
	public void setXMY0151(String XMY0151);

	/**
	 * Returns the xmy0152 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0152 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0152();

	/**
	 * Sets the xmy0152 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0152 the xmy0152 of this vr technical spec_xmy part3
	 */
	public void setXMY0152(String XMY0152);

	/**
	 * Returns the xmy0153 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0153 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0153();

	/**
	 * Sets the xmy0153 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0153 the xmy0153 of this vr technical spec_xmy part3
	 */
	public void setXMY0153(String XMY0153);

	/**
	 * Returns the xmy0154 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0154 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0154();

	/**
	 * Sets the xmy0154 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0154 the xmy0154 of this vr technical spec_xmy part3
	 */
	public void setXMY0154(String XMY0154);

	/**
	 * Returns the xmy0155 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0155 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0155();

	/**
	 * Sets the xmy0155 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0155 the xmy0155 of this vr technical spec_xmy part3
	 */
	public void setXMY0155(String XMY0155);

	/**
	 * Returns the xmy0156 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0156 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0156();

	/**
	 * Sets the xmy0156 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0156 the xmy0156 of this vr technical spec_xmy part3
	 */
	public void setXMY0156(String XMY0156);

	/**
	 * Returns the xmy0157 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0157 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0157();

	/**
	 * Sets the xmy0157 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0157 the xmy0157 of this vr technical spec_xmy part3
	 */
	public void setXMY0157(String XMY0157);

	/**
	 * Returns the xmy0158 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0158 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0158();

	/**
	 * Sets the xmy0158 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0158 the xmy0158 of this vr technical spec_xmy part3
	 */
	public void setXMY0158(String XMY0158);

	/**
	 * Returns the xmy0159 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0159 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0159();

	/**
	 * Sets the xmy0159 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0159 the xmy0159 of this vr technical spec_xmy part3
	 */
	public void setXMY0159(String XMY0159);

	/**
	 * Returns the xmy0160 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0160 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0160();

	/**
	 * Sets the xmy0160 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0160 the xmy0160 of this vr technical spec_xmy part3
	 */
	public void setXMY0160(String XMY0160);

	/**
	 * Returns the xmy0161 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0161 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0161();

	/**
	 * Sets the xmy0161 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0161 the xmy0161 of this vr technical spec_xmy part3
	 */
	public void setXMY0161(String XMY0161);

	/**
	 * Returns the xmy0162 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0162 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0162();

	/**
	 * Sets the xmy0162 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0162 the xmy0162 of this vr technical spec_xmy part3
	 */
	public void setXMY0162(String XMY0162);

	/**
	 * Returns the xmy0163 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0163 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0163();

	/**
	 * Sets the xmy0163 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0163 the xmy0163 of this vr technical spec_xmy part3
	 */
	public void setXMY0163(String XMY0163);

	/**
	 * Returns the xmy0164 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0164 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0164();

	/**
	 * Sets the xmy0164 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0164 the xmy0164 of this vr technical spec_xmy part3
	 */
	public void setXMY0164(String XMY0164);

	/**
	 * Returns the xmy0165 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0165 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0165();

	/**
	 * Sets the xmy0165 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0165 the xmy0165 of this vr technical spec_xmy part3
	 */
	public void setXMY0165(String XMY0165);

	/**
	 * Returns the xmy0166 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0166 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0166();

	/**
	 * Sets the xmy0166 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0166 the xmy0166 of this vr technical spec_xmy part3
	 */
	public void setXMY0166(String XMY0166);

	/**
	 * Returns the xmy0167 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0167 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0167();

	/**
	 * Sets the xmy0167 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0167 the xmy0167 of this vr technical spec_xmy part3
	 */
	public void setXMY0167(String XMY0167);

	/**
	 * Returns the xmy0168 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0168 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0168();

	/**
	 * Sets the xmy0168 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0168 the xmy0168 of this vr technical spec_xmy part3
	 */
	public void setXMY0168(String XMY0168);

	/**
	 * Returns the xmy0169 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0169 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0169();

	/**
	 * Sets the xmy0169 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0169 the xmy0169 of this vr technical spec_xmy part3
	 */
	public void setXMY0169(String XMY0169);

	/**
	 * Returns the xmy0170 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0170 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0170();

	/**
	 * Sets the xmy0170 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0170 the xmy0170 of this vr technical spec_xmy part3
	 */
	public void setXMY0170(String XMY0170);

	/**
	 * Returns the xmy0171 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0171 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0171();

	/**
	 * Sets the xmy0171 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0171 the xmy0171 of this vr technical spec_xmy part3
	 */
	public void setXMY0171(String XMY0171);

	/**
	 * Returns the xmy0172 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0172 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0172();

	/**
	 * Sets the xmy0172 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0172 the xmy0172 of this vr technical spec_xmy part3
	 */
	public void setXMY0172(String XMY0172);

	/**
	 * Returns the xmy0173 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0173 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0173();

	/**
	 * Sets the xmy0173 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0173 the xmy0173 of this vr technical spec_xmy part3
	 */
	public void setXMY0173(String XMY0173);

	/**
	 * Returns the xmy0174 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0174 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0174();

	/**
	 * Sets the xmy0174 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0174 the xmy0174 of this vr technical spec_xmy part3
	 */
	public void setXMY0174(String XMY0174);

	/**
	 * Returns the xmy0175 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0175 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0175();

	/**
	 * Sets the xmy0175 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0175 the xmy0175 of this vr technical spec_xmy part3
	 */
	public void setXMY0175(String XMY0175);

	/**
	 * Returns the xmy0176 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0176 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0176();

	/**
	 * Sets the xmy0176 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0176 the xmy0176 of this vr technical spec_xmy part3
	 */
	public void setXMY0176(String XMY0176);

	/**
	 * Returns the xmy0177 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0177 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0177();

	/**
	 * Sets the xmy0177 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0177 the xmy0177 of this vr technical spec_xmy part3
	 */
	public void setXMY0177(String XMY0177);

	/**
	 * Returns the xmy0178 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0178 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0178();

	/**
	 * Sets the xmy0178 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0178 the xmy0178 of this vr technical spec_xmy part3
	 */
	public void setXMY0178(String XMY0178);

	/**
	 * Returns the xmy0179 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0179 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0179();

	/**
	 * Sets the xmy0179 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0179 the xmy0179 of this vr technical spec_xmy part3
	 */
	public void setXMY0179(String XMY0179);

	/**
	 * Returns the xmy0180 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0180 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0180();

	/**
	 * Sets the xmy0180 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0180 the xmy0180 of this vr technical spec_xmy part3
	 */
	public void setXMY0180(String XMY0180);

	/**
	 * Returns the xmy0181 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0181 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0181();

	/**
	 * Sets the xmy0181 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0181 the xmy0181 of this vr technical spec_xmy part3
	 */
	public void setXMY0181(String XMY0181);

	/**
	 * Returns the xmy0182 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0182 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0182();

	/**
	 * Sets the xmy0182 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0182 the xmy0182 of this vr technical spec_xmy part3
	 */
	public void setXMY0182(String XMY0182);

	/**
	 * Returns the xmy0183 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0183 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0183();

	/**
	 * Sets the xmy0183 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0183 the xmy0183 of this vr technical spec_xmy part3
	 */
	public void setXMY0183(String XMY0183);

	/**
	 * Returns the xmy0184 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0184 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0184();

	/**
	 * Sets the xmy0184 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0184 the xmy0184 of this vr technical spec_xmy part3
	 */
	public void setXMY0184(String XMY0184);

	/**
	 * Returns the xmy0185 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0185 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0185();

	/**
	 * Sets the xmy0185 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0185 the xmy0185 of this vr technical spec_xmy part3
	 */
	public void setXMY0185(String XMY0185);

	/**
	 * Returns the xmy0186 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0186 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0186();

	/**
	 * Sets the xmy0186 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0186 the xmy0186 of this vr technical spec_xmy part3
	 */
	public void setXMY0186(String XMY0186);

	/**
	 * Returns the xmy0187 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0187 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0187();

	/**
	 * Sets the xmy0187 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0187 the xmy0187 of this vr technical spec_xmy part3
	 */
	public void setXMY0187(String XMY0187);

	/**
	 * Returns the xmy0188 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0188 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0188();

	/**
	 * Sets the xmy0188 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0188 the xmy0188 of this vr technical spec_xmy part3
	 */
	public void setXMY0188(String XMY0188);

	/**
	 * Returns the xmy0189 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0189 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0189();

	/**
	 * Sets the xmy0189 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0189 the xmy0189 of this vr technical spec_xmy part3
	 */
	public void setXMY0189(String XMY0189);

	/**
	 * Returns the xmy0190 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0190 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0190();

	/**
	 * Sets the xmy0190 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0190 the xmy0190 of this vr technical spec_xmy part3
	 */
	public void setXMY0190(String XMY0190);

	/**
	 * Returns the xmy0191 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0191 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0191();

	/**
	 * Sets the xmy0191 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0191 the xmy0191 of this vr technical spec_xmy part3
	 */
	public void setXMY0191(String XMY0191);

	/**
	 * Returns the xmy0192 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0192 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0192();

	/**
	 * Sets the xmy0192 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0192 the xmy0192 of this vr technical spec_xmy part3
	 */
	public void setXMY0192(String XMY0192);

	/**
	 * Returns the xmy0193 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0193 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0193();

	/**
	 * Sets the xmy0193 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0193 the xmy0193 of this vr technical spec_xmy part3
	 */
	public void setXMY0193(String XMY0193);

	/**
	 * Returns the xmy0194 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0194 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0194();

	/**
	 * Sets the xmy0194 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0194 the xmy0194 of this vr technical spec_xmy part3
	 */
	public void setXMY0194(String XMY0194);

	/**
	 * Returns the xmy0195 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0195 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0195();

	/**
	 * Sets the xmy0195 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0195 the xmy0195 of this vr technical spec_xmy part3
	 */
	public void setXMY0195(String XMY0195);

	/**
	 * Returns the xmy0196 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0196 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0196();

	/**
	 * Sets the xmy0196 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0196 the xmy0196 of this vr technical spec_xmy part3
	 */
	public void setXMY0196(String XMY0196);

	/**
	 * Returns the xmy0197 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0197 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0197();

	/**
	 * Sets the xmy0197 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0197 the xmy0197 of this vr technical spec_xmy part3
	 */
	public void setXMY0197(String XMY0197);

	/**
	 * Returns the xmy0198 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0198 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0198();

	/**
	 * Sets the xmy0198 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0198 the xmy0198 of this vr technical spec_xmy part3
	 */
	public void setXMY0198(String XMY0198);

	/**
	 * Returns the xmy0199 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0199 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0199();

	/**
	 * Sets the xmy0199 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0199 the xmy0199 of this vr technical spec_xmy part3
	 */
	public void setXMY0199(String XMY0199);

	/**
	 * Returns the xmy0200 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0200 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0200();

	/**
	 * Sets the xmy0200 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0200 the xmy0200 of this vr technical spec_xmy part3
	 */
	public void setXMY0200(String XMY0200);

	/**
	 * Returns the xmy0201 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0201 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0201();

	/**
	 * Sets the xmy0201 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0201 the xmy0201 of this vr technical spec_xmy part3
	 */
	public void setXMY0201(String XMY0201);

	/**
	 * Returns the xmy0202 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0202 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0202();

	/**
	 * Sets the xmy0202 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0202 the xmy0202 of this vr technical spec_xmy part3
	 */
	public void setXMY0202(String XMY0202);

	/**
	 * Returns the xmy0203 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0203 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0203();

	/**
	 * Sets the xmy0203 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0203 the xmy0203 of this vr technical spec_xmy part3
	 */
	public void setXMY0203(String XMY0203);

	/**
	 * Returns the xmy0204 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0204 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0204();

	/**
	 * Sets the xmy0204 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0204 the xmy0204 of this vr technical spec_xmy part3
	 */
	public void setXMY0204(String XMY0204);

	/**
	 * Returns the xmy0205 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0205 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0205();

	/**
	 * Sets the xmy0205 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0205 the xmy0205 of this vr technical spec_xmy part3
	 */
	public void setXMY0205(String XMY0205);

	/**
	 * Returns the xmy0207 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0207 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0207();

	/**
	 * Sets the xmy0207 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0207 the xmy0207 of this vr technical spec_xmy part3
	 */
	public void setXMY0207(String XMY0207);

	/**
	 * Returns the xmy0208 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0208 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0208();

	/**
	 * Sets the xmy0208 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0208 the xmy0208 of this vr technical spec_xmy part3
	 */
	public void setXMY0208(String XMY0208);

	/**
	 * Returns the xmy0209 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0209 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0209();

	/**
	 * Sets the xmy0209 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0209 the xmy0209 of this vr technical spec_xmy part3
	 */
	public void setXMY0209(String XMY0209);

	/**
	 * Returns the xmy0210 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0210 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0210();

	/**
	 * Sets the xmy0210 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0210 the xmy0210 of this vr technical spec_xmy part3
	 */
	public void setXMY0210(String XMY0210);

	/**
	 * Returns the xmy0211 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0211 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0211();

	/**
	 * Sets the xmy0211 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0211 the xmy0211 of this vr technical spec_xmy part3
	 */
	public void setXMY0211(String XMY0211);

	/**
	 * Returns the xmy0212 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0212 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0212();

	/**
	 * Sets the xmy0212 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0212 the xmy0212 of this vr technical spec_xmy part3
	 */
	public void setXMY0212(String XMY0212);

	/**
	 * Returns the xmy0213 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0213 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0213();

	/**
	 * Sets the xmy0213 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0213 the xmy0213 of this vr technical spec_xmy part3
	 */
	public void setXMY0213(String XMY0213);

	/**
	 * Returns the xmy0214 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0214 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0214();

	/**
	 * Sets the xmy0214 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0214 the xmy0214 of this vr technical spec_xmy part3
	 */
	public void setXMY0214(String XMY0214);

	/**
	 * Returns the xmy0215 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0215 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0215();

	/**
	 * Sets the xmy0215 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0215 the xmy0215 of this vr technical spec_xmy part3
	 */
	public void setXMY0215(String XMY0215);

	/**
	 * Returns the xmy0216 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0216 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0216();

	/**
	 * Sets the xmy0216 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0216 the xmy0216 of this vr technical spec_xmy part3
	 */
	public void setXMY0216(String XMY0216);

	/**
	 * Returns the xmy0217 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0217 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0217();

	/**
	 * Sets the xmy0217 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0217 the xmy0217 of this vr technical spec_xmy part3
	 */
	public void setXMY0217(String XMY0217);

	/**
	 * Returns the xmy0218 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0218 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0218();

	/**
	 * Sets the xmy0218 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0218 the xmy0218 of this vr technical spec_xmy part3
	 */
	public void setXMY0218(String XMY0218);

	/**
	 * Returns the xmy0219 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0219 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0219();

	/**
	 * Sets the xmy0219 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0219 the xmy0219 of this vr technical spec_xmy part3
	 */
	public void setXMY0219(String XMY0219);

	/**
	 * Returns the xmy0220 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0220 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0220();

	/**
	 * Sets the xmy0220 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0220 the xmy0220 of this vr technical spec_xmy part3
	 */
	public void setXMY0220(String XMY0220);

	/**
	 * Returns the xmy0221 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0221 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0221();

	/**
	 * Sets the xmy0221 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0221 the xmy0221 of this vr technical spec_xmy part3
	 */
	public void setXMY0221(String XMY0221);

	/**
	 * Returns the xmy0222 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0222 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0222();

	/**
	 * Sets the xmy0222 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0222 the xmy0222 of this vr technical spec_xmy part3
	 */
	public void setXMY0222(String XMY0222);

	/**
	 * Returns the xmy0223 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0223 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0223();

	/**
	 * Sets the xmy0223 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0223 the xmy0223 of this vr technical spec_xmy part3
	 */
	public void setXMY0223(String XMY0223);

	/**
	 * Returns the xmy0224 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0224 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0224();

	/**
	 * Sets the xmy0224 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0224 the xmy0224 of this vr technical spec_xmy part3
	 */
	public void setXMY0224(String XMY0224);

	/**
	 * Returns the xmy0225 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0225 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0225();

	/**
	 * Sets the xmy0225 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0225 the xmy0225 of this vr technical spec_xmy part3
	 */
	public void setXMY0225(String XMY0225);

	/**
	 * Returns the xmy0226 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0226 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0226();

	/**
	 * Sets the xmy0226 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0226 the xmy0226 of this vr technical spec_xmy part3
	 */
	public void setXMY0226(String XMY0226);

	/**
	 * Returns the xmy0227 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0227 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0227();

	/**
	 * Sets the xmy0227 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0227 the xmy0227 of this vr technical spec_xmy part3
	 */
	public void setXMY0227(String XMY0227);

	/**
	 * Returns the xmy0228 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0228 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0228();

	/**
	 * Sets the xmy0228 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0228 the xmy0228 of this vr technical spec_xmy part3
	 */
	public void setXMY0228(String XMY0228);

	/**
	 * Returns the xmy0229 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0229 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0229();

	/**
	 * Sets the xmy0229 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0229 the xmy0229 of this vr technical spec_xmy part3
	 */
	public void setXMY0229(String XMY0229);

	/**
	 * Returns the xmy0230 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0230 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0230();

	/**
	 * Sets the xmy0230 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0230 the xmy0230 of this vr technical spec_xmy part3
	 */
	public void setXMY0230(String XMY0230);

	/**
	 * Returns the xmy0231 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0231 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0231();

	/**
	 * Sets the xmy0231 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0231 the xmy0231 of this vr technical spec_xmy part3
	 */
	public void setXMY0231(String XMY0231);

	/**
	 * Returns the xmy0232 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0232 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0232();

	/**
	 * Sets the xmy0232 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0232 the xmy0232 of this vr technical spec_xmy part3
	 */
	public void setXMY0232(String XMY0232);

	/**
	 * Returns the xmy0233 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0233 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0233();

	/**
	 * Sets the xmy0233 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0233 the xmy0233 of this vr technical spec_xmy part3
	 */
	public void setXMY0233(String XMY0233);

	/**
	 * Returns the xmy0234 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0234 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0234();

	/**
	 * Sets the xmy0234 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0234 the xmy0234 of this vr technical spec_xmy part3
	 */
	public void setXMY0234(String XMY0234);

	/**
	 * Returns the xmy0235 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0235 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0235();

	/**
	 * Sets the xmy0235 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0235 the xmy0235 of this vr technical spec_xmy part3
	 */
	public void setXMY0235(String XMY0235);

	/**
	 * Returns the xmy0236 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0236 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0236();

	/**
	 * Sets the xmy0236 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0236 the xmy0236 of this vr technical spec_xmy part3
	 */
	public void setXMY0236(String XMY0236);

	/**
	 * Returns the xmy0237 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0237 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0237();

	/**
	 * Sets the xmy0237 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0237 the xmy0237 of this vr technical spec_xmy part3
	 */
	public void setXMY0237(String XMY0237);

	/**
	 * Returns the xmy0238 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0238 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0238();

	/**
	 * Sets the xmy0238 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0238 the xmy0238 of this vr technical spec_xmy part3
	 */
	public void setXMY0238(String XMY0238);

	/**
	 * Returns the xmy0239 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0239 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0239();

	/**
	 * Sets the xmy0239 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0239 the xmy0239 of this vr technical spec_xmy part3
	 */
	public void setXMY0239(String XMY0239);

	/**
	 * Returns the xmy0240 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0240 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0240();

	/**
	 * Sets the xmy0240 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0240 the xmy0240 of this vr technical spec_xmy part3
	 */
	public void setXMY0240(String XMY0240);

	/**
	 * Returns the xmy0241 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0241 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0241();

	/**
	 * Sets the xmy0241 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0241 the xmy0241 of this vr technical spec_xmy part3
	 */
	public void setXMY0241(String XMY0241);

	/**
	 * Returns the xmy0242 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0242 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0242();

	/**
	 * Sets the xmy0242 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0242 the xmy0242 of this vr technical spec_xmy part3
	 */
	public void setXMY0242(String XMY0242);

	/**
	 * Returns the xmy0243 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0243 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0243();

	/**
	 * Sets the xmy0243 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0243 the xmy0243 of this vr technical spec_xmy part3
	 */
	public void setXMY0243(String XMY0243);

	/**
	 * Returns the xmy0244 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0244 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0244();

	/**
	 * Sets the xmy0244 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0244 the xmy0244 of this vr technical spec_xmy part3
	 */
	public void setXMY0244(String XMY0244);

	/**
	 * Returns the xmy0245 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0245 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0245();

	/**
	 * Sets the xmy0245 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0245 the xmy0245 of this vr technical spec_xmy part3
	 */
	public void setXMY0245(String XMY0245);

	/**
	 * Returns the xmy0246 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0246 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0246();

	/**
	 * Sets the xmy0246 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0246 the xmy0246 of this vr technical spec_xmy part3
	 */
	public void setXMY0246(String XMY0246);

	/**
	 * Returns the xmy0247 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0247 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0247();

	/**
	 * Sets the xmy0247 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0247 the xmy0247 of this vr technical spec_xmy part3
	 */
	public void setXMY0247(String XMY0247);

	/**
	 * Returns the xmy0248 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0248 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0248();

	/**
	 * Sets the xmy0248 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0248 the xmy0248 of this vr technical spec_xmy part3
	 */
	public void setXMY0248(String XMY0248);

	/**
	 * Returns the xmy0249 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0249 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0249();

	/**
	 * Sets the xmy0249 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0249 the xmy0249 of this vr technical spec_xmy part3
	 */
	public void setXMY0249(String XMY0249);

	/**
	 * Returns the xmy0250 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0250 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0250();

	/**
	 * Sets the xmy0250 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0250 the xmy0250 of this vr technical spec_xmy part3
	 */
	public void setXMY0250(String XMY0250);

	/**
	 * Returns the xmy0251 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0251 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0251();

	/**
	 * Sets the xmy0251 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0251 the xmy0251 of this vr technical spec_xmy part3
	 */
	public void setXMY0251(String XMY0251);

	/**
	 * Returns the xmy0252 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0252 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0252();

	/**
	 * Sets the xmy0252 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0252 the xmy0252 of this vr technical spec_xmy part3
	 */
	public void setXMY0252(String XMY0252);

	/**
	 * Returns the xmy0253 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0253 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0253();

	/**
	 * Sets the xmy0253 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0253 the xmy0253 of this vr technical spec_xmy part3
	 */
	public void setXMY0253(String XMY0253);

	/**
	 * Returns the xmy0254 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0254 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0254();

	/**
	 * Sets the xmy0254 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0254 the xmy0254 of this vr technical spec_xmy part3
	 */
	public void setXMY0254(String XMY0254);

	/**
	 * Returns the xmy0255 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0255 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0255();

	/**
	 * Sets the xmy0255 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0255 the xmy0255 of this vr technical spec_xmy part3
	 */
	public void setXMY0255(String XMY0255);

	/**
	 * Returns the xmy0256 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0256 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0256();

	/**
	 * Sets the xmy0256 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0256 the xmy0256 of this vr technical spec_xmy part3
	 */
	public void setXMY0256(String XMY0256);

	/**
	 * Returns the xmy0257 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0257 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0257();

	/**
	 * Sets the xmy0257 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0257 the xmy0257 of this vr technical spec_xmy part3
	 */
	public void setXMY0257(String XMY0257);

	/**
	 * Returns the xmy0258 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0258 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0258();

	/**
	 * Sets the xmy0258 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0258 the xmy0258 of this vr technical spec_xmy part3
	 */
	public void setXMY0258(String XMY0258);

	/**
	 * Returns the xmy0259 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0259 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0259();

	/**
	 * Sets the xmy0259 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0259 the xmy0259 of this vr technical spec_xmy part3
	 */
	public void setXMY0259(String XMY0259);

	/**
	 * Returns the xmy0260 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0260 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0260();

	/**
	 * Sets the xmy0260 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0260 the xmy0260 of this vr technical spec_xmy part3
	 */
	public void setXMY0260(String XMY0260);

	/**
	 * Returns the xmy0261 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0261 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0261();

	/**
	 * Sets the xmy0261 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0261 the xmy0261 of this vr technical spec_xmy part3
	 */
	public void setXMY0261(String XMY0261);

	/**
	 * Returns the xmy0262 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0262 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0262();

	/**
	 * Sets the xmy0262 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0262 the xmy0262 of this vr technical spec_xmy part3
	 */
	public void setXMY0262(String XMY0262);

	/**
	 * Returns the xmy0263 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0263 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0263();

	/**
	 * Sets the xmy0263 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0263 the xmy0263 of this vr technical spec_xmy part3
	 */
	public void setXMY0263(String XMY0263);

	/**
	 * Returns the xmy0264 of this vr technical spec_xmy part3.
	 *
	 * @return the xmy0264 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getXMY0264();

	/**
	 * Sets the xmy0264 of this vr technical spec_xmy part3.
	 *
	 * @param XMY0264 the xmy0264 of this vr technical spec_xmy part3
	 */
	public void setXMY0264(String XMY0264);

	/**
	 * Returns the bbcnclklxmy001 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy001 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY001();

	/**
	 * Sets the bbcnclklxmy001 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY001 the bbcnclklxmy001 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY001(String BBCNCLKLXMY001);

	/**
	 * Returns the bbcnclklxmy002 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy002 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY002();

	/**
	 * Sets the bbcnclklxmy002 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY002 the bbcnclklxmy002 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY002(String BBCNCLKLXMY002);

	/**
	 * Returns the bbcnclklxmy003 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy003 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY003();

	/**
	 * Sets the bbcnclklxmy003 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY003 the bbcnclklxmy003 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY003(String BBCNCLKLXMY003);

	/**
	 * Returns the bbcnclklxmy004 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy004 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY004();

	/**
	 * Sets the bbcnclklxmy004 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY004 the bbcnclklxmy004 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY004(String BBCNCLKLXMY004);

	/**
	 * Returns the bbcnclklxmy005 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy005 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY005();

	/**
	 * Sets the bbcnclklxmy005 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY005 the bbcnclklxmy005 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY005(String BBCNCLKLXMY005);

	/**
	 * Returns the bbcnclklxmy006 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy006 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY006();

	/**
	 * Sets the bbcnclklxmy006 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY006 the bbcnclklxmy006 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY006(String BBCNCLKLXMY006);

	/**
	 * Returns the bbcnclklxmy012 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy012 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY012();

	/**
	 * Sets the bbcnclklxmy012 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY012 the bbcnclklxmy012 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY012(String BBCNCLKLXMY012);

	/**
	 * Returns the bbcnclklxmy013 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy013 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY013();

	/**
	 * Sets the bbcnclklxmy013 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY013 the bbcnclklxmy013 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY013(String BBCNCLKLXMY013);

	/**
	 * Returns the bbcnclklxmy014 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy014 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY014();

	/**
	 * Sets the bbcnclklxmy014 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY014 the bbcnclklxmy014 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY014(String BBCNCLKLXMY014);

	/**
	 * Returns the bbcnclklxmy015 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy015 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY015();

	/**
	 * Sets the bbcnclklxmy015 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY015 the bbcnclklxmy015 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY015(String BBCNCLKLXMY015);

	/**
	 * Returns the bbcnclklxmy016 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy016 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY016();

	/**
	 * Sets the bbcnclklxmy016 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY016 the bbcnclklxmy016 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY016(String BBCNCLKLXMY016);

	/**
	 * Returns the bbcnclklxmy017 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy017 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY017();

	/**
	 * Sets the bbcnclklxmy017 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY017 the bbcnclklxmy017 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY017(String BBCNCLKLXMY017);

	/**
	 * Returns the bbcnclklxmy018 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy018 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY018();

	/**
	 * Sets the bbcnclklxmy018 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY018 the bbcnclklxmy018 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY018(String BBCNCLKLXMY018);

	/**
	 * Returns the bbcnclklxmy019 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy019 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY019();

	/**
	 * Sets the bbcnclklxmy019 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY019 the bbcnclklxmy019 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY019(String BBCNCLKLXMY019);

	/**
	 * Returns the bbcnclklxmy020 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy020 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY020();

	/**
	 * Sets the bbcnclklxmy020 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY020 the bbcnclklxmy020 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY020(String BBCNCLKLXMY020);

	/**
	 * Returns the bbcnclklxmy021 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy021 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY021();

	/**
	 * Sets the bbcnclklxmy021 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY021 the bbcnclklxmy021 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY021(String BBCNCLKLXMY021);

	/**
	 * Returns the bbcnclklxmy022 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy022 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY022();

	/**
	 * Sets the bbcnclklxmy022 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY022 the bbcnclklxmy022 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY022(String BBCNCLKLXMY022);

	/**
	 * Returns the bbcnclklxmy024 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy024 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY024();

	/**
	 * Sets the bbcnclklxmy024 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY024 the bbcnclklxmy024 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY024(String BBCNCLKLXMY024);

	/**
	 * Returns the bbcnclklxmy026 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy026 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY026();

	/**
	 * Sets the bbcnclklxmy026 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY026 the bbcnclklxmy026 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY026(String BBCNCLKLXMY026);

	/**
	 * Returns the bbcnclklxmy027 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy027 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY027();

	/**
	 * Sets the bbcnclklxmy027 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY027 the bbcnclklxmy027 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY027(String BBCNCLKLXMY027);

	/**
	 * Returns the bbcnclklxmy028 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy028 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY028();

	/**
	 * Sets the bbcnclklxmy028 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY028 the bbcnclklxmy028 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY028(String BBCNCLKLXMY028);

	/**
	 * Returns the bbcnclklxmy029 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy029 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY029();

	/**
	 * Sets the bbcnclklxmy029 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY029 the bbcnclklxmy029 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY029(String BBCNCLKLXMY029);

	/**
	 * Returns the bbcnclklxmy033 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy033 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY033();

	/**
	 * Sets the bbcnclklxmy033 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY033 the bbcnclklxmy033 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY033(String BBCNCLKLXMY033);

	/**
	 * Returns the bbcnclklxmy034 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy034 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY034();

	/**
	 * Sets the bbcnclklxmy034 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY034 the bbcnclklxmy034 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY034(String BBCNCLKLXMY034);

	/**
	 * Returns the bbcnclklxmy037 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy037 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY037();

	/**
	 * Sets the bbcnclklxmy037 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY037 the bbcnclklxmy037 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY037(String BBCNCLKLXMY037);

	/**
	 * Returns the bbcnclklxmy038 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy038 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY038();

	/**
	 * Sets the bbcnclklxmy038 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY038 the bbcnclklxmy038 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY038(String BBCNCLKLXMY038);

	/**
	 * Returns the bbcnclklxmy039 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy039 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY039();

	/**
	 * Sets the bbcnclklxmy039 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY039 the bbcnclklxmy039 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY039(String BBCNCLKLXMY039);

	/**
	 * Returns the bbcnclklxmy040 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy040 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY040();

	/**
	 * Sets the bbcnclklxmy040 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY040 the bbcnclklxmy040 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY040(String BBCNCLKLXMY040);

	/**
	 * Returns the bbcnclklxmy041 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy041 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY041();

	/**
	 * Sets the bbcnclklxmy041 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY041 the bbcnclklxmy041 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY041(String BBCNCLKLXMY041);

	/**
	 * Returns the bbcnclklxmy042 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy042 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY042();

	/**
	 * Sets the bbcnclklxmy042 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY042 the bbcnclklxmy042 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY042(String BBCNCLKLXMY042);

	/**
	 * Returns the bbcnclklxmy043 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy043 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY043();

	/**
	 * Sets the bbcnclklxmy043 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY043 the bbcnclklxmy043 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY043(String BBCNCLKLXMY043);

	/**
	 * Returns the bbcnclklxmy044 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy044 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY044();

	/**
	 * Sets the bbcnclklxmy044 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY044 the bbcnclklxmy044 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY044(String BBCNCLKLXMY044);

	/**
	 * Returns the bbcnclklxmy045 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy045 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY045();

	/**
	 * Sets the bbcnclklxmy045 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY045 the bbcnclklxmy045 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY045(String BBCNCLKLXMY045);

	/**
	 * Returns the bbcnclklxdd030 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxdd030 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXDD030();

	/**
	 * Sets the bbcnclklxdd030 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXDD030 the bbcnclklxdd030 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXDD030(String BBCNCLKLXDD030);

	/**
	 * Returns the bbcnclklxmy046 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy046 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY046();

	/**
	 * Sets the bbcnclklxmy046 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY046 the bbcnclklxmy046 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY046(String BBCNCLKLXMY046);

	/**
	 * Returns the bbcnclklxmy047 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy047 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY047();

	/**
	 * Sets the bbcnclklxmy047 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY047 the bbcnclklxmy047 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY047(String BBCNCLKLXMY047);

	/**
	 * Returns the bbcnclklxmy053 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy053 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY053();

	/**
	 * Sets the bbcnclklxmy053 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY053 the bbcnclklxmy053 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY053(String BBCNCLKLXMY053);

	/**
	 * Returns the bbcnclklxmy054 of this vr technical spec_xmy part3.
	 *
	 * @return the bbcnclklxmy054 of this vr technical spec_xmy part3
	 */
	@AutoEscape
	public String getBBCNCLKLXMY054();

	/**
	 * Sets the bbcnclklxmy054 of this vr technical spec_xmy part3.
	 *
	 * @param BBCNCLKLXMY054 the bbcnclklxmy054 of this vr technical spec_xmy part3
	 */
	public void setBBCNCLKLXMY054(String BBCNCLKLXMY054);

	/**
	 * Returns the modify date of this vr technical spec_xmy part3.
	 *
	 * @return the modify date of this vr technical spec_xmy part3
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr technical spec_xmy part3.
	 *
	 * @param modifyDate the modify date of this vr technical spec_xmy part3
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr technical spec_xmy part3.
	 *
	 * @return the sync date of this vr technical spec_xmy part3
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr technical spec_xmy part3.
	 *
	 * @param syncDate the sync date of this vr technical spec_xmy part3
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTechnicalSpec_XMYPart3 vrTechnicalSpec_XMYPart3);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTechnicalSpec_XMYPart3> toCacheModel();

	@Override
	public VRTechnicalSpec_XMYPart3 toEscapedModel();

	@Override
	public VRTechnicalSpec_XMYPart3 toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}