/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRTrackchanges service. Represents a row in the &quot;vr_trackchanges&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRTrackchangesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRTrackchangesImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRTrackchanges
 * @see com.fds.vr.business.model.impl.VRTrackchangesImpl
 * @see com.fds.vr.business.model.impl.VRTrackchangesModelImpl
 * @generated
 */
@ProviderType
public interface VRTrackchangesModel extends BaseModel<VRTrackchanges> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr trackchanges model instance should use the {@link VRTrackchanges} interface instead.
	 */

	/**
	 * Returns the primary key of this vr trackchanges.
	 *
	 * @return the primary key of this vr trackchanges
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr trackchanges.
	 *
	 * @param primaryKey the primary key of this vr trackchanges
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr trackchanges.
	 *
	 * @return the ID of this vr trackchanges
	 */
	public long getId();

	/**
	 * Sets the ID of this vr trackchanges.
	 *
	 * @param id the ID of this vr trackchanges
	 */
	public void setId(long id);

	/**
	 * Returns the applicant code of this vr trackchanges.
	 *
	 * @return the applicant code of this vr trackchanges
	 */
	@AutoEscape
	public String getApplicantCode();

	/**
	 * Sets the applicant code of this vr trackchanges.
	 *
	 * @param applicantCode the applicant code of this vr trackchanges
	 */
	public void setApplicantCode(String applicantCode);

	/**
	 * Returns the production plant code of this vr trackchanges.
	 *
	 * @return the production plant code of this vr trackchanges
	 */
	@AutoEscape
	public String getProductionPlantCode();

	/**
	 * Sets the production plant code of this vr trackchanges.
	 *
	 * @param productionPlantCode the production plant code of this vr trackchanges
	 */
	public void setProductionPlantCode(String productionPlantCode);

	/**
	 * Returns the content type of this vr trackchanges.
	 *
	 * @return the content type of this vr trackchanges
	 */
	@AutoEscape
	public String getContentType();

	/**
	 * Sets the content type of this vr trackchanges.
	 *
	 * @param contentType the content type of this vr trackchanges
	 */
	public void setContentType(String contentType);

	/**
	 * Returns the content file template of this vr trackchanges.
	 *
	 * @return the content file template of this vr trackchanges
	 */
	@AutoEscape
	public String getContentFileTemplate();

	/**
	 * Sets the content file template of this vr trackchanges.
	 *
	 * @param contentFileTemplate the content file template of this vr trackchanges
	 */
	public void setContentFileTemplate(String contentFileTemplate);

	/**
	 * Returns the previous content file entry ID of this vr trackchanges.
	 *
	 * @return the previous content file entry ID of this vr trackchanges
	 */
	public long getPreviousContentFileEntryId();

	/**
	 * Sets the previous content file entry ID of this vr trackchanges.
	 *
	 * @param previousContentFileEntryId the previous content file entry ID of this vr trackchanges
	 */
	public void setPreviousContentFileEntryId(long previousContentFileEntryId);

	/**
	 * Returns the current content file entry ID of this vr trackchanges.
	 *
	 * @return the current content file entry ID of this vr trackchanges
	 */
	public long getCurrentContentFileEntryId();

	/**
	 * Sets the current content file entry ID of this vr trackchanges.
	 *
	 * @param currentContentFileEntryId the current content file entry ID of this vr trackchanges
	 */
	public void setCurrentContentFileEntryId(long currentContentFileEntryId);

	/**
	 * Returns the next content file entry ID of this vr trackchanges.
	 *
	 * @return the next content file entry ID of this vr trackchanges
	 */
	public long getNextContentFileEntryId();

	/**
	 * Sets the next content file entry ID of this vr trackchanges.
	 *
	 * @param nextContentFileEntryId the next content file entry ID of this vr trackchanges
	 */
	public void setNextContentFileEntryId(long nextContentFileEntryId);

	/**
	 * Returns the dossier ID of this vr trackchanges.
	 *
	 * @return the dossier ID of this vr trackchanges
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr trackchanges.
	 *
	 * @param dossierId the dossier ID of this vr trackchanges
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier ID ctn of this vr trackchanges.
	 *
	 * @return the dossier ID ctn of this vr trackchanges
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr trackchanges.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr trackchanges
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the dossier no of this vr trackchanges.
	 *
	 * @return the dossier no of this vr trackchanges
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr trackchanges.
	 *
	 * @param dossierNo the dossier no of this vr trackchanges
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the modify user ID of this vr trackchanges.
	 *
	 * @return the modify user ID of this vr trackchanges
	 */
	public long getModifyUserId();

	/**
	 * Sets the modify user ID of this vr trackchanges.
	 *
	 * @param modifyUserId the modify user ID of this vr trackchanges
	 */
	public void setModifyUserId(long modifyUserId);

	/**
	 * Returns the modify user uuid of this vr trackchanges.
	 *
	 * @return the modify user uuid of this vr trackchanges
	 */
	public String getModifyUserUuid();

	/**
	 * Sets the modify user uuid of this vr trackchanges.
	 *
	 * @param modifyUserUuid the modify user uuid of this vr trackchanges
	 */
	public void setModifyUserUuid(String modifyUserUuid);

	/**
	 * Returns the created date of this vr trackchanges.
	 *
	 * @return the created date of this vr trackchanges
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this vr trackchanges.
	 *
	 * @param createdDate the created date of this vr trackchanges
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modify date of this vr trackchanges.
	 *
	 * @return the modify date of this vr trackchanges
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr trackchanges.
	 *
	 * @param modifyDate the modify date of this vr trackchanges
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr trackchanges.
	 *
	 * @return the sync date of this vr trackchanges
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr trackchanges.
	 *
	 * @param syncDate the sync date of this vr trackchanges
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRTrackchanges vrTrackchanges);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRTrackchanges> toCacheModel();

	@Override
	public VRTrackchanges toEscapedModel();

	@Override
	public VRTrackchanges toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}