/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRVehicleEquipment service. Represents a row in the &quot;vr_vehicleequipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRVehicleEquipmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRVehicleEquipmentImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRVehicleEquipment
 * @see com.fds.vr.business.model.impl.VRVehicleEquipmentImpl
 * @see com.fds.vr.business.model.impl.VRVehicleEquipmentModelImpl
 * @generated
 */
@ProviderType
public interface VRVehicleEquipmentModel extends BaseModel<VRVehicleEquipment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr vehicle equipment model instance should use the {@link VRVehicleEquipment} interface instead.
	 */

	/**
	 * Returns the primary key of this vr vehicle equipment.
	 *
	 * @return the primary key of this vr vehicle equipment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr vehicle equipment.
	 *
	 * @param primaryKey the primary key of this vr vehicle equipment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr vehicle equipment.
	 *
	 * @return the ID of this vr vehicle equipment
	 */
	public long getId();

	/**
	 * Sets the ID of this vr vehicle equipment.
	 *
	 * @param id the ID of this vr vehicle equipment
	 */
	public void setId(long id);

	/**
	 * Returns the vehicle certificate ID of this vr vehicle equipment.
	 *
	 * @return the vehicle certificate ID of this vr vehicle equipment
	 */
	public long getVehicleCertificateId();

	/**
	 * Sets the vehicle certificate ID of this vr vehicle equipment.
	 *
	 * @param vehicleCertificateId the vehicle certificate ID of this vr vehicle equipment
	 */
	public void setVehicleCertificateId(long vehicleCertificateId);

	/**
	 * Returns the certificate record ID of this vr vehicle equipment.
	 *
	 * @return the certificate record ID of this vr vehicle equipment
	 */
	public long getCertificateRecordId();

	/**
	 * Sets the certificate record ID of this vr vehicle equipment.
	 *
	 * @param certificateRecordId the certificate record ID of this vr vehicle equipment
	 */
	public void setCertificateRecordId(long certificateRecordId);

	/**
	 * Returns the modify date of this vr vehicle equipment.
	 *
	 * @return the modify date of this vr vehicle equipment
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr vehicle equipment.
	 *
	 * @param modifyDate the modify date of this vr vehicle equipment
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr vehicle equipment.
	 *
	 * @return the sync date of this vr vehicle equipment
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr vehicle equipment.
	 *
	 * @param syncDate the sync date of this vr vehicle equipment
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRVehicleEquipment vrVehicleEquipment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRVehicleEquipment> toCacheModel();

	@Override
	public VRVehicleEquipment toEscapedModel();

	@Override
	public VRVehicleEquipment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}