/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the VRVehicleEquipment service. Represents a row in the &quot;vr_vehicleequipment&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.business.model.impl.VRVehicleEquipmentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.business.model.impl.VRVehicleEquipmentImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRVehicleEquipment
 * @see com.fds.vr.business.model.impl.VRVehicleEquipmentImpl
 * @see com.fds.vr.business.model.impl.VRVehicleEquipmentModelImpl
 * @generated
 */
@ProviderType
public interface VRVehicleEquipmentModel extends BaseModel<VRVehicleEquipment> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vr vehicle equipment model instance should use the {@link VRVehicleEquipment} interface instead.
	 */

	/**
	 * Returns the primary key of this vr vehicle equipment.
	 *
	 * @return the primary key of this vr vehicle equipment
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vr vehicle equipment.
	 *
	 * @param primaryKey the primary key of this vr vehicle equipment
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this vr vehicle equipment.
	 *
	 * @return the ID of this vr vehicle equipment
	 */
	public long getId();

	/**
	 * Sets the ID of this vr vehicle equipment.
	 *
	 * @param id the ID of this vr vehicle equipment
	 */
	public void setId(long id);

	/**
	 * Returns the vehicle type certificate ID of this vr vehicle equipment.
	 *
	 * @return the vehicle type certificate ID of this vr vehicle equipment
	 */
	public long getVehicleTypeCertificateId();

	/**
	 * Sets the vehicle type certificate ID of this vr vehicle equipment.
	 *
	 * @param vehicleTypeCertificateId the vehicle type certificate ID of this vr vehicle equipment
	 */
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId);

	/**
	 * Returns the certificate record ID of this vr vehicle equipment.
	 *
	 * @return the certificate record ID of this vr vehicle equipment
	 */
	public long getCertificateRecordId();

	/**
	 * Sets the certificate record ID of this vr vehicle equipment.
	 *
	 * @param certificateRecordId the certificate record ID of this vr vehicle equipment
	 */
	public void setCertificateRecordId(long certificateRecordId);

	/**
	 * Returns the dossier ID of this vr vehicle equipment.
	 *
	 * @return the dossier ID of this vr vehicle equipment
	 */
	public long getDossierId();

	/**
	 * Sets the dossier ID of this vr vehicle equipment.
	 *
	 * @param dossierId the dossier ID of this vr vehicle equipment
	 */
	public void setDossierId(long dossierId);

	/**
	 * Returns the dossier ID ctn of this vr vehicle equipment.
	 *
	 * @return the dossier ID ctn of this vr vehicle equipment
	 */
	@AutoEscape
	public String getDossierIdCTN();

	/**
	 * Sets the dossier ID ctn of this vr vehicle equipment.
	 *
	 * @param dossierIdCTN the dossier ID ctn of this vr vehicle equipment
	 */
	public void setDossierIdCTN(String dossierIdCTN);

	/**
	 * Returns the dossier no of this vr vehicle equipment.
	 *
	 * @return the dossier no of this vr vehicle equipment
	 */
	@AutoEscape
	public String getDossierNo();

	/**
	 * Sets the dossier no of this vr vehicle equipment.
	 *
	 * @param dossierNo the dossier no of this vr vehicle equipment
	 */
	public void setDossierNo(String dossierNo);

	/**
	 * Returns the is mandatory of this vr vehicle equipment.
	 *
	 * @return the is mandatory of this vr vehicle equipment
	 */
	public int getIsMandatory();

	/**
	 * Sets the is mandatory of this vr vehicle equipment.
	 *
	 * @param isMandatory the is mandatory of this vr vehicle equipment
	 */
	public void setIsMandatory(int isMandatory);

	/**
	 * Returns the sequence no of this vr vehicle equipment.
	 *
	 * @return the sequence no of this vr vehicle equipment
	 */
	public long getSequenceNo();

	/**
	 * Sets the sequence no of this vr vehicle equipment.
	 *
	 * @param sequenceNo the sequence no of this vr vehicle equipment
	 */
	public void setSequenceNo(long sequenceNo);

	/**
	 * Returns the certificate record no of this vr vehicle equipment.
	 *
	 * @return the certificate record no of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCertificateRecordNo();

	/**
	 * Sets the certificate record no of this vr vehicle equipment.
	 *
	 * @param certificateRecordNo the certificate record no of this vr vehicle equipment
	 */
	public void setCertificateRecordNo(String certificateRecordNo);

	/**
	 * Returns the certificate record date of this vr vehicle equipment.
	 *
	 * @return the certificate record date of this vr vehicle equipment
	 */
	public Date getCertificateRecordDate();

	/**
	 * Sets the certificate record date of this vr vehicle equipment.
	 *
	 * @param certificateRecordDate the certificate record date of this vr vehicle equipment
	 */
	public void setCertificateRecordDate(Date certificateRecordDate);

	/**
	 * Returns the certificate record expire date of this vr vehicle equipment.
	 *
	 * @return the certificate record expire date of this vr vehicle equipment
	 */
	public Date getCertificateRecordExpireDate();

	/**
	 * Sets the certificate record expire date of this vr vehicle equipment.
	 *
	 * @param certificateRecordExpireDate the certificate record expire date of this vr vehicle equipment
	 */
	public void setCertificateRecordExpireDate(Date certificateRecordExpireDate);

	/**
	 * Returns the expired status of this vr vehicle equipment.
	 *
	 * @return the expired status of this vr vehicle equipment
	 */
	public int getExpiredStatus();

	/**
	 * Sets the expired status of this vr vehicle equipment.
	 *
	 * @param expiredStatus the expired status of this vr vehicle equipment
	 */
	public void setExpiredStatus(int expiredStatus);

	/**
	 * Returns the vehicle class of this vr vehicle equipment.
	 *
	 * @return the vehicle class of this vr vehicle equipment
	 */
	@AutoEscape
	public String getVehicleClass();

	/**
	 * Sets the vehicle class of this vr vehicle equipment.
	 *
	 * @param vehicleClass the vehicle class of this vr vehicle equipment
	 */
	public void setVehicleClass(String vehicleClass);

	/**
	 * Returns the equipment code of this vr vehicle equipment.
	 *
	 * @return the equipment code of this vr vehicle equipment
	 */
	@AutoEscape
	public String getEquipmentCode();

	/**
	 * Sets the equipment code of this vr vehicle equipment.
	 *
	 * @param equipmentCode the equipment code of this vr vehicle equipment
	 */
	public void setEquipmentCode(String equipmentCode);

	/**
	 * Returns the equipment name of this vr vehicle equipment.
	 *
	 * @return the equipment name of this vr vehicle equipment
	 */
	@AutoEscape
	public String getEquipmentName();

	/**
	 * Sets the equipment name of this vr vehicle equipment.
	 *
	 * @param equipmentName the equipment name of this vr vehicle equipment
	 */
	public void setEquipmentName(String equipmentName);

	/**
	 * Returns the certified vehicle type of this vr vehicle equipment.
	 *
	 * @return the certified vehicle type of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCertifiedVehicleType();

	/**
	 * Sets the certified vehicle type of this vr vehicle equipment.
	 *
	 * @param certifiedVehicleType the certified vehicle type of this vr vehicle equipment
	 */
	public void setCertifiedVehicleType(String certifiedVehicleType);

	/**
	 * Returns the certified vehicle type description of this vr vehicle equipment.
	 *
	 * @return the certified vehicle type description of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCertifiedVehicleTypeDescription();

	/**
	 * Sets the certified vehicle type description of this vr vehicle equipment.
	 *
	 * @param certifiedVehicleTypeDescription the certified vehicle type description of this vr vehicle equipment
	 */
	public void setCertifiedVehicleTypeDescription(
		String certifiedVehicleTypeDescription);

	/**
	 * Returns the certified trademark of this vr vehicle equipment.
	 *
	 * @return the certified trademark of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCertifiedTrademark();

	/**
	 * Sets the certified trademark of this vr vehicle equipment.
	 *
	 * @param certifiedTrademark the certified trademark of this vr vehicle equipment
	 */
	public void setCertifiedTrademark(String certifiedTrademark);

	/**
	 * Returns the certified trademark name of this vr vehicle equipment.
	 *
	 * @return the certified trademark name of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCertifiedTrademarkName();

	/**
	 * Sets the certified trademark name of this vr vehicle equipment.
	 *
	 * @param certifiedTrademarkName the certified trademark name of this vr vehicle equipment
	 */
	public void setCertifiedTrademarkName(String certifiedTrademarkName);

	/**
	 * Returns the certified commercial name of this vr vehicle equipment.
	 *
	 * @return the certified commercial name of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCertifiedCommercialName();

	/**
	 * Sets the certified commercial name of this vr vehicle equipment.
	 *
	 * @param certifiedCommercialName the certified commercial name of this vr vehicle equipment
	 */
	public void setCertifiedCommercialName(String certifiedCommercialName);

	/**
	 * Returns the certified model code of this vr vehicle equipment.
	 *
	 * @return the certified model code of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCertifiedModelCode();

	/**
	 * Sets the certified model code of this vr vehicle equipment.
	 *
	 * @param certifiedModelCode the certified model code of this vr vehicle equipment
	 */
	public void setCertifiedModelCode(String certifiedModelCode);

	/**
	 * Returns the production country of this vr vehicle equipment.
	 *
	 * @return the production country of this vr vehicle equipment
	 */
	@AutoEscape
	public String getProductionCountry();

	/**
	 * Sets the production country of this vr vehicle equipment.
	 *
	 * @param productionCountry the production country of this vr vehicle equipment
	 */
	public void setProductionCountry(String productionCountry);

	/**
	 * Returns the original code of this vr vehicle equipment.
	 *
	 * @return the original code of this vr vehicle equipment
	 */
	@AutoEscape
	public String getOriginalCode();

	/**
	 * Sets the original code of this vr vehicle equipment.
	 *
	 * @param originalCode the original code of this vr vehicle equipment
	 */
	public void setOriginalCode(String originalCode);

	/**
	 * Returns the original name of this vr vehicle equipment.
	 *
	 * @return the original name of this vr vehicle equipment
	 */
	@AutoEscape
	public String getOriginalName();

	/**
	 * Sets the original name of this vr vehicle equipment.
	 *
	 * @param originalName the original name of this vr vehicle equipment
	 */
	public void setOriginalName(String originalName);

	/**
	 * Returns the production name of this vr vehicle equipment.
	 *
	 * @return the production name of this vr vehicle equipment
	 */
	@AutoEscape
	public String getProductionName();

	/**
	 * Sets the production name of this vr vehicle equipment.
	 *
	 * @param productionName the production name of this vr vehicle equipment
	 */
	public void setProductionName(String productionName);

	/**
	 * Returns the production address of this vr vehicle equipment.
	 *
	 * @return the production address of this vr vehicle equipment
	 */
	@AutoEscape
	public String getProductionAddress();

	/**
	 * Sets the production address of this vr vehicle equipment.
	 *
	 * @param productionAddress the production address of this vr vehicle equipment
	 */
	public void setProductionAddress(String productionAddress);

	/**
	 * Returns the manufacturer name of this vr vehicle equipment.
	 *
	 * @return the manufacturer name of this vr vehicle equipment
	 */
	@AutoEscape
	public String getManufacturerName();

	/**
	 * Sets the manufacturer name of this vr vehicle equipment.
	 *
	 * @param manufacturerName the manufacturer name of this vr vehicle equipment
	 */
	public void setManufacturerName(String manufacturerName);

	/**
	 * Returns the manufacturer address of this vr vehicle equipment.
	 *
	 * @return the manufacturer address of this vr vehicle equipment
	 */
	@AutoEscape
	public String getManufacturerAddress();

	/**
	 * Sets the manufacturer address of this vr vehicle equipment.
	 *
	 * @param manufacturerAddress the manufacturer address of this vr vehicle equipment
	 */
	public void setManufacturerAddress(String manufacturerAddress);

	/**
	 * Returns the safetytest report no of this vr vehicle equipment.
	 *
	 * @return the safetytest report no of this vr vehicle equipment
	 */
	@AutoEscape
	public String getSafetytestReportNo();

	/**
	 * Sets the safetytest report no of this vr vehicle equipment.
	 *
	 * @param safetytestReportNo the safetytest report no of this vr vehicle equipment
	 */
	public void setSafetytestReportNo(String safetytestReportNo);

	/**
	 * Returns the safetytest report date of this vr vehicle equipment.
	 *
	 * @return the safetytest report date of this vr vehicle equipment
	 */
	public Date getSafetytestReportDate();

	/**
	 * Sets the safetytest report date of this vr vehicle equipment.
	 *
	 * @param safetytestReportDate the safetytest report date of this vr vehicle equipment
	 */
	public void setSafetytestReportDate(Date safetytestReportDate);

	/**
	 * Returns the emission test report no of this vr vehicle equipment.
	 *
	 * @return the emission test report no of this vr vehicle equipment
	 */
	@AutoEscape
	public String getEmissionTestReportNo();

	/**
	 * Sets the emission test report no of this vr vehicle equipment.
	 *
	 * @param emissionTestReportNo the emission test report no of this vr vehicle equipment
	 */
	public void setEmissionTestReportNo(String emissionTestReportNo);

	/**
	 * Returns the emission test report date of this vr vehicle equipment.
	 *
	 * @return the emission test report date of this vr vehicle equipment
	 */
	public Date getEmissionTestReportDate();

	/**
	 * Sets the emission test report date of this vr vehicle equipment.
	 *
	 * @param emissionTestReportDate the emission test report date of this vr vehicle equipment
	 */
	public void setEmissionTestReportDate(Date emissionTestReportDate);

	/**
	 * Returns the common safety standard of this vr vehicle equipment.
	 *
	 * @return the common safety standard of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCommonSafetyStandard();

	/**
	 * Sets the common safety standard of this vr vehicle equipment.
	 *
	 * @param commonSafetyStandard the common safety standard of this vr vehicle equipment
	 */
	public void setCommonSafetyStandard(String commonSafetyStandard);

	/**
	 * Returns the common safety description of this vr vehicle equipment.
	 *
	 * @return the common safety description of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCommonSafetyDescription();

	/**
	 * Sets the common safety description of this vr vehicle equipment.
	 *
	 * @param commonSafetyDescription the common safety description of this vr vehicle equipment
	 */
	public void setCommonSafetyDescription(String commonSafetyDescription);

	/**
	 * Returns the emission standard of this vr vehicle equipment.
	 *
	 * @return the emission standard of this vr vehicle equipment
	 */
	@AutoEscape
	public String getEmissionStandard();

	/**
	 * Sets the emission standard of this vr vehicle equipment.
	 *
	 * @param emissionStandard the emission standard of this vr vehicle equipment
	 */
	public void setEmissionStandard(String emissionStandard);

	/**
	 * Returns the emission description of this vr vehicle equipment.
	 *
	 * @return the emission description of this vr vehicle equipment
	 */
	@AutoEscape
	public String getEmissionDescription();

	/**
	 * Sets the emission description of this vr vehicle equipment.
	 *
	 * @param emissionDescription the emission description of this vr vehicle equipment
	 */
	public void setEmissionDescription(String emissionDescription);

	/**
	 * Returns the othertest report no of this vr vehicle equipment.
	 *
	 * @return the othertest report no of this vr vehicle equipment
	 */
	@AutoEscape
	public String getOthertestReportNo();

	/**
	 * Sets the othertest report no of this vr vehicle equipment.
	 *
	 * @param othertestReportNo the othertest report no of this vr vehicle equipment
	 */
	public void setOthertestReportNo(String othertestReportNo);

	/**
	 * Returns the othertest report date of this vr vehicle equipment.
	 *
	 * @return the othertest report date of this vr vehicle equipment
	 */
	public Date getOthertestReportDate();

	/**
	 * Sets the othertest report date of this vr vehicle equipment.
	 *
	 * @param othertestReportDate the othertest report date of this vr vehicle equipment
	 */
	public void setOthertestReportDate(Date othertestReportDate);

	/**
	 * Returns the cop report no of this vr vehicle equipment.
	 *
	 * @return the cop report no of this vr vehicle equipment
	 */
	@AutoEscape
	public String getCopReportNo();

	/**
	 * Sets the cop report no of this vr vehicle equipment.
	 *
	 * @param copReportNo the cop report no of this vr vehicle equipment
	 */
	public void setCopReportNo(String copReportNo);

	/**
	 * Returns the cop report date of this vr vehicle equipment.
	 *
	 * @return the cop report date of this vr vehicle equipment
	 */
	public Date getCopReportDate();

	/**
	 * Sets the cop report date of this vr vehicle equipment.
	 *
	 * @param copReportDate the cop report date of this vr vehicle equipment
	 */
	public void setCopReportDate(Date copReportDate);

	/**
	 * Returns the cop report expire date of this vr vehicle equipment.
	 *
	 * @return the cop report expire date of this vr vehicle equipment
	 */
	public Date getCopReportExpireDate();

	/**
	 * Sets the cop report expire date of this vr vehicle equipment.
	 *
	 * @param copReportExpireDate the cop report expire date of this vr vehicle equipment
	 */
	public void setCopReportExpireDate(Date copReportExpireDate);

	/**
	 * Returns the modify date of this vr vehicle equipment.
	 *
	 * @return the modify date of this vr vehicle equipment
	 */
	public Date getModifyDate();

	/**
	 * Sets the modify date of this vr vehicle equipment.
	 *
	 * @param modifyDate the modify date of this vr vehicle equipment
	 */
	public void setModifyDate(Date modifyDate);

	/**
	 * Returns the sync date of this vr vehicle equipment.
	 *
	 * @return the sync date of this vr vehicle equipment
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this vr vehicle equipment.
	 *
	 * @param syncDate the sync date of this vr vehicle equipment
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(VRVehicleEquipment vrVehicleEquipment);

	@Override
	public int hashCode();

	@Override
	public CacheModel<VRVehicleEquipment> toCacheModel();

	@Override
	public VRVehicleEquipment toEscapedModel();

	@Override
	public VRVehicleEquipment toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}