//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.18 at 09:33:50 AM ICT 
//


package com.fds.vr.cop.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VRCOPProductionPlantProdEquipmentModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VRCOPProductionPlantProdEquipmentModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="mtCore" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="COPReportRepositoryID" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="COPReportNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sequenceNo" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="equipmentCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="equipmentName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="equipmentType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tradeMark" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="tradeMarkName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commercialName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="designSymbolNo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="productionCountryCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="equipmentStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="modifyDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="syncDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VRCOPProductionPlantProdEquipmentModel", propOrder = {
    "mtCore",
    "copReportRepositoryID",
    "copReportNo",
    "sequenceNo",
    "equipmentCode",
    "equipmentName",
    "equipmentType",
    "tradeMark",
    "tradeMarkName",
    "commercialName",
    "modelCode",
    "designSymbolNo",
    "productionCountryCode",
    "equipmentStatus",
    "notes",
    "modifyDate",
    "syncDate"
})
public class VRCOPProductionPlantProdEquipmentModel {

    protected Integer mtCore;
    @XmlElement(name = "COPReportRepositoryID")
    protected Long copReportRepositoryID;
    @XmlElement(name = "COPReportNo")
    protected String copReportNo;
    protected Long sequenceNo;
    protected String equipmentCode;
    protected String equipmentName;
    protected String equipmentType;
    protected String tradeMark;
    protected String tradeMarkName;
    protected String commercialName;
    protected String modelCode;
    protected String designSymbolNo;
    protected Long productionCountryCode;
    protected String equipmentStatus;
    protected String notes;
    protected String modifyDate;
    protected String syncDate;

    /**
     * Gets the value of the mtCore property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMtCore() {
        return mtCore;
    }

    /**
     * Sets the value of the mtCore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMtCore(Integer value) {
        this.mtCore = value;
    }

    /**
     * Gets the value of the copReportRepositoryID property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCOPReportRepositoryID() {
        return copReportRepositoryID;
    }

    /**
     * Sets the value of the copReportRepositoryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCOPReportRepositoryID(Long value) {
        this.copReportRepositoryID = value;
    }

    /**
     * Gets the value of the copReportNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOPReportNo() {
        return copReportNo;
    }

    /**
     * Sets the value of the copReportNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOPReportNo(String value) {
        this.copReportNo = value;
    }

    /**
     * Gets the value of the sequenceNo property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSequenceNo() {
        return sequenceNo;
    }

    /**
     * Sets the value of the sequenceNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSequenceNo(Long value) {
        this.sequenceNo = value;
    }

    /**
     * Gets the value of the equipmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentCode() {
        return equipmentCode;
    }

    /**
     * Sets the value of the equipmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentCode(String value) {
        this.equipmentCode = value;
    }

    /**
     * Gets the value of the equipmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentName() {
        return equipmentName;
    }

    /**
     * Sets the value of the equipmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentName(String value) {
        this.equipmentName = value;
    }

    /**
     * Gets the value of the equipmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentType() {
        return equipmentType;
    }

    /**
     * Sets the value of the equipmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentType(String value) {
        this.equipmentType = value;
    }

    /**
     * Gets the value of the tradeMark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeMark() {
        return tradeMark;
    }

    /**
     * Sets the value of the tradeMark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeMark(String value) {
        this.tradeMark = value;
    }

    /**
     * Gets the value of the tradeMarkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeMarkName() {
        return tradeMarkName;
    }

    /**
     * Sets the value of the tradeMarkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeMarkName(String value) {
        this.tradeMarkName = value;
    }

    /**
     * Gets the value of the commercialName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommercialName() {
        return commercialName;
    }

    /**
     * Sets the value of the commercialName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommercialName(String value) {
        this.commercialName = value;
    }

    /**
     * Gets the value of the modelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelCode() {
        return modelCode;
    }

    /**
     * Sets the value of the modelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelCode(String value) {
        this.modelCode = value;
    }

    /**
     * Gets the value of the designSymbolNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignSymbolNo() {
        return designSymbolNo;
    }

    /**
     * Sets the value of the designSymbolNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignSymbolNo(String value) {
        this.designSymbolNo = value;
    }

    /**
     * Gets the value of the productionCountryCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getProductionCountryCode() {
        return productionCountryCode;
    }

    /**
     * Sets the value of the productionCountryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setProductionCountryCode(Long value) {
        this.productionCountryCode = value;
    }

    /**
     * Gets the value of the equipmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEquipmentStatus() {
        return equipmentStatus;
    }

    /**
     * Sets the value of the equipmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEquipmentStatus(String value) {
        this.equipmentStatus = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotes(String value) {
        this.notes = value;
    }

    /**
     * Gets the value of the modifyDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModifyDate() {
        return modifyDate;
    }

    /**
     * Sets the value of the modifyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModifyDate(String value) {
        this.modifyDate = value;
    }

    /**
     * Gets the value of the syncDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSyncDate() {
        return syncDate;
    }

    /**
     * Sets the value of the syncDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSyncDate(String value) {
        this.syncDate = value;
    }

}
