/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.fds.vr.business.model.VRCOPProductClassification;
import com.fds.vr.business.model.VRCOPProductClassificationModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VRCOPProductClassification service. Represents a row in the &quot;vr_copproductclassification&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VRCOPProductClassificationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VRCOPProductClassificationImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRCOPProductClassificationImpl
 * @see VRCOPProductClassification
 * @see VRCOPProductClassificationModel
 * @generated
 */
@ProviderType
public class VRCOPProductClassificationModelImpl extends BaseModelImpl<VRCOPProductClassification>
	implements VRCOPProductClassificationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vrcop product classification model instance should use the {@link VRCOPProductClassification} interface instead.
	 */
	public static final String TABLE_NAME = "vr_copproductclassification";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "mtCore", Types.BIGINT },
			{ "copReportRepositoryID", Types.BIGINT },
			{ "copReportNo", Types.VARCHAR },
			{ "sequenceNo", Types.BIGINT },
			{ "productClassificationCode", Types.VARCHAR },
			{ "productClassificationDescription", Types.VARCHAR },
			{ "modifyDate", Types.TIMESTAMP },
			{ "syncDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mtCore", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("copReportRepositoryID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("copReportNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("sequenceNo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productClassificationCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("productClassificationDescription", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifyDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("syncDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table vr_copproductclassification (id LONG not null primary key,mtCore LONG,copReportRepositoryID LONG,copReportNo VARCHAR(75) null,sequenceNo LONG,productClassificationCode VARCHAR(75) null,productClassificationDescription VARCHAR(75) null,modifyDate DATE null,syncDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table vr_copproductclassification";
	public static final String ORDER_BY_JPQL = " ORDER BY vrcopProductClassification.modifyDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY vr_copproductclassification.modifyDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fds.vr.business.model.VRCOPProductClassification"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fds.vr.business.model.VRCOPProductClassification"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.fds.vr.business.model.VRCOPProductClassification"),
			true);
	public static final long COPREPORTNO_COLUMN_BITMASK = 1L;
	public static final long COPREPORTREPOSITORYID_COLUMN_BITMASK = 2L;
	public static final long MTCORE_COLUMN_BITMASK = 4L;
	public static final long MODIFYDATE_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.fds.vr.service.util.ServiceProps.get(
				"lock.expiration.time.com.fds.vr.business.model.VRCOPProductClassification"));

	public VRCOPProductClassificationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VRCOPProductClassification.class;
	}

	@Override
	public String getModelClassName() {
		return VRCOPProductClassification.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("mtCore", getMtCore());
		attributes.put("copReportRepositoryID", getCopReportRepositoryID());
		attributes.put("copReportNo", getCopReportNo());
		attributes.put("sequenceNo", getSequenceNo());
		attributes.put("productClassificationCode",
			getProductClassificationCode());
		attributes.put("productClassificationDescription",
			getProductClassificationDescription());
		attributes.put("modifyDate", getModifyDate());
		attributes.put("syncDate", getSyncDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long mtCore = (Long)attributes.get("mtCore");

		if (mtCore != null) {
			setMtCore(mtCore);
		}

		Long copReportRepositoryID = (Long)attributes.get(
				"copReportRepositoryID");

		if (copReportRepositoryID != null) {
			setCopReportRepositoryID(copReportRepositoryID);
		}

		String copReportNo = (String)attributes.get("copReportNo");

		if (copReportNo != null) {
			setCopReportNo(copReportNo);
		}

		Long sequenceNo = (Long)attributes.get("sequenceNo");

		if (sequenceNo != null) {
			setSequenceNo(sequenceNo);
		}

		String productClassificationCode = (String)attributes.get(
				"productClassificationCode");

		if (productClassificationCode != null) {
			setProductClassificationCode(productClassificationCode);
		}

		String productClassificationDescription = (String)attributes.get(
				"productClassificationDescription");

		if (productClassificationDescription != null) {
			setProductClassificationDescription(productClassificationDescription);
		}

		Date modifyDate = (Date)attributes.get("modifyDate");

		if (modifyDate != null) {
			setModifyDate(modifyDate);
		}

		Date syncDate = (Date)attributes.get("syncDate");

		if (syncDate != null) {
			setSyncDate(syncDate);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getMtCore() {
		return _mtCore;
	}

	@Override
	public void setMtCore(long mtCore) {
		_columnBitmask |= MTCORE_COLUMN_BITMASK;

		if (!_setOriginalMtCore) {
			_setOriginalMtCore = true;

			_originalMtCore = _mtCore;
		}

		_mtCore = mtCore;
	}

	public long getOriginalMtCore() {
		return _originalMtCore;
	}

	@Override
	public long getCopReportRepositoryID() {
		return _copReportRepositoryID;
	}

	@Override
	public void setCopReportRepositoryID(long copReportRepositoryID) {
		_columnBitmask |= COPREPORTREPOSITORYID_COLUMN_BITMASK;

		if (!_setOriginalCopReportRepositoryID) {
			_setOriginalCopReportRepositoryID = true;

			_originalCopReportRepositoryID = _copReportRepositoryID;
		}

		_copReportRepositoryID = copReportRepositoryID;
	}

	public long getOriginalCopReportRepositoryID() {
		return _originalCopReportRepositoryID;
	}

	@Override
	public String getCopReportNo() {
		if (_copReportNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _copReportNo;
		}
	}

	@Override
	public void setCopReportNo(String copReportNo) {
		_columnBitmask |= COPREPORTNO_COLUMN_BITMASK;

		if (_originalCopReportNo == null) {
			_originalCopReportNo = _copReportNo;
		}

		_copReportNo = copReportNo;
	}

	public String getOriginalCopReportNo() {
		return GetterUtil.getString(_originalCopReportNo);
	}

	@Override
	public long getSequenceNo() {
		return _sequenceNo;
	}

	@Override
	public void setSequenceNo(long sequenceNo) {
		_sequenceNo = sequenceNo;
	}

	@Override
	public String getProductClassificationCode() {
		if (_productClassificationCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _productClassificationCode;
		}
	}

	@Override
	public void setProductClassificationCode(String productClassificationCode) {
		_productClassificationCode = productClassificationCode;
	}

	@Override
	public String getProductClassificationDescription() {
		if (_productClassificationDescription == null) {
			return StringPool.BLANK;
		}
		else {
			return _productClassificationDescription;
		}
	}

	@Override
	public void setProductClassificationDescription(
		String productClassificationDescription) {
		_productClassificationDescription = productClassificationDescription;
	}

	@Override
	public Date getModifyDate() {
		return _modifyDate;
	}

	@Override
	public void setModifyDate(Date modifyDate) {
		_columnBitmask = -1L;

		_modifyDate = modifyDate;
	}

	@Override
	public Date getSyncDate() {
		return _syncDate;
	}

	@Override
	public void setSyncDate(Date syncDate) {
		_syncDate = syncDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VRCOPProductClassification.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VRCOPProductClassification toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VRCOPProductClassification)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VRCOPProductClassificationImpl vrcopProductClassificationImpl = new VRCOPProductClassificationImpl();

		vrcopProductClassificationImpl.setId(getId());
		vrcopProductClassificationImpl.setMtCore(getMtCore());
		vrcopProductClassificationImpl.setCopReportRepositoryID(getCopReportRepositoryID());
		vrcopProductClassificationImpl.setCopReportNo(getCopReportNo());
		vrcopProductClassificationImpl.setSequenceNo(getSequenceNo());
		vrcopProductClassificationImpl.setProductClassificationCode(getProductClassificationCode());
		vrcopProductClassificationImpl.setProductClassificationDescription(getProductClassificationDescription());
		vrcopProductClassificationImpl.setModifyDate(getModifyDate());
		vrcopProductClassificationImpl.setSyncDate(getSyncDate());

		vrcopProductClassificationImpl.resetOriginalValues();

		return vrcopProductClassificationImpl;
	}

	@Override
	public int compareTo(VRCOPProductClassification vrcopProductClassification) {
		int value = 0;

		value = DateUtil.compareTo(getModifyDate(),
				vrcopProductClassification.getModifyDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VRCOPProductClassification)) {
			return false;
		}

		VRCOPProductClassification vrcopProductClassification = (VRCOPProductClassification)obj;

		long primaryKey = vrcopProductClassification.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VRCOPProductClassificationModelImpl vrcopProductClassificationModelImpl = this;

		vrcopProductClassificationModelImpl._originalMtCore = vrcopProductClassificationModelImpl._mtCore;

		vrcopProductClassificationModelImpl._setOriginalMtCore = false;

		vrcopProductClassificationModelImpl._originalCopReportRepositoryID = vrcopProductClassificationModelImpl._copReportRepositoryID;

		vrcopProductClassificationModelImpl._setOriginalCopReportRepositoryID = false;

		vrcopProductClassificationModelImpl._originalCopReportNo = vrcopProductClassificationModelImpl._copReportNo;

		vrcopProductClassificationModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VRCOPProductClassification> toCacheModel() {
		VRCOPProductClassificationCacheModel vrcopProductClassificationCacheModel =
			new VRCOPProductClassificationCacheModel();

		vrcopProductClassificationCacheModel.id = getId();

		vrcopProductClassificationCacheModel.mtCore = getMtCore();

		vrcopProductClassificationCacheModel.copReportRepositoryID = getCopReportRepositoryID();

		vrcopProductClassificationCacheModel.copReportNo = getCopReportNo();

		String copReportNo = vrcopProductClassificationCacheModel.copReportNo;

		if ((copReportNo != null) && (copReportNo.length() == 0)) {
			vrcopProductClassificationCacheModel.copReportNo = null;
		}

		vrcopProductClassificationCacheModel.sequenceNo = getSequenceNo();

		vrcopProductClassificationCacheModel.productClassificationCode = getProductClassificationCode();

		String productClassificationCode = vrcopProductClassificationCacheModel.productClassificationCode;

		if ((productClassificationCode != null) &&
				(productClassificationCode.length() == 0)) {
			vrcopProductClassificationCacheModel.productClassificationCode = null;
		}

		vrcopProductClassificationCacheModel.productClassificationDescription = getProductClassificationDescription();

		String productClassificationDescription = vrcopProductClassificationCacheModel.productClassificationDescription;

		if ((productClassificationDescription != null) &&
				(productClassificationDescription.length() == 0)) {
			vrcopProductClassificationCacheModel.productClassificationDescription = null;
		}

		Date modifyDate = getModifyDate();

		if (modifyDate != null) {
			vrcopProductClassificationCacheModel.modifyDate = modifyDate.getTime();
		}
		else {
			vrcopProductClassificationCacheModel.modifyDate = Long.MIN_VALUE;
		}

		Date syncDate = getSyncDate();

		if (syncDate != null) {
			vrcopProductClassificationCacheModel.syncDate = syncDate.getTime();
		}
		else {
			vrcopProductClassificationCacheModel.syncDate = Long.MIN_VALUE;
		}

		return vrcopProductClassificationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(19);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", mtCore=");
		sb.append(getMtCore());
		sb.append(", copReportRepositoryID=");
		sb.append(getCopReportRepositoryID());
		sb.append(", copReportNo=");
		sb.append(getCopReportNo());
		sb.append(", sequenceNo=");
		sb.append(getSequenceNo());
		sb.append(", productClassificationCode=");
		sb.append(getProductClassificationCode());
		sb.append(", productClassificationDescription=");
		sb.append(getProductClassificationDescription());
		sb.append(", modifyDate=");
		sb.append(getModifyDate());
		sb.append(", syncDate=");
		sb.append(getSyncDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(31);

		sb.append("<model><model-name>");
		sb.append("com.fds.vr.business.model.VRCOPProductClassification");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mtCore</column-name><column-value><![CDATA[");
		sb.append(getMtCore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>copReportRepositoryID</column-name><column-value><![CDATA[");
		sb.append(getCopReportRepositoryID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>copReportNo</column-name><column-value><![CDATA[");
		sb.append(getCopReportNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sequenceNo</column-name><column-value><![CDATA[");
		sb.append(getSequenceNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productClassificationCode</column-name><column-value><![CDATA[");
		sb.append(getProductClassificationCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>productClassificationDescription</column-name><column-value><![CDATA[");
		sb.append(getProductClassificationDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDate</column-name><column-value><![CDATA[");
		sb.append(getModifyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>syncDate</column-name><column-value><![CDATA[");
		sb.append(getSyncDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VRCOPProductClassification.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VRCOPProductClassification.class
		};
	private long _id;
	private long _mtCore;
	private long _originalMtCore;
	private boolean _setOriginalMtCore;
	private long _copReportRepositoryID;
	private long _originalCopReportRepositoryID;
	private boolean _setOriginalCopReportRepositoryID;
	private String _copReportNo;
	private String _originalCopReportNo;
	private long _sequenceNo;
	private String _productClassificationCode;
	private String _productClassificationDescription;
	private Date _modifyDate;
	private Date _syncDate;
	private long _columnBitmask;
	private VRCOPProductClassification _escapedModel;
}