/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.fds.vr.business.model.VRCOPProductLine;
import com.fds.vr.business.model.VRCOPProductLineModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VRCOPProductLine service. Represents a row in the &quot;vr_copproductline&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VRCOPProductLineModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VRCOPProductLineImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRCOPProductLineImpl
 * @see VRCOPProductLine
 * @see VRCOPProductLineModel
 * @generated
 */
@ProviderType
public class VRCOPProductLineModelImpl extends BaseModelImpl<VRCOPProductLine>
	implements VRCOPProductLineModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vrcop product line model instance should use the {@link VRCOPProductLine} interface instead.
	 */
	public static final String TABLE_NAME = "vr_copproductline";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "mtCore", Types.BIGINT },
			{ "copReportRepositoryID", Types.BIGINT },
			{ "copReportNo", Types.VARCHAR },
			{ "copProductTypeID", Types.BIGINT },
			{ "sequenceNo", Types.BIGINT },
			{ "trademark", Types.VARCHAR },
			{ "trademarkName", Types.VARCHAR },
			{ "commercialName", Types.VARCHAR },
			{ "modelCode", Types.VARCHAR },
			{ "designSymbolNo", Types.VARCHAR },
			{ "modifyDate", Types.TIMESTAMP },
			{ "syncDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mtCore", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("copReportRepositoryID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("copReportNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("copProductTypeID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("sequenceNo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("trademark", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trademarkName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("commercialName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modelCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("designSymbolNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifyDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("syncDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table vr_copproductline (id LONG not null primary key,mtCore LONG,copReportRepositoryID LONG,copReportNo VARCHAR(75) null,copProductTypeID LONG,sequenceNo LONG,trademark VARCHAR(75) null,trademarkName VARCHAR(75) null,commercialName VARCHAR(75) null,modelCode VARCHAR(75) null,designSymbolNo VARCHAR(75) null,modifyDate DATE null,syncDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table vr_copproductline";
	public static final String ORDER_BY_JPQL = " ORDER BY vrcopProductLine.modifyDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY vr_copproductline.modifyDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fds.vr.business.model.VRCOPProductLine"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fds.vr.business.model.VRCOPProductLine"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.fds.vr.business.model.VRCOPProductLine"),
			true);
	public static final long COPREPORTNO_COLUMN_BITMASK = 1L;
	public static final long COPREPORTREPOSITORYID_COLUMN_BITMASK = 2L;
	public static final long MTCORE_COLUMN_BITMASK = 4L;
	public static final long MODIFYDATE_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.fds.vr.service.util.ServiceProps.get(
				"lock.expiration.time.com.fds.vr.business.model.VRCOPProductLine"));

	public VRCOPProductLineModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VRCOPProductLine.class;
	}

	@Override
	public String getModelClassName() {
		return VRCOPProductLine.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("mtCore", getMtCore());
		attributes.put("copReportRepositoryID", getCopReportRepositoryID());
		attributes.put("copReportNo", getCopReportNo());
		attributes.put("copProductTypeID", getCopProductTypeID());
		attributes.put("sequenceNo", getSequenceNo());
		attributes.put("trademark", getTrademark());
		attributes.put("trademarkName", getTrademarkName());
		attributes.put("commercialName", getCommercialName());
		attributes.put("modelCode", getModelCode());
		attributes.put("designSymbolNo", getDesignSymbolNo());
		attributes.put("modifyDate", getModifyDate());
		attributes.put("syncDate", getSyncDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long mtCore = (Long)attributes.get("mtCore");

		if (mtCore != null) {
			setMtCore(mtCore);
		}

		Long copReportRepositoryID = (Long)attributes.get(
				"copReportRepositoryID");

		if (copReportRepositoryID != null) {
			setCopReportRepositoryID(copReportRepositoryID);
		}

		String copReportNo = (String)attributes.get("copReportNo");

		if (copReportNo != null) {
			setCopReportNo(copReportNo);
		}

		Long copProductTypeID = (Long)attributes.get("copProductTypeID");

		if (copProductTypeID != null) {
			setCopProductTypeID(copProductTypeID);
		}

		Long sequenceNo = (Long)attributes.get("sequenceNo");

		if (sequenceNo != null) {
			setSequenceNo(sequenceNo);
		}

		String trademark = (String)attributes.get("trademark");

		if (trademark != null) {
			setTrademark(trademark);
		}

		String trademarkName = (String)attributes.get("trademarkName");

		if (trademarkName != null) {
			setTrademarkName(trademarkName);
		}

		String commercialName = (String)attributes.get("commercialName");

		if (commercialName != null) {
			setCommercialName(commercialName);
		}

		String modelCode = (String)attributes.get("modelCode");

		if (modelCode != null) {
			setModelCode(modelCode);
		}

		String designSymbolNo = (String)attributes.get("designSymbolNo");

		if (designSymbolNo != null) {
			setDesignSymbolNo(designSymbolNo);
		}

		Date modifyDate = (Date)attributes.get("modifyDate");

		if (modifyDate != null) {
			setModifyDate(modifyDate);
		}

		Date syncDate = (Date)attributes.get("syncDate");

		if (syncDate != null) {
			setSyncDate(syncDate);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getMtCore() {
		return _mtCore;
	}

	@Override
	public void setMtCore(long mtCore) {
		_columnBitmask |= MTCORE_COLUMN_BITMASK;

		if (!_setOriginalMtCore) {
			_setOriginalMtCore = true;

			_originalMtCore = _mtCore;
		}

		_mtCore = mtCore;
	}

	public long getOriginalMtCore() {
		return _originalMtCore;
	}

	@Override
	public long getCopReportRepositoryID() {
		return _copReportRepositoryID;
	}

	@Override
	public void setCopReportRepositoryID(long copReportRepositoryID) {
		_columnBitmask |= COPREPORTREPOSITORYID_COLUMN_BITMASK;

		if (!_setOriginalCopReportRepositoryID) {
			_setOriginalCopReportRepositoryID = true;

			_originalCopReportRepositoryID = _copReportRepositoryID;
		}

		_copReportRepositoryID = copReportRepositoryID;
	}

	public long getOriginalCopReportRepositoryID() {
		return _originalCopReportRepositoryID;
	}

	@Override
	public String getCopReportNo() {
		if (_copReportNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _copReportNo;
		}
	}

	@Override
	public void setCopReportNo(String copReportNo) {
		_columnBitmask |= COPREPORTNO_COLUMN_BITMASK;

		if (_originalCopReportNo == null) {
			_originalCopReportNo = _copReportNo;
		}

		_copReportNo = copReportNo;
	}

	public String getOriginalCopReportNo() {
		return GetterUtil.getString(_originalCopReportNo);
	}

	@Override
	public long getCopProductTypeID() {
		return _copProductTypeID;
	}

	@Override
	public void setCopProductTypeID(long copProductTypeID) {
		_copProductTypeID = copProductTypeID;
	}

	@Override
	public long getSequenceNo() {
		return _sequenceNo;
	}

	@Override
	public void setSequenceNo(long sequenceNo) {
		_sequenceNo = sequenceNo;
	}

	@Override
	public String getTrademark() {
		if (_trademark == null) {
			return StringPool.BLANK;
		}
		else {
			return _trademark;
		}
	}

	@Override
	public void setTrademark(String trademark) {
		_trademark = trademark;
	}

	@Override
	public String getTrademarkName() {
		if (_trademarkName == null) {
			return StringPool.BLANK;
		}
		else {
			return _trademarkName;
		}
	}

	@Override
	public void setTrademarkName(String trademarkName) {
		_trademarkName = trademarkName;
	}

	@Override
	public String getCommercialName() {
		if (_commercialName == null) {
			return StringPool.BLANK;
		}
		else {
			return _commercialName;
		}
	}

	@Override
	public void setCommercialName(String commercialName) {
		_commercialName = commercialName;
	}

	@Override
	public String getModelCode() {
		if (_modelCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _modelCode;
		}
	}

	@Override
	public void setModelCode(String modelCode) {
		_modelCode = modelCode;
	}

	@Override
	public String getDesignSymbolNo() {
		if (_designSymbolNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _designSymbolNo;
		}
	}

	@Override
	public void setDesignSymbolNo(String designSymbolNo) {
		_designSymbolNo = designSymbolNo;
	}

	@Override
	public Date getModifyDate() {
		return _modifyDate;
	}

	@Override
	public void setModifyDate(Date modifyDate) {
		_columnBitmask = -1L;

		_modifyDate = modifyDate;
	}

	@Override
	public Date getSyncDate() {
		return _syncDate;
	}

	@Override
	public void setSyncDate(Date syncDate) {
		_syncDate = syncDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VRCOPProductLine.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VRCOPProductLine toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VRCOPProductLine)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VRCOPProductLineImpl vrcopProductLineImpl = new VRCOPProductLineImpl();

		vrcopProductLineImpl.setId(getId());
		vrcopProductLineImpl.setMtCore(getMtCore());
		vrcopProductLineImpl.setCopReportRepositoryID(getCopReportRepositoryID());
		vrcopProductLineImpl.setCopReportNo(getCopReportNo());
		vrcopProductLineImpl.setCopProductTypeID(getCopProductTypeID());
		vrcopProductLineImpl.setSequenceNo(getSequenceNo());
		vrcopProductLineImpl.setTrademark(getTrademark());
		vrcopProductLineImpl.setTrademarkName(getTrademarkName());
		vrcopProductLineImpl.setCommercialName(getCommercialName());
		vrcopProductLineImpl.setModelCode(getModelCode());
		vrcopProductLineImpl.setDesignSymbolNo(getDesignSymbolNo());
		vrcopProductLineImpl.setModifyDate(getModifyDate());
		vrcopProductLineImpl.setSyncDate(getSyncDate());

		vrcopProductLineImpl.resetOriginalValues();

		return vrcopProductLineImpl;
	}

	@Override
	public int compareTo(VRCOPProductLine vrcopProductLine) {
		int value = 0;

		value = DateUtil.compareTo(getModifyDate(),
				vrcopProductLine.getModifyDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VRCOPProductLine)) {
			return false;
		}

		VRCOPProductLine vrcopProductLine = (VRCOPProductLine)obj;

		long primaryKey = vrcopProductLine.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VRCOPProductLineModelImpl vrcopProductLineModelImpl = this;

		vrcopProductLineModelImpl._originalMtCore = vrcopProductLineModelImpl._mtCore;

		vrcopProductLineModelImpl._setOriginalMtCore = false;

		vrcopProductLineModelImpl._originalCopReportRepositoryID = vrcopProductLineModelImpl._copReportRepositoryID;

		vrcopProductLineModelImpl._setOriginalCopReportRepositoryID = false;

		vrcopProductLineModelImpl._originalCopReportNo = vrcopProductLineModelImpl._copReportNo;

		vrcopProductLineModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VRCOPProductLine> toCacheModel() {
		VRCOPProductLineCacheModel vrcopProductLineCacheModel = new VRCOPProductLineCacheModel();

		vrcopProductLineCacheModel.id = getId();

		vrcopProductLineCacheModel.mtCore = getMtCore();

		vrcopProductLineCacheModel.copReportRepositoryID = getCopReportRepositoryID();

		vrcopProductLineCacheModel.copReportNo = getCopReportNo();

		String copReportNo = vrcopProductLineCacheModel.copReportNo;

		if ((copReportNo != null) && (copReportNo.length() == 0)) {
			vrcopProductLineCacheModel.copReportNo = null;
		}

		vrcopProductLineCacheModel.copProductTypeID = getCopProductTypeID();

		vrcopProductLineCacheModel.sequenceNo = getSequenceNo();

		vrcopProductLineCacheModel.trademark = getTrademark();

		String trademark = vrcopProductLineCacheModel.trademark;

		if ((trademark != null) && (trademark.length() == 0)) {
			vrcopProductLineCacheModel.trademark = null;
		}

		vrcopProductLineCacheModel.trademarkName = getTrademarkName();

		String trademarkName = vrcopProductLineCacheModel.trademarkName;

		if ((trademarkName != null) && (trademarkName.length() == 0)) {
			vrcopProductLineCacheModel.trademarkName = null;
		}

		vrcopProductLineCacheModel.commercialName = getCommercialName();

		String commercialName = vrcopProductLineCacheModel.commercialName;

		if ((commercialName != null) && (commercialName.length() == 0)) {
			vrcopProductLineCacheModel.commercialName = null;
		}

		vrcopProductLineCacheModel.modelCode = getModelCode();

		String modelCode = vrcopProductLineCacheModel.modelCode;

		if ((modelCode != null) && (modelCode.length() == 0)) {
			vrcopProductLineCacheModel.modelCode = null;
		}

		vrcopProductLineCacheModel.designSymbolNo = getDesignSymbolNo();

		String designSymbolNo = vrcopProductLineCacheModel.designSymbolNo;

		if ((designSymbolNo != null) && (designSymbolNo.length() == 0)) {
			vrcopProductLineCacheModel.designSymbolNo = null;
		}

		Date modifyDate = getModifyDate();

		if (modifyDate != null) {
			vrcopProductLineCacheModel.modifyDate = modifyDate.getTime();
		}
		else {
			vrcopProductLineCacheModel.modifyDate = Long.MIN_VALUE;
		}

		Date syncDate = getSyncDate();

		if (syncDate != null) {
			vrcopProductLineCacheModel.syncDate = syncDate.getTime();
		}
		else {
			vrcopProductLineCacheModel.syncDate = Long.MIN_VALUE;
		}

		return vrcopProductLineCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(27);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", mtCore=");
		sb.append(getMtCore());
		sb.append(", copReportRepositoryID=");
		sb.append(getCopReportRepositoryID());
		sb.append(", copReportNo=");
		sb.append(getCopReportNo());
		sb.append(", copProductTypeID=");
		sb.append(getCopProductTypeID());
		sb.append(", sequenceNo=");
		sb.append(getSequenceNo());
		sb.append(", trademark=");
		sb.append(getTrademark());
		sb.append(", trademarkName=");
		sb.append(getTrademarkName());
		sb.append(", commercialName=");
		sb.append(getCommercialName());
		sb.append(", modelCode=");
		sb.append(getModelCode());
		sb.append(", designSymbolNo=");
		sb.append(getDesignSymbolNo());
		sb.append(", modifyDate=");
		sb.append(getModifyDate());
		sb.append(", syncDate=");
		sb.append(getSyncDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(43);

		sb.append("<model><model-name>");
		sb.append("com.fds.vr.business.model.VRCOPProductLine");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mtCore</column-name><column-value><![CDATA[");
		sb.append(getMtCore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>copReportRepositoryID</column-name><column-value><![CDATA[");
		sb.append(getCopReportRepositoryID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>copReportNo</column-name><column-value><![CDATA[");
		sb.append(getCopReportNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>copProductTypeID</column-name><column-value><![CDATA[");
		sb.append(getCopProductTypeID());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sequenceNo</column-name><column-value><![CDATA[");
		sb.append(getSequenceNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trademark</column-name><column-value><![CDATA[");
		sb.append(getTrademark());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>trademarkName</column-name><column-value><![CDATA[");
		sb.append(getTrademarkName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>commercialName</column-name><column-value><![CDATA[");
		sb.append(getCommercialName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modelCode</column-name><column-value><![CDATA[");
		sb.append(getModelCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>designSymbolNo</column-name><column-value><![CDATA[");
		sb.append(getDesignSymbolNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDate</column-name><column-value><![CDATA[");
		sb.append(getModifyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>syncDate</column-name><column-value><![CDATA[");
		sb.append(getSyncDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VRCOPProductLine.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VRCOPProductLine.class
		};
	private long _id;
	private long _mtCore;
	private long _originalMtCore;
	private boolean _setOriginalMtCore;
	private long _copReportRepositoryID;
	private long _originalCopReportRepositoryID;
	private boolean _setOriginalCopReportRepositoryID;
	private String _copReportNo;
	private String _originalCopReportNo;
	private long _copProductTypeID;
	private long _sequenceNo;
	private String _trademark;
	private String _trademarkName;
	private String _commercialName;
	private String _modelCode;
	private String _designSymbolNo;
	private Date _modifyDate;
	private Date _syncDate;
	private long _columnBitmask;
	private VRCOPProductLine _escapedModel;
}