/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.business.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.fds.vr.business.model.VRTechnicalSpec_XCG;
import com.fds.vr.business.model.VRTechnicalSpec_XCGModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the VRTechnicalSpec_XCG service. Represents a row in the &quot;vr_technicalspec_xcg&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VRTechnicalSpec_XCGModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VRTechnicalSpec_XCGImpl}.
 * </p>
 *
 * @author LamTV
 * @see VRTechnicalSpec_XCGImpl
 * @see VRTechnicalSpec_XCG
 * @see VRTechnicalSpec_XCGModel
 * @generated
 */
@ProviderType
public class VRTechnicalSpec_XCGModelImpl extends BaseModelImpl<VRTechnicalSpec_XCG>
	implements VRTechnicalSpec_XCGModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vr technical spec_xcg model instance should use the {@link VRTechnicalSpec_XCG} interface instead.
	 */
	public static final String TABLE_NAME = "vr_technicalspec_xcg";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id", Types.BIGINT },
			{ "mtCore", Types.BIGINT },
			{ "convertassembleId", Types.BIGINT },
			{ "dossierId", Types.BIGINT },
			{ "dossierNo", Types.VARCHAR },
			{ "referenceUid", Types.VARCHAR },
			{ "dossierIdCTN", Types.VARCHAR },
			{ "deliverableCode", Types.VARCHAR },
			{ "vehicleTypeCertificateId", Types.BIGINT },
			{ "XCG01070", Types.VARCHAR },
			{ "XCG01072", Types.VARCHAR },
			{ "XCG01083", Types.VARCHAR },
			{ "XCG01084", Types.VARCHAR },
			{ "XCG01085", Types.VARCHAR },
			{ "XCG01086", Types.VARCHAR },
			{ "XCG01087", Types.VARCHAR },
			{ "XCG01088", Types.VARCHAR },
			{ "XCG01090", Types.VARCHAR },
			{ "XCG01091", Types.VARCHAR },
			{ "XCG01092", Types.VARCHAR },
			{ "XCG01123", Types.VARCHAR },
			{ "XCG01124", Types.VARCHAR },
			{ "XCG01125", Types.VARCHAR },
			{ "XCG01156", Types.VARCHAR },
			{ "XCG01157", Types.VARCHAR },
			{ "XCG01163", Types.VARCHAR },
			{ "XCG01169", Types.VARCHAR },
			{ "XCG01170", Types.VARCHAR },
			{ "XCG01171", Types.VARCHAR },
			{ "XCG01172", Types.VARCHAR },
			{ "XCG01173", Types.VARCHAR },
			{ "XCG01182", Types.VARCHAR },
			{ "XCG01183", Types.VARCHAR },
			{ "XCG01192", Types.VARCHAR },
			{ "loai_dong_co", Types.VARCHAR },
			{ "modifyDate", Types.TIMESTAMP },
			{ "syncDate", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mtCore", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("convertassembleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dossierId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dossierNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("referenceUid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierIdCTN", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("deliverableCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vehicleTypeCertificateId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("XCG01070", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01072", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01083", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01084", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01085", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01086", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01087", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01088", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01090", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01091", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01092", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01123", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01124", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01125", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01156", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01157", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01163", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01169", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01170", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01171", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01172", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01173", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01182", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01183", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("XCG01192", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("loai_dong_co", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("modifyDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("syncDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table vr_technicalspec_xcg (id LONG not null primary key,mtCore LONG,convertassembleId LONG,dossierId LONG,dossierNo VARCHAR(75) null,referenceUid VARCHAR(75) null,dossierIdCTN VARCHAR(75) null,deliverableCode VARCHAR(75) null,vehicleTypeCertificateId LONG,XCG01070 VARCHAR(75) null,XCG01072 VARCHAR(75) null,XCG01083 VARCHAR(75) null,XCG01084 VARCHAR(75) null,XCG01085 VARCHAR(75) null,XCG01086 VARCHAR(75) null,XCG01087 VARCHAR(75) null,XCG01088 VARCHAR(75) null,XCG01090 VARCHAR(75) null,XCG01091 VARCHAR(75) null,XCG01092 VARCHAR(75) null,XCG01123 VARCHAR(75) null,XCG01124 VARCHAR(75) null,XCG01125 VARCHAR(75) null,XCG01156 VARCHAR(75) null,XCG01157 VARCHAR(75) null,XCG01163 VARCHAR(75) null,XCG01169 VARCHAR(75) null,XCG01170 VARCHAR(75) null,XCG01171 VARCHAR(75) null,XCG01172 VARCHAR(75) null,XCG01173 VARCHAR(75) null,XCG01182 VARCHAR(75) null,XCG01183 VARCHAR(75) null,XCG01192 VARCHAR(75) null,loai_dong_co VARCHAR(75) null,modifyDate DATE null,syncDate DATE null)";
	public static final String TABLE_SQL_DROP = "drop table vr_technicalspec_xcg";
	public static final String ORDER_BY_JPQL = " ORDER BY vrTechnicalSpec_XCG.modifyDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY vr_technicalspec_xcg.modifyDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.fds.vr.business.model.VRTechnicalSpec_XCG"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.fds.vr.business.model.VRTechnicalSpec_XCG"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.fds.vr.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.fds.vr.business.model.VRTechnicalSpec_XCG"),
			true);
	public static final long CONVERTASSEMBLEID_COLUMN_BITMASK = 1L;
	public static final long DELIVERABLECODE_COLUMN_BITMASK = 2L;
	public static final long DOSSIERID_COLUMN_BITMASK = 4L;
	public static final long DOSSIERIDCTN_COLUMN_BITMASK = 8L;
	public static final long DOSSIERNO_COLUMN_BITMASK = 16L;
	public static final long MTCORE_COLUMN_BITMASK = 32L;
	public static final long REFERENCEUID_COLUMN_BITMASK = 64L;
	public static final long VEHICLETYPECERTIFICATEID_COLUMN_BITMASK = 128L;
	public static final long MODIFYDATE_COLUMN_BITMASK = 256L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.fds.vr.service.util.ServiceProps.get(
				"lock.expiration.time.com.fds.vr.business.model.VRTechnicalSpec_XCG"));

	public VRTechnicalSpec_XCGModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return VRTechnicalSpec_XCG.class;
	}

	@Override
	public String getModelClassName() {
		return VRTechnicalSpec_XCG.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("mtCore", getMtCore());
		attributes.put("convertAssembleId", getConvertAssembleId());
		attributes.put("dossierId", getDossierId());
		attributes.put("dossierNo", getDossierNo());
		attributes.put("referenceUid", getReferenceUid());
		attributes.put("dossierIdCTN", getDossierIdCTN());
		attributes.put("deliverableCode", getDeliverableCode());
		attributes.put("vehicleTypeCertificateId", getVehicleTypeCertificateId());
		attributes.put("XCG01070", getXCG01070());
		attributes.put("XCG01072", getXCG01072());
		attributes.put("XCG01083", getXCG01083());
		attributes.put("XCG01084", getXCG01084());
		attributes.put("XCG01085", getXCG01085());
		attributes.put("XCG01086", getXCG01086());
		attributes.put("XCG01087", getXCG01087());
		attributes.put("XCG01088", getXCG01088());
		attributes.put("XCG01090", getXCG01090());
		attributes.put("XCG01091", getXCG01091());
		attributes.put("XCG01092", getXCG01092());
		attributes.put("XCG01123", getXCG01123());
		attributes.put("XCG01124", getXCG01124());
		attributes.put("XCG01125", getXCG01125());
		attributes.put("XCG01156", getXCG01156());
		attributes.put("XCG01157", getXCG01157());
		attributes.put("XCG01163", getXCG01163());
		attributes.put("XCG01169", getXCG01169());
		attributes.put("XCG01170", getXCG01170());
		attributes.put("XCG01171", getXCG01171());
		attributes.put("XCG01172", getXCG01172());
		attributes.put("XCG01173", getXCG01173());
		attributes.put("XCG01182", getXCG01182());
		attributes.put("XCG01183", getXCG01183());
		attributes.put("XCG01192", getXCG01192());
		attributes.put("loai_dong_co", getLoai_dong_co());
		attributes.put("modifyDate", getModifyDate());
		attributes.put("syncDate", getSyncDate());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long mtCore = (Long)attributes.get("mtCore");

		if (mtCore != null) {
			setMtCore(mtCore);
		}

		Long convertAssembleId = (Long)attributes.get("convertAssembleId");

		if (convertAssembleId != null) {
			setConvertAssembleId(convertAssembleId);
		}

		Long dossierId = (Long)attributes.get("dossierId");

		if (dossierId != null) {
			setDossierId(dossierId);
		}

		String dossierNo = (String)attributes.get("dossierNo");

		if (dossierNo != null) {
			setDossierNo(dossierNo);
		}

		String referenceUid = (String)attributes.get("referenceUid");

		if (referenceUid != null) {
			setReferenceUid(referenceUid);
		}

		String dossierIdCTN = (String)attributes.get("dossierIdCTN");

		if (dossierIdCTN != null) {
			setDossierIdCTN(dossierIdCTN);
		}

		String deliverableCode = (String)attributes.get("deliverableCode");

		if (deliverableCode != null) {
			setDeliverableCode(deliverableCode);
		}

		Long vehicleTypeCertificateId = (Long)attributes.get(
				"vehicleTypeCertificateId");

		if (vehicleTypeCertificateId != null) {
			setVehicleTypeCertificateId(vehicleTypeCertificateId);
		}

		String XCG01070 = (String)attributes.get("XCG01070");

		if (XCG01070 != null) {
			setXCG01070(XCG01070);
		}

		String XCG01072 = (String)attributes.get("XCG01072");

		if (XCG01072 != null) {
			setXCG01072(XCG01072);
		}

		String XCG01083 = (String)attributes.get("XCG01083");

		if (XCG01083 != null) {
			setXCG01083(XCG01083);
		}

		String XCG01084 = (String)attributes.get("XCG01084");

		if (XCG01084 != null) {
			setXCG01084(XCG01084);
		}

		String XCG01085 = (String)attributes.get("XCG01085");

		if (XCG01085 != null) {
			setXCG01085(XCG01085);
		}

		String XCG01086 = (String)attributes.get("XCG01086");

		if (XCG01086 != null) {
			setXCG01086(XCG01086);
		}

		String XCG01087 = (String)attributes.get("XCG01087");

		if (XCG01087 != null) {
			setXCG01087(XCG01087);
		}

		String XCG01088 = (String)attributes.get("XCG01088");

		if (XCG01088 != null) {
			setXCG01088(XCG01088);
		}

		String XCG01090 = (String)attributes.get("XCG01090");

		if (XCG01090 != null) {
			setXCG01090(XCG01090);
		}

		String XCG01091 = (String)attributes.get("XCG01091");

		if (XCG01091 != null) {
			setXCG01091(XCG01091);
		}

		String XCG01092 = (String)attributes.get("XCG01092");

		if (XCG01092 != null) {
			setXCG01092(XCG01092);
		}

		String XCG01123 = (String)attributes.get("XCG01123");

		if (XCG01123 != null) {
			setXCG01123(XCG01123);
		}

		String XCG01124 = (String)attributes.get("XCG01124");

		if (XCG01124 != null) {
			setXCG01124(XCG01124);
		}

		String XCG01125 = (String)attributes.get("XCG01125");

		if (XCG01125 != null) {
			setXCG01125(XCG01125);
		}

		String XCG01156 = (String)attributes.get("XCG01156");

		if (XCG01156 != null) {
			setXCG01156(XCG01156);
		}

		String XCG01157 = (String)attributes.get("XCG01157");

		if (XCG01157 != null) {
			setXCG01157(XCG01157);
		}

		String XCG01163 = (String)attributes.get("XCG01163");

		if (XCG01163 != null) {
			setXCG01163(XCG01163);
		}

		String XCG01169 = (String)attributes.get("XCG01169");

		if (XCG01169 != null) {
			setXCG01169(XCG01169);
		}

		String XCG01170 = (String)attributes.get("XCG01170");

		if (XCG01170 != null) {
			setXCG01170(XCG01170);
		}

		String XCG01171 = (String)attributes.get("XCG01171");

		if (XCG01171 != null) {
			setXCG01171(XCG01171);
		}

		String XCG01172 = (String)attributes.get("XCG01172");

		if (XCG01172 != null) {
			setXCG01172(XCG01172);
		}

		String XCG01173 = (String)attributes.get("XCG01173");

		if (XCG01173 != null) {
			setXCG01173(XCG01173);
		}

		String XCG01182 = (String)attributes.get("XCG01182");

		if (XCG01182 != null) {
			setXCG01182(XCG01182);
		}

		String XCG01183 = (String)attributes.get("XCG01183");

		if (XCG01183 != null) {
			setXCG01183(XCG01183);
		}

		String XCG01192 = (String)attributes.get("XCG01192");

		if (XCG01192 != null) {
			setXCG01192(XCG01192);
		}

		String loai_dong_co = (String)attributes.get("loai_dong_co");

		if (loai_dong_co != null) {
			setLoai_dong_co(loai_dong_co);
		}

		Date modifyDate = (Date)attributes.get("modifyDate");

		if (modifyDate != null) {
			setModifyDate(modifyDate);
		}

		Date syncDate = (Date)attributes.get("syncDate");

		if (syncDate != null) {
			setSyncDate(syncDate);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@Override
	public long getMtCore() {
		return _mtCore;
	}

	@Override
	public void setMtCore(long mtCore) {
		_columnBitmask |= MTCORE_COLUMN_BITMASK;

		if (!_setOriginalMtCore) {
			_setOriginalMtCore = true;

			_originalMtCore = _mtCore;
		}

		_mtCore = mtCore;
	}

	public long getOriginalMtCore() {
		return _originalMtCore;
	}

	@Override
	public long getConvertAssembleId() {
		return _convertAssembleId;
	}

	@Override
	public void setConvertAssembleId(long convertAssembleId) {
		_columnBitmask |= CONVERTASSEMBLEID_COLUMN_BITMASK;

		if (!_setOriginalConvertAssembleId) {
			_setOriginalConvertAssembleId = true;

			_originalConvertAssembleId = _convertAssembleId;
		}

		_convertAssembleId = convertAssembleId;
	}

	public long getOriginalConvertAssembleId() {
		return _originalConvertAssembleId;
	}

	@Override
	public long getDossierId() {
		return _dossierId;
	}

	@Override
	public void setDossierId(long dossierId) {
		_columnBitmask |= DOSSIERID_COLUMN_BITMASK;

		if (!_setOriginalDossierId) {
			_setOriginalDossierId = true;

			_originalDossierId = _dossierId;
		}

		_dossierId = dossierId;
	}

	public long getOriginalDossierId() {
		return _originalDossierId;
	}

	@Override
	public String getDossierNo() {
		if (_dossierNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierNo;
		}
	}

	@Override
	public void setDossierNo(String dossierNo) {
		_columnBitmask |= DOSSIERNO_COLUMN_BITMASK;

		if (_originalDossierNo == null) {
			_originalDossierNo = _dossierNo;
		}

		_dossierNo = dossierNo;
	}

	public String getOriginalDossierNo() {
		return GetterUtil.getString(_originalDossierNo);
	}

	@Override
	public String getReferenceUid() {
		if (_referenceUid == null) {
			return StringPool.BLANK;
		}
		else {
			return _referenceUid;
		}
	}

	@Override
	public void setReferenceUid(String referenceUid) {
		_columnBitmask |= REFERENCEUID_COLUMN_BITMASK;

		if (_originalReferenceUid == null) {
			_originalReferenceUid = _referenceUid;
		}

		_referenceUid = referenceUid;
	}

	public String getOriginalReferenceUid() {
		return GetterUtil.getString(_originalReferenceUid);
	}

	@Override
	public String getDossierIdCTN() {
		if (_dossierIdCTN == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierIdCTN;
		}
	}

	@Override
	public void setDossierIdCTN(String dossierIdCTN) {
		_columnBitmask |= DOSSIERIDCTN_COLUMN_BITMASK;

		if (_originalDossierIdCTN == null) {
			_originalDossierIdCTN = _dossierIdCTN;
		}

		_dossierIdCTN = dossierIdCTN;
	}

	public String getOriginalDossierIdCTN() {
		return GetterUtil.getString(_originalDossierIdCTN);
	}

	@Override
	public String getDeliverableCode() {
		if (_deliverableCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _deliverableCode;
		}
	}

	@Override
	public void setDeliverableCode(String deliverableCode) {
		_columnBitmask |= DELIVERABLECODE_COLUMN_BITMASK;

		if (_originalDeliverableCode == null) {
			_originalDeliverableCode = _deliverableCode;
		}

		_deliverableCode = deliverableCode;
	}

	public String getOriginalDeliverableCode() {
		return GetterUtil.getString(_originalDeliverableCode);
	}

	@Override
	public long getVehicleTypeCertificateId() {
		return _vehicleTypeCertificateId;
	}

	@Override
	public void setVehicleTypeCertificateId(long vehicleTypeCertificateId) {
		_columnBitmask |= VEHICLETYPECERTIFICATEID_COLUMN_BITMASK;

		if (!_setOriginalVehicleTypeCertificateId) {
			_setOriginalVehicleTypeCertificateId = true;

			_originalVehicleTypeCertificateId = _vehicleTypeCertificateId;
		}

		_vehicleTypeCertificateId = vehicleTypeCertificateId;
	}

	public long getOriginalVehicleTypeCertificateId() {
		return _originalVehicleTypeCertificateId;
	}

	@Override
	public String getXCG01070() {
		if (_XCG01070 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01070;
		}
	}

	@Override
	public void setXCG01070(String XCG01070) {
		_XCG01070 = XCG01070;
	}

	@Override
	public String getXCG01072() {
		if (_XCG01072 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01072;
		}
	}

	@Override
	public void setXCG01072(String XCG01072) {
		_XCG01072 = XCG01072;
	}

	@Override
	public String getXCG01083() {
		if (_XCG01083 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01083;
		}
	}

	@Override
	public void setXCG01083(String XCG01083) {
		_XCG01083 = XCG01083;
	}

	@Override
	public String getXCG01084() {
		if (_XCG01084 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01084;
		}
	}

	@Override
	public void setXCG01084(String XCG01084) {
		_XCG01084 = XCG01084;
	}

	@Override
	public String getXCG01085() {
		if (_XCG01085 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01085;
		}
	}

	@Override
	public void setXCG01085(String XCG01085) {
		_XCG01085 = XCG01085;
	}

	@Override
	public String getXCG01086() {
		if (_XCG01086 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01086;
		}
	}

	@Override
	public void setXCG01086(String XCG01086) {
		_XCG01086 = XCG01086;
	}

	@Override
	public String getXCG01087() {
		if (_XCG01087 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01087;
		}
	}

	@Override
	public void setXCG01087(String XCG01087) {
		_XCG01087 = XCG01087;
	}

	@Override
	public String getXCG01088() {
		if (_XCG01088 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01088;
		}
	}

	@Override
	public void setXCG01088(String XCG01088) {
		_XCG01088 = XCG01088;
	}

	@Override
	public String getXCG01090() {
		if (_XCG01090 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01090;
		}
	}

	@Override
	public void setXCG01090(String XCG01090) {
		_XCG01090 = XCG01090;
	}

	@Override
	public String getXCG01091() {
		if (_XCG01091 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01091;
		}
	}

	@Override
	public void setXCG01091(String XCG01091) {
		_XCG01091 = XCG01091;
	}

	@Override
	public String getXCG01092() {
		if (_XCG01092 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01092;
		}
	}

	@Override
	public void setXCG01092(String XCG01092) {
		_XCG01092 = XCG01092;
	}

	@Override
	public String getXCG01123() {
		if (_XCG01123 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01123;
		}
	}

	@Override
	public void setXCG01123(String XCG01123) {
		_XCG01123 = XCG01123;
	}

	@Override
	public String getXCG01124() {
		if (_XCG01124 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01124;
		}
	}

	@Override
	public void setXCG01124(String XCG01124) {
		_XCG01124 = XCG01124;
	}

	@Override
	public String getXCG01125() {
		if (_XCG01125 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01125;
		}
	}

	@Override
	public void setXCG01125(String XCG01125) {
		_XCG01125 = XCG01125;
	}

	@Override
	public String getXCG01156() {
		if (_XCG01156 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01156;
		}
	}

	@Override
	public void setXCG01156(String XCG01156) {
		_XCG01156 = XCG01156;
	}

	@Override
	public String getXCG01157() {
		if (_XCG01157 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01157;
		}
	}

	@Override
	public void setXCG01157(String XCG01157) {
		_XCG01157 = XCG01157;
	}

	@Override
	public String getXCG01163() {
		if (_XCG01163 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01163;
		}
	}

	@Override
	public void setXCG01163(String XCG01163) {
		_XCG01163 = XCG01163;
	}

	@Override
	public String getXCG01169() {
		if (_XCG01169 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01169;
		}
	}

	@Override
	public void setXCG01169(String XCG01169) {
		_XCG01169 = XCG01169;
	}

	@Override
	public String getXCG01170() {
		if (_XCG01170 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01170;
		}
	}

	@Override
	public void setXCG01170(String XCG01170) {
		_XCG01170 = XCG01170;
	}

	@Override
	public String getXCG01171() {
		if (_XCG01171 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01171;
		}
	}

	@Override
	public void setXCG01171(String XCG01171) {
		_XCG01171 = XCG01171;
	}

	@Override
	public String getXCG01172() {
		if (_XCG01172 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01172;
		}
	}

	@Override
	public void setXCG01172(String XCG01172) {
		_XCG01172 = XCG01172;
	}

	@Override
	public String getXCG01173() {
		if (_XCG01173 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01173;
		}
	}

	@Override
	public void setXCG01173(String XCG01173) {
		_XCG01173 = XCG01173;
	}

	@Override
	public String getXCG01182() {
		if (_XCG01182 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01182;
		}
	}

	@Override
	public void setXCG01182(String XCG01182) {
		_XCG01182 = XCG01182;
	}

	@Override
	public String getXCG01183() {
		if (_XCG01183 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01183;
		}
	}

	@Override
	public void setXCG01183(String XCG01183) {
		_XCG01183 = XCG01183;
	}

	@Override
	public String getXCG01192() {
		if (_XCG01192 == null) {
			return StringPool.BLANK;
		}
		else {
			return _XCG01192;
		}
	}

	@Override
	public void setXCG01192(String XCG01192) {
		_XCG01192 = XCG01192;
	}

	@Override
	public String getLoai_dong_co() {
		if (_loai_dong_co == null) {
			return StringPool.BLANK;
		}
		else {
			return _loai_dong_co;
		}
	}

	@Override
	public void setLoai_dong_co(String loai_dong_co) {
		_loai_dong_co = loai_dong_co;
	}

	@Override
	public Date getModifyDate() {
		return _modifyDate;
	}

	@Override
	public void setModifyDate(Date modifyDate) {
		_columnBitmask = -1L;

		_modifyDate = modifyDate;
	}

	@Override
	public Date getSyncDate() {
		return _syncDate;
	}

	@Override
	public void setSyncDate(Date syncDate) {
		_syncDate = syncDate;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			VRTechnicalSpec_XCG.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public VRTechnicalSpec_XCG toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (VRTechnicalSpec_XCG)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VRTechnicalSpec_XCGImpl vrTechnicalSpec_XCGImpl = new VRTechnicalSpec_XCGImpl();

		vrTechnicalSpec_XCGImpl.setId(getId());
		vrTechnicalSpec_XCGImpl.setMtCore(getMtCore());
		vrTechnicalSpec_XCGImpl.setConvertAssembleId(getConvertAssembleId());
		vrTechnicalSpec_XCGImpl.setDossierId(getDossierId());
		vrTechnicalSpec_XCGImpl.setDossierNo(getDossierNo());
		vrTechnicalSpec_XCGImpl.setReferenceUid(getReferenceUid());
		vrTechnicalSpec_XCGImpl.setDossierIdCTN(getDossierIdCTN());
		vrTechnicalSpec_XCGImpl.setDeliverableCode(getDeliverableCode());
		vrTechnicalSpec_XCGImpl.setVehicleTypeCertificateId(getVehicleTypeCertificateId());
		vrTechnicalSpec_XCGImpl.setXCG01070(getXCG01070());
		vrTechnicalSpec_XCGImpl.setXCG01072(getXCG01072());
		vrTechnicalSpec_XCGImpl.setXCG01083(getXCG01083());
		vrTechnicalSpec_XCGImpl.setXCG01084(getXCG01084());
		vrTechnicalSpec_XCGImpl.setXCG01085(getXCG01085());
		vrTechnicalSpec_XCGImpl.setXCG01086(getXCG01086());
		vrTechnicalSpec_XCGImpl.setXCG01087(getXCG01087());
		vrTechnicalSpec_XCGImpl.setXCG01088(getXCG01088());
		vrTechnicalSpec_XCGImpl.setXCG01090(getXCG01090());
		vrTechnicalSpec_XCGImpl.setXCG01091(getXCG01091());
		vrTechnicalSpec_XCGImpl.setXCG01092(getXCG01092());
		vrTechnicalSpec_XCGImpl.setXCG01123(getXCG01123());
		vrTechnicalSpec_XCGImpl.setXCG01124(getXCG01124());
		vrTechnicalSpec_XCGImpl.setXCG01125(getXCG01125());
		vrTechnicalSpec_XCGImpl.setXCG01156(getXCG01156());
		vrTechnicalSpec_XCGImpl.setXCG01157(getXCG01157());
		vrTechnicalSpec_XCGImpl.setXCG01163(getXCG01163());
		vrTechnicalSpec_XCGImpl.setXCG01169(getXCG01169());
		vrTechnicalSpec_XCGImpl.setXCG01170(getXCG01170());
		vrTechnicalSpec_XCGImpl.setXCG01171(getXCG01171());
		vrTechnicalSpec_XCGImpl.setXCG01172(getXCG01172());
		vrTechnicalSpec_XCGImpl.setXCG01173(getXCG01173());
		vrTechnicalSpec_XCGImpl.setXCG01182(getXCG01182());
		vrTechnicalSpec_XCGImpl.setXCG01183(getXCG01183());
		vrTechnicalSpec_XCGImpl.setXCG01192(getXCG01192());
		vrTechnicalSpec_XCGImpl.setLoai_dong_co(getLoai_dong_co());
		vrTechnicalSpec_XCGImpl.setModifyDate(getModifyDate());
		vrTechnicalSpec_XCGImpl.setSyncDate(getSyncDate());

		vrTechnicalSpec_XCGImpl.resetOriginalValues();

		return vrTechnicalSpec_XCGImpl;
	}

	@Override
	public int compareTo(VRTechnicalSpec_XCG vrTechnicalSpec_XCG) {
		int value = 0;

		value = DateUtil.compareTo(getModifyDate(),
				vrTechnicalSpec_XCG.getModifyDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof VRTechnicalSpec_XCG)) {
			return false;
		}

		VRTechnicalSpec_XCG vrTechnicalSpec_XCG = (VRTechnicalSpec_XCG)obj;

		long primaryKey = vrTechnicalSpec_XCG.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		VRTechnicalSpec_XCGModelImpl vrTechnicalSpec_XCGModelImpl = this;

		vrTechnicalSpec_XCGModelImpl._originalMtCore = vrTechnicalSpec_XCGModelImpl._mtCore;

		vrTechnicalSpec_XCGModelImpl._setOriginalMtCore = false;

		vrTechnicalSpec_XCGModelImpl._originalConvertAssembleId = vrTechnicalSpec_XCGModelImpl._convertAssembleId;

		vrTechnicalSpec_XCGModelImpl._setOriginalConvertAssembleId = false;

		vrTechnicalSpec_XCGModelImpl._originalDossierId = vrTechnicalSpec_XCGModelImpl._dossierId;

		vrTechnicalSpec_XCGModelImpl._setOriginalDossierId = false;

		vrTechnicalSpec_XCGModelImpl._originalDossierNo = vrTechnicalSpec_XCGModelImpl._dossierNo;

		vrTechnicalSpec_XCGModelImpl._originalReferenceUid = vrTechnicalSpec_XCGModelImpl._referenceUid;

		vrTechnicalSpec_XCGModelImpl._originalDossierIdCTN = vrTechnicalSpec_XCGModelImpl._dossierIdCTN;

		vrTechnicalSpec_XCGModelImpl._originalDeliverableCode = vrTechnicalSpec_XCGModelImpl._deliverableCode;

		vrTechnicalSpec_XCGModelImpl._originalVehicleTypeCertificateId = vrTechnicalSpec_XCGModelImpl._vehicleTypeCertificateId;

		vrTechnicalSpec_XCGModelImpl._setOriginalVehicleTypeCertificateId = false;

		vrTechnicalSpec_XCGModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<VRTechnicalSpec_XCG> toCacheModel() {
		VRTechnicalSpec_XCGCacheModel vrTechnicalSpec_XCGCacheModel = new VRTechnicalSpec_XCGCacheModel();

		vrTechnicalSpec_XCGCacheModel.id = getId();

		vrTechnicalSpec_XCGCacheModel.mtCore = getMtCore();

		vrTechnicalSpec_XCGCacheModel.convertAssembleId = getConvertAssembleId();

		vrTechnicalSpec_XCGCacheModel.dossierId = getDossierId();

		vrTechnicalSpec_XCGCacheModel.dossierNo = getDossierNo();

		String dossierNo = vrTechnicalSpec_XCGCacheModel.dossierNo;

		if ((dossierNo != null) && (dossierNo.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.dossierNo = null;
		}

		vrTechnicalSpec_XCGCacheModel.referenceUid = getReferenceUid();

		String referenceUid = vrTechnicalSpec_XCGCacheModel.referenceUid;

		if ((referenceUid != null) && (referenceUid.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.referenceUid = null;
		}

		vrTechnicalSpec_XCGCacheModel.dossierIdCTN = getDossierIdCTN();

		String dossierIdCTN = vrTechnicalSpec_XCGCacheModel.dossierIdCTN;

		if ((dossierIdCTN != null) && (dossierIdCTN.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.dossierIdCTN = null;
		}

		vrTechnicalSpec_XCGCacheModel.deliverableCode = getDeliverableCode();

		String deliverableCode = vrTechnicalSpec_XCGCacheModel.deliverableCode;

		if ((deliverableCode != null) && (deliverableCode.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.deliverableCode = null;
		}

		vrTechnicalSpec_XCGCacheModel.vehicleTypeCertificateId = getVehicleTypeCertificateId();

		vrTechnicalSpec_XCGCacheModel.XCG01070 = getXCG01070();

		String XCG01070 = vrTechnicalSpec_XCGCacheModel.XCG01070;

		if ((XCG01070 != null) && (XCG01070.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01070 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01072 = getXCG01072();

		String XCG01072 = vrTechnicalSpec_XCGCacheModel.XCG01072;

		if ((XCG01072 != null) && (XCG01072.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01072 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01083 = getXCG01083();

		String XCG01083 = vrTechnicalSpec_XCGCacheModel.XCG01083;

		if ((XCG01083 != null) && (XCG01083.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01083 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01084 = getXCG01084();

		String XCG01084 = vrTechnicalSpec_XCGCacheModel.XCG01084;

		if ((XCG01084 != null) && (XCG01084.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01084 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01085 = getXCG01085();

		String XCG01085 = vrTechnicalSpec_XCGCacheModel.XCG01085;

		if ((XCG01085 != null) && (XCG01085.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01085 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01086 = getXCG01086();

		String XCG01086 = vrTechnicalSpec_XCGCacheModel.XCG01086;

		if ((XCG01086 != null) && (XCG01086.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01086 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01087 = getXCG01087();

		String XCG01087 = vrTechnicalSpec_XCGCacheModel.XCG01087;

		if ((XCG01087 != null) && (XCG01087.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01087 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01088 = getXCG01088();

		String XCG01088 = vrTechnicalSpec_XCGCacheModel.XCG01088;

		if ((XCG01088 != null) && (XCG01088.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01088 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01090 = getXCG01090();

		String XCG01090 = vrTechnicalSpec_XCGCacheModel.XCG01090;

		if ((XCG01090 != null) && (XCG01090.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01090 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01091 = getXCG01091();

		String XCG01091 = vrTechnicalSpec_XCGCacheModel.XCG01091;

		if ((XCG01091 != null) && (XCG01091.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01091 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01092 = getXCG01092();

		String XCG01092 = vrTechnicalSpec_XCGCacheModel.XCG01092;

		if ((XCG01092 != null) && (XCG01092.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01092 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01123 = getXCG01123();

		String XCG01123 = vrTechnicalSpec_XCGCacheModel.XCG01123;

		if ((XCG01123 != null) && (XCG01123.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01123 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01124 = getXCG01124();

		String XCG01124 = vrTechnicalSpec_XCGCacheModel.XCG01124;

		if ((XCG01124 != null) && (XCG01124.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01124 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01125 = getXCG01125();

		String XCG01125 = vrTechnicalSpec_XCGCacheModel.XCG01125;

		if ((XCG01125 != null) && (XCG01125.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01125 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01156 = getXCG01156();

		String XCG01156 = vrTechnicalSpec_XCGCacheModel.XCG01156;

		if ((XCG01156 != null) && (XCG01156.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01156 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01157 = getXCG01157();

		String XCG01157 = vrTechnicalSpec_XCGCacheModel.XCG01157;

		if ((XCG01157 != null) && (XCG01157.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01157 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01163 = getXCG01163();

		String XCG01163 = vrTechnicalSpec_XCGCacheModel.XCG01163;

		if ((XCG01163 != null) && (XCG01163.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01163 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01169 = getXCG01169();

		String XCG01169 = vrTechnicalSpec_XCGCacheModel.XCG01169;

		if ((XCG01169 != null) && (XCG01169.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01169 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01170 = getXCG01170();

		String XCG01170 = vrTechnicalSpec_XCGCacheModel.XCG01170;

		if ((XCG01170 != null) && (XCG01170.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01170 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01171 = getXCG01171();

		String XCG01171 = vrTechnicalSpec_XCGCacheModel.XCG01171;

		if ((XCG01171 != null) && (XCG01171.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01171 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01172 = getXCG01172();

		String XCG01172 = vrTechnicalSpec_XCGCacheModel.XCG01172;

		if ((XCG01172 != null) && (XCG01172.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01172 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01173 = getXCG01173();

		String XCG01173 = vrTechnicalSpec_XCGCacheModel.XCG01173;

		if ((XCG01173 != null) && (XCG01173.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01173 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01182 = getXCG01182();

		String XCG01182 = vrTechnicalSpec_XCGCacheModel.XCG01182;

		if ((XCG01182 != null) && (XCG01182.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01182 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01183 = getXCG01183();

		String XCG01183 = vrTechnicalSpec_XCGCacheModel.XCG01183;

		if ((XCG01183 != null) && (XCG01183.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01183 = null;
		}

		vrTechnicalSpec_XCGCacheModel.XCG01192 = getXCG01192();

		String XCG01192 = vrTechnicalSpec_XCGCacheModel.XCG01192;

		if ((XCG01192 != null) && (XCG01192.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.XCG01192 = null;
		}

		vrTechnicalSpec_XCGCacheModel.loai_dong_co = getLoai_dong_co();

		String loai_dong_co = vrTechnicalSpec_XCGCacheModel.loai_dong_co;

		if ((loai_dong_co != null) && (loai_dong_co.length() == 0)) {
			vrTechnicalSpec_XCGCacheModel.loai_dong_co = null;
		}

		Date modifyDate = getModifyDate();

		if (modifyDate != null) {
			vrTechnicalSpec_XCGCacheModel.modifyDate = modifyDate.getTime();
		}
		else {
			vrTechnicalSpec_XCGCacheModel.modifyDate = Long.MIN_VALUE;
		}

		Date syncDate = getSyncDate();

		if (syncDate != null) {
			vrTechnicalSpec_XCGCacheModel.syncDate = syncDate.getTime();
		}
		else {
			vrTechnicalSpec_XCGCacheModel.syncDate = Long.MIN_VALUE;
		}

		return vrTechnicalSpec_XCGCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(75);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", mtCore=");
		sb.append(getMtCore());
		sb.append(", convertAssembleId=");
		sb.append(getConvertAssembleId());
		sb.append(", dossierId=");
		sb.append(getDossierId());
		sb.append(", dossierNo=");
		sb.append(getDossierNo());
		sb.append(", referenceUid=");
		sb.append(getReferenceUid());
		sb.append(", dossierIdCTN=");
		sb.append(getDossierIdCTN());
		sb.append(", deliverableCode=");
		sb.append(getDeliverableCode());
		sb.append(", vehicleTypeCertificateId=");
		sb.append(getVehicleTypeCertificateId());
		sb.append(", XCG01070=");
		sb.append(getXCG01070());
		sb.append(", XCG01072=");
		sb.append(getXCG01072());
		sb.append(", XCG01083=");
		sb.append(getXCG01083());
		sb.append(", XCG01084=");
		sb.append(getXCG01084());
		sb.append(", XCG01085=");
		sb.append(getXCG01085());
		sb.append(", XCG01086=");
		sb.append(getXCG01086());
		sb.append(", XCG01087=");
		sb.append(getXCG01087());
		sb.append(", XCG01088=");
		sb.append(getXCG01088());
		sb.append(", XCG01090=");
		sb.append(getXCG01090());
		sb.append(", XCG01091=");
		sb.append(getXCG01091());
		sb.append(", XCG01092=");
		sb.append(getXCG01092());
		sb.append(", XCG01123=");
		sb.append(getXCG01123());
		sb.append(", XCG01124=");
		sb.append(getXCG01124());
		sb.append(", XCG01125=");
		sb.append(getXCG01125());
		sb.append(", XCG01156=");
		sb.append(getXCG01156());
		sb.append(", XCG01157=");
		sb.append(getXCG01157());
		sb.append(", XCG01163=");
		sb.append(getXCG01163());
		sb.append(", XCG01169=");
		sb.append(getXCG01169());
		sb.append(", XCG01170=");
		sb.append(getXCG01170());
		sb.append(", XCG01171=");
		sb.append(getXCG01171());
		sb.append(", XCG01172=");
		sb.append(getXCG01172());
		sb.append(", XCG01173=");
		sb.append(getXCG01173());
		sb.append(", XCG01182=");
		sb.append(getXCG01182());
		sb.append(", XCG01183=");
		sb.append(getXCG01183());
		sb.append(", XCG01192=");
		sb.append(getXCG01192());
		sb.append(", loai_dong_co=");
		sb.append(getLoai_dong_co());
		sb.append(", modifyDate=");
		sb.append(getModifyDate());
		sb.append(", syncDate=");
		sb.append(getSyncDate());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(115);

		sb.append("<model><model-name>");
		sb.append("com.fds.vr.business.model.VRTechnicalSpec_XCG");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mtCore</column-name><column-value><![CDATA[");
		sb.append(getMtCore());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>convertAssembleId</column-name><column-value><![CDATA[");
		sb.append(getConvertAssembleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierId</column-name><column-value><![CDATA[");
		sb.append(getDossierId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierNo</column-name><column-value><![CDATA[");
		sb.append(getDossierNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>referenceUid</column-name><column-value><![CDATA[");
		sb.append(getReferenceUid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierIdCTN</column-name><column-value><![CDATA[");
		sb.append(getDossierIdCTN());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>deliverableCode</column-name><column-value><![CDATA[");
		sb.append(getDeliverableCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vehicleTypeCertificateId</column-name><column-value><![CDATA[");
		sb.append(getVehicleTypeCertificateId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01070</column-name><column-value><![CDATA[");
		sb.append(getXCG01070());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01072</column-name><column-value><![CDATA[");
		sb.append(getXCG01072());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01083</column-name><column-value><![CDATA[");
		sb.append(getXCG01083());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01084</column-name><column-value><![CDATA[");
		sb.append(getXCG01084());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01085</column-name><column-value><![CDATA[");
		sb.append(getXCG01085());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01086</column-name><column-value><![CDATA[");
		sb.append(getXCG01086());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01087</column-name><column-value><![CDATA[");
		sb.append(getXCG01087());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01088</column-name><column-value><![CDATA[");
		sb.append(getXCG01088());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01090</column-name><column-value><![CDATA[");
		sb.append(getXCG01090());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01091</column-name><column-value><![CDATA[");
		sb.append(getXCG01091());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01092</column-name><column-value><![CDATA[");
		sb.append(getXCG01092());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01123</column-name><column-value><![CDATA[");
		sb.append(getXCG01123());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01124</column-name><column-value><![CDATA[");
		sb.append(getXCG01124());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01125</column-name><column-value><![CDATA[");
		sb.append(getXCG01125());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01156</column-name><column-value><![CDATA[");
		sb.append(getXCG01156());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01157</column-name><column-value><![CDATA[");
		sb.append(getXCG01157());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01163</column-name><column-value><![CDATA[");
		sb.append(getXCG01163());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01169</column-name><column-value><![CDATA[");
		sb.append(getXCG01169());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01170</column-name><column-value><![CDATA[");
		sb.append(getXCG01170());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01171</column-name><column-value><![CDATA[");
		sb.append(getXCG01171());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01172</column-name><column-value><![CDATA[");
		sb.append(getXCG01172());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01173</column-name><column-value><![CDATA[");
		sb.append(getXCG01173());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01182</column-name><column-value><![CDATA[");
		sb.append(getXCG01182());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01183</column-name><column-value><![CDATA[");
		sb.append(getXCG01183());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>XCG01192</column-name><column-value><![CDATA[");
		sb.append(getXCG01192());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>loai_dong_co</column-name><column-value><![CDATA[");
		sb.append(getLoai_dong_co());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifyDate</column-name><column-value><![CDATA[");
		sb.append(getModifyDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>syncDate</column-name><column-value><![CDATA[");
		sb.append(getSyncDate());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = VRTechnicalSpec_XCG.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			VRTechnicalSpec_XCG.class
		};
	private long _id;
	private long _mtCore;
	private long _originalMtCore;
	private boolean _setOriginalMtCore;
	private long _convertAssembleId;
	private long _originalConvertAssembleId;
	private boolean _setOriginalConvertAssembleId;
	private long _dossierId;
	private long _originalDossierId;
	private boolean _setOriginalDossierId;
	private String _dossierNo;
	private String _originalDossierNo;
	private String _referenceUid;
	private String _originalReferenceUid;
	private String _dossierIdCTN;
	private String _originalDossierIdCTN;
	private String _deliverableCode;
	private String _originalDeliverableCode;
	private long _vehicleTypeCertificateId;
	private long _originalVehicleTypeCertificateId;
	private boolean _setOriginalVehicleTypeCertificateId;
	private String _XCG01070;
	private String _XCG01072;
	private String _XCG01083;
	private String _XCG01084;
	private String _XCG01085;
	private String _XCG01086;
	private String _XCG01087;
	private String _XCG01088;
	private String _XCG01090;
	private String _XCG01091;
	private String _XCG01092;
	private String _XCG01123;
	private String _XCG01124;
	private String _XCG01125;
	private String _XCG01156;
	private String _XCG01157;
	private String _XCG01163;
	private String _XCG01169;
	private String _XCG01170;
	private String _XCG01171;
	private String _XCG01172;
	private String _XCG01173;
	private String _XCG01182;
	private String _XCG01183;
	private String _XCG01192;
	private String _loai_dong_co;
	private Date _modifyDate;
	private Date _syncDate;
	private long _columnBitmask;
	private VRTechnicalSpec_XCG _escapedModel;
}