/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.backend.migrate.vr.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DoanhNghiep service. Represents a row in the &quot;ttnd_doanhnghiep&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.backend.migrate.vr.model.impl.DoanhNghiepModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.backend.migrate.vr.model.impl.DoanhNghiepImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DoanhNghiep
 * @see com.backend.migrate.vr.model.impl.DoanhNghiepImpl
 * @see com.backend.migrate.vr.model.impl.DoanhNghiepModelImpl
 * @generated
 */
@ProviderType
public interface DoanhNghiepModel extends BaseModel<DoanhNghiep> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a doanh nghiep model instance should use the {@link DoanhNghiep} interface instead.
	 */

	/**
	 * Returns the primary key of this doanh nghiep.
	 *
	 * @return the primary key of this doanh nghiep
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this doanh nghiep.
	 *
	 * @param primaryKey the primary key of this doanh nghiep
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this doanh nghiep.
	 *
	 * @return the ID of this doanh nghiep
	 */
	public long getId();

	/**
	 * Sets the ID of this doanh nghiep.
	 *
	 * @param id the ID of this doanh nghiep
	 */
	public void setId(long id);

	/**
	 * Returns the ten of this doanh nghiep.
	 *
	 * @return the ten of this doanh nghiep
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this doanh nghiep.
	 *
	 * @param ten the ten of this doanh nghiep
	 */
	public void setTen(String ten);

	/**
	 * Returns the ten_viettat of this doanh nghiep.
	 *
	 * @return the ten_viettat of this doanh nghiep
	 */
	@AutoEscape
	public String getTen_viettat();

	/**
	 * Sets the ten_viettat of this doanh nghiep.
	 *
	 * @param ten_viettat the ten_viettat of this doanh nghiep
	 */
	public void setTen_viettat(String ten_viettat);

	/**
	 * Returns the ten_tienganh of this doanh nghiep.
	 *
	 * @return the ten_tienganh of this doanh nghiep
	 */
	@AutoEscape
	public String getTen_tienganh();

	/**
	 * Sets the ten_tienganh of this doanh nghiep.
	 *
	 * @param ten_tienganh the ten_tienganh of this doanh nghiep
	 */
	public void setTen_tienganh(String ten_tienganh);

	/**
	 * Returns the sogcn_dkkd of this doanh nghiep.
	 *
	 * @return the sogcn_dkkd of this doanh nghiep
	 */
	@AutoEscape
	public String getSogcn_dkkd();

	/**
	 * Sets the sogcn_dkkd of this doanh nghiep.
	 *
	 * @param sogcn_dkkd the sogcn_dkkd of this doanh nghiep
	 */
	public void setSogcn_dkkd(String sogcn_dkkd);

	/**
	 * Returns the ngaycap_dkkd of this doanh nghiep.
	 *
	 * @return the ngaycap_dkkd of this doanh nghiep
	 */
	public Date getNgaycap_dkkd();

	/**
	 * Sets the ngaycap_dkkd of this doanh nghiep.
	 *
	 * @param ngaycap_dkkd the ngaycap_dkkd of this doanh nghiep
	 */
	public void setNgaycap_dkkd(Date ngaycap_dkkd);

	/**
	 * Returns the ngayhethan_dkkd of this doanh nghiep.
	 *
	 * @return the ngayhethan_dkkd of this doanh nghiep
	 */
	public Date getNgayhethan_dkkd();

	/**
	 * Sets the ngayhethan_dkkd of this doanh nghiep.
	 *
	 * @param ngayhethan_dkkd the ngayhethan_dkkd of this doanh nghiep
	 */
	public void setNgayhethan_dkkd(Date ngayhethan_dkkd);

	/**
	 * Returns the ten_donvicapphep of this doanh nghiep.
	 *
	 * @return the ten_donvicapphep of this doanh nghiep
	 */
	@AutoEscape
	public String getTen_donvicapphep();

	/**
	 * Sets the ten_donvicapphep of this doanh nghiep.
	 *
	 * @param ten_donvicapphep the ten_donvicapphep of this doanh nghiep
	 */
	public void setTen_donvicapphep(String ten_donvicapphep);

	/**
	 * Returns the masothue of this doanh nghiep.
	 *
	 * @return the masothue of this doanh nghiep
	 */
	@AutoEscape
	public String getMasothue();

	/**
	 * Sets the masothue of this doanh nghiep.
	 *
	 * @param masothue the masothue of this doanh nghiep
	 */
	public void setMasothue(String masothue);

	/**
	 * Returns the ten_nguoidaidien of this doanh nghiep.
	 *
	 * @return the ten_nguoidaidien of this doanh nghiep
	 */
	@AutoEscape
	public String getTen_nguoidaidien();

	/**
	 * Sets the ten_nguoidaidien of this doanh nghiep.
	 *
	 * @param ten_nguoidaidien the ten_nguoidaidien of this doanh nghiep
	 */
	public void setTen_nguoidaidien(String ten_nguoidaidien);

	/**
	 * Returns the chucvu_nguoidaidien of this doanh nghiep.
	 *
	 * @return the chucvu_nguoidaidien of this doanh nghiep
	 */
	@AutoEscape
	public String getChucvu_nguoidaidien();

	/**
	 * Sets the chucvu_nguoidaidien of this doanh nghiep.
	 *
	 * @param chucvu_nguoidaidien the chucvu_nguoidaidien of this doanh nghiep
	 */
	public void setChucvu_nguoidaidien(String chucvu_nguoidaidien);

	/**
	 * Returns the gioitinh_nguoidaidien of this doanh nghiep.
	 *
	 * @return the gioitinh_nguoidaidien of this doanh nghiep
	 */
	public long getGioitinh_nguoidaidien();

	/**
	 * Sets the gioitinh_nguoidaidien of this doanh nghiep.
	 *
	 * @param gioitinh_nguoidaidien the gioitinh_nguoidaidien of this doanh nghiep
	 */
	public void setGioitinh_nguoidaidien(long gioitinh_nguoidaidien);

	/**
	 * Returns the diachi_nguoidaidien of this doanh nghiep.
	 *
	 * @return the diachi_nguoidaidien of this doanh nghiep
	 */
	@AutoEscape
	public String getDiachi_nguoidaidien();

	/**
	 * Sets the diachi_nguoidaidien of this doanh nghiep.
	 *
	 * @param diachi_nguoidaidien the diachi_nguoidaidien of this doanh nghiep
	 */
	public void setDiachi_nguoidaidien(String diachi_nguoidaidien);

	/**
	 * Returns the diachi_ndd_tinh_id of this doanh nghiep.
	 *
	 * @return the diachi_ndd_tinh_id of this doanh nghiep
	 */
	public long getDiachi_ndd_tinh_id();

	/**
	 * Sets the diachi_ndd_tinh_id of this doanh nghiep.
	 *
	 * @param diachi_ndd_tinh_id the diachi_ndd_tinh_id of this doanh nghiep
	 */
	public void setDiachi_ndd_tinh_id(long diachi_ndd_tinh_id);

	/**
	 * Returns the diachi_ndd_huyen_id of this doanh nghiep.
	 *
	 * @return the diachi_ndd_huyen_id of this doanh nghiep
	 */
	public long getDiachi_ndd_huyen_id();

	/**
	 * Sets the diachi_ndd_huyen_id of this doanh nghiep.
	 *
	 * @param diachi_ndd_huyen_id the diachi_ndd_huyen_id of this doanh nghiep
	 */
	public void setDiachi_ndd_huyen_id(long diachi_ndd_huyen_id);

	/**
	 * Returns the diachi_ndd_xa_id of this doanh nghiep.
	 *
	 * @return the diachi_ndd_xa_id of this doanh nghiep
	 */
	public long getDiachi_ndd_xa_id();

	/**
	 * Sets the diachi_ndd_xa_id of this doanh nghiep.
	 *
	 * @param diachi_ndd_xa_id the diachi_ndd_xa_id of this doanh nghiep
	 */
	public void setDiachi_ndd_xa_id(long diachi_ndd_xa_id);

	/**
	 * Returns the hktt_nguoidaidien of this doanh nghiep.
	 *
	 * @return the hktt_nguoidaidien of this doanh nghiep
	 */
	@AutoEscape
	public String getHktt_nguoidaidien();

	/**
	 * Sets the hktt_nguoidaidien of this doanh nghiep.
	 *
	 * @param hktt_nguoidaidien the hktt_nguoidaidien of this doanh nghiep
	 */
	public void setHktt_nguoidaidien(String hktt_nguoidaidien);

	/**
	 * Returns the dantoc_nguoidaidien_id of this doanh nghiep.
	 *
	 * @return the dantoc_nguoidaidien_id of this doanh nghiep
	 */
	public long getDantoc_nguoidaidien_id();

	/**
	 * Sets the dantoc_nguoidaidien_id of this doanh nghiep.
	 *
	 * @param dantoc_nguoidaidien_id the dantoc_nguoidaidien_id of this doanh nghiep
	 */
	public void setDantoc_nguoidaidien_id(long dantoc_nguoidaidien_id);

	/**
	 * Returns the tongiao_nguoidaidien_id of this doanh nghiep.
	 *
	 * @return the tongiao_nguoidaidien_id of this doanh nghiep
	 */
	public long getTongiao_nguoidaidien_id();

	/**
	 * Sets the tongiao_nguoidaidien_id of this doanh nghiep.
	 *
	 * @param tongiao_nguoidaidien_id the tongiao_nguoidaidien_id of this doanh nghiep
	 */
	public void setTongiao_nguoidaidien_id(long tongiao_nguoidaidien_id);

	/**
	 * Returns the quoctich_nguoidaidien_id of this doanh nghiep.
	 *
	 * @return the quoctich_nguoidaidien_id of this doanh nghiep
	 */
	public long getQuoctich_nguoidaidien_id();

	/**
	 * Sets the quoctich_nguoidaidien_id of this doanh nghiep.
	 *
	 * @param quoctich_nguoidaidien_id the quoctich_nguoidaidien_id of this doanh nghiep
	 */
	public void setQuoctich_nguoidaidien_id(long quoctich_nguoidaidien_id);

	/**
	 * Returns the ngaysinh_nguoidaidien of this doanh nghiep.
	 *
	 * @return the ngaysinh_nguoidaidien of this doanh nghiep
	 */
	public Date getNgaysinh_nguoidaidien();

	/**
	 * Sets the ngaysinh_nguoidaidien of this doanh nghiep.
	 *
	 * @param ngaysinh_nguoidaidien the ngaysinh_nguoidaidien of this doanh nghiep
	 */
	public void setNgaysinh_nguoidaidien(Date ngaysinh_nguoidaidien);

	/**
	 * Returns the dienthoai_nguoidaidien of this doanh nghiep.
	 *
	 * @return the dienthoai_nguoidaidien of this doanh nghiep
	 */
	@AutoEscape
	public String getDienthoai_nguoidaidien();

	/**
	 * Sets the dienthoai_nguoidaidien of this doanh nghiep.
	 *
	 * @param dienthoai_nguoidaidien the dienthoai_nguoidaidien of this doanh nghiep
	 */
	public void setDienthoai_nguoidaidien(String dienthoai_nguoidaidien);

	/**
	 * Returns the giayto_canhan_nguoidaidien of this doanh nghiep.
	 *
	 * @return the giayto_canhan_nguoidaidien of this doanh nghiep
	 */
	@AutoEscape
	public String getGiayto_canhan_nguoidaidien();

	/**
	 * Sets the giayto_canhan_nguoidaidien of this doanh nghiep.
	 *
	 * @param giayto_canhan_nguoidaidien the giayto_canhan_nguoidaidien of this doanh nghiep
	 */
	public void setGiayto_canhan_nguoidaidien(String giayto_canhan_nguoidaidien);

	/**
	 * Returns the giayto_ngaycap_nguoidaidien of this doanh nghiep.
	 *
	 * @return the giayto_ngaycap_nguoidaidien of this doanh nghiep
	 */
	public Date getGiayto_ngaycap_nguoidaidien();

	/**
	 * Sets the giayto_ngaycap_nguoidaidien of this doanh nghiep.
	 *
	 * @param giayto_ngaycap_nguoidaidien the giayto_ngaycap_nguoidaidien of this doanh nghiep
	 */
	public void setGiayto_ngaycap_nguoidaidien(Date giayto_ngaycap_nguoidaidien);

	/**
	 * Returns the giayto_noicap_nguoidaidien of this doanh nghiep.
	 *
	 * @return the giayto_noicap_nguoidaidien of this doanh nghiep
	 */
	@AutoEscape
	public String getGiayto_noicap_nguoidaidien();

	/**
	 * Sets the giayto_noicap_nguoidaidien of this doanh nghiep.
	 *
	 * @param giayto_noicap_nguoidaidien the giayto_noicap_nguoidaidien of this doanh nghiep
	 */
	public void setGiayto_noicap_nguoidaidien(String giayto_noicap_nguoidaidien);

	/**
	 * Returns the loai_doanhnghiep_id of this doanh nghiep.
	 *
	 * @return the loai_doanhnghiep_id of this doanh nghiep
	 */
	public long getLoai_doanhnghiep_id();

	/**
	 * Sets the loai_doanhnghiep_id of this doanh nghiep.
	 *
	 * @param loai_doanhnghiep_id the loai_doanhnghiep_id of this doanh nghiep
	 */
	public void setLoai_doanhnghiep_id(long loai_doanhnghiep_id);

	/**
	 * Returns the diachi_trusochinh of this doanh nghiep.
	 *
	 * @return the diachi_trusochinh of this doanh nghiep
	 */
	@AutoEscape
	public String getDiachi_trusochinh();

	/**
	 * Sets the diachi_trusochinh of this doanh nghiep.
	 *
	 * @param diachi_trusochinh the diachi_trusochinh of this doanh nghiep
	 */
	public void setDiachi_trusochinh(String diachi_trusochinh);

	/**
	 * Returns the diachi_truso_tinh_id of this doanh nghiep.
	 *
	 * @return the diachi_truso_tinh_id of this doanh nghiep
	 */
	public long getDiachi_truso_tinh_id();

	/**
	 * Sets the diachi_truso_tinh_id of this doanh nghiep.
	 *
	 * @param diachi_truso_tinh_id the diachi_truso_tinh_id of this doanh nghiep
	 */
	public void setDiachi_truso_tinh_id(long diachi_truso_tinh_id);

	/**
	 * Returns the diachi_truso_huyen_id of this doanh nghiep.
	 *
	 * @return the diachi_truso_huyen_id of this doanh nghiep
	 */
	public long getDiachi_truso_huyen_id();

	/**
	 * Sets the diachi_truso_huyen_id of this doanh nghiep.
	 *
	 * @param diachi_truso_huyen_id the diachi_truso_huyen_id of this doanh nghiep
	 */
	public void setDiachi_truso_huyen_id(long diachi_truso_huyen_id);

	/**
	 * Returns the diachi_truso_xa_id of this doanh nghiep.
	 *
	 * @return the diachi_truso_xa_id of this doanh nghiep
	 */
	public long getDiachi_truso_xa_id();

	/**
	 * Sets the diachi_truso_xa_id of this doanh nghiep.
	 *
	 * @param diachi_truso_xa_id the diachi_truso_xa_id of this doanh nghiep
	 */
	public void setDiachi_truso_xa_id(long diachi_truso_xa_id);

	/**
	 * Returns the dienthoai of this doanh nghiep.
	 *
	 * @return the dienthoai of this doanh nghiep
	 */
	@AutoEscape
	public String getDienthoai();

	/**
	 * Sets the dienthoai of this doanh nghiep.
	 *
	 * @param dienthoai the dienthoai of this doanh nghiep
	 */
	public void setDienthoai(String dienthoai);

	/**
	 * Returns the fax of this doanh nghiep.
	 *
	 * @return the fax of this doanh nghiep
	 */
	@AutoEscape
	public String getFax();

	/**
	 * Sets the fax of this doanh nghiep.
	 *
	 * @param fax the fax of this doanh nghiep
	 */
	public void setFax(String fax);

	/**
	 * Returns the email of this doanh nghiep.
	 *
	 * @return the email of this doanh nghiep
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this doanh nghiep.
	 *
	 * @param email the email of this doanh nghiep
	 */
	public void setEmail(String email);

	/**
	 * Returns the website of this doanh nghiep.
	 *
	 * @return the website of this doanh nghiep
	 */
	@AutoEscape
	public String getWebsite();

	/**
	 * Sets the website of this doanh nghiep.
	 *
	 * @param website the website of this doanh nghiep
	 */
	public void setWebsite(String website);

	/**
	 * Returns the von_dieule of this doanh nghiep.
	 *
	 * @return the von_dieule of this doanh nghiep
	 */
	@AutoEscape
	public String getVon_dieule();

	/**
	 * Sets the von_dieule of this doanh nghiep.
	 *
	 * @param von_dieule the von_dieule of this doanh nghiep
	 */
	public void setVon_dieule(String von_dieule);

	/**
	 * Returns the von_phapdinh of this doanh nghiep.
	 *
	 * @return the von_phapdinh of this doanh nghiep
	 */
	@AutoEscape
	public String getVon_phapdinh();

	/**
	 * Sets the von_phapdinh of this doanh nghiep.
	 *
	 * @param von_phapdinh the von_phapdinh of this doanh nghiep
	 */
	public void setVon_phapdinh(String von_phapdinh);

	/**
	 * Returns the user_id of this doanh nghiep.
	 *
	 * @return the user_id of this doanh nghiep
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this doanh nghiep.
	 *
	 * @param user_id the user_id of this doanh nghiep
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the doituongsudung_id of this doanh nghiep.
	 *
	 * @return the doituongsudung_id of this doanh nghiep
	 */
	public long getDoituongsudung_id();

	/**
	 * Sets the doituongsudung_id of this doanh nghiep.
	 *
	 * @param doituongsudung_id the doituongsudung_id of this doanh nghiep
	 */
	public void setDoituongsudung_id(long doituongsudung_id);

	/**
	 * Returns the trangthai of this doanh nghiep.
	 *
	 * @return the trangthai of this doanh nghiep
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this doanh nghiep.
	 *
	 * @param trangthai the trangthai of this doanh nghiep
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the ngaytao of this doanh nghiep.
	 *
	 * @return the ngaytao of this doanh nghiep
	 */
	public Date getNgaytao();

	/**
	 * Sets the ngaytao of this doanh nghiep.
	 *
	 * @param ngaytao the ngaytao of this doanh nghiep
	 */
	public void setNgaytao(Date ngaytao);

	/**
	 * Returns the ngaycap_taikhoan of this doanh nghiep.
	 *
	 * @return the ngaycap_taikhoan of this doanh nghiep
	 */
	public Date getNgaycap_taikhoan();

	/**
	 * Sets the ngaycap_taikhoan of this doanh nghiep.
	 *
	 * @param ngaycap_taikhoan the ngaycap_taikhoan of this doanh nghiep
	 */
	public void setNgaycap_taikhoan(Date ngaycap_taikhoan);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DoanhNghiep doanhNghiep);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DoanhNghiep> toCacheModel();

	@Override
	public DoanhNghiep toEscapedModel();

	@Override
	public DoanhNghiep toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}