/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.backend.migrate.vr.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the PhuHieuBienHieu service. Represents a row in the &quot;phbh_phuhieubienhieu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.backend.migrate.vr.model.impl.PhuHieuBienHieuModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.backend.migrate.vr.model.impl.PhuHieuBienHieuImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhuHieuBienHieu
 * @see com.backend.migrate.vr.model.impl.PhuHieuBienHieuImpl
 * @see com.backend.migrate.vr.model.impl.PhuHieuBienHieuModelImpl
 * @generated
 */
@ProviderType
public interface PhuHieuBienHieuModel extends BaseModel<PhuHieuBienHieu> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phu hieu bien hieu model instance should use the {@link PhuHieuBienHieu} interface instead.
	 */

	/**
	 * Returns the primary key of this phu hieu bien hieu.
	 *
	 * @return the primary key of this phu hieu bien hieu
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this phu hieu bien hieu.
	 *
	 * @param primaryKey the primary key of this phu hieu bien hieu
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this phu hieu bien hieu.
	 *
	 * @return the ID of this phu hieu bien hieu
	 */
	public long getId();

	/**
	 * Sets the ID of this phu hieu bien hieu.
	 *
	 * @param id the ID of this phu hieu bien hieu
	 */
	public void setId(long id);

	/**
	 * Returns the sophuhieu of this phu hieu bien hieu.
	 *
	 * @return the sophuhieu of this phu hieu bien hieu
	 */
	@AutoEscape
	public String getSophuhieu();

	/**
	 * Sets the sophuhieu of this phu hieu bien hieu.
	 *
	 * @param sophuhieu the sophuhieu of this phu hieu bien hieu
	 */
	public void setSophuhieu(String sophuhieu);

	/**
	 * Returns the phuongtien_id of this phu hieu bien hieu.
	 *
	 * @return the phuongtien_id of this phu hieu bien hieu
	 */
	public long getPhuongtien_id();

	/**
	 * Sets the phuongtien_id of this phu hieu bien hieu.
	 *
	 * @param phuongtien_id the phuongtien_id of this phu hieu bien hieu
	 */
	public void setPhuongtien_id(long phuongtien_id);

	/**
	 * Returns the loaihinh_id of this phu hieu bien hieu.
	 *
	 * @return the loaihinh_id of this phu hieu bien hieu
	 */
	public long getLoaihinh_id();

	/**
	 * Sets the loaihinh_id of this phu hieu bien hieu.
	 *
	 * @param loaihinh_id the loaihinh_id of this phu hieu bien hieu
	 */
	public void setLoaihinh_id(long loaihinh_id);

	/**
	 * Returns the tuyenkhaithac_id of this phu hieu bien hieu.
	 *
	 * @return the tuyenkhaithac_id of this phu hieu bien hieu
	 */
	public long getTuyenkhaithac_id();

	/**
	 * Sets the tuyenkhaithac_id of this phu hieu bien hieu.
	 *
	 * @param tuyenkhaithac_id the tuyenkhaithac_id of this phu hieu bien hieu
	 */
	public void setTuyenkhaithac_id(long tuyenkhaithac_id);

	/**
	 * Returns the phamvi_id of this phu hieu bien hieu.
	 *
	 * @return the phamvi_id of this phu hieu bien hieu
	 */
	public long getPhamvi_id();

	/**
	 * Sets the phamvi_id of this phu hieu bien hieu.
	 *
	 * @param phamvi_id the phamvi_id of this phu hieu bien hieu
	 */
	public void setPhamvi_id(long phamvi_id);

	/**
	 * Returns the loai of this phu hieu bien hieu.
	 *
	 * @return the loai of this phu hieu bien hieu
	 */
	public int getLoai();

	/**
	 * Sets the loai of this phu hieu bien hieu.
	 *
	 * @param loai the loai of this phu hieu bien hieu
	 */
	public void setLoai(int loai);

	/**
	 * Returns the ngaycap of this phu hieu bien hieu.
	 *
	 * @return the ngaycap of this phu hieu bien hieu
	 */
	public Date getNgaycap();

	/**
	 * Sets the ngaycap of this phu hieu bien hieu.
	 *
	 * @param ngaycap the ngaycap of this phu hieu bien hieu
	 */
	public void setNgaycap(Date ngaycap);

	/**
	 * Returns the ngayhethan of this phu hieu bien hieu.
	 *
	 * @return the ngayhethan of this phu hieu bien hieu
	 */
	public Date getNgayhethan();

	/**
	 * Sets the ngayhethan of this phu hieu bien hieu.
	 *
	 * @param ngayhethan the ngayhethan of this phu hieu bien hieu
	 */
	public void setNgayhethan(Date ngayhethan);

	/**
	 * Returns the ngaythuhoi of this phu hieu bien hieu.
	 *
	 * @return the ngaythuhoi of this phu hieu bien hieu
	 */
	public Date getNgaythuhoi();

	/**
	 * Sets the ngaythuhoi of this phu hieu bien hieu.
	 *
	 * @param ngaythuhoi the ngaythuhoi of this phu hieu bien hieu
	 */
	public void setNgaythuhoi(Date ngaythuhoi);

	/**
	 * Returns the lydo_thuhoi of this phu hieu bien hieu.
	 *
	 * @return the lydo_thuhoi of this phu hieu bien hieu
	 */
	@AutoEscape
	public String getLydo_thuhoi();

	/**
	 * Sets the lydo_thuhoi of this phu hieu bien hieu.
	 *
	 * @param lydo_thuhoi the lydo_thuhoi of this phu hieu bien hieu
	 */
	public void setLydo_thuhoi(String lydo_thuhoi);

	/**
	 * Returns the nguoitao of this phu hieu bien hieu.
	 *
	 * @return the nguoitao of this phu hieu bien hieu
	 */
	@AutoEscape
	public String getNguoitao();

	/**
	 * Sets the nguoitao of this phu hieu bien hieu.
	 *
	 * @param nguoitao the nguoitao of this phu hieu bien hieu
	 */
	public void setNguoitao(String nguoitao);

	/**
	 * Returns the ngaytao of this phu hieu bien hieu.
	 *
	 * @return the ngaytao of this phu hieu bien hieu
	 */
	public Date getNgaytao();

	/**
	 * Sets the ngaytao of this phu hieu bien hieu.
	 *
	 * @param ngaytao the ngaytao of this phu hieu bien hieu
	 */
	public void setNgaytao(Date ngaytao);

	/**
	 * Returns the nguoiky of this phu hieu bien hieu.
	 *
	 * @return the nguoiky of this phu hieu bien hieu
	 */
	@AutoEscape
	public String getNguoiky();

	/**
	 * Sets the nguoiky of this phu hieu bien hieu.
	 *
	 * @param nguoiky the nguoiky of this phu hieu bien hieu
	 */
	public void setNguoiky(String nguoiky);

	/**
	 * Returns the nguoiky_id of this phu hieu bien hieu.
	 *
	 * @return the nguoiky_id of this phu hieu bien hieu
	 */
	public long getNguoiky_id();

	/**
	 * Sets the nguoiky_id of this phu hieu bien hieu.
	 *
	 * @param nguoiky_id the nguoiky_id of this phu hieu bien hieu
	 */
	public void setNguoiky_id(long nguoiky_id);

	/**
	 * Returns the ngayky of this phu hieu bien hieu.
	 *
	 * @return the ngayky of this phu hieu bien hieu
	 */
	public Date getNgayky();

	/**
	 * Sets the ngayky of this phu hieu bien hieu.
	 *
	 * @param ngayky the ngayky of this phu hieu bien hieu
	 */
	public void setNgayky(Date ngayky);

	/**
	 * Returns the ghichu of this phu hieu bien hieu.
	 *
	 * @return the ghichu of this phu hieu bien hieu
	 */
	@AutoEscape
	public String getGhichu();

	/**
	 * Sets the ghichu of this phu hieu bien hieu.
	 *
	 * @param ghichu the ghichu of this phu hieu bien hieu
	 */
	public void setGhichu(String ghichu);

	/**
	 * Returns the trangthai of this phu hieu bien hieu.
	 *
	 * @return the trangthai of this phu hieu bien hieu
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this phu hieu bien hieu.
	 *
	 * @param trangthai the trangthai of this phu hieu bien hieu
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the coquanquanly_id of this phu hieu bien hieu.
	 *
	 * @return the coquanquanly_id of this phu hieu bien hieu
	 */
	public long getCoquanquanly_id();

	/**
	 * Sets the coquanquanly_id of this phu hieu bien hieu.
	 *
	 * @param coquanquanly_id the coquanquanly_id of this phu hieu bien hieu
	 */
	public void setCoquanquanly_id(long coquanquanly_id);

	/**
	 * Returns the labienhieu of this phu hieu bien hieu.
	 *
	 * @return the labienhieu of this phu hieu bien hieu
	 */
	public int getLabienhieu();

	/**
	 * Sets the labienhieu of this phu hieu bien hieu.
	 *
	 * @param labienhieu the labienhieu of this phu hieu bien hieu
	 */
	public void setLabienhieu(int labienhieu);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(PhuHieuBienHieu phuHieuBienHieu);

	@Override
	public int hashCode();

	@Override
	public CacheModel<PhuHieuBienHieu> toCacheModel();

	@Override
	public PhuHieuBienHieu toEscapedModel();

	@Override
	public PhuHieuBienHieu toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}