/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.backend.migrate.vr.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SRCGiayPhepLienVan service. Represents a row in the &quot;nsw_giaypheplienvan&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.backend.migrate.vr.model.impl.SRCGiayPhepLienVanModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.backend.migrate.vr.model.impl.SRCGiayPhepLienVanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SRCGiayPhepLienVan
 * @see com.backend.migrate.vr.model.impl.SRCGiayPhepLienVanImpl
 * @see com.backend.migrate.vr.model.impl.SRCGiayPhepLienVanModelImpl
 * @generated
 */
@ProviderType
public interface SRCGiayPhepLienVanModel extends BaseModel<SRCGiayPhepLienVan> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a src giay phep lien van model instance should use the {@link SRCGiayPhepLienVan} interface instead.
	 */

	/**
	 * Returns the primary key of this src giay phep lien van.
	 *
	 * @return the primary key of this src giay phep lien van
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this src giay phep lien van.
	 *
	 * @param primaryKey the primary key of this src giay phep lien van
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this src giay phep lien van.
	 *
	 * @return the ID of this src giay phep lien van
	 */
	public long getId();

	/**
	 * Sets the ID of this src giay phep lien van.
	 *
	 * @param id the ID of this src giay phep lien van
	 */
	public void setId(long id);

	/**
	 * Returns the so_phuhieu_lienvan of this src giay phep lien van.
	 *
	 * @return the so_phuhieu_lienvan of this src giay phep lien van
	 */
	@AutoEscape
	public String getSo_phuhieu_lienvan();

	/**
	 * Sets the so_phuhieu_lienvan of this src giay phep lien van.
	 *
	 * @param so_phuhieu_lienvan the so_phuhieu_lienvan of this src giay phep lien van
	 */
	public void setSo_phuhieu_lienvan(String so_phuhieu_lienvan);

	/**
	 * Returns the lancapphep of this src giay phep lien van.
	 *
	 * @return the lancapphep of this src giay phep lien van
	 */
	public int getLancapphep();

	/**
	 * Sets the lancapphep of this src giay phep lien van.
	 *
	 * @param lancapphep the lancapphep of this src giay phep lien van
	 */
	public void setLancapphep(int lancapphep);

	/**
	 * Returns the phuongtien_id of this src giay phep lien van.
	 *
	 * @return the phuongtien_id of this src giay phep lien van
	 */
	public long getPhuongtien_id();

	/**
	 * Sets the phuongtien_id of this src giay phep lien van.
	 *
	 * @param phuongtien_id the phuongtien_id of this src giay phep lien van
	 */
	public void setPhuongtien_id(long phuongtien_id);

	/**
	 * Returns the bienkiemsoat of this src giay phep lien van.
	 *
	 * @return the bienkiemsoat of this src giay phep lien van
	 */
	@AutoEscape
	public String getBienkiemsoat();

	/**
	 * Sets the bienkiemsoat of this src giay phep lien van.
	 *
	 * @param bienkiemsoat the bienkiemsoat of this src giay phep lien van
	 */
	public void setBienkiemsoat(String bienkiemsoat);

	/**
	 * Returns the succhua of this src giay phep lien van.
	 *
	 * @return the succhua of this src giay phep lien van
	 */
	public int getSucchua();

	/**
	 * Sets the succhua of this src giay phep lien van.
	 *
	 * @param succhua the succhua of this src giay phep lien van
	 */
	public void setSucchua(int succhua);

	/**
	 * Returns the namsanxuat of this src giay phep lien van.
	 *
	 * @return the namsanxuat of this src giay phep lien van
	 */
	public int getNamsanxuat();

	/**
	 * Sets the namsanxuat of this src giay phep lien van.
	 *
	 * @param namsanxuat the namsanxuat of this src giay phep lien van
	 */
	public void setNamsanxuat(int namsanxuat);

	/**
	 * Returns the nhanhieu_id of this src giay phep lien van.
	 *
	 * @return the nhanhieu_id of this src giay phep lien van
	 */
	public long getNhanhieu_id();

	/**
	 * Sets the nhanhieu_id of this src giay phep lien van.
	 *
	 * @param nhanhieu_id the nhanhieu_id of this src giay phep lien van
	 */
	public void setNhanhieu_id(long nhanhieu_id);

	/**
	 * Returns the sokhung of this src giay phep lien van.
	 *
	 * @return the sokhung of this src giay phep lien van
	 */
	@AutoEscape
	public String getSokhung();

	/**
	 * Sets the sokhung of this src giay phep lien van.
	 *
	 * @param sokhung the sokhung of this src giay phep lien van
	 */
	public void setSokhung(String sokhung);

	/**
	 * Returns the somay of this src giay phep lien van.
	 *
	 * @return the somay of this src giay phep lien van
	 */
	@AutoEscape
	public String getSomay();

	/**
	 * Sets the somay of this src giay phep lien van.
	 *
	 * @param somay the somay of this src giay phep lien van
	 */
	public void setSomay(String somay);

	/**
	 * Returns the mauson_id of this src giay phep lien van.
	 *
	 * @return the mauson_id of this src giay phep lien van
	 */
	public long getMauson_id();

	/**
	 * Sets the mauson_id of this src giay phep lien van.
	 *
	 * @param mauson_id the mauson_id of this src giay phep lien van
	 */
	public void setMauson_id(long mauson_id);

	/**
	 * Returns the loaihinh_id of this src giay phep lien van.
	 *
	 * @return the loaihinh_id of this src giay phep lien van
	 */
	public long getLoaihinh_id();

	/**
	 * Sets the loaihinh_id of this src giay phep lien van.
	 *
	 * @param loaihinh_id the loaihinh_id of this src giay phep lien van
	 */
	public void setLoaihinh_id(long loaihinh_id);

	/**
	 * Returns the cuakhau_id of this src giay phep lien van.
	 *
	 * @return the cuakhau_id of this src giay phep lien van
	 */
	public long getCuakhau_id();

	/**
	 * Sets the cuakhau_id of this src giay phep lien van.
	 *
	 * @param cuakhau_id the cuakhau_id of this src giay phep lien van
	 */
	public void setCuakhau_id(long cuakhau_id);

	/**
	 * Returns the denghi_captu of this src giay phep lien van.
	 *
	 * @return the denghi_captu of this src giay phep lien van
	 */
	public Date getDenghi_captu();

	/**
	 * Sets the denghi_captu of this src giay phep lien van.
	 *
	 * @param denghi_captu the denghi_captu of this src giay phep lien van
	 */
	public void setDenghi_captu(Date denghi_captu);

	/**
	 * Returns the denghi_capden of this src giay phep lien van.
	 *
	 * @return the denghi_capden of this src giay phep lien van
	 */
	public Date getDenghi_capden();

	/**
	 * Sets the denghi_capden of this src giay phep lien van.
	 *
	 * @param denghi_capden the denghi_capden of this src giay phep lien van
	 */
	public void setDenghi_capden(Date denghi_capden);

	/**
	 * Returns the ngaycap of this src giay phep lien van.
	 *
	 * @return the ngaycap of this src giay phep lien van
	 */
	public Date getNgaycap();

	/**
	 * Sets the ngaycap of this src giay phep lien van.
	 *
	 * @param ngaycap the ngaycap of this src giay phep lien van
	 */
	public void setNgaycap(Date ngaycap);

	/**
	 * Returns the nguoicap of this src giay phep lien van.
	 *
	 * @return the nguoicap of this src giay phep lien van
	 */
	@AutoEscape
	public String getNguoicap();

	/**
	 * Sets the nguoicap of this src giay phep lien van.
	 *
	 * @param nguoicap the nguoicap of this src giay phep lien van
	 */
	public void setNguoicap(String nguoicap);

	/**
	 * Returns the ngayhethan of this src giay phep lien van.
	 *
	 * @return the ngayhethan of this src giay phep lien van
	 */
	public Date getNgayhethan();

	/**
	 * Sets the ngayhethan of this src giay phep lien van.
	 *
	 * @param ngayhethan the ngayhethan of this src giay phep lien van
	 */
	public void setNgayhethan(Date ngayhethan);

	/**
	 * Returns the ngaythuhoi of this src giay phep lien van.
	 *
	 * @return the ngaythuhoi of this src giay phep lien van
	 */
	public Date getNgaythuhoi();

	/**
	 * Sets the ngaythuhoi of this src giay phep lien van.
	 *
	 * @param ngaythuhoi the ngaythuhoi of this src giay phep lien van
	 */
	public void setNgaythuhoi(Date ngaythuhoi);

	/**
	 * Returns the lydo_thuhoi of this src giay phep lien van.
	 *
	 * @return the lydo_thuhoi of this src giay phep lien van
	 */
	@AutoEscape
	public String getLydo_thuhoi();

	/**
	 * Sets the lydo_thuhoi of this src giay phep lien van.
	 *
	 * @param lydo_thuhoi the lydo_thuhoi of this src giay phep lien van
	 */
	public void setLydo_thuhoi(String lydo_thuhoi);

	/**
	 * Returns the ngayky of this src giay phep lien van.
	 *
	 * @return the ngayky of this src giay phep lien van
	 */
	public Date getNgayky();

	/**
	 * Sets the ngayky of this src giay phep lien van.
	 *
	 * @param ngayky the ngayky of this src giay phep lien van
	 */
	public void setNgayky(Date ngayky);

	/**
	 * Returns the nguoiky of this src giay phep lien van.
	 *
	 * @return the nguoiky of this src giay phep lien van
	 */
	@AutoEscape
	public String getNguoiky();

	/**
	 * Sets the nguoiky of this src giay phep lien van.
	 *
	 * @param nguoiky the nguoiky of this src giay phep lien van
	 */
	public void setNguoiky(String nguoiky);

	/**
	 * Returns the nguoi_ky_id of this src giay phep lien van.
	 *
	 * @return the nguoi_ky_id of this src giay phep lien van
	 */
	public long getNguoi_ky_id();

	/**
	 * Sets the nguoi_ky_id of this src giay phep lien van.
	 *
	 * @param nguoi_ky_id the nguoi_ky_id of this src giay phep lien van
	 */
	public void setNguoi_ky_id(long nguoi_ky_id);

	/**
	 * Returns the ghichu of this src giay phep lien van.
	 *
	 * @return the ghichu of this src giay phep lien van
	 */
	@AutoEscape
	public String getGhichu();

	/**
	 * Sets the ghichu of this src giay phep lien van.
	 *
	 * @param ghichu the ghichu of this src giay phep lien van
	 */
	public void setGhichu(String ghichu);

	/**
	 * Returns the url_file_gplv of this src giay phep lien van.
	 *
	 * @return the url_file_gplv of this src giay phep lien van
	 */
	@AutoEscape
	public String getUrl_file_gplv();

	/**
	 * Sets the url_file_gplv of this src giay phep lien van.
	 *
	 * @param url_file_gplv the url_file_gplv of this src giay phep lien van
	 */
	public void setUrl_file_gplv(String url_file_gplv);

	/**
	 * Returns the trangthai of this src giay phep lien van.
	 *
	 * @return the trangthai of this src giay phep lien van
	 */
	@AutoEscape
	public String getTrangthai();

	/**
	 * Sets the trangthai of this src giay phep lien van.
	 *
	 * @param trangthai the trangthai of this src giay phep lien van
	 */
	public void setTrangthai(String trangthai);

	/**
	 * Returns the quocgia_id of this src giay phep lien van.
	 *
	 * @return the quocgia_id of this src giay phep lien van
	 */
	public long getQuocgia_id();

	/**
	 * Sets the quocgia_id of this src giay phep lien van.
	 *
	 * @param quocgia_id the quocgia_id of this src giay phep lien van
	 */
	public void setQuocgia_id(long quocgia_id);

	/**
	 * Returns the tuyen_id of this src giay phep lien van.
	 *
	 * @return the tuyen_id of this src giay phep lien van
	 */
	public long getTuyen_id();

	/**
	 * Sets the tuyen_id of this src giay phep lien van.
	 *
	 * @param tuyen_id the tuyen_id of this src giay phep lien van
	 */
	public void setTuyen_id(long tuyen_id);

	/**
	 * Returns the coquanquanly_id of this src giay phep lien van.
	 *
	 * @return the coquanquanly_id of this src giay phep lien van
	 */
	public long getCoquanquanly_id();

	/**
	 * Sets the coquanquanly_id of this src giay phep lien van.
	 *
	 * @param coquanquanly_id the coquanquanly_id of this src giay phep lien van
	 */
	public void setCoquanquanly_id(long coquanquanly_id);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SRCGiayPhepLienVan srcGiayPhepLienVan);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SRCGiayPhepLienVan> toCacheModel();

	@Override
	public SRCGiayPhepLienVan toEscapedModel();

	@Override
	public SRCGiayPhepLienVan toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}