/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.backend.migrate.vr.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the SRCPHBHGiayPhepVanTai service. Represents a row in the &quot;phbh_giayphepvantai&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.backend.migrate.vr.model.impl.SRCPHBHGiayPhepVanTaiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.backend.migrate.vr.model.impl.SRCPHBHGiayPhepVanTaiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SRCPHBHGiayPhepVanTai
 * @see com.backend.migrate.vr.model.impl.SRCPHBHGiayPhepVanTaiImpl
 * @see com.backend.migrate.vr.model.impl.SRCPHBHGiayPhepVanTaiModelImpl
 * @generated
 */
@ProviderType
public interface SRCPHBHGiayPhepVanTaiModel extends BaseModel<SRCPHBHGiayPhepVanTai> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a srcphbh giay phep van tai model instance should use the {@link SRCPHBHGiayPhepVanTai} interface instead.
	 */

	/**
	 * Returns the primary key of this srcphbh giay phep van tai.
	 *
	 * @return the primary key of this srcphbh giay phep van tai
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this srcphbh giay phep van tai.
	 *
	 * @param primaryKey the primary key of this srcphbh giay phep van tai
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this srcphbh giay phep van tai.
	 *
	 * @return the ID of this srcphbh giay phep van tai
	 */
	public long getId();

	/**
	 * Sets the ID of this srcphbh giay phep van tai.
	 *
	 * @param id the ID of this srcphbh giay phep van tai
	 */
	public void setId(long id);

	/**
	 * Returns the coquanquanly_id of this srcphbh giay phep van tai.
	 *
	 * @return the coquanquanly_id of this srcphbh giay phep van tai
	 */
	public long getCoquanquanly_id();

	/**
	 * Sets the coquanquanly_id of this srcphbh giay phep van tai.
	 *
	 * @param coquanquanly_id the coquanquanly_id of this srcphbh giay phep van tai
	 */
	public void setCoquanquanly_id(long coquanquanly_id);

	/**
	 * Returns the doanhnghiep_id of this srcphbh giay phep van tai.
	 *
	 * @return the doanhnghiep_id of this srcphbh giay phep van tai
	 */
	public long getDoanhnghiep_id();

	/**
	 * Sets the doanhnghiep_id of this srcphbh giay phep van tai.
	 *
	 * @param doanhnghiep_id the doanhnghiep_id of this srcphbh giay phep van tai
	 */
	public void setDoanhnghiep_id(long doanhnghiep_id);

	/**
	 * Returns the sogiayphep of this srcphbh giay phep van tai.
	 *
	 * @return the sogiayphep of this srcphbh giay phep van tai
	 */
	@AutoEscape
	public String getSogiayphep();

	/**
	 * Sets the sogiayphep of this srcphbh giay phep van tai.
	 *
	 * @param sogiayphep the sogiayphep of this srcphbh giay phep van tai
	 */
	public void setSogiayphep(String sogiayphep);

	/**
	 * Returns the lancapphep of this srcphbh giay phep van tai.
	 *
	 * @return the lancapphep of this srcphbh giay phep van tai
	 */
	public int getLancapphep();

	/**
	 * Sets the lancapphep of this srcphbh giay phep van tai.
	 *
	 * @param lancapphep the lancapphep of this srcphbh giay phep van tai
	 */
	public void setLancapphep(int lancapphep);

	/**
	 * Returns the ngaycap of this srcphbh giay phep van tai.
	 *
	 * @return the ngaycap of this srcphbh giay phep van tai
	 */
	public Date getNgaycap();

	/**
	 * Sets the ngaycap of this srcphbh giay phep van tai.
	 *
	 * @param ngaycap the ngaycap of this srcphbh giay phep van tai
	 */
	public void setNgaycap(Date ngaycap);

	/**
	 * Returns the nguoicap of this srcphbh giay phep van tai.
	 *
	 * @return the nguoicap of this srcphbh giay phep van tai
	 */
	@AutoEscape
	public String getNguoicap();

	/**
	 * Sets the nguoicap of this srcphbh giay phep van tai.
	 *
	 * @param nguoicap the nguoicap of this srcphbh giay phep van tai
	 */
	public void setNguoicap(String nguoicap);

	/**
	 * Returns the ngayhethan of this srcphbh giay phep van tai.
	 *
	 * @return the ngayhethan of this srcphbh giay phep van tai
	 */
	public Date getNgayhethan();

	/**
	 * Sets the ngayhethan of this srcphbh giay phep van tai.
	 *
	 * @param ngayhethan the ngayhethan of this srcphbh giay phep van tai
	 */
	public void setNgayhethan(Date ngayhethan);

	/**
	 * Returns the nguoidieuhanh of this srcphbh giay phep van tai.
	 *
	 * @return the nguoidieuhanh of this srcphbh giay phep van tai
	 */
	@AutoEscape
	public String getNguoidieuhanh();

	/**
	 * Sets the nguoidieuhanh of this srcphbh giay phep van tai.
	 *
	 * @param nguoidieuhanh the nguoidieuhanh of this srcphbh giay phep van tai
	 */
	public void setNguoidieuhanh(String nguoidieuhanh);

	/**
	 * Returns the bangcap of this srcphbh giay phep van tai.
	 *
	 * @return the bangcap of this srcphbh giay phep van tai
	 */
	@AutoEscape
	public String getBangcap();

	/**
	 * Sets the bangcap of this srcphbh giay phep van tai.
	 *
	 * @param bangcap the bangcap of this srcphbh giay phep van tai
	 */
	public void setBangcap(String bangcap);

	/**
	 * Returns the ngaysinh of this srcphbh giay phep van tai.
	 *
	 * @return the ngaysinh of this srcphbh giay phep van tai
	 */
	public Date getNgaysinh();

	/**
	 * Sets the ngaysinh of this srcphbh giay phep van tai.
	 *
	 * @param ngaysinh the ngaysinh of this srcphbh giay phep van tai
	 */
	public void setNgaysinh(Date ngaysinh);

	/**
	 * Returns the socmnd of this srcphbh giay phep van tai.
	 *
	 * @return the socmnd of this srcphbh giay phep van tai
	 */
	@AutoEscape
	public String getSocmnd();

	/**
	 * Sets the socmnd of this srcphbh giay phep van tai.
	 *
	 * @param socmnd the socmnd of this srcphbh giay phep van tai
	 */
	public void setSocmnd(String socmnd);

	/**
	 * Returns the nguoiky of this srcphbh giay phep van tai.
	 *
	 * @return the nguoiky of this srcphbh giay phep van tai
	 */
	@AutoEscape
	public String getNguoiky();

	/**
	 * Sets the nguoiky of this srcphbh giay phep van tai.
	 *
	 * @param nguoiky the nguoiky of this srcphbh giay phep van tai
	 */
	public void setNguoiky(String nguoiky);

	/**
	 * Returns the nguoiky_id of this srcphbh giay phep van tai.
	 *
	 * @return the nguoiky_id of this srcphbh giay phep van tai
	 */
	public long getNguoiky_id();

	/**
	 * Sets the nguoiky_id of this srcphbh giay phep van tai.
	 *
	 * @param nguoiky_id the nguoiky_id of this srcphbh giay phep van tai
	 */
	public void setNguoiky_id(long nguoiky_id);

	/**
	 * Returns the ngayky of this srcphbh giay phep van tai.
	 *
	 * @return the ngayky of this srcphbh giay phep van tai
	 */
	public Date getNgayky();

	/**
	 * Sets the ngayky of this srcphbh giay phep van tai.
	 *
	 * @param ngayky the ngayky of this srcphbh giay phep van tai
	 */
	public void setNgayky(Date ngayky);

	/**
	 * Returns the ngay_thuhoi of this srcphbh giay phep van tai.
	 *
	 * @return the ngay_thuhoi of this srcphbh giay phep van tai
	 */
	public Date getNgay_thuhoi();

	/**
	 * Sets the ngay_thuhoi of this srcphbh giay phep van tai.
	 *
	 * @param ngay_thuhoi the ngay_thuhoi of this srcphbh giay phep van tai
	 */
	public void setNgay_thuhoi(Date ngay_thuhoi);

	/**
	 * Returns the lydo_thuhoi of this srcphbh giay phep van tai.
	 *
	 * @return the lydo_thuhoi of this srcphbh giay phep van tai
	 */
	@AutoEscape
	public String getLydo_thuhoi();

	/**
	 * Sets the lydo_thuhoi of this srcphbh giay phep van tai.
	 *
	 * @param lydo_thuhoi the lydo_thuhoi of this srcphbh giay phep van tai
	 */
	public void setLydo_thuhoi(String lydo_thuhoi);

	/**
	 * Returns the ghichu of this srcphbh giay phep van tai.
	 *
	 * @return the ghichu of this srcphbh giay phep van tai
	 */
	@AutoEscape
	public String getGhichu();

	/**
	 * Sets the ghichu of this srcphbh giay phep van tai.
	 *
	 * @param ghichu the ghichu of this srcphbh giay phep van tai
	 */
	public void setGhichu(String ghichu);

	/**
	 * Returns the trangthai of this srcphbh giay phep van tai.
	 *
	 * @return the trangthai of this srcphbh giay phep van tai
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this srcphbh giay phep van tai.
	 *
	 * @param trangthai the trangthai of this srcphbh giay phep van tai
	 */
	public void setTrangthai(int trangthai);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(SRCPHBHGiayPhepVanTai srcphbhGiayPhepVanTai);

	@Override
	public int hashCode();

	@Override
	public CacheModel<SRCPHBHGiayPhepVanTai> toCacheModel();

	@Override
	public SRCPHBHGiayPhepVanTai toEscapedModel();

	@Override
	public SRCPHBHGiayPhepVanTai toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}