/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.backend.migrate.vr.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ViPham service. Represents a row in the &quot;phbh_vipham&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.backend.migrate.vr.model.impl.ViPhamModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.backend.migrate.vr.model.impl.ViPhamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ViPham
 * @see com.backend.migrate.vr.model.impl.ViPhamImpl
 * @see com.backend.migrate.vr.model.impl.ViPhamModelImpl
 * @generated
 */
@ProviderType
public interface ViPhamModel extends BaseModel<ViPham> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a vi pham model instance should use the {@link ViPham} interface instead.
	 */

	/**
	 * Returns the primary key of this vi pham.
	 *
	 * @return the primary key of this vi pham
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this vi pham.
	 *
	 * @param primaryKey the primary key of this vi pham
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this vi pham.
	 *
	 * @return the uuid of this vi pham
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this vi pham.
	 *
	 * @param uuid the uuid of this vi pham
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this vi pham.
	 *
	 * @return the ID of this vi pham
	 */
	public long getId();

	/**
	 * Sets the ID of this vi pham.
	 *
	 * @param id the ID of this vi pham
	 */
	public void setId(long id);

	/**
	 * Returns the phuongtien_id of this vi pham.
	 *
	 * @return the phuongtien_id of this vi pham
	 */
	public long getPhuongtien_id();

	/**
	 * Sets the phuongtien_id of this vi pham.
	 *
	 * @param phuongtien_id the phuongtien_id of this vi pham
	 */
	public void setPhuongtien_id(long phuongtien_id);

	/**
	 * Returns the ngayvipham of this vi pham.
	 *
	 * @return the ngayvipham of this vi pham
	 */
	public Date getNgayvipham();

	/**
	 * Sets the ngayvipham of this vi pham.
	 *
	 * @param ngayvipham the ngayvipham of this vi pham
	 */
	public void setNgayvipham(Date ngayvipham);

	/**
	 * Returns the loaivipham_id of this vi pham.
	 *
	 * @return the loaivipham_id of this vi pham
	 */
	public long getLoaivipham_id();

	/**
	 * Sets the loaivipham_id of this vi pham.
	 *
	 * @param loaivipham_id the loaivipham_id of this vi pham
	 */
	public void setLoaivipham_id(long loaivipham_id);

	/**
	 * Returns the mota of this vi pham.
	 *
	 * @return the mota of this vi pham
	 */
	@AutoEscape
	public String getMota();

	/**
	 * Sets the mota of this vi pham.
	 *
	 * @param mota the mota of this vi pham
	 */
	public void setMota(String mota);

	/**
	 * Returns the url_bienban of this vi pham.
	 *
	 * @return the url_bienban of this vi pham
	 */
	@AutoEscape
	public String getUrl_bienban();

	/**
	 * Sets the url_bienban of this vi pham.
	 *
	 * @param url_bienban the url_bienban of this vi pham
	 */
	public void setUrl_bienban(String url_bienban);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ViPham viPham);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ViPham> toCacheModel();

	@Override
	public ViPham toEscapedModel();

	@Override
	public ViPham toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}