/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.fds.vr.filterconfig.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DMDataItem service. Represents a row in the &quot;dm_dataitem&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.fds.vr.filterconfig.model.impl.DMDataItemModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.fds.vr.filterconfig.model.impl.DMDataItemImpl}.
 * </p>
 *
 * @author NhanHoang
 * @see DMDataItem
 * @see com.fds.vr.filterconfig.model.impl.DMDataItemImpl
 * @see com.fds.vr.filterconfig.model.impl.DMDataItemModelImpl
 * @generated
 */
@ProviderType
public interface DMDataItemModel extends BaseModel<DMDataItem> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dm data item model instance should use the {@link DMDataItem} interface instead.
	 */

	/**
	 * Returns the primary key of this dm data item.
	 *
	 * @return the primary key of this dm data item
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dm data item.
	 *
	 * @param primaryKey the primary key of this dm data item
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this dm data item.
	 *
	 * @return the ID of this dm data item
	 */
	public long getId();

	/**
	 * Sets the ID of this dm data item.
	 *
	 * @param id the ID of this dm data item
	 */
	public void setId(long id);

	/**
	 * Returns the data group ID of this dm data item.
	 *
	 * @return the data group ID of this dm data item
	 */
	public long getDataGroupId();

	/**
	 * Sets the data group ID of this dm data item.
	 *
	 * @param dataGroupId the data group ID of this dm data item
	 */
	public void setDataGroupId(long dataGroupId);

	/**
	 * Returns the code_0 of this dm data item.
	 *
	 * @return the code_0 of this dm data item
	 */
	@AutoEscape
	public String getCode_0();

	/**
	 * Sets the code_0 of this dm data item.
	 *
	 * @param code_0 the code_0 of this dm data item
	 */
	public void setCode_0(String code_0);

	/**
	 * Returns the code_1 of this dm data item.
	 *
	 * @return the code_1 of this dm data item
	 */
	@AutoEscape
	public String getCode_1();

	/**
	 * Sets the code_1 of this dm data item.
	 *
	 * @param code_1 the code_1 of this dm data item
	 */
	public void setCode_1(String code_1);

	/**
	 * Returns the code_2 of this dm data item.
	 *
	 * @return the code_2 of this dm data item
	 */
	@AutoEscape
	public String getCode_2();

	/**
	 * Sets the code_2 of this dm data item.
	 *
	 * @param code_2 the code_2 of this dm data item
	 */
	public void setCode_2(String code_2);

	/**
	 * Returns the code_3 of this dm data item.
	 *
	 * @return the code_3 of this dm data item
	 */
	@AutoEscape
	public String getCode_3();

	/**
	 * Sets the code_3 of this dm data item.
	 *
	 * @param code_3 the code_3 of this dm data item
	 */
	public void setCode_3(String code_3);

	/**
	 * Returns the level of this dm data item.
	 *
	 * @return the level of this dm data item
	 */
	public int getLevel();

	/**
	 * Sets the level of this dm data item.
	 *
	 * @param level the level of this dm data item
	 */
	public void setLevel(int level);

	/**
	 * Returns the name of this dm data item.
	 *
	 * @return the name of this dm data item
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dm data item.
	 *
	 * @param name the name of this dm data item
	 */
	public void setName(String name);

	/**
	 * Returns the altername of this dm data item.
	 *
	 * @return the altername of this dm data item
	 */
	@AutoEscape
	public String getAltername();

	/**
	 * Sets the altername of this dm data item.
	 *
	 * @param altername the altername of this dm data item
	 */
	public void setAltername(String altername);

	/**
	 * Returns the description of this dm data item.
	 *
	 * @return the description of this dm data item
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this dm data item.
	 *
	 * @param description the description of this dm data item
	 */
	public void setDescription(String description);

	/**
	 * Returns the validated from of this dm data item.
	 *
	 * @return the validated from of this dm data item
	 */
	public Date getValidatedFrom();

	/**
	 * Sets the validated from of this dm data item.
	 *
	 * @param validatedFrom the validated from of this dm data item
	 */
	public void setValidatedFrom(Date validatedFrom);

	/**
	 * Returns the validated to of this dm data item.
	 *
	 * @return the validated to of this dm data item
	 */
	public Date getValidatedTo();

	/**
	 * Sets the validated to of this dm data item.
	 *
	 * @param validatedTo the validated to of this dm data item
	 */
	public void setValidatedTo(Date validatedTo);

	/**
	 * Returns the status of this dm data item.
	 *
	 * @return the status of this dm data item
	 */
	public int getStatus();

	/**
	 * Sets the status of this dm data item.
	 *
	 * @param status the status of this dm data item
	 */
	public void setStatus(int status);

	/**
	 * Returns the sync date of this dm data item.
	 *
	 * @return the sync date of this dm data item
	 */
	public Date getSyncDate();

	/**
	 * Sets the sync date of this dm data item.
	 *
	 * @param syncDate the sync date of this dm data item
	 */
	public void setSyncDate(Date syncDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DMDataItem dmDataItem);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DMDataItem> toCacheModel();

	@Override
	public DMDataItem toEscapedModel();

	@Override
	public DMDataItem toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}