/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package vn.gt.dao.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the CompressFileLog service. Represents a row in the &quot;compressfile_CompressFileLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link vn.gt.dao.model.impl.CompressFileLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link vn.gt.dao.model.impl.CompressFileLogImpl}.
 * </p>
 *
 * @author huymq
 * @see CompressFileLog
 * @see vn.gt.dao.model.impl.CompressFileLogImpl
 * @see vn.gt.dao.model.impl.CompressFileLogModelImpl
 * @generated
 */
@ProviderType
public interface CompressFileLogModel extends BaseModel<CompressFileLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a compress file log model instance should use the {@link CompressFileLog} interface instead.
	 */

	/**
	 * Returns the primary key of this compress file log.
	 *
	 * @return the primary key of this compress file log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this compress file log.
	 *
	 * @param primaryKey the primary key of this compress file log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this compress file log.
	 *
	 * @return the ID of this compress file log
	 */
	public long getId();

	/**
	 * Sets the ID of this compress file log.
	 *
	 * @param id the ID of this compress file log
	 */
	public void setId(long id);

	/**
	 * Returns the create date of this compress file log.
	 *
	 * @return the create date of this compress file log
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this compress file log.
	 *
	 * @param createDate the create date of this compress file log
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the ho so ID of this compress file log.
	 *
	 * @return the ho so ID of this compress file log
	 */
	public long getHoSoId();

	/**
	 * Sets the ho so ID of this compress file log.
	 *
	 * @param hoSoId the ho so ID of this compress file log
	 */
	public void setHoSoId(long hoSoId);

	/**
	 * Returns the file entry ID of this compress file log.
	 *
	 * @return the file entry ID of this compress file log
	 */
	public long getFileEntryId();

	/**
	 * Sets the file entry ID of this compress file log.
	 *
	 * @param fileEntryId the file entry ID of this compress file log
	 */
	public void setFileEntryId(long fileEntryId);

	/**
	 * Returns the old size of this compress file log.
	 *
	 * @return the old size of this compress file log
	 */
	public long getOldSize();

	/**
	 * Sets the old size of this compress file log.
	 *
	 * @param oldSize the old size of this compress file log
	 */
	public void setOldSize(long oldSize);

	/**
	 * Returns the new size of this compress file log.
	 *
	 * @return the new size of this compress file log
	 */
	public long getNewSize();

	/**
	 * Sets the new size of this compress file log.
	 *
	 * @param newSize the new size of this compress file log
	 */
	public void setNewSize(long newSize);

	/**
	 * Returns the status of this compress file log.
	 *
	 * @return the status of this compress file log
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this compress file log is status.
	 *
	 * @return <code>true</code> if this compress file log is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this compress file log is status.
	 *
	 * @param status the status of this compress file log
	 */
	public void setStatus(boolean status);

	/**
	 * Returns the error msg of this compress file log.
	 *
	 * @return the error msg of this compress file log
	 */
	@AutoEscape
	public String getErrorMsg();

	/**
	 * Sets the error msg of this compress file log.
	 *
	 * @param errorMsg the error msg of this compress file log
	 */
	public void setErrorMsg(String errorMsg);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(vn.gt.dao.model.CompressFileLog compressFileLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<vn.gt.dao.model.CompressFileLog> toCacheModel();

	@Override
	public vn.gt.dao.model.CompressFileLog toEscapedModel();

	@Override
	public vn.gt.dao.model.CompressFileLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}