/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.opencps.dossiermgt.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import org.opencps.dossiermgt.model.Dossier;
import org.opencps.dossiermgt.model.DossierModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Dossier service. Represents a row in the &quot;opencps_dossier&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DossierModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DossierImpl}.
 * </p>
 *
 * @author huymq
 * @see DossierImpl
 * @see Dossier
 * @see DossierModel
 * @generated
 */
@ProviderType
public class DossierModelImpl extends BaseModelImpl<Dossier>
	implements DossierModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a dossier model instance should use the {@link Dossier} interface instead.
	 */
	public static final String TABLE_NAME = "opencps_dossier";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "dossierId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "referenceUid", Types.VARCHAR },
			{ "counter", Types.INTEGER },
			{ "serviceCode", Types.VARCHAR },
			{ "serviceName", Types.VARCHAR },
			{ "govAgencyCode", Types.VARCHAR },
			{ "govAgencyName", Types.VARCHAR },
			{ "applicantName", Types.VARCHAR },
			{ "applicantIdType", Types.VARCHAR },
			{ "applicantIdNo", Types.VARCHAR },
			{ "applicantIdDate", Types.TIMESTAMP },
			{ "address", Types.VARCHAR },
			{ "cityCode", Types.VARCHAR },
			{ "cityName", Types.VARCHAR },
			{ "districtCode", Types.VARCHAR },
			{ "districtName", Types.VARCHAR },
			{ "wardCode", Types.VARCHAR },
			{ "wardName", Types.VARCHAR },
			{ "contactName", Types.VARCHAR },
			{ "contactTelNo", Types.VARCHAR },
			{ "contactEmail", Types.VARCHAR },
			{ "dossierTemplateNo", Types.VARCHAR },
			{ "dossierTemplateName", Types.VARCHAR },
			{ "dossierNote", Types.VARCHAR },
			{ "submissionNote", Types.VARCHAR },
			{ "applicantNote", Types.VARCHAR },
			{ "briefNote", Types.VARCHAR },
			{ "dossierNo", Types.VARCHAR },
			{ "submitting", Types.BOOLEAN },
			{ "submitDate", Types.TIMESTAMP },
			{ "receiveDate", Types.TIMESTAMP },
			{ "dueDate", Types.TIMESTAMP },
			{ "releaseDate", Types.TIMESTAMP },
			{ "finishDate", Types.TIMESTAMP },
			{ "cancellingDate", Types.TIMESTAMP },
			{ "correcttingDate", Types.TIMESTAMP },
			{ "dossierStatus", Types.VARCHAR },
			{ "dossierStatusText", Types.VARCHAR },
			{ "dossierSubStatus", Types.VARCHAR },
			{ "dossierSubStatusText", Types.VARCHAR },
			{ "folderId", Types.BIGINT },
			{ "dossierActionId", Types.BIGINT },
			{ "viaPostal", Types.INTEGER },
			{ "postalAddress", Types.VARCHAR },
			{ "postalCityCode", Types.VARCHAR },
			{ "postalCityName", Types.VARCHAR },
			{ "postalTelNo", Types.VARCHAR },
			{ "password_", Types.VARCHAR },
			{ "notification", Types.BOOLEAN },
			{ "online_", Types.BOOLEAN },
			{ "serverNo", Types.VARCHAR },
			{ "endorsementDate", Types.TIMESTAMP },
			{ "lockState", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("referenceUid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("counter", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("serviceCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("serviceName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("govAgencyCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("govAgencyName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("applicantName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("applicantIdType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("applicantIdNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("applicantIdDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("address", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cityCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("cityName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("districtCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("districtName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("wardCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("wardName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactTelNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("contactEmail", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierTemplateNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierTemplateName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierNote", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("submissionNote", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("applicantNote", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("briefNote", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("submitting", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("submitDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("receiveDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("releaseDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("finishDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("cancellingDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("correcttingDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dossierStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierStatusText", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierSubStatus", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dossierSubStatusText", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("folderId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("dossierActionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("viaPostal", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("postalAddress", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postalCityCode", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postalCityName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("postalTelNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("password_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("notification", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("online_", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("serverNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("endorsementDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("lockState", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table opencps_dossier (uuid_ VARCHAR(75) null,dossierId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,referenceUid VARCHAR(75) null,counter INTEGER,serviceCode VARCHAR(75) null,serviceName VARCHAR(75) null,govAgencyCode VARCHAR(75) null,govAgencyName VARCHAR(75) null,applicantName VARCHAR(75) null,applicantIdType VARCHAR(75) null,applicantIdNo VARCHAR(75) null,applicantIdDate DATE null,address VARCHAR(75) null,cityCode VARCHAR(75) null,cityName VARCHAR(75) null,districtCode VARCHAR(75) null,districtName VARCHAR(75) null,wardCode VARCHAR(75) null,wardName VARCHAR(75) null,contactName VARCHAR(75) null,contactTelNo VARCHAR(75) null,contactEmail VARCHAR(75) null,dossierTemplateNo VARCHAR(75) null,dossierTemplateName VARCHAR(75) null,dossierNote VARCHAR(75) null,submissionNote VARCHAR(75) null,applicantNote VARCHAR(75) null,briefNote VARCHAR(75) null,dossierNo VARCHAR(75) null,submitting BOOLEAN,submitDate DATE null,receiveDate DATE null,dueDate DATE null,releaseDate DATE null,finishDate DATE null,cancellingDate DATE null,correcttingDate DATE null,dossierStatus VARCHAR(75) null,dossierStatusText VARCHAR(75) null,dossierSubStatus VARCHAR(75) null,dossierSubStatusText VARCHAR(75) null,folderId LONG,dossierActionId LONG,viaPostal INTEGER,postalAddress VARCHAR(75) null,postalCityCode VARCHAR(75) null,postalCityName VARCHAR(75) null,postalTelNo VARCHAR(75) null,password_ VARCHAR(75) null,notification BOOLEAN,online_ BOOLEAN,serverNo VARCHAR(75) null,endorsementDate DATE null,lockState VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table opencps_dossier";
	public static final String ORDER_BY_JPQL = " ORDER BY dossier.dossierId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY opencps_dossier.dossierId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(org.opencps.backend.dossiermgt.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.org.opencps.dossiermgt.model.Dossier"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(org.opencps.backend.dossiermgt.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.org.opencps.dossiermgt.model.Dossier"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(org.opencps.backend.dossiermgt.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.org.opencps.dossiermgt.model.Dossier"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long DOSSIERID_COLUMN_BITMASK = 2L;
	public static final long DOSSIERSTATUS_COLUMN_BITMASK = 4L;
	public static final long DOSSIERTEMPLATENO_COLUMN_BITMASK = 8L;
	public static final long GOVAGENCYCODE_COLUMN_BITMASK = 16L;
	public static final long GROUPID_COLUMN_BITMASK = 32L;
	public static final long REFERENCEUID_COLUMN_BITMASK = 64L;
	public static final long SERVICECODE_COLUMN_BITMASK = 128L;
	public static final long SUBMITTING_COLUMN_BITMASK = 256L;
	public static final long USERID_COLUMN_BITMASK = 512L;
	public static final long UUID_COLUMN_BITMASK = 1024L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(org.opencps.backend.dossiermgt.service.util.ServiceProps.get(
				"lock.expiration.time.org.opencps.dossiermgt.model.Dossier"));

	public DossierModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dossierId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDossierId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dossierId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Dossier.class;
	}

	@Override
	public String getModelClassName() {
		return Dossier.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("dossierId", getDossierId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("referenceUid", getReferenceUid());
		attributes.put("counter", getCounter());
		attributes.put("serviceCode", getServiceCode());
		attributes.put("serviceName", getServiceName());
		attributes.put("govAgencyCode", getGovAgencyCode());
		attributes.put("govAgencyName", getGovAgencyName());
		attributes.put("applicantName", getApplicantName());
		attributes.put("applicantIdType", getApplicantIdType());
		attributes.put("applicantIdNo", getApplicantIdNo());
		attributes.put("applicantIdDate", getApplicantIdDate());
		attributes.put("address", getAddress());
		attributes.put("cityCode", getCityCode());
		attributes.put("cityName", getCityName());
		attributes.put("districtCode", getDistrictCode());
		attributes.put("districtName", getDistrictName());
		attributes.put("wardCode", getWardCode());
		attributes.put("wardName", getWardName());
		attributes.put("contactName", getContactName());
		attributes.put("contactTelNo", getContactTelNo());
		attributes.put("contactEmail", getContactEmail());
		attributes.put("dossierTemplateNo", getDossierTemplateNo());
		attributes.put("dossierTemplateName", getDossierTemplateName());
		attributes.put("dossierNote", getDossierNote());
		attributes.put("submissionNote", getSubmissionNote());
		attributes.put("applicantNote", getApplicantNote());
		attributes.put("briefNote", getBriefNote());
		attributes.put("dossierNo", getDossierNo());
		attributes.put("submitting", getSubmitting());
		attributes.put("submitDate", getSubmitDate());
		attributes.put("receiveDate", getReceiveDate());
		attributes.put("dueDate", getDueDate());
		attributes.put("releaseDate", getReleaseDate());
		attributes.put("finishDate", getFinishDate());
		attributes.put("cancellingDate", getCancellingDate());
		attributes.put("correcttingDate", getCorrecttingDate());
		attributes.put("dossierStatus", getDossierStatus());
		attributes.put("dossierStatusText", getDossierStatusText());
		attributes.put("dossierSubStatus", getDossierSubStatus());
		attributes.put("dossierSubStatusText", getDossierSubStatusText());
		attributes.put("folderId", getFolderId());
		attributes.put("dossierActionId", getDossierActionId());
		attributes.put("viaPostal", getViaPostal());
		attributes.put("postalAddress", getPostalAddress());
		attributes.put("postalCityCode", getPostalCityCode());
		attributes.put("postalCityName", getPostalCityName());
		attributes.put("postalTelNo", getPostalTelNo());
		attributes.put("password", getPassword());
		attributes.put("notification", getNotification());
		attributes.put("online", getOnline());
		attributes.put("serverNo", getServerNo());
		attributes.put("endorsementDate", getEndorsementDate());
		attributes.put("lockState", getLockState());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long dossierId = (Long)attributes.get("dossierId");

		if (dossierId != null) {
			setDossierId(dossierId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String referenceUid = (String)attributes.get("referenceUid");

		if (referenceUid != null) {
			setReferenceUid(referenceUid);
		}

		Integer counter = (Integer)attributes.get("counter");

		if (counter != null) {
			setCounter(counter);
		}

		String serviceCode = (String)attributes.get("serviceCode");

		if (serviceCode != null) {
			setServiceCode(serviceCode);
		}

		String serviceName = (String)attributes.get("serviceName");

		if (serviceName != null) {
			setServiceName(serviceName);
		}

		String govAgencyCode = (String)attributes.get("govAgencyCode");

		if (govAgencyCode != null) {
			setGovAgencyCode(govAgencyCode);
		}

		String govAgencyName = (String)attributes.get("govAgencyName");

		if (govAgencyName != null) {
			setGovAgencyName(govAgencyName);
		}

		String applicantName = (String)attributes.get("applicantName");

		if (applicantName != null) {
			setApplicantName(applicantName);
		}

		String applicantIdType = (String)attributes.get("applicantIdType");

		if (applicantIdType != null) {
			setApplicantIdType(applicantIdType);
		}

		String applicantIdNo = (String)attributes.get("applicantIdNo");

		if (applicantIdNo != null) {
			setApplicantIdNo(applicantIdNo);
		}

		Date applicantIdDate = (Date)attributes.get("applicantIdDate");

		if (applicantIdDate != null) {
			setApplicantIdDate(applicantIdDate);
		}

		String address = (String)attributes.get("address");

		if (address != null) {
			setAddress(address);
		}

		String cityCode = (String)attributes.get("cityCode");

		if (cityCode != null) {
			setCityCode(cityCode);
		}

		String cityName = (String)attributes.get("cityName");

		if (cityName != null) {
			setCityName(cityName);
		}

		String districtCode = (String)attributes.get("districtCode");

		if (districtCode != null) {
			setDistrictCode(districtCode);
		}

		String districtName = (String)attributes.get("districtName");

		if (districtName != null) {
			setDistrictName(districtName);
		}

		String wardCode = (String)attributes.get("wardCode");

		if (wardCode != null) {
			setWardCode(wardCode);
		}

		String wardName = (String)attributes.get("wardName");

		if (wardName != null) {
			setWardName(wardName);
		}

		String contactName = (String)attributes.get("contactName");

		if (contactName != null) {
			setContactName(contactName);
		}

		String contactTelNo = (String)attributes.get("contactTelNo");

		if (contactTelNo != null) {
			setContactTelNo(contactTelNo);
		}

		String contactEmail = (String)attributes.get("contactEmail");

		if (contactEmail != null) {
			setContactEmail(contactEmail);
		}

		String dossierTemplateNo = (String)attributes.get("dossierTemplateNo");

		if (dossierTemplateNo != null) {
			setDossierTemplateNo(dossierTemplateNo);
		}

		String dossierTemplateName = (String)attributes.get(
				"dossierTemplateName");

		if (dossierTemplateName != null) {
			setDossierTemplateName(dossierTemplateName);
		}

		String dossierNote = (String)attributes.get("dossierNote");

		if (dossierNote != null) {
			setDossierNote(dossierNote);
		}

		String submissionNote = (String)attributes.get("submissionNote");

		if (submissionNote != null) {
			setSubmissionNote(submissionNote);
		}

		String applicantNote = (String)attributes.get("applicantNote");

		if (applicantNote != null) {
			setApplicantNote(applicantNote);
		}

		String briefNote = (String)attributes.get("briefNote");

		if (briefNote != null) {
			setBriefNote(briefNote);
		}

		String dossierNo = (String)attributes.get("dossierNo");

		if (dossierNo != null) {
			setDossierNo(dossierNo);
		}

		Boolean submitting = (Boolean)attributes.get("submitting");

		if (submitting != null) {
			setSubmitting(submitting);
		}

		Date submitDate = (Date)attributes.get("submitDate");

		if (submitDate != null) {
			setSubmitDate(submitDate);
		}

		Date receiveDate = (Date)attributes.get("receiveDate");

		if (receiveDate != null) {
			setReceiveDate(receiveDate);
		}

		Date dueDate = (Date)attributes.get("dueDate");

		if (dueDate != null) {
			setDueDate(dueDate);
		}

		Date releaseDate = (Date)attributes.get("releaseDate");

		if (releaseDate != null) {
			setReleaseDate(releaseDate);
		}

		Date finishDate = (Date)attributes.get("finishDate");

		if (finishDate != null) {
			setFinishDate(finishDate);
		}

		Date cancellingDate = (Date)attributes.get("cancellingDate");

		if (cancellingDate != null) {
			setCancellingDate(cancellingDate);
		}

		Date correcttingDate = (Date)attributes.get("correcttingDate");

		if (correcttingDate != null) {
			setCorrecttingDate(correcttingDate);
		}

		String dossierStatus = (String)attributes.get("dossierStatus");

		if (dossierStatus != null) {
			setDossierStatus(dossierStatus);
		}

		String dossierStatusText = (String)attributes.get("dossierStatusText");

		if (dossierStatusText != null) {
			setDossierStatusText(dossierStatusText);
		}

		String dossierSubStatus = (String)attributes.get("dossierSubStatus");

		if (dossierSubStatus != null) {
			setDossierSubStatus(dossierSubStatus);
		}

		String dossierSubStatusText = (String)attributes.get(
				"dossierSubStatusText");

		if (dossierSubStatusText != null) {
			setDossierSubStatusText(dossierSubStatusText);
		}

		Long folderId = (Long)attributes.get("folderId");

		if (folderId != null) {
			setFolderId(folderId);
		}

		Long dossierActionId = (Long)attributes.get("dossierActionId");

		if (dossierActionId != null) {
			setDossierActionId(dossierActionId);
		}

		Integer viaPostal = (Integer)attributes.get("viaPostal");

		if (viaPostal != null) {
			setViaPostal(viaPostal);
		}

		String postalAddress = (String)attributes.get("postalAddress");

		if (postalAddress != null) {
			setPostalAddress(postalAddress);
		}

		String postalCityCode = (String)attributes.get("postalCityCode");

		if (postalCityCode != null) {
			setPostalCityCode(postalCityCode);
		}

		String postalCityName = (String)attributes.get("postalCityName");

		if (postalCityName != null) {
			setPostalCityName(postalCityName);
		}

		String postalTelNo = (String)attributes.get("postalTelNo");

		if (postalTelNo != null) {
			setPostalTelNo(postalTelNo);
		}

		String password = (String)attributes.get("password");

		if (password != null) {
			setPassword(password);
		}

		Boolean notification = (Boolean)attributes.get("notification");

		if (notification != null) {
			setNotification(notification);
		}

		Boolean online = (Boolean)attributes.get("online");

		if (online != null) {
			setOnline(online);
		}

		String serverNo = (String)attributes.get("serverNo");

		if (serverNo != null) {
			setServerNo(serverNo);
		}

		Date endorsementDate = (Date)attributes.get("endorsementDate");

		if (endorsementDate != null) {
			setEndorsementDate(endorsementDate);
		}

		String lockState = (String)attributes.get("lockState");

		if (lockState != null) {
			setLockState(lockState);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getDossierId() {
		return _dossierId;
	}

	@Override
	public void setDossierId(long dossierId) {
		_columnBitmask |= DOSSIERID_COLUMN_BITMASK;

		if (!_setOriginalDossierId) {
			_setOriginalDossierId = true;

			_originalDossierId = _dossierId;
		}

		_dossierId = dossierId;
	}

	public long getOriginalDossierId() {
		return _originalDossierId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getReferenceUid() {
		if (_referenceUid == null) {
			return StringPool.BLANK;
		}
		else {
			return _referenceUid;
		}
	}

	@Override
	public void setReferenceUid(String referenceUid) {
		_columnBitmask |= REFERENCEUID_COLUMN_BITMASK;

		if (_originalReferenceUid == null) {
			_originalReferenceUid = _referenceUid;
		}

		_referenceUid = referenceUid;
	}

	public String getOriginalReferenceUid() {
		return GetterUtil.getString(_originalReferenceUid);
	}

	@Override
	public int getCounter() {
		return _counter;
	}

	@Override
	public void setCounter(int counter) {
		_counter = counter;
	}

	@Override
	public String getServiceCode() {
		if (_serviceCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceCode;
		}
	}

	@Override
	public void setServiceCode(String serviceCode) {
		_columnBitmask |= SERVICECODE_COLUMN_BITMASK;

		if (_originalServiceCode == null) {
			_originalServiceCode = _serviceCode;
		}

		_serviceCode = serviceCode;
	}

	public String getOriginalServiceCode() {
		return GetterUtil.getString(_originalServiceCode);
	}

	@Override
	public String getServiceName() {
		if (_serviceName == null) {
			return StringPool.BLANK;
		}
		else {
			return _serviceName;
		}
	}

	@Override
	public void setServiceName(String serviceName) {
		_serviceName = serviceName;
	}

	@Override
	public String getGovAgencyCode() {
		if (_govAgencyCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgencyCode;
		}
	}

	@Override
	public void setGovAgencyCode(String govAgencyCode) {
		_columnBitmask |= GOVAGENCYCODE_COLUMN_BITMASK;

		if (_originalGovAgencyCode == null) {
			_originalGovAgencyCode = _govAgencyCode;
		}

		_govAgencyCode = govAgencyCode;
	}

	public String getOriginalGovAgencyCode() {
		return GetterUtil.getString(_originalGovAgencyCode);
	}

	@Override
	public String getGovAgencyName() {
		if (_govAgencyName == null) {
			return StringPool.BLANK;
		}
		else {
			return _govAgencyName;
		}
	}

	@Override
	public void setGovAgencyName(String govAgencyName) {
		_govAgencyName = govAgencyName;
	}

	@Override
	public String getApplicantName() {
		if (_applicantName == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicantName;
		}
	}

	@Override
	public void setApplicantName(String applicantName) {
		_applicantName = applicantName;
	}

	@Override
	public String getApplicantIdType() {
		if (_applicantIdType == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicantIdType;
		}
	}

	@Override
	public void setApplicantIdType(String applicantIdType) {
		_applicantIdType = applicantIdType;
	}

	@Override
	public String getApplicantIdNo() {
		if (_applicantIdNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicantIdNo;
		}
	}

	@Override
	public void setApplicantIdNo(String applicantIdNo) {
		_applicantIdNo = applicantIdNo;
	}

	@Override
	public Date getApplicantIdDate() {
		return _applicantIdDate;
	}

	@Override
	public void setApplicantIdDate(Date applicantIdDate) {
		_applicantIdDate = applicantIdDate;
	}

	@Override
	public String getAddress() {
		if (_address == null) {
			return StringPool.BLANK;
		}
		else {
			return _address;
		}
	}

	@Override
	public void setAddress(String address) {
		_address = address;
	}

	@Override
	public String getCityCode() {
		if (_cityCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _cityCode;
		}
	}

	@Override
	public void setCityCode(String cityCode) {
		_cityCode = cityCode;
	}

	@Override
	public String getCityName() {
		if (_cityName == null) {
			return StringPool.BLANK;
		}
		else {
			return _cityName;
		}
	}

	@Override
	public void setCityName(String cityName) {
		_cityName = cityName;
	}

	@Override
	public String getDistrictCode() {
		if (_districtCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _districtCode;
		}
	}

	@Override
	public void setDistrictCode(String districtCode) {
		_districtCode = districtCode;
	}

	@Override
	public String getDistrictName() {
		if (_districtName == null) {
			return StringPool.BLANK;
		}
		else {
			return _districtName;
		}
	}

	@Override
	public void setDistrictName(String districtName) {
		_districtName = districtName;
	}

	@Override
	public String getWardCode() {
		if (_wardCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _wardCode;
		}
	}

	@Override
	public void setWardCode(String wardCode) {
		_wardCode = wardCode;
	}

	@Override
	public String getWardName() {
		if (_wardName == null) {
			return StringPool.BLANK;
		}
		else {
			return _wardName;
		}
	}

	@Override
	public void setWardName(String wardName) {
		_wardName = wardName;
	}

	@Override
	public String getContactName() {
		if (_contactName == null) {
			return StringPool.BLANK;
		}
		else {
			return _contactName;
		}
	}

	@Override
	public void setContactName(String contactName) {
		_contactName = contactName;
	}

	@Override
	public String getContactTelNo() {
		if (_contactTelNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _contactTelNo;
		}
	}

	@Override
	public void setContactTelNo(String contactTelNo) {
		_contactTelNo = contactTelNo;
	}

	@Override
	public String getContactEmail() {
		if (_contactEmail == null) {
			return StringPool.BLANK;
		}
		else {
			return _contactEmail;
		}
	}

	@Override
	public void setContactEmail(String contactEmail) {
		_contactEmail = contactEmail;
	}

	@Override
	public String getDossierTemplateNo() {
		if (_dossierTemplateNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierTemplateNo;
		}
	}

	@Override
	public void setDossierTemplateNo(String dossierTemplateNo) {
		_columnBitmask |= DOSSIERTEMPLATENO_COLUMN_BITMASK;

		if (_originalDossierTemplateNo == null) {
			_originalDossierTemplateNo = _dossierTemplateNo;
		}

		_dossierTemplateNo = dossierTemplateNo;
	}

	public String getOriginalDossierTemplateNo() {
		return GetterUtil.getString(_originalDossierTemplateNo);
	}

	@Override
	public String getDossierTemplateName() {
		if (_dossierTemplateName == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierTemplateName;
		}
	}

	@Override
	public void setDossierTemplateName(String dossierTemplateName) {
		_dossierTemplateName = dossierTemplateName;
	}

	@Override
	public String getDossierNote() {
		if (_dossierNote == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierNote;
		}
	}

	@Override
	public void setDossierNote(String dossierNote) {
		_dossierNote = dossierNote;
	}

	@Override
	public String getSubmissionNote() {
		if (_submissionNote == null) {
			return StringPool.BLANK;
		}
		else {
			return _submissionNote;
		}
	}

	@Override
	public void setSubmissionNote(String submissionNote) {
		_submissionNote = submissionNote;
	}

	@Override
	public String getApplicantNote() {
		if (_applicantNote == null) {
			return StringPool.BLANK;
		}
		else {
			return _applicantNote;
		}
	}

	@Override
	public void setApplicantNote(String applicantNote) {
		_applicantNote = applicantNote;
	}

	@Override
	public String getBriefNote() {
		if (_briefNote == null) {
			return StringPool.BLANK;
		}
		else {
			return _briefNote;
		}
	}

	@Override
	public void setBriefNote(String briefNote) {
		_briefNote = briefNote;
	}

	@Override
	public String getDossierNo() {
		if (_dossierNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierNo;
		}
	}

	@Override
	public void setDossierNo(String dossierNo) {
		_dossierNo = dossierNo;
	}

	@Override
	public boolean getSubmitting() {
		return _submitting;
	}

	@Override
	public boolean isSubmitting() {
		return _submitting;
	}

	@Override
	public void setSubmitting(boolean submitting) {
		_columnBitmask |= SUBMITTING_COLUMN_BITMASK;

		if (!_setOriginalSubmitting) {
			_setOriginalSubmitting = true;

			_originalSubmitting = _submitting;
		}

		_submitting = submitting;
	}

	public boolean getOriginalSubmitting() {
		return _originalSubmitting;
	}

	@Override
	public Date getSubmitDate() {
		return _submitDate;
	}

	@Override
	public void setSubmitDate(Date submitDate) {
		_submitDate = submitDate;
	}

	@Override
	public Date getReceiveDate() {
		return _receiveDate;
	}

	@Override
	public void setReceiveDate(Date receiveDate) {
		_receiveDate = receiveDate;
	}

	@Override
	public Date getDueDate() {
		return _dueDate;
	}

	@Override
	public void setDueDate(Date dueDate) {
		_dueDate = dueDate;
	}

	@Override
	public Date getReleaseDate() {
		return _releaseDate;
	}

	@Override
	public void setReleaseDate(Date releaseDate) {
		_releaseDate = releaseDate;
	}

	@Override
	public Date getFinishDate() {
		return _finishDate;
	}

	@Override
	public void setFinishDate(Date finishDate) {
		_finishDate = finishDate;
	}

	@Override
	public Date getCancellingDate() {
		return _cancellingDate;
	}

	@Override
	public void setCancellingDate(Date cancellingDate) {
		_cancellingDate = cancellingDate;
	}

	@Override
	public Date getCorrecttingDate() {
		return _correcttingDate;
	}

	@Override
	public void setCorrecttingDate(Date correcttingDate) {
		_correcttingDate = correcttingDate;
	}

	@Override
	public String getDossierStatus() {
		if (_dossierStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierStatus;
		}
	}

	@Override
	public void setDossierStatus(String dossierStatus) {
		_columnBitmask |= DOSSIERSTATUS_COLUMN_BITMASK;

		if (_originalDossierStatus == null) {
			_originalDossierStatus = _dossierStatus;
		}

		_dossierStatus = dossierStatus;
	}

	public String getOriginalDossierStatus() {
		return GetterUtil.getString(_originalDossierStatus);
	}

	@Override
	public String getDossierStatusText() {
		if (_dossierStatusText == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierStatusText;
		}
	}

	@Override
	public void setDossierStatusText(String dossierStatusText) {
		_dossierStatusText = dossierStatusText;
	}

	@Override
	public String getDossierSubStatus() {
		if (_dossierSubStatus == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierSubStatus;
		}
	}

	@Override
	public void setDossierSubStatus(String dossierSubStatus) {
		_dossierSubStatus = dossierSubStatus;
	}

	@Override
	public String getDossierSubStatusText() {
		if (_dossierSubStatusText == null) {
			return StringPool.BLANK;
		}
		else {
			return _dossierSubStatusText;
		}
	}

	@Override
	public void setDossierSubStatusText(String dossierSubStatusText) {
		_dossierSubStatusText = dossierSubStatusText;
	}

	@Override
	public long getFolderId() {
		return _folderId;
	}

	@Override
	public void setFolderId(long folderId) {
		_folderId = folderId;
	}

	@Override
	public long getDossierActionId() {
		return _dossierActionId;
	}

	@Override
	public void setDossierActionId(long dossierActionId) {
		_dossierActionId = dossierActionId;
	}

	@Override
	public int getViaPostal() {
		return _viaPostal;
	}

	@Override
	public void setViaPostal(int viaPostal) {
		_viaPostal = viaPostal;
	}

	@Override
	public String getPostalAddress() {
		if (_postalAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _postalAddress;
		}
	}

	@Override
	public void setPostalAddress(String postalAddress) {
		_postalAddress = postalAddress;
	}

	@Override
	public String getPostalCityCode() {
		if (_postalCityCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _postalCityCode;
		}
	}

	@Override
	public void setPostalCityCode(String postalCityCode) {
		_postalCityCode = postalCityCode;
	}

	@Override
	public String getPostalCityName() {
		if (_postalCityName == null) {
			return StringPool.BLANK;
		}
		else {
			return _postalCityName;
		}
	}

	@Override
	public void setPostalCityName(String postalCityName) {
		_postalCityName = postalCityName;
	}

	@Override
	public String getPostalTelNo() {
		if (_postalTelNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _postalTelNo;
		}
	}

	@Override
	public void setPostalTelNo(String postalTelNo) {
		_postalTelNo = postalTelNo;
	}

	@Override
	public String getPassword() {
		if (_password == null) {
			return StringPool.BLANK;
		}
		else {
			return _password;
		}
	}

	@Override
	public void setPassword(String password) {
		_password = password;
	}

	@Override
	public boolean getNotification() {
		return _notification;
	}

	@Override
	public boolean isNotification() {
		return _notification;
	}

	@Override
	public void setNotification(boolean notification) {
		_notification = notification;
	}

	@Override
	public boolean getOnline() {
		return _online;
	}

	@Override
	public boolean isOnline() {
		return _online;
	}

	@Override
	public void setOnline(boolean online) {
		_online = online;
	}

	@Override
	public String getServerNo() {
		if (_serverNo == null) {
			return StringPool.BLANK;
		}
		else {
			return _serverNo;
		}
	}

	@Override
	public void setServerNo(String serverNo) {
		_serverNo = serverNo;
	}

	@Override
	public Date getEndorsementDate() {
		return _endorsementDate;
	}

	@Override
	public void setEndorsementDate(Date endorsementDate) {
		_endorsementDate = endorsementDate;
	}

	@Override
	public String getLockState() {
		if (_lockState == null) {
			return StringPool.BLANK;
		}
		else {
			return _lockState;
		}
	}

	@Override
	public void setLockState(String lockState) {
		_lockState = lockState;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Dossier.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Dossier.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Dossier toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Dossier)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DossierImpl dossierImpl = new DossierImpl();

		dossierImpl.setUuid(getUuid());
		dossierImpl.setDossierId(getDossierId());
		dossierImpl.setGroupId(getGroupId());
		dossierImpl.setCompanyId(getCompanyId());
		dossierImpl.setUserId(getUserId());
		dossierImpl.setUserName(getUserName());
		dossierImpl.setCreateDate(getCreateDate());
		dossierImpl.setModifiedDate(getModifiedDate());
		dossierImpl.setReferenceUid(getReferenceUid());
		dossierImpl.setCounter(getCounter());
		dossierImpl.setServiceCode(getServiceCode());
		dossierImpl.setServiceName(getServiceName());
		dossierImpl.setGovAgencyCode(getGovAgencyCode());
		dossierImpl.setGovAgencyName(getGovAgencyName());
		dossierImpl.setApplicantName(getApplicantName());
		dossierImpl.setApplicantIdType(getApplicantIdType());
		dossierImpl.setApplicantIdNo(getApplicantIdNo());
		dossierImpl.setApplicantIdDate(getApplicantIdDate());
		dossierImpl.setAddress(getAddress());
		dossierImpl.setCityCode(getCityCode());
		dossierImpl.setCityName(getCityName());
		dossierImpl.setDistrictCode(getDistrictCode());
		dossierImpl.setDistrictName(getDistrictName());
		dossierImpl.setWardCode(getWardCode());
		dossierImpl.setWardName(getWardName());
		dossierImpl.setContactName(getContactName());
		dossierImpl.setContactTelNo(getContactTelNo());
		dossierImpl.setContactEmail(getContactEmail());
		dossierImpl.setDossierTemplateNo(getDossierTemplateNo());
		dossierImpl.setDossierTemplateName(getDossierTemplateName());
		dossierImpl.setDossierNote(getDossierNote());
		dossierImpl.setSubmissionNote(getSubmissionNote());
		dossierImpl.setApplicantNote(getApplicantNote());
		dossierImpl.setBriefNote(getBriefNote());
		dossierImpl.setDossierNo(getDossierNo());
		dossierImpl.setSubmitting(getSubmitting());
		dossierImpl.setSubmitDate(getSubmitDate());
		dossierImpl.setReceiveDate(getReceiveDate());
		dossierImpl.setDueDate(getDueDate());
		dossierImpl.setReleaseDate(getReleaseDate());
		dossierImpl.setFinishDate(getFinishDate());
		dossierImpl.setCancellingDate(getCancellingDate());
		dossierImpl.setCorrecttingDate(getCorrecttingDate());
		dossierImpl.setDossierStatus(getDossierStatus());
		dossierImpl.setDossierStatusText(getDossierStatusText());
		dossierImpl.setDossierSubStatus(getDossierSubStatus());
		dossierImpl.setDossierSubStatusText(getDossierSubStatusText());
		dossierImpl.setFolderId(getFolderId());
		dossierImpl.setDossierActionId(getDossierActionId());
		dossierImpl.setViaPostal(getViaPostal());
		dossierImpl.setPostalAddress(getPostalAddress());
		dossierImpl.setPostalCityCode(getPostalCityCode());
		dossierImpl.setPostalCityName(getPostalCityName());
		dossierImpl.setPostalTelNo(getPostalTelNo());
		dossierImpl.setPassword(getPassword());
		dossierImpl.setNotification(getNotification());
		dossierImpl.setOnline(getOnline());
		dossierImpl.setServerNo(getServerNo());
		dossierImpl.setEndorsementDate(getEndorsementDate());
		dossierImpl.setLockState(getLockState());

		dossierImpl.resetOriginalValues();

		return dossierImpl;
	}

	@Override
	public int compareTo(Dossier dossier) {
		long primaryKey = dossier.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Dossier)) {
			return false;
		}

		Dossier dossier = (Dossier)obj;

		long primaryKey = dossier.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DossierModelImpl dossierModelImpl = this;

		dossierModelImpl._originalUuid = dossierModelImpl._uuid;

		dossierModelImpl._originalDossierId = dossierModelImpl._dossierId;

		dossierModelImpl._setOriginalDossierId = false;

		dossierModelImpl._originalGroupId = dossierModelImpl._groupId;

		dossierModelImpl._setOriginalGroupId = false;

		dossierModelImpl._originalCompanyId = dossierModelImpl._companyId;

		dossierModelImpl._setOriginalCompanyId = false;

		dossierModelImpl._originalUserId = dossierModelImpl._userId;

		dossierModelImpl._setOriginalUserId = false;

		dossierModelImpl._setModifiedDate = false;

		dossierModelImpl._originalReferenceUid = dossierModelImpl._referenceUid;

		dossierModelImpl._originalServiceCode = dossierModelImpl._serviceCode;

		dossierModelImpl._originalGovAgencyCode = dossierModelImpl._govAgencyCode;

		dossierModelImpl._originalDossierTemplateNo = dossierModelImpl._dossierTemplateNo;

		dossierModelImpl._originalSubmitting = dossierModelImpl._submitting;

		dossierModelImpl._setOriginalSubmitting = false;

		dossierModelImpl._originalDossierStatus = dossierModelImpl._dossierStatus;

		dossierModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Dossier> toCacheModel() {
		DossierCacheModel dossierCacheModel = new DossierCacheModel();

		dossierCacheModel.uuid = getUuid();

		String uuid = dossierCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dossierCacheModel.uuid = null;
		}

		dossierCacheModel.dossierId = getDossierId();

		dossierCacheModel.groupId = getGroupId();

		dossierCacheModel.companyId = getCompanyId();

		dossierCacheModel.userId = getUserId();

		dossierCacheModel.userName = getUserName();

		String userName = dossierCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dossierCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dossierCacheModel.createDate = createDate.getTime();
		}
		else {
			dossierCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dossierCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dossierCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dossierCacheModel.referenceUid = getReferenceUid();

		String referenceUid = dossierCacheModel.referenceUid;

		if ((referenceUid != null) && (referenceUid.length() == 0)) {
			dossierCacheModel.referenceUid = null;
		}

		dossierCacheModel.counter = getCounter();

		dossierCacheModel.serviceCode = getServiceCode();

		String serviceCode = dossierCacheModel.serviceCode;

		if ((serviceCode != null) && (serviceCode.length() == 0)) {
			dossierCacheModel.serviceCode = null;
		}

		dossierCacheModel.serviceName = getServiceName();

		String serviceName = dossierCacheModel.serviceName;

		if ((serviceName != null) && (serviceName.length() == 0)) {
			dossierCacheModel.serviceName = null;
		}

		dossierCacheModel.govAgencyCode = getGovAgencyCode();

		String govAgencyCode = dossierCacheModel.govAgencyCode;

		if ((govAgencyCode != null) && (govAgencyCode.length() == 0)) {
			dossierCacheModel.govAgencyCode = null;
		}

		dossierCacheModel.govAgencyName = getGovAgencyName();

		String govAgencyName = dossierCacheModel.govAgencyName;

		if ((govAgencyName != null) && (govAgencyName.length() == 0)) {
			dossierCacheModel.govAgencyName = null;
		}

		dossierCacheModel.applicantName = getApplicantName();

		String applicantName = dossierCacheModel.applicantName;

		if ((applicantName != null) && (applicantName.length() == 0)) {
			dossierCacheModel.applicantName = null;
		}

		dossierCacheModel.applicantIdType = getApplicantIdType();

		String applicantIdType = dossierCacheModel.applicantIdType;

		if ((applicantIdType != null) && (applicantIdType.length() == 0)) {
			dossierCacheModel.applicantIdType = null;
		}

		dossierCacheModel.applicantIdNo = getApplicantIdNo();

		String applicantIdNo = dossierCacheModel.applicantIdNo;

		if ((applicantIdNo != null) && (applicantIdNo.length() == 0)) {
			dossierCacheModel.applicantIdNo = null;
		}

		Date applicantIdDate = getApplicantIdDate();

		if (applicantIdDate != null) {
			dossierCacheModel.applicantIdDate = applicantIdDate.getTime();
		}
		else {
			dossierCacheModel.applicantIdDate = Long.MIN_VALUE;
		}

		dossierCacheModel.address = getAddress();

		String address = dossierCacheModel.address;

		if ((address != null) && (address.length() == 0)) {
			dossierCacheModel.address = null;
		}

		dossierCacheModel.cityCode = getCityCode();

		String cityCode = dossierCacheModel.cityCode;

		if ((cityCode != null) && (cityCode.length() == 0)) {
			dossierCacheModel.cityCode = null;
		}

		dossierCacheModel.cityName = getCityName();

		String cityName = dossierCacheModel.cityName;

		if ((cityName != null) && (cityName.length() == 0)) {
			dossierCacheModel.cityName = null;
		}

		dossierCacheModel.districtCode = getDistrictCode();

		String districtCode = dossierCacheModel.districtCode;

		if ((districtCode != null) && (districtCode.length() == 0)) {
			dossierCacheModel.districtCode = null;
		}

		dossierCacheModel.districtName = getDistrictName();

		String districtName = dossierCacheModel.districtName;

		if ((districtName != null) && (districtName.length() == 0)) {
			dossierCacheModel.districtName = null;
		}

		dossierCacheModel.wardCode = getWardCode();

		String wardCode = dossierCacheModel.wardCode;

		if ((wardCode != null) && (wardCode.length() == 0)) {
			dossierCacheModel.wardCode = null;
		}

		dossierCacheModel.wardName = getWardName();

		String wardName = dossierCacheModel.wardName;

		if ((wardName != null) && (wardName.length() == 0)) {
			dossierCacheModel.wardName = null;
		}

		dossierCacheModel.contactName = getContactName();

		String contactName = dossierCacheModel.contactName;

		if ((contactName != null) && (contactName.length() == 0)) {
			dossierCacheModel.contactName = null;
		}

		dossierCacheModel.contactTelNo = getContactTelNo();

		String contactTelNo = dossierCacheModel.contactTelNo;

		if ((contactTelNo != null) && (contactTelNo.length() == 0)) {
			dossierCacheModel.contactTelNo = null;
		}

		dossierCacheModel.contactEmail = getContactEmail();

		String contactEmail = dossierCacheModel.contactEmail;

		if ((contactEmail != null) && (contactEmail.length() == 0)) {
			dossierCacheModel.contactEmail = null;
		}

		dossierCacheModel.dossierTemplateNo = getDossierTemplateNo();

		String dossierTemplateNo = dossierCacheModel.dossierTemplateNo;

		if ((dossierTemplateNo != null) && (dossierTemplateNo.length() == 0)) {
			dossierCacheModel.dossierTemplateNo = null;
		}

		dossierCacheModel.dossierTemplateName = getDossierTemplateName();

		String dossierTemplateName = dossierCacheModel.dossierTemplateName;

		if ((dossierTemplateName != null) &&
				(dossierTemplateName.length() == 0)) {
			dossierCacheModel.dossierTemplateName = null;
		}

		dossierCacheModel.dossierNote = getDossierNote();

		String dossierNote = dossierCacheModel.dossierNote;

		if ((dossierNote != null) && (dossierNote.length() == 0)) {
			dossierCacheModel.dossierNote = null;
		}

		dossierCacheModel.submissionNote = getSubmissionNote();

		String submissionNote = dossierCacheModel.submissionNote;

		if ((submissionNote != null) && (submissionNote.length() == 0)) {
			dossierCacheModel.submissionNote = null;
		}

		dossierCacheModel.applicantNote = getApplicantNote();

		String applicantNote = dossierCacheModel.applicantNote;

		if ((applicantNote != null) && (applicantNote.length() == 0)) {
			dossierCacheModel.applicantNote = null;
		}

		dossierCacheModel.briefNote = getBriefNote();

		String briefNote = dossierCacheModel.briefNote;

		if ((briefNote != null) && (briefNote.length() == 0)) {
			dossierCacheModel.briefNote = null;
		}

		dossierCacheModel.dossierNo = getDossierNo();

		String dossierNo = dossierCacheModel.dossierNo;

		if ((dossierNo != null) && (dossierNo.length() == 0)) {
			dossierCacheModel.dossierNo = null;
		}

		dossierCacheModel.submitting = getSubmitting();

		Date submitDate = getSubmitDate();

		if (submitDate != null) {
			dossierCacheModel.submitDate = submitDate.getTime();
		}
		else {
			dossierCacheModel.submitDate = Long.MIN_VALUE;
		}

		Date receiveDate = getReceiveDate();

		if (receiveDate != null) {
			dossierCacheModel.receiveDate = receiveDate.getTime();
		}
		else {
			dossierCacheModel.receiveDate = Long.MIN_VALUE;
		}

		Date dueDate = getDueDate();

		if (dueDate != null) {
			dossierCacheModel.dueDate = dueDate.getTime();
		}
		else {
			dossierCacheModel.dueDate = Long.MIN_VALUE;
		}

		Date releaseDate = getReleaseDate();

		if (releaseDate != null) {
			dossierCacheModel.releaseDate = releaseDate.getTime();
		}
		else {
			dossierCacheModel.releaseDate = Long.MIN_VALUE;
		}

		Date finishDate = getFinishDate();

		if (finishDate != null) {
			dossierCacheModel.finishDate = finishDate.getTime();
		}
		else {
			dossierCacheModel.finishDate = Long.MIN_VALUE;
		}

		Date cancellingDate = getCancellingDate();

		if (cancellingDate != null) {
			dossierCacheModel.cancellingDate = cancellingDate.getTime();
		}
		else {
			dossierCacheModel.cancellingDate = Long.MIN_VALUE;
		}

		Date correcttingDate = getCorrecttingDate();

		if (correcttingDate != null) {
			dossierCacheModel.correcttingDate = correcttingDate.getTime();
		}
		else {
			dossierCacheModel.correcttingDate = Long.MIN_VALUE;
		}

		dossierCacheModel.dossierStatus = getDossierStatus();

		String dossierStatus = dossierCacheModel.dossierStatus;

		if ((dossierStatus != null) && (dossierStatus.length() == 0)) {
			dossierCacheModel.dossierStatus = null;
		}

		dossierCacheModel.dossierStatusText = getDossierStatusText();

		String dossierStatusText = dossierCacheModel.dossierStatusText;

		if ((dossierStatusText != null) && (dossierStatusText.length() == 0)) {
			dossierCacheModel.dossierStatusText = null;
		}

		dossierCacheModel.dossierSubStatus = getDossierSubStatus();

		String dossierSubStatus = dossierCacheModel.dossierSubStatus;

		if ((dossierSubStatus != null) && (dossierSubStatus.length() == 0)) {
			dossierCacheModel.dossierSubStatus = null;
		}

		dossierCacheModel.dossierSubStatusText = getDossierSubStatusText();

		String dossierSubStatusText = dossierCacheModel.dossierSubStatusText;

		if ((dossierSubStatusText != null) &&
				(dossierSubStatusText.length() == 0)) {
			dossierCacheModel.dossierSubStatusText = null;
		}

		dossierCacheModel.folderId = getFolderId();

		dossierCacheModel.dossierActionId = getDossierActionId();

		dossierCacheModel.viaPostal = getViaPostal();

		dossierCacheModel.postalAddress = getPostalAddress();

		String postalAddress = dossierCacheModel.postalAddress;

		if ((postalAddress != null) && (postalAddress.length() == 0)) {
			dossierCacheModel.postalAddress = null;
		}

		dossierCacheModel.postalCityCode = getPostalCityCode();

		String postalCityCode = dossierCacheModel.postalCityCode;

		if ((postalCityCode != null) && (postalCityCode.length() == 0)) {
			dossierCacheModel.postalCityCode = null;
		}

		dossierCacheModel.postalCityName = getPostalCityName();

		String postalCityName = dossierCacheModel.postalCityName;

		if ((postalCityName != null) && (postalCityName.length() == 0)) {
			dossierCacheModel.postalCityName = null;
		}

		dossierCacheModel.postalTelNo = getPostalTelNo();

		String postalTelNo = dossierCacheModel.postalTelNo;

		if ((postalTelNo != null) && (postalTelNo.length() == 0)) {
			dossierCacheModel.postalTelNo = null;
		}

		dossierCacheModel.password = getPassword();

		String password = dossierCacheModel.password;

		if ((password != null) && (password.length() == 0)) {
			dossierCacheModel.password = null;
		}

		dossierCacheModel.notification = getNotification();

		dossierCacheModel.online = getOnline();

		dossierCacheModel.serverNo = getServerNo();

		String serverNo = dossierCacheModel.serverNo;

		if ((serverNo != null) && (serverNo.length() == 0)) {
			dossierCacheModel.serverNo = null;
		}

		Date endorsementDate = getEndorsementDate();

		if (endorsementDate != null) {
			dossierCacheModel.endorsementDate = endorsementDate.getTime();
		}
		else {
			dossierCacheModel.endorsementDate = Long.MIN_VALUE;
		}

		dossierCacheModel.lockState = getLockState();

		String lockState = dossierCacheModel.lockState;

		if ((lockState != null) && (lockState.length() == 0)) {
			dossierCacheModel.lockState = null;
		}

		return dossierCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(121);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", dossierId=");
		sb.append(getDossierId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", referenceUid=");
		sb.append(getReferenceUid());
		sb.append(", counter=");
		sb.append(getCounter());
		sb.append(", serviceCode=");
		sb.append(getServiceCode());
		sb.append(", serviceName=");
		sb.append(getServiceName());
		sb.append(", govAgencyCode=");
		sb.append(getGovAgencyCode());
		sb.append(", govAgencyName=");
		sb.append(getGovAgencyName());
		sb.append(", applicantName=");
		sb.append(getApplicantName());
		sb.append(", applicantIdType=");
		sb.append(getApplicantIdType());
		sb.append(", applicantIdNo=");
		sb.append(getApplicantIdNo());
		sb.append(", applicantIdDate=");
		sb.append(getApplicantIdDate());
		sb.append(", address=");
		sb.append(getAddress());
		sb.append(", cityCode=");
		sb.append(getCityCode());
		sb.append(", cityName=");
		sb.append(getCityName());
		sb.append(", districtCode=");
		sb.append(getDistrictCode());
		sb.append(", districtName=");
		sb.append(getDistrictName());
		sb.append(", wardCode=");
		sb.append(getWardCode());
		sb.append(", wardName=");
		sb.append(getWardName());
		sb.append(", contactName=");
		sb.append(getContactName());
		sb.append(", contactTelNo=");
		sb.append(getContactTelNo());
		sb.append(", contactEmail=");
		sb.append(getContactEmail());
		sb.append(", dossierTemplateNo=");
		sb.append(getDossierTemplateNo());
		sb.append(", dossierTemplateName=");
		sb.append(getDossierTemplateName());
		sb.append(", dossierNote=");
		sb.append(getDossierNote());
		sb.append(", submissionNote=");
		sb.append(getSubmissionNote());
		sb.append(", applicantNote=");
		sb.append(getApplicantNote());
		sb.append(", briefNote=");
		sb.append(getBriefNote());
		sb.append(", dossierNo=");
		sb.append(getDossierNo());
		sb.append(", submitting=");
		sb.append(getSubmitting());
		sb.append(", submitDate=");
		sb.append(getSubmitDate());
		sb.append(", receiveDate=");
		sb.append(getReceiveDate());
		sb.append(", dueDate=");
		sb.append(getDueDate());
		sb.append(", releaseDate=");
		sb.append(getReleaseDate());
		sb.append(", finishDate=");
		sb.append(getFinishDate());
		sb.append(", cancellingDate=");
		sb.append(getCancellingDate());
		sb.append(", correcttingDate=");
		sb.append(getCorrecttingDate());
		sb.append(", dossierStatus=");
		sb.append(getDossierStatus());
		sb.append(", dossierStatusText=");
		sb.append(getDossierStatusText());
		sb.append(", dossierSubStatus=");
		sb.append(getDossierSubStatus());
		sb.append(", dossierSubStatusText=");
		sb.append(getDossierSubStatusText());
		sb.append(", folderId=");
		sb.append(getFolderId());
		sb.append(", dossierActionId=");
		sb.append(getDossierActionId());
		sb.append(", viaPostal=");
		sb.append(getViaPostal());
		sb.append(", postalAddress=");
		sb.append(getPostalAddress());
		sb.append(", postalCityCode=");
		sb.append(getPostalCityCode());
		sb.append(", postalCityName=");
		sb.append(getPostalCityName());
		sb.append(", postalTelNo=");
		sb.append(getPostalTelNo());
		sb.append(", password=");
		sb.append(getPassword());
		sb.append(", notification=");
		sb.append(getNotification());
		sb.append(", online=");
		sb.append(getOnline());
		sb.append(", serverNo=");
		sb.append(getServerNo());
		sb.append(", endorsementDate=");
		sb.append(getEndorsementDate());
		sb.append(", lockState=");
		sb.append(getLockState());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(184);

		sb.append("<model><model-name>");
		sb.append("org.opencps.dossiermgt.model.Dossier");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierId</column-name><column-value><![CDATA[");
		sb.append(getDossierId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>referenceUid</column-name><column-value><![CDATA[");
		sb.append(getReferenceUid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>counter</column-name><column-value><![CDATA[");
		sb.append(getCounter());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceCode</column-name><column-value><![CDATA[");
		sb.append(getServiceCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serviceName</column-name><column-value><![CDATA[");
		sb.append(getServiceName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgencyCode</column-name><column-value><![CDATA[");
		sb.append(getGovAgencyCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>govAgencyName</column-name><column-value><![CDATA[");
		sb.append(getGovAgencyName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicantName</column-name><column-value><![CDATA[");
		sb.append(getApplicantName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicantIdType</column-name><column-value><![CDATA[");
		sb.append(getApplicantIdType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicantIdNo</column-name><column-value><![CDATA[");
		sb.append(getApplicantIdNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicantIdDate</column-name><column-value><![CDATA[");
		sb.append(getApplicantIdDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>address</column-name><column-value><![CDATA[");
		sb.append(getAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityCode</column-name><column-value><![CDATA[");
		sb.append(getCityCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cityName</column-name><column-value><![CDATA[");
		sb.append(getCityName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>districtCode</column-name><column-value><![CDATA[");
		sb.append(getDistrictCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>districtName</column-name><column-value><![CDATA[");
		sb.append(getDistrictName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wardCode</column-name><column-value><![CDATA[");
		sb.append(getWardCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wardName</column-name><column-value><![CDATA[");
		sb.append(getWardName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactName</column-name><column-value><![CDATA[");
		sb.append(getContactName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactTelNo</column-name><column-value><![CDATA[");
		sb.append(getContactTelNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>contactEmail</column-name><column-value><![CDATA[");
		sb.append(getContactEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierTemplateNo</column-name><column-value><![CDATA[");
		sb.append(getDossierTemplateNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierTemplateName</column-name><column-value><![CDATA[");
		sb.append(getDossierTemplateName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierNote</column-name><column-value><![CDATA[");
		sb.append(getDossierNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>submissionNote</column-name><column-value><![CDATA[");
		sb.append(getSubmissionNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>applicantNote</column-name><column-value><![CDATA[");
		sb.append(getApplicantNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>briefNote</column-name><column-value><![CDATA[");
		sb.append(getBriefNote());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierNo</column-name><column-value><![CDATA[");
		sb.append(getDossierNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>submitting</column-name><column-value><![CDATA[");
		sb.append(getSubmitting());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>submitDate</column-name><column-value><![CDATA[");
		sb.append(getSubmitDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>receiveDate</column-name><column-value><![CDATA[");
		sb.append(getReceiveDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dueDate</column-name><column-value><![CDATA[");
		sb.append(getDueDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>releaseDate</column-name><column-value><![CDATA[");
		sb.append(getReleaseDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>finishDate</column-name><column-value><![CDATA[");
		sb.append(getFinishDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cancellingDate</column-name><column-value><![CDATA[");
		sb.append(getCancellingDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>correcttingDate</column-name><column-value><![CDATA[");
		sb.append(getCorrecttingDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierStatus</column-name><column-value><![CDATA[");
		sb.append(getDossierStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierStatusText</column-name><column-value><![CDATA[");
		sb.append(getDossierStatusText());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierSubStatus</column-name><column-value><![CDATA[");
		sb.append(getDossierSubStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierSubStatusText</column-name><column-value><![CDATA[");
		sb.append(getDossierSubStatusText());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>folderId</column-name><column-value><![CDATA[");
		sb.append(getFolderId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dossierActionId</column-name><column-value><![CDATA[");
		sb.append(getDossierActionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>viaPostal</column-name><column-value><![CDATA[");
		sb.append(getViaPostal());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postalAddress</column-name><column-value><![CDATA[");
		sb.append(getPostalAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postalCityCode</column-name><column-value><![CDATA[");
		sb.append(getPostalCityCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postalCityName</column-name><column-value><![CDATA[");
		sb.append(getPostalCityName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>postalTelNo</column-name><column-value><![CDATA[");
		sb.append(getPostalTelNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>password</column-name><column-value><![CDATA[");
		sb.append(getPassword());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>notification</column-name><column-value><![CDATA[");
		sb.append(getNotification());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>online</column-name><column-value><![CDATA[");
		sb.append(getOnline());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>serverNo</column-name><column-value><![CDATA[");
		sb.append(getServerNo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>endorsementDate</column-name><column-value><![CDATA[");
		sb.append(getEndorsementDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lockState</column-name><column-value><![CDATA[");
		sb.append(getLockState());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Dossier.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Dossier.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _dossierId;
	private long _originalDossierId;
	private boolean _setOriginalDossierId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _referenceUid;
	private String _originalReferenceUid;
	private int _counter;
	private String _serviceCode;
	private String _originalServiceCode;
	private String _serviceName;
	private String _govAgencyCode;
	private String _originalGovAgencyCode;
	private String _govAgencyName;
	private String _applicantName;
	private String _applicantIdType;
	private String _applicantIdNo;
	private Date _applicantIdDate;
	private String _address;
	private String _cityCode;
	private String _cityName;
	private String _districtCode;
	private String _districtName;
	private String _wardCode;
	private String _wardName;
	private String _contactName;
	private String _contactTelNo;
	private String _contactEmail;
	private String _dossierTemplateNo;
	private String _originalDossierTemplateNo;
	private String _dossierTemplateName;
	private String _dossierNote;
	private String _submissionNote;
	private String _applicantNote;
	private String _briefNote;
	private String _dossierNo;
	private boolean _submitting;
	private boolean _originalSubmitting;
	private boolean _setOriginalSubmitting;
	private Date _submitDate;
	private Date _receiveDate;
	private Date _dueDate;
	private Date _releaseDate;
	private Date _finishDate;
	private Date _cancellingDate;
	private Date _correcttingDate;
	private String _dossierStatus;
	private String _originalDossierStatus;
	private String _dossierStatusText;
	private String _dossierSubStatus;
	private String _dossierSubStatusText;
	private long _folderId;
	private long _dossierActionId;
	private int _viaPostal;
	private String _postalAddress;
	private String _postalCityCode;
	private String _postalCityName;
	private String _postalTelNo;
	private String _password;
	private boolean _notification;
	private boolean _online;
	private String _serverNo;
	private Date _endorsementDate;
	private String _lockState;
	private long _columnBitmask;
	private Dossier _escapedModel;
}